-- Seed 200 additional questions across all categories
-- Same proportions as the original 121-question seed (009_seed_questions.sql)
-- Difficulty: 1-3 = easy, 4-6 = medium, 7-9 = hard

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which battle in 1777 is considered the turning point of the American Revolution, convincing France to ally with the colonists?',
 ARRAY['Battle of Bunker Hill','Battle of Saratoga','Battle of Trenton','Battle of Yorktown'],
 'Battle of Saratoga', 'US History', 1),
('Who was the second President of the United States?',
 ARRAY['Alexander Hamilton','John Adams','James Madison','Thomas Jefferson'],
 'John Adams', 'US History', 1),
('The Boston Tea Party took place in which year?',
 ARRAY['1770','1773','1776','1781'],
 '1773', 'US History', 2),
('Which Constitutional Convention delegate is known as the "Father of the Constitution"?',
 ARRAY['Benjamin Franklin','George Washington','James Madison','John Jay'],
 'James Madison', 'US History', 2),
('What was the name of the ship that brought the Pilgrims to Plymouth in 1620?',
 ARRAY['Mayflower','Santa Maria','Endeavour','Speedwell'],
 'Mayflower', 'US History', 3),
('Which President signed the Social Security Act into law in 1935?',
 ARRAY['Harry Truman','Herbert Hoover','Franklin D. Roosevelt','Woodrow Wilson'],
 'Franklin D. Roosevelt', 'US History', 3),
('What was the name of the plan to rebuild the South after the Civil War?',
 ARRAY['The New Deal','Reconstruction','The Marshall Plan','Manifest Destiny'],
 'Reconstruction', 'US History', 4),
('The Trail of Tears refers to the forced removal of which Native American nation?',
 ARRAY['Sioux','Apache','Cherokee','Comanche'],
 'Cherokee', 'US History', 4),
('Which President ordered the internment of Japanese Americans during World War II?',
 ARRAY['Harry Truman','Dwight Eisenhower','Franklin D. Roosevelt','Herbert Hoover'],
 'Franklin D. Roosevelt', 'US History', 4),
('The Homestead Act of 1862 offered settlers how many acres of public land?',
 ARRAY['40 acres','100 acres','160 acres','320 acres'],
 '160 acres', 'US History', 5),
('Who was the US President when the atomic bombs were dropped on Japan in 1945?',
 ARRAY['Franklin D. Roosevelt','Harry Truman','Dwight Eisenhower','Herbert Hoover'],
 'Harry Truman', 'US History', 5),
('What was the name of the first US space station launched in 1973?',
 ARRAY['Mir','Skylab','Freedom','Genesis'],
 'Skylab', 'US History', 6),
('The Seneca Falls Convention of 1848 primarily focused on which issue?',
 ARRAY['Abolition of slavery','Labor rights','Women''s rights','Native American rights'],
 'Women''s rights', 'US History', 6),
('Which 1803 Supreme Court decision established the principle of judicial review?',
 ARRAY['McCulloch v. Maryland','Marbury v. Madison','Gibbons v. Ogden','Fletcher v. Peck'],
 'Marbury v. Madison', 'US History', 6),
('During Prohibition, the manufacture and sale of alcohol was banned under which Constitutional amendment?',
 ARRAY['16th Amendment','17th Amendment','18th Amendment','19th Amendment'],
 '18th Amendment', 'US History', 7),
('What was the name of the US government''s top-secret program to study UFOs that ran from 1947 to 1969?',
 ARRAY['Project Blue Book','Project MK-Ultra','Operation Paperclip','Project Stargate'],
 'Project Blue Book', 'US History', 7),
('Which President signed the Civil Rights Act of 1964?',
 ARRAY['John F. Kennedy','Lyndon B. Johnson','Richard Nixon','Dwight Eisenhower'],
 'Lyndon B. Johnson', 'US History', 7),
('The Dred Scott decision of 1857 ruled that enslaved people were what?',
 ARRAY['Citizens with limited rights','Property with no legal rights','Entitled to freedom in free states','Protected under the Bill of Rights'],
 'Property with no legal rights', 'US History', 8),
('The Zimmermann Telegram, which helped bring the US into WWI, proposed a military alliance between Germany and which country?',
 ARRAY['Austria-Hungary','Mexico','Japan','Ottoman Empire'],
 'Mexico', 'US History', 8),
('Which act, passed in 1798, made it a crime to publish "false, scandalous, and malicious writing" against the government?',
 ARRAY['Alien and Sedition Acts','Espionage Act','Seditious Libel Act','Gag Rule'],
 'Alien and Sedition Acts', 'US History', 8),
('What was the name of the first permanent European settlement in what is now the continental United States, established in 1565?',
 ARRAY['St. Augustine','Santa Fe','Plymouth','Roanoke'],
 'St. Augustine', 'US History', 9),
('The XYZ Affair of 1797–1798 nearly brought the United States to war with which country?',
 ARRAY['Britain','Spain','France','the Netherlands'],
 'France', 'US History', 9),

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('How many US Senators does each state have?',
 ARRAY['1','2','3','4'],
 '2', 'Civics', 1),
('What is the highest court in the United States?',
 ARRAY['Court of Appeals','Federal District Court','Supreme Court','Circuit Court'],
 'Supreme Court', 'Civics', 1),
('Which document begins with the words "We the People"?',
 ARRAY['Declaration of Independence','Bill of Rights','The Constitution','The Federalist Papers'],
 'The Constitution', 'Civics', 2),
('What is the term for the President''s power to reject a bill passed by Congress?',
 ARRAY['Filibuster','Veto','Injunction','Prorogation'],
 'Veto', 'Civics', 2),
('How many voting members does the US Senate have?',
 ARRAY['50','100','150','435'],
 '100', 'Civics', 3),
('Which amendment guarantees the right to bear arms?',
 ARRAY['1st Amendment','2nd Amendment','4th Amendment','5th Amendment'],
 '2nd Amendment', 'Civics', 3),
('The President is elected for a term of how many years?',
 ARRAY['2','4','6','8'],
 '4', 'Civics', 4),
('What is the process called when the Senate approves or rejects presidential appointees and treaties?',
 ARRAY['Cloture','Ratification','Confirmation','Appropriation'],
 'Confirmation', 'Civics', 4),
('Which amendment prohibits unreasonable searches and seizures?',
 ARRAY['3rd Amendment','4th Amendment','5th Amendment','6th Amendment'],
 '4th Amendment', 'Civics', 4),
('The 14th Amendment, ratified in 1868, primarily granted citizenship to whom?',
 ARRAY['Women','Formerly enslaved people','Native Americans','Immigrants'],
 'Formerly enslaved people', 'Civics', 5),
('What is the minimum number of Supreme Court justices needed to hear a case (a quorum)?',
 ARRAY['4','5','6','7'],
 '6', 'Civics', 5),
('Which clause of the Constitution requires states to honor the laws and judicial decisions of other states?',
 ARRAY['Supremacy Clause','Commerce Clause','Full Faith and Credit Clause','Extradition Clause'],
 'Full Faith and Credit Clause', 'Civics', 5),
('What is the name of the system that gives each branch of government power to limit the other branches?',
 ARRAY['Separation of powers','Federalism','Checks and balances','Judicial review'],
 'Checks and balances', 'Civics', 6),
('A president who is impeached by the House but acquitted by the Senate does what?',
 ARRAY['Is automatically removed','Remains in office','Must resign','Loses all executive powers'],
 'Remains in office', 'Civics', 6),
('Which amendment extended the right to vote to citizens aged 18 and older?',
 ARRAY['24th Amendment','25th Amendment','26th Amendment','27th Amendment'],
 '26th Amendment', 'Civics', 6),
('The 17th Amendment changed how US Senators are elected — from being chosen by state legislatures to being chosen by whom?',
 ARRAY['The President','The Electoral College','Direct popular vote','State governors'],
 'Direct popular vote', 'Civics', 7),
('What is the term for the constitutional provision that allows Congress to make laws on topics not explicitly listed in the Constitution?',
 ARRAY['Commerce Clause','Supremacy Clause','Necessary and Proper Clause','General Welfare Clause'],
 'Necessary and Proper Clause', 'Civics', 7),
('How many states must ratify a constitutional amendment after Congress proposes it?',
 ARRAY['Two-thirds of states','Three-quarters of states','Half of states plus one','All 50 states'],
 'Three-quarters of states', 'Civics', 7),
('Which amendment, ratified in 1992, prohibits congressional pay raises from taking effect until after the next election?',
 ARRAY['25th Amendment','26th Amendment','27th Amendment','28th Amendment'],
 '27th Amendment', 'Civics', 8),
('What is the constitutional process called when a state''s presidential electors officially cast their votes?',
 ARRAY['General election','Electoral College vote','Congressional certification','Ratification'],
 'Electoral College vote', 'Civics', 8),
('Under the 25th Amendment, who assumes the presidency if the president is unable to discharge their duties?',
 ARRAY['Speaker of the House','President pro tempore of the Senate','Vice President','Secretary of State'],
 'Vice President', 'Civics', 8),
('What legal principle, established in Miranda v. Arizona, requires police to inform suspects of their rights?',
 ARRAY['Due Process','Miranda Warning','Habeas Corpus','Ex Post Facto'],
 'Miranda Warning', 'Civics', 9),
('Which clause of the 14th Amendment has been used to apply the Bill of Rights to state governments?',
 ARRAY['Equal Protection Clause','Due Process Clause','Privileges and Immunities Clause','Citizenship Clause'],
 'Due Process Clause', 'Civics', 9),
('The concept of "one person, one vote" was established in which landmark Supreme Court case?',
 ARRAY['Reynolds v. Sims','Baker v. Carr','Wesberry v. Sanders','Shaw v. Reno'],
 'Reynolds v. Sims', 'Civics', 9);

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the name of the body of water that separates Alaska from Russia?',
 ARRAY['Bering Strait','Cook Inlet','Prince William Sound','Gulf of Alaska'],
 'Bering Strait', 'Geography', 1),
('Which US state is made up entirely of islands?',
 ARRAY['Puerto Rico','Florida','Hawaii','Alaska'],
 'Hawaii', 'Geography', 2),
('What is the name of the large bay on the eastern coast of Maryland and Virginia?',
 ARRAY['Narragansett Bay','Delaware Bay','Chesapeake Bay','Mobile Bay'],
 'Chesapeake Bay', 'Geography', 2),
('Which city is the largest in the United States by population?',
 ARRAY['Los Angeles','Chicago','Houston','New York City'],
 'New York City', 'Geography', 3),
('Which US state shares its name with a European country?',
 ARRAY['Georgia','Indiana','Oregon','Virginia'],
 'Georgia', 'Geography', 3),
('Which river forms much of the border between Iowa and Illinois?',
 ARRAY['Ohio River','Missouri River','Mississippi River','Wabash River'],
 'Mississippi River', 'Geography', 4),
('The Florida Everglades is primarily what type of ecosystem?',
 ARRAY['Desert','Tropical rainforest','Wetland','Savanna'],
 'Wetland', 'Geography', 4),
('Which state is known as the "Sunshine State"?',
 ARRAY['California','Arizona','Nevada','Florida'],
 'Florida', 'Geography', 4),
('What is the name of the peninsula in the Pacific Northwest famous for its temperate rainforest?',
 ARRAY['Kenai Peninsula','Olympic Peninsula','Kitsap Peninsula','Point Reyes'],
 'Olympic Peninsula', 'Geography', 5),
('Which four US states meet at a single point known as "Four Corners"?',
 ARRAY['Utah, Colorado, Arizona, New Mexico','Utah, Colorado, Nevada, Arizona','Colorado, Wyoming, Idaho, Utah','New Mexico, Texas, Oklahoma, Colorado'],
 'Utah, Colorado, Arizona, New Mexico', 'Geography', 5),
('The Piedmont region lies between which two geographic features in the eastern United States?',
 ARRAY['The Appalachians and the Atlantic Coastal Plain','The Mississippi River and the Ohio River','The Blue Ridge and the Great Lakes','The Ozarks and the Gulf Coast'],
 'The Appalachians and the Atlantic Coastal Plain', 'Geography', 5),
('Which Great Lake does NOT border the state of Michigan?',
 ARRAY['Lake Superior','Lake Erie','Lake Ontario','Lake Huron'],
 'Lake Ontario', 'Geography', 6),
('The Ogallala Aquifer, one of the world''s largest, underlies which region of the United States?',
 ARRAY['Southeast','Pacific Northwest','Great Plains','Great Lakes region'],
 'Great Plains', 'Geography', 6),
('Which US state has the most active volcanoes?',
 ARRAY['Hawaii','California','Washington','Oregon'],
 'Alaska', 'Geography', 6),
('What is the name of the narrow strip of land connecting California to the rest of the contiguous United States along the Pacific coast?',
 ARRAY['There is no narrow strip','Baja Extension','The Pacific Corridor','The California Corridor'],
 'There is no narrow strip', 'Geography', 7),
('The geographic center of the contiguous 48 states is located in which state?',
 ARRAY['Missouri','Nebraska','Kansas','Oklahoma'],
 'Kansas', 'Geography', 7),
('Which US city is closest to the geographic center of the nation''s population?',
 ARRAY['Indianapolis','Columbus','St. Louis','Kansas City'],
 'Columbus', 'Geography', 7),
('The Driftless Area, a region that was never glaciated during the last Ice Age, spans parts of which states?',
 ARRAY['Wisconsin, Iowa, Minnesota, Illinois','Ohio, Indiana, Michigan, Wisconsin','Missouri, Illinois, Kentucky, Tennessee','Iowa, Nebraska, Kansas, Missouri'],
 'Wisconsin, Iowa, Minnesota, Illinois', 'Geography', 8),
('Lake Champlain, sometimes informally called "the sixth Great Lake," borders which US states?',
 ARRAY['New Hampshire and Maine','Vermont and New York','Massachusetts and Connecticut','Pennsylvania and New York'],
 'Vermont and New York', 'Geography', 8),
('Which US territory lies closest to the geographic South Pole''s antipode in the northern hemisphere?',
 ARRAY['Guam','American Samoa','Puerto Rico','US Virgin Islands'],
 'American Samoa', 'Geography', 8),
('The Salton Sea, a large inland lake in California, was created accidentally in which year?',
 ARRAY['1885','1905','1925','1945'],
 '1905', 'Geography', 9),
('The geographic region known as "Appalachia" encompasses parts of how many US states?',
 ARRAY['8','13','17','20'],
 '13', 'Geography', 9),
('Which US state contains the geographic point farthest from any ocean, known as a pole of inaccessibility?',
 ARRAY['Wyoming','Colorado','Nebraska','South Dakota'],
 'South Dakota', 'Geography', 9),
('What is the name of the underwater volcanic mountain range that runs along the ocean floor west of the Pacific Coast?',
 ARRAY['Cascadia Ridge','Juan de Fuca Ridge','Pacific Spine','Farallon Ridge'],
 'Juan de Fuca Ridge', 'Geography', 9);

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('On which island in New York Harbor does the Statue of Liberty stand?',
 ARRAY['Ellis Island','Governors Island','Liberty Island','Manhattan Island'],
 'Liberty Island', 'Landmarks', 1),
('In which city is the Empire State Building located?',
 ARRAY['Chicago','Boston','Philadelphia','New York City'],
 'New York City', 'Landmarks', 1),
('The Hollywood Sign overlooks which California city?',
 ARRAY['San Francisco','San Diego','Sacramento','Los Angeles'],
 'Los Angeles', 'Landmarks', 2),
('Niagara Falls is located on the border between New York and which Canadian province?',
 ARRAY['Quebec','Ontario','British Columbia','Manitoba'],
 'Ontario', 'Landmarks', 2),
('In which city is the National Mall located?',
 ARRAY['Philadelphia','Boston','Washington D.C.','Baltimore'],
 'Washington D.C.', 'Landmarks', 3),
('Which famous bridge connects Manhattan to Brooklyn?',
 ARRAY['George Washington Bridge','Verrazano-Narrows Bridge','Queensboro Bridge','Brooklyn Bridge'],
 'Brooklyn Bridge', 'Landmarks', 3),
('The Vietnam Veterans Memorial in Washington D.C. was designed by which architect?',
 ARRAY['I.M. Pei','Maya Lin','Frank Lloyd Wright','Zaha Hadid'],
 'Maya Lin', 'Landmarks', 4),
('The Hoover Dam sits on the border between which two US states?',
 ARRAY['California and Nevada','Arizona and Utah','Nevada and Arizona','Colorado and Utah'],
 'Nevada and Arizona', 'Landmarks', 4),
('Alcatraz Island, site of a famous former federal prison, is located in which bay?',
 ARRAY['Monterey Bay','San Diego Bay','San Francisco Bay','Half Moon Bay'],
 'San Francisco Bay', 'Landmarks', 4),
('The Eisenhower Interstate Highway System''s first section was opened in which state?',
 ARRAY['Kansas','Pennsylvania','Missouri','Illinois'],
 'Kansas', 'Landmarks', 5),
('Which skyscraper held the title of tallest building in the world for 41 years after its completion in 1931?',
 ARRAY['Chrysler Building','Empire State Building','One World Trade Center','Willis Tower'],
 'Empire State Building', 'Landmarks', 5),
('The National Cathedral in Washington D.C. is officially called what?',
 ARRAY['Washington National Cathedral','Cathedral of St. Peter','Basilica of the National Shrine','Cathedral of St. Matthew'],
 'Washington National Cathedral', 'Landmarks', 5),
('The original Faneuil Hall in Boston was built primarily to serve as what?',
 ARRAY['A church','A marketplace','A courthouse','A government hall'],
 'A marketplace', 'Landmarks', 6),
('The Crazy Horse Memorial, a mountain carving larger than Mount Rushmore, is located in which state?',
 ARRAY['Wyoming','Montana','South Dakota','North Dakota'],
 'South Dakota', 'Landmarks', 6),
('Independence Hall in Philadelphia is notable as the building where which document was debated and adopted in 1787?',
 ARRAY['The Monroe Doctrine','The Constitution','The Articles of Confederation','The Federalist Papers'],
 'The Constitution', 'Landmarks', 6),
('The Washington Monument stands at approximately how many feet tall?',
 ARRAY['455 feet','555 feet','655 feet','755 feet'],
 '555 feet', 'Landmarks', 7),
('The Biltmore Estate in Asheville, North Carolina, was built by which wealthy industrialist family?',
 ARRAY['Rockefeller','Carnegie','Vanderbilt','Morgan'],
 'Vanderbilt', 'Landmarks', 7),
('Monticello, the home of Thomas Jefferson, is located near which Virginia city?',
 ARRAY['Richmond','Charlottesville','Roanoke','Winchester'],
 'Charlottesville', 'Landmarks', 7),
('The Flatiron Building in New York City gets its name from its triangular shape. In what year was it completed?',
 ARRAY['1892','1902','1912','1922'],
 '1902', 'Landmarks', 8),
('Frank Lloyd Wright''s famous "Fallingwater" house is located in which state?',
 ARRAY['Wisconsin','Ohio','Illinois','Pennsylvania'],
 'Pennsylvania', 'Landmarks', 8);

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which branch of the US military was established first?',
 ARRAY['Army','Navy','Marine Corps','Air Force'],
 'Army', 'Military', 1),
('What is the highest military honor in the United States?',
 ARRAY['Distinguished Service Cross','Bronze Star','Medal of Honor','Silver Star'],
 'Medal of Honor', 'Military', 1),
('The US Air Force was established as a separate branch of the military in which year?',
 ARRAY['1941','1944','1947','1950'],
 '1947', 'Military', 2),
('What is the name of the military academy located in Colorado Springs?',
 ARRAY['US Naval Academy','US Military Academy','US Air Force Academy','US Coast Guard Academy'],
 'US Air Force Academy', 'Military', 2),
('Which US military operation liberated Kuwait in 1991?',
 ARRAY['Operation Enduring Freedom','Operation Iraqi Freedom','Operation Desert Storm','Operation Just Cause'],
 'Operation Desert Storm', 'Military', 3),
('The Pentagon, headquarters of the US Department of Defense, is located in which state?',
 ARRAY['Maryland','Washington D.C.','Virginia','Delaware'],
 'Virginia', 'Military', 3),
('What was the code name for the D-Day invasion of Normandy on June 6, 1944?',
 ARRAY['Operation Market Garden','Operation Torch','Operation Overlord','Operation Barbarossa'],
 'Operation Overlord', 'Military', 4),
('The Battle of Gettysburg, the deadliest battle of the Civil War, took place in which state?',
 ARRAY['Virginia','Maryland','Pennsylvania','West Virginia'],
 'Pennsylvania', 'Military', 4),
('Which US military operation in 1989 removed Panamanian leader Manuel Noriega from power?',
 ARRAY['Operation Desert Shield','Operation Just Cause','Operation Urgent Fury','Operation Eagle Claw'],
 'Operation Just Cause', 'Military', 4),
('What name was given to the US military strategy in Vietnam of destroying villages suspected of harboring enemy combatants?',
 ARRAY['Scorched Earth','Search and Destroy','Strategic Hamlets','Pacification'],
 'Search and Destroy', 'Military', 5),
('The Battle of Midway was fought primarily using which type of military asset?',
 ARRAY['Tanks','Infantry','Aircraft carriers','Submarines'],
 'Aircraft carriers', 'Military', 5),
('Which US general famously said "I shall return" after being forced to leave the Philippines in 1942?',
 ARRAY['George Patton','Omar Bradley','Douglas MacArthur','Dwight Eisenhower'],
 'Douglas MacArthur', 'Military', 5),
('The US special operations raid that killed Osama bin Laden in 2011 was carried out by which unit?',
 ARRAY['Delta Force','Rangers','Navy SEAL Team 6','Green Berets'],
 'Navy SEAL Team 6', 'Military', 6),
('The Battle of Chosin Reservoir was a critical engagement of which conflict?',
 ARRAY['Vietnam War','World War II','Korean War','Gulf War'],
 'Korean War', 'Military', 6),
('In which Pacific island battle did US Marines raise a flag on Mount Suribachi, as captured in an iconic photo?',
 ARRAY['Guadalcanal','Iwo Jima','Okinawa','Tarawa'],
 'Iwo Jima', 'Military', 6),
('Operation Neptune Spear, which killed Osama bin Laden, took place in which Pakistani city?',
 ARRAY['Islamabad','Lahore','Karachi','Abbottabad'],
 'Abbottabad', 'Military', 7),
('The "Forgotten War" is a nickname commonly applied to which conflict?',
 ARRAY['Philippine-American War','Spanish-American War','Korean War','Gulf War'],
 'Korean War', 'Military', 7),
('Which military general commanded all Allied forces in Europe during World War II?',
 ARRAY['George Patton','Bernard Montgomery','Dwight D. Eisenhower','Omar Bradley'],
 'Dwight D. Eisenhower', 'Military', 8),
('The US military''s first use of helicopter assault tactics in combat occurred during which conflict?',
 ARRAY['Korean War','Vietnam War','World War II','Gulf War'],
 'Vietnam War', 'Military', 8),
('What was the name of the secret US government project that recruited former Nazi scientists after World War II?',
 ARRAY['Project Blue Book','Operation Paperclip','Project Manhigh','Operation Crossroads'],
 'Operation Paperclip', 'Military', 9);

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Zion National Park is located in which US state?',
 ARRAY['Arizona','Nevada','Utah','Colorado'],
 'Utah', 'National Parks', 1),
('Which national park is famous for its giant sequoia trees, the largest living things on Earth by volume?',
 ARRAY['Redwood National Park','Olympic National Park','Sequoia National Park','Joshua Tree National Park'],
 'Sequoia National Park', 'National Parks', 1),
('Grand Teton National Park is located adjacent to which other famous national park?',
 ARRAY['Glacier National Park','Yellowstone National Park','Rocky Mountain National Park','Bryce Canyon National Park'],
 'Yellowstone National Park', 'National Parks', 2),
('Which national park in Florida is known for its coral reef and is accessible only by boat?',
 ARRAY['Everglades National Park','Biscayne National Park','Dry Tortugas National Park','Big Cypress National Preserve'],
 'Dry Tortugas National Park', 'National Parks', 2),
('The Appalachian Trail passes through how many US states?',
 ARRAY['10','12','14','16'],
 '14', 'National Parks', 3),
('Which national park contains the largest known cave system in the world?',
 ARRAY['Wind Cave National Park','Carlsbad Caverns National Park','Mammoth Cave National Park','Lehman Caves'],
 'Mammoth Cave National Park', 'National Parks', 3),
('Crater Lake National Park in Oregon was formed by the collapse of which ancient volcano?',
 ARRAY['Mount Hood','Mount Mazama','Mount Jefferson','Mount Bailey'],
 'Mount Mazama', 'National Parks', 4),
('Which national park straddles the border between the United States and Canada?',
 ARRAY['Olympic National Park','North Cascades National Park','Waterton-Glacier International Peace Park','Mount Rainier National Park'],
 'Waterton-Glacier International Peace Park', 'National Parks', 4),
('The volcanic landscape of Craters of the Moon National Monument is located in which state?',
 ARRAY['Washington','Oregon','Idaho','Montana'],
 'Idaho', 'National Parks', 4),
('Which national park in Hawaii was established to protect active volcanoes?',
 ARRAY['Haleakala National Park','Hawaii Volcanoes National Park','Kaloko-Honokohau National Historical Park','Pu''uhonua o Honaunau National Historical Park'],
 'Hawaii Volcanoes National Park', 'National Parks', 5),
('Bryce Canyon National Park is known for its unique rock formations called what?',
 ARRAY['Mesas','Buttes','Hoodoos','Spires'],
 'Hoodoos', 'National Parks', 5),
('Which US state contains the most national parks within its borders?',
 ARRAY['Colorado','Utah','California','Alaska'],
 'California', 'National Parks', 5),
('The Chesapeake and Ohio Canal National Historical Park follows the route of which river?',
 ARRAY['Shenandoah River','Susquehanna River','Potomac River','James River'],
 'Potomac River', 'National Parks', 6),
('Petrified Forest National Park contains fossilized trees that are approximately how old?',
 ARRAY['65 million years','150 million years','225 million years','300 million years'],
 '225 million years', 'National Parks', 6),
('Which national park contains Angel''s Landing, a famous and challenging hiking trail?',
 ARRAY['Grand Canyon National Park','Bryce Canyon National Park','Capitol Reef National Park','Zion National Park'],
 'Zion National Park', 'National Parks', 6),
('The Channel Islands National Park off the coast of California is sometimes called "America''s Galapagos." How many islands make up the park?',
 ARRAY['3','5','7','9'],
 '5', 'National Parks', 7),
('Which national park is home to the highest sand dunes in North America?',
 ARRAY['Death Valley National Park','White Sands National Park','Great Sand Dunes National Park','Joshua Tree National Park'],
 'Great Sand Dunes National Park', 'National Parks', 7),
('Isle Royale National Park, accessible only by boat or seaplane, is located in which Great Lake?',
 ARRAY['Lake Superior','Lake Michigan','Lake Huron','Lake Erie'],
 'Lake Superior', 'National Parks', 8),
('Congaree National Park, the largest intact expanse of old-growth bottomland hardwoods in the US, is located in which state?',
 ARRAY['Georgia','Alabama','South Carolina','Mississippi'],
 'South Carolina', 'National Parks', 8),
('Which national park''s name comes from a Blackfeet word meaning "backbone of the world"?',
 ARRAY['Glacier National Park','Badlands National Park','Wind Cave National Park','Theodore Roosevelt National Park'],
 'Glacier National Park', 'National Parks', 9);

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which annual American holiday celebrates workers and is observed on the first Monday of September?',
 ARRAY['Memorial Day','Veterans Day','Labor Day','Columbus Day'],
 'Labor Day', 'American Culture', 1),
('What is the name of the famous annual parade held in New York City on Thanksgiving Day?',
 ARRAY['Rose Parade','Macy''s Thanksgiving Day Parade','St. Patrick''s Day Parade','Columbus Day Parade'],
 'Macy''s Thanksgiving Day Parade', 'American Culture', 1),
('The Grammy Awards recognize achievement in which field?',
 ARRAY['Film','Television','Music','Theatre'],
 'Music', 'American Culture', 2),
('What style of music, born in the American South, blends gospel, rhythm and blues, and country music?',
 ARRAY['Bluegrass','Soul','Rock and Roll','Zydeco'],
 'Rock and Roll', 'American Culture', 2),
('Which annual event in Pasadena, California features elaborate flower-covered floats on New Year''s Day?',
 ARRAY['Macy''s Parade','Rose Parade','Mardi Gras','Cherry Blossom Festival'],
 'Rose Parade', 'American Culture', 3),
('Norman Rockwell is best known for his illustrations that appeared on the cover of which American magazine?',
 ARRAY['Life','Time','The Saturday Evening Post','Collier''s Weekly'],
 'The Saturday Evening Post', 'American Culture', 3),
('Which American novelist wrote "To Kill a Mockingbird," published in 1960?',
 ARRAY['Flannery O''Connor','Truman Capote','Harper Lee','Carson McCullers'],
 'Harper Lee', 'American Culture', 4),
('The term "American Dream" is most closely associated with the belief that anyone can achieve success through what?',
 ARRAY['Government assistance','Hard work and determination','Family connections','Higher education'],
 'Hard work and determination', 'American Culture', 4),
('The first drive-in movie theater in the United States opened in 1933 in which state?',
 ARRAY['California','Texas','New Jersey','Ohio'],
 'New Jersey', 'American Culture', 5),
('Which American author wrote the dystopian novel "Brave New World" set in part inspired by American consumer culture?',
 ARRAY['George Orwell','Aldous Huxley','Ray Bradbury','Kurt Vonnegut'],
 'Aldous Huxley', 'American Culture', 6),
('The "Harlem Renaissance" was a cultural movement primarily associated with which art forms?',
 ARRAY['Country music and folk art','Literature, music, and visual arts','Film and theater','Architecture and sculpture'],
 'Literature, music, and visual arts', 'American Culture', 6),
('Which 1950s American TV show featured a suburban family headed by Ozzie and Harriet Nelson?',
 ARRAY['Father Knows Best','Leave It to Beaver','The Adventures of Ozzie and Harriet','I Love Lucy'],
 'The Adventures of Ozzie and Harriet', 'American Culture', 7),
('The "Beat Generation" literary movement of the 1950s was centered in which two US cities?',
 ARRAY['Chicago and Detroit','New York City and San Francisco','Los Angeles and Seattle','Boston and New Orleans'],
 'New York City and San Francisco', 'American Culture', 7),
('Which American artist became famous in the 1960s for pop art paintings of Campbell''s soup cans?',
 ARRAY['Roy Lichtenstein','Jasper Johns','Robert Rauschenberg','Andy Warhol'],
 'Andy Warhol', 'American Culture', 8),
('The Chautauqua Institution, which began in 1874 as a training camp for Sunday school teachers, evolved into a significant center for what?',
 ARRAY['Sports training','Adult education and liberal arts','Religious revival','Political campaigning'],
 'Adult education and liberal arts', 'American Culture', 9),
('Which American literary figure wrote the foundational transcendentalist essay "Self-Reliance" in 1841?',
 ARRAY['Henry David Thoreau','Nathaniel Hawthorne','Herman Melville','Ralph Waldo Emerson'],
 'Ralph Waldo Emerson', 'American Culture', 9);

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which Founding Father is featured on the $100 bill?',
 ARRAY['George Washington','Alexander Hamilton','Benjamin Franklin','Andrew Jackson'],
 'Benjamin Franklin', 'Famous Americans', 1),
('Which American civil rights leader was assassinated in Memphis, Tennessee, in 1968?',
 ARRAY['Malcolm X','Medgar Evers','Martin Luther King Jr.','Thurgood Marshall'],
 'Martin Luther King Jr.', 'Famous Americans', 1),
('Who was the first woman to serve as US Secretary of State?',
 ARRAY['Hillary Clinton','Condoleezza Rice','Madeleine Albright','Janet Reno'],
 'Madeleine Albright', 'Famous Americans', 2),
('Which American inventor is credited with developing the practical electric light bulb?',
 ARRAY['Nikola Tesla','Alexander Graham Bell','Thomas Edison','George Westinghouse'],
 'Thomas Edison', 'Famous Americans', 3),
('Who was the first African American to serve as a US Supreme Court Justice?',
 ARRAY['Clarence Thomas','Thurgood Marshall','John Marshall Harlan','Louis Brandeis'],
 'Thurgood Marshall', 'Famous Americans', 3),
('Which American aviator became the first person to fly solo nonstop across the Atlantic Ocean in 1927?',
 ARRAY['Orville Wright','Howard Hughes','Eddie Rickenbacker','Charles Lindbergh'],
 'Charles Lindbergh', 'Famous Americans', 4),
('Susan B. Anthony appeared on the US dollar coin introduced in which year?',
 ARRAY['1969','1979','1989','1999'],
 '1979', 'Famous Americans', 4),
('Which American scientist and diplomat helped draft the Declaration of Independence and invented bifocals?',
 ARRAY['Thomas Jefferson','John Adams','Benjamin Franklin','Alexander Hamilton'],
 'Benjamin Franklin', 'Famous Americans', 4),
('Which American entrepreneur founded Apple Computer with Steve Wozniak in 1976?',
 ARRAY['Bill Gates','Steve Jobs','Michael Dell','Jeff Bezos'],
 'Steve Jobs', 'Famous Americans', 5),
('Frederick Douglass, the abolitionist and writer, escaped from slavery in which state?',
 ARRAY['Virginia','Georgia','Maryland','South Carolina'],
 'Maryland', 'Famous Americans', 5),
('Which American poet wrote "Leaves of Grass," first published in 1855?',
 ARRAY['Emily Dickinson','Walt Whitman','Henry Wadsworth Longfellow','Edgar Allan Poe'],
 'Walt Whitman', 'Famous Americans', 5),
('Which famous American industrialist established the assembly line for automobile production in the early 20th century?',
 ARRAY['Andrew Carnegie','John D. Rockefeller','Henry Ford','Cornelius Vanderbilt'],
 'Henry Ford', 'Famous Americans', 6),
('Georgia O''Keeffe, famous for her paintings of desert landscapes and flowers, was most closely associated with which US state?',
 ARRAY['Arizona','Colorado','Texas','New Mexico'],
 'New Mexico', 'Famous Americans', 6),
('Which American physicist, known as the "father of the atomic bomb," led the Manhattan Project''s Los Alamos laboratory?',
 ARRAY['Enrico Fermi','J. Robert Oppenheimer','Richard Feynman','Edward Teller'],
 'J. Robert Oppenheimer', 'Famous Americans', 6),
('Cesar Chavez co-founded which labor organization to advocate for farmworkers'' rights in the 1960s?',
 ARRAY['AFL-CIO','International Brotherhood of Teamsters','United Farm Workers','Congress of Industrial Organizations'],
 'United Farm Workers', 'Famous Americans', 7),
('Which American architect designed the Guggenheim Museum in New York City?',
 ARRAY['Ludwig Mies van der Rohe','Philip Johnson','Frank Lloyd Wright','Louis Sullivan'],
 'Frank Lloyd Wright', 'Famous Americans', 8),
('Rachel Carson''s 1962 book "Silent Spring" is credited with launching which movement?',
 ARRAY['Civil rights movement','Anti-war movement','Modern environmental movement','Consumer rights movement'],
 'Modern environmental movement', 'Famous Americans', 9),
('Which Supreme Court Justice, nicknamed "The Great Dissenter," was the sole dissenter in Plessy v. Ferguson?',
 ARRAY['Oliver Wendell Holmes','Louis Brandeis','John Marshall Harlan','Stephen Field'],
 'John Marshall Harlan', 'Famous Americans', 9);

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('How many players are on the field for each side in a standard American football game?',
 ARRAY['9','10','11','12'],
 '11', 'US Sports', 1),
('Which city is home to the NFL team known as the Cowboys?',
 ARRAY['Houston','Austin','San Antonio','Dallas'],
 'Dallas', 'US Sports', 1),
('How many strikes does it take to strike out a batter in baseball?',
 ARRAY['2','3','4','5'],
 '3', 'US Sports', 2),
('The Boston Marathon is run on which holiday in Massachusetts?',
 ARRAY['Memorial Day','Labor Day','Patriots'' Day','Bunker Hill Day'],
 'Patriots'' Day', 'US Sports', 2),
('Which US city hosted the first modern Olympic Games held on American soil, in 1904?',
 ARRAY['Chicago','New York','Los Angeles','St. Louis'],
 'St. Louis', 'US Sports', 3),
('In basketball, how many points is a shot worth if it is made from beyond the arc?',
 ARRAY['1','2','3','4'],
 '3', 'US Sports', 4),
('Which American swimmer won the most gold medals at a single Olympic Games, at the 2008 Beijing Olympics?',
 ARRAY['Ryan Lochte','Mark Spitz','Nathan Adrian','Michael Phelps'],
 'Michael Phelps', 'US Sports', 4),
('The Triple Crown of horse racing consists of the Kentucky Derby, the Preakness Stakes, and which third race?',
 ARRAY['Breeders'' Cup','Belmont Stakes','Arlington Million','Santa Anita Derby'],
 'Belmont Stakes', 'US Sports', 4),
('Which NFL team has played in the most Super Bowls?',
 ARRAY['San Francisco 49ers','Dallas Cowboys','Pittsburgh Steelers','New England Patriots'],
 'New England Patriots', 'US Sports', 5),
('Which golfer won the Masters Tournament at Augusta National in 1997, becoming the youngest champion at age 21?',
 ARRAY['Phil Mickelson','Vijay Singh','Ernie Els','Tiger Woods'],
 'Tiger Woods', 'US Sports', 5),
('In which year did Major League Baseball first introduce the designated hitter rule in the American League?',
 ARRAY['1968','1973','1977','1980'],
 '1973', 'US Sports', 6),
('Which NBA team won the most consecutive championships, winning eight in a row from 1959 to 1966?',
 ARRAY['Los Angeles Lakers','Chicago Bulls','Boston Celtics','Golden State Warriors'],
 'Boston Celtics', 'US Sports', 6),
('The "Miracle on Ice" at the 1980 Winter Olympics involved the US men''s hockey team defeating which opponent?',
 ARRAY['Canada','Sweden','Czechoslovakia','Soviet Union'],
 'Soviet Union', 'US Sports', 6),
('Babe Ruth set his single-season home run record of 60 homers in which year?',
 ARRAY['1921','1924','1927','1930'],
 '1927', 'US Sports', 7),
('Which American tennis player won a record 18 Grand Slam singles titles, later surpassed by players like Djokovic?',
 ARRAY['Jimmy Connors','John McEnroe','Andre Agassi','Pete Sampras'],
 'Pete Sampras', 'US Sports', 7),
('The "Black Sox Scandal" of 1919 involved players from which baseball team deliberately losing the World Series?',
 ARRAY['New York Yankees','Cincinnati Reds','Chicago Cubs','Chicago White Sox'],
 'Chicago White Sox', 'US Sports', 8),
('Which US city held both the 1932 Summer and Winter Olympics, the only city to host both in the same year?',
 ARRAY['New York','Chicago','Los Angeles','San Francisco'],
 'Los Angeles', 'US Sports', 9),
('The first college football game in US history was played in 1869 between Rutgers and which other university?',
 ARRAY['Yale','Harvard','Princeton','Columbia'],
 'Princeton', 'US Sports', 9);

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which president signed the Kansas-Nebraska Act of 1854, effectively repealing the Missouri Compromise?',
 ARRAY['James Buchanan','Franklin Pierce','Millard Fillmore','Zachary Taylor'],
 'Franklin Pierce', 'US History', 2),
('What was the name of the first successful powered airplane flight by the Wright Brothers in 1903?',
 ARRAY['Kitty Hawk','Dayton Flyer','Carolina Glider','Atlantic Soarer'],
 'Kitty Hawk', 'US History', 2),
('Which war was ended by the Treaty of Paris of 1783?',
 ARRAY['War of 1812','French and Indian War','American Revolutionary War','Mexican-American War'],
 'American Revolutionary War', 'US History', 1),
('What nickname was given to the era of economic prosperity and cultural change in the United States during the 1920s?',
 ARRAY['The Gilded Age','The Progressive Era','The Roaring Twenties','The Jazz Revolution'],
 'The Roaring Twenties', 'US History', 1),
('Which U.S. president issued the order to desegregate the U.S. military with Executive Order 9981 in 1948?',
 ARRAY['Franklin D. Roosevelt','Dwight D. Eisenhower','Harry S. Truman','John F. Kennedy'],
 'Harry S. Truman', 'US History', 4),
('What was the name of the 1944 Allied invasion of Nazi-occupied Western Europe that began on the beaches of Normandy?',
 ARRAY['Operation Barbarossa','Operation Overlord','Operation Market Garden','Operation Torch'],
 'Operation Overlord', 'US History', 4),
('Which U.S. Supreme Court case ruled that racially gerrymandered congressional districts violated the Equal Protection Clause?',
 ARRAY['Gomillion v. Lightfoot','Shaw v. Reno','Miller v. Johnson','Thornburg v. Gingles'],
 'Shaw v. Reno', 'US History', 8),
('The Compromise of 1850 included which of the following provisions?',
 ARRAY['Banning slavery in all new western territories','Admitting California as a free state','Granting statehood to Kansas and Nebraska','Repealing the Missouri Compromise'],
 'Admitting California as a free state', 'US History', 5),
('Which president oversaw the completion of the first transcontinental railroad in 1869?',
 ARRAY['Abraham Lincoln','Andrew Johnson','Ulysses S. Grant','Rutherford B. Hayes'],
 'Ulysses S. Grant', 'US History', 5),
('What was the primary purpose of the Dawes Act of 1887?',
 ARRAY['To grant citizenship to all Native Americans','To divide tribal lands into individual allotments for Native Americans','To create reservations for Native American tribes','To establish trading rights between Native Americans and settlers'],
 'To divide tribal lands into individual allotments for Native Americans', 'US History', 7),
('How many justices currently serve on the United States Supreme Court?',
 ARRAY['7','8','9','11'],
 '9', 'Civics', 1),
('Which branch of the U.S. government has the power to declare war?',
 ARRAY['Executive','Judicial','Legislative','Military'],
 'Legislative', 'Civics', 2),
('What is the minimum age requirement to serve as a U.S. Senator?',
 ARRAY['25','30','35','40'],
 '30', 'Civics', 5),
('Under the U.S. Constitution, which clause requires that laws enacted by Congress take precedence over conflicting state laws?',
 ARRAY['Commerce Clause','Supremacy Clause','Establishment Clause','Preemption Clause'],
 'Supremacy Clause', 'Civics', 5),
('Which U.S. Supreme Court case established that the Bill of Rights protections apply to state governments through the 14th Amendment?',
 ARRAY['Gitlow v. New York','Palko v. Connecticut','Mapp v. Ohio','Barron v. Baltimore'],
 'Gitlow v. New York', 'Civics', 8);