-- Seed 200 additional questions across all 9 categories
-- Same category/difficulty proportions as 009_seed_questions.sql
-- Difficulty: 1-3 = easy, 4-6 = medium, 7-9 = hard

INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which amendment to the US Constitution abolished poll taxes in federal elections?',
 ARRAY['21st Amendment','22nd Amendment','24th Amendment','25th Amendment'],
 '24th Amendment', 'Civics', 1),
('What is the minimum age requirement to serve as President of the United States?',
 ARRAY['30','35','40','25'],
 '35', 'Civics', 2),
('Which branch of the US government is responsible for interpreting laws?',
 ARRAY['Executive','Legislative','Judicial','Administrative'],
 'Judicial', 'Civics', 2),
('How many years is a US Senator''s term?',
 ARRAY['2','4','6','8'],
 '6', 'Civics', 3),
('The Bill of Rights consists of how many amendments?',
 ARRAY['8','10','12','15'],
 '10', 'Civics', 3),
('Which amendment gives citizens the right to a speedy and public trial?',
 ARRAY['5th Amendment','6th Amendment','7th Amendment','8th Amendment'],
 '6th Amendment', 'Civics', 2),
('What term describes the process by which a foreign national becomes a US citizen?',
 ARRAY['Immigration','Naturalization','Assimilation','Registration'],
 'Naturalization', 'Civics', 3),
('Which document outlines the duties and powers of the three branches of government?',
 ARRAY['The Federalist Papers','The Articles of Confederation','The Constitution','The Magna Carta'],
 'The Constitution', 'Civics', 1),
('How many electoral votes are needed to win the presidency?',
 ARRAY['250','270','300','320'],
 '270', 'Civics', 2),
('Which amendment protects citizens from being forced to testify against themselves?',
 ARRAY['4th Amendment','5th Amendment','6th Amendment','8th Amendment'],
 '5th Amendment', 'Civics', 4),
('What is the official term for the first ten amendments to the Constitution?',
 ARRAY['The Constitutional Amendments','The Bill of Rights','The Founding Clauses','The Liberty Articles'],
 'The Bill of Rights', 'Civics', 4),
('Which clause of the Constitution requires each state to honor the laws of other states?',
 ARRAY['Commerce Clause','Equal Protection Clause','Full Faith and Credit Clause','Privileges and Immunities Clause'],
 'Full Faith and Credit Clause', 'Civics', 5),
('Which article of the Constitution establishes the Executive Branch?',
 ARRAY['Article I','Article II','Article III','Article IV'],
 'Article II', 'Civics', 5),
('What is the term for the president''s power to reject legislation passed by Congress?',
 ARRAY['Filibuster','Veto','Pocket veto','Line-item veto'],
 'Veto', 'Civics', 4),
('What constitutional concept prevents any one branch of government from becoming too powerful?',
 ARRAY['Federalism','Separation of powers','Judicial review','Popular sovereignty'],
 'Separation of powers', 'Civics', 5),
('Which amendment to the Constitution banned the manufacture and sale of alcohol?',
 ARRAY['16th Amendment','17th Amendment','18th Amendment','19th Amendment'],
 '18th Amendment', 'Civics', 6),
('How long is the term of a US Supreme Court Justice?',
 ARRAY['10 years','20 years','Life tenure','Until age 75'],
 'Life tenure', 'Civics', 6),
('Which landmark Supreme Court case established the principle of one person, one vote in state legislative districts?',
 ARRAY['Baker v. Carr','Reynolds v. Sims','Wesberry v. Sanders','Gray v. Sanders'],
 'Reynolds v. Sims', 'Civics', 6),
('What constitutional clause gives Congress implied powers beyond those explicitly listed?',
 ARRAY['Commerce Clause','Supremacy Clause','Necessary and Proper Clause','Elastic Clause'],
 'Necessary and Proper Clause', 'Civics', 4),
('Which amendment grants Congress the power to levy income taxes?',
 ARRAY['15th Amendment','16th Amendment','17th Amendment','19th Amendment'],
 '16th Amendment', 'Civics', 7),
('What is the constitutional term for the number of congressional representatives needed to conduct official business?',
 ARRAY['Majority','Quorum','Plurality','Filibuster'],
 'Quorum', 'Civics', 7),
('Which Supreme Court case held that the Constitution''s protection against self-incrimination applies to police interrogations?',
 ARRAY['Gideon v. Wainwright','Miranda v. Arizona','Mapp v. Ohio','Escobedo v. Illinois'],
 'Miranda v. Arizona', 'Civics', 8),
('Under the Constitution, who has the power to declare war?',
 ARRAY['The President','The Secretary of Defense','Congress','The Joint Chiefs of Staff'],
 'Congress', 'Civics', 7),
('Which doctrine, established in McCulloch v. Maryland, affirmed federal power over states?',
 ARRAY['Supremacy Doctrine','Nullification Doctrine','Implied Powers Doctrine','Commerce Doctrine'],
 'Implied Powers Doctrine', 'Civics', 8),
('How many states must ratify a constitutional amendment for it to become law?',
 ARRAY['Two-thirds','Three-fourths','Simple majority','Four-fifths'],
 'Three-fourths', 'Civics', 8),
('Which constitutional provision requires that the President be a natural-born citizen?',
 ARRAY['Article I, Section 2','Article II, Section 1','Article III, Section 2','Amendment XII'],
 'Article II, Section 1', 'Civics', 9),
('What is the constitutional term for the formal accusation of a federal official by the House of Representatives?',
 ARRAY['Censure','Indictment','Impeachment','Removal'],
 'Impeachment', 'Civics', 9),
('Which Supreme Court case ruled that political spending is a form of protected free speech under the First Amendment?',
 ARRAY['Buckley v. Valeo','Citizens United v. FEC','McConnell v. FEC','First National Bank v. Bellotti'],
 'Citizens United v. FEC', 'Civics', 9),
('In which city was the US Constitution signed?',
 ARRAY['New York City','Boston','Philadelphia','Washington DC'],
 'Philadelphia', 'Civics', 5),
('What was the first permanent English settlement in America, established in 1607?',
 ARRAY['Plymouth','Roanoke','Jamestown','St. Augustine'],
 'Jamestown', 'Civics', 6),
('Which war was fought between the United States and Mexico from 1846 to 1848?',
 ARRAY['The War of 1812','The Mexican-American War','The Spanish-American War','The Texas Revolution'],
 'The Mexican-American War', 'US History', 1),
('Who was the US President during World War I?',
 ARRAY['Theodore Roosevelt','William Howard Taft','Woodrow Wilson','Warren G. Harding'],
 'Woodrow Wilson', 'US History', 1),
('Which treaty ended the Spanish-American War in 1898?',
 ARRAY['Treaty of Versailles','Treaty of Paris','Treaty of Guadalupe Hidalgo','Treaty of Madrid'],
 'Treaty of Paris', 'US History', 2),
('What nickname was given to the 1920s era of economic prosperity and cultural change?',
 ARRAY['The Golden Age','The Jazz Age','The Progressive Era','The Gilded Age'],
 'The Jazz Age', 'US History', 2),
('Which president issued the Monroe Doctrine warning European powers against colonizing the Americas?',
 ARRAY['George Washington','John Adams','James Monroe','Andrew Jackson'],
 'James Monroe', 'US History', 3),
('What was the name of the US military alliance formed after World War II to counter Soviet expansion?',
 ARRAY['League of Nations','The Marshall Plan','NATO','SEATO'],
 'NATO', 'US History', 3),
('Which year did the United States enter World War II following the attack on Pearl Harbor?',
 ARRAY['1939','1940','1941','1942'],
 '1941', 'US History', 1),
('What was the name of the economic recovery program introduced by FDR in the 1930s?',
 ARRAY['The Fair Deal','The New Deal','The Square Deal','The Great Society'],
 'The New Deal', 'US History', 2),
('Who was the first American to travel in space?',
 ARRAY['John Glenn','Buzz Aldrin','Alan Shepard','Scott Carpenter'],
 'Alan Shepard', 'US History', 3),
('Which amendment gave women the right to vote in 1920?',
 ARRAY['17th Amendment','18th Amendment','19th Amendment','20th Amendment'],
 '19th Amendment', 'US History', 1),
('What was the main cause of the Dust Bowl during the 1930s?',
 ARRAY['Flooding','Volcanic eruptions','Drought and poor farming practices','Deforestation'],
 'Drought and poor farming practices', 'US History', 2),
('Which US President ordered the integration of the US military with Executive Order 9981?',
 ARRAY['Franklin D. Roosevelt','Harry S. Truman','Dwight D. Eisenhower','John F. Kennedy'],
 'Harry S. Truman', 'US History', 3),
('What was the name of the 1944 Allied invasion of Normandy, France?',
 ARRAY['Operation Market Garden','Operation Torch','Operation Overlord','Operation Barbarossa'],
 'Operation Overlord', 'US History', 4),
('Which Native American leader led the Sioux at the Battle of Little Bighorn?',
 ARRAY['Geronimo','Crazy Horse','Sitting Bull','Red Cloud'],
 'Crazy Horse', 'US History', 4),
('What was the primary goal of the Marshall Plan after World War II?',
 ARRAY['Rebuilding European economies','Establishing NATO','Containing Soviet expansion in Asia','Rebuilding Japan'],
 'Rebuilding European economies', 'US History', 5),
('Which event triggered the US entry into the Korean War in 1950?',
 ARRAY['Soviet invasion of South Korea','North Korean invasion of South Korea','Chinese invasion of South Korea','Attack on a US military base'],
 'North Korean invasion of South Korea', 'US History', 5),
('What was the name of the first artificial satellite launched by the US in 1958?',
 ARRAY['Explorer 1','Vanguard 1','Pioneer 1','Sputnik 2'],
 'Explorer 1', 'US History', 5),
('Which president signed the National Security Act of 1947 that created the CIA and modern military structure?',
 ARRAY['Franklin D. Roosevelt','Harry S. Truman','Dwight D. Eisenhower','John F. Kennedy'],
 'Harry S. Truman', 'US History', 4),
('What was the main purpose of the GI Bill passed in 1944?',
 ARRAY['Drafting soldiers for WWII','Providing benefits to returning veterans','Establishing the VA hospital system','Funding the Manhattan Project'],
 'Providing benefits to returning veterans', 'US History', 6),
('Which event is considered the start of the Space Race between the US and Soviet Union?',
 ARRAY['The launch of Apollo 1','The launch of Sputnik','The Mercury program','The launch of Explorer 1'],
 'The launch of Sputnik', 'US History', 6),
('What was the name of the 1973 agreement that ended direct US military involvement in Vietnam?',
 ARRAY['Paris Peace Accords','Geneva Accords','Camp David Accords','Hanoi Agreement'],
 'Paris Peace Accords', 'US History', 6),
('Which president established the Peace Corps in 1961?',
 ARRAY['Harry S. Truman','Dwight D. Eisenhower','John F. Kennedy','Lyndon B. Johnson'],
 'John F. Kennedy', 'US History', 4),
('What was the name of the Supreme Court case that ruled school prayer unconstitutional?',
 ARRAY['Abington School District v. Schempp','Engel v. Vitale','Lee v. Weisman','Santa Fe ISD v. Doe'],
 'Engel v. Vitale', 'US History', 7),
('Which US military operation removed Manuel Noriega from power in Panama in 1989?',
 ARRAY['Operation Just Cause','Operation Urgent Fury','Operation Eagle Claw','Operation Desert Storm'],
 'Operation Just Cause', 'US History', 7),
('What was the Taft-Hartley Act of 1947 primarily concerned with?',
 ARRAY['Regulating labor unions','Expanding Social Security','Establishing NATO','Desegregating the military'],
 'Regulating labor unions', 'US History', 7),
('Which president was in office when the Berlin Wall fell in 1989?',
 ARRAY['Ronald Reagan','Jimmy Carter','George H.W. Bush','Bill Clinton'],
 'George H.W. Bush', 'US History', 5),
('What was the name of the program that brought over 400,000 Nazi scientists and engineers to the US after WWII?',
 ARRAY['Operation Paperclip','Operation Overcast','Operation Epsilon','Operation Lusty'],
 'Operation Paperclip', 'US History', 8),
('Which US Supreme Court decision in 1973 established a constitutional right to abortion?',
 ARRAY['Planned Parenthood v. Casey','Roe v. Wade','Griswold v. Connecticut','Doe v. Bolton'],
 'Roe v. Wade', 'US History', 8),
('What was the name of the scandal that led to President Nixon''s resignation in 1974?',
 ARRAY['Iran-Contra Affair','Teapot Dome Scandal','Watergate Scandal','Whitewater Scandal'],
 'Watergate Scandal', 'US History', 8),
('Which US constitutional amendment lowered the voting age from 21 to 18 in 1971?',
 ARRAY['24th Amendment','25th Amendment','26th Amendment','27th Amendment'],
 '26th Amendment', 'US History', 9),
('What was the name of the federal program established in 1965 to provide healthcare for the elderly?',
 ARRAY['Medicaid','Medicare','Social Security','Veterans'' Administration'],
 'Medicare', 'US History', 9),
('Which treaty, signed in 1987 between the US and USSR, eliminated an entire class of nuclear weapons?',
 ARRAY['SALT I','SALT II','START Treaty','Intermediate-Range Nuclear Forces Treaty'],
 'Intermediate-Range Nuclear Forces Treaty', 'US History', 9),
('What is the capital of the US state of Texas?',
 ARRAY['Houston','Dallas','San Antonio','Austin'],
 'Austin', 'Geography', 1),
('Which US state is known as the "Peach State"?',
 ARRAY['South Carolina','Georgia','Florida','Alabama'],
 'Georgia', 'Geography', 1),
('Which ocean borders the western coast of the United States?',
 ARRAY['Arctic Ocean','Atlantic Ocean','Pacific Ocean','Indian Ocean'],
 'Pacific Ocean', 'Geography', 2),
('What is the largest state in the contiguous United States by area?',
 ARRAY['California','Montana','Texas','New Mexico'],
 'Texas', 'Geography', 2),
('Which Great Lake is the largest by surface area?',
 ARRAY['Lake Michigan','Lake Erie','Lake Superior','Lake Huron'],
 'Lake Superior', 'Geography', 3),
('What river forms the boundary between Illinois and Missouri?',
 ARRAY['Ohio River','Missouri River','Mississippi River','Illinois River'],
 'Mississippi River', 'Geography', 3),
('Which US state shares a border with Canada and is located in New England?',
 ARRAY['Vermont','New Hampshire','Massachusetts','Connecticut'],
 'Vermont', 'Geography', 1),
('What is the name of the large peninsula that forms the southwestern tip of Florida?',
 ARRAY['Cape Canaveral','The Florida Keys','The Yucatan Peninsula','The Florida Panhandle'],
 'The Florida Panhandle', 'Geography', 2),
('In which state is the Grand Canyon located?',
 ARRAY['Utah','Nevada','New Mexico','Arizona'],
 'Arizona', 'Geography', 3),
('Which US mountain range runs along the Pacific coast of the Pacific Northwest?',
 ARRAY['Rocky Mountains','Sierra Nevada','Cascade Range','Coast Ranges'],
 'Cascade Range', 'Geography', 4),
('What is the name of the fertile agricultural valley in central California?',
 ARRAY['Napa Valley','Sacramento Valley','San Joaquin Valley','Central Valley'],
 'Central Valley', 'Geography', 5),
('Which US state contains the largest number of active volcanoes?',
 ARRAY['Hawaii','Alaska','Washington','California'],
 'Alaska', 'Geography', 4),
('What is the name of the desert that covers much of southern Nevada and extends into California?',
 ARRAY['Sonoran Desert','Great Basin Desert','Mojave Desert','Chihuahuan Desert'],
 'Mojave Desert', 'Geography', 5),
('Which river drains into the Gulf of Mexico and is the longest river system in North America?',
 ARRAY['Colorado River','Missouri River','Mississippi River','Arkansas River'],
 'Mississippi River', 'Geography', 5),
('What is the easternmost point of the contiguous United States?',
 ARRAY['Cape Cod, Massachusetts','Cape Hatteras, North Carolina','West Quoddy Head, Maine','Cape Fear, North Carolina'],
 'West Quoddy Head, Maine', 'Geography', 6),
('Which US state has the longest coastline among the contiguous 48 states?',
 ARRAY['California','Texas','Florida','Maine'],
 'Florida', 'Geography', 6),
('What is the name of the large island off the coast of Maine that is home to Acadia National Park?',
 ARRAY['Nantucket Island','Block Island','Mount Desert Island','Long Island'],
 'Mount Desert Island', 'Geography', 6),
('Which state contains Death Valley, the lowest point in North America?',
 ARRAY['Nevada','Arizona','Utah','California'],
 'California', 'Geography', 7),
('What is the name of the underwater volcanic chain in the Pacific that formed the Hawaiian Islands?',
 ARRAY['Juan de Fuca Ridge','Emperor Seamount Chain','Pacific Ring of Fire','Mid-Pacific Ridge'],
 'Emperor Seamount Chain', 'Geography', 7),
('Which US city is located at the confluence of the Ohio and Mississippi Rivers?',
 ARRAY['Memphis, Tennessee','Cairo, Illinois','Paducah, Kentucky','Natchez, Mississippi'],
 'Cairo, Illinois', 'Geography', 7),
('What is the name of the large estuary system in the mid-Atlantic region fed by over 150 tributaries?',
 ARRAY['Long Island Sound','Delaware Bay','Chesapeake Bay','Pamlico Sound'],
 'Chesapeake Bay', 'Geography', 8),
('Which US state contains the Ouachita Mountains?',
 ARRAY['Mississippi','Alabama','Arkansas','Tennessee'],
 'Arkansas', 'Geography', 8),
('What is the name of the geographic region in the southeastern US characterized by flat, low-lying terrain and subtropical climate?',
 ARRAY['Gulf Coastal Plain','Mississippi Embayment','Florida Platform','Sea Island Coast'],
 'Gulf Coastal Plain', 'Geography', 8),
('Which peninsula separates the Chesapeake Bay from the Atlantic Ocean?',
 ARRAY['Cape Cod','Delmarva Peninsula','Cape Hatteras','Eastern Shore'],
 'Delmarva Peninsula', 'Geography', 9),
('What geological feature divides North America into Atlantic and Pacific watersheds?',
 ARRAY['The Appalachian Mountains','The Sierra Nevada','The Continental Divide','The Rocky Mountain Front'],
 'The Continental Divide', 'Geography', 9),
('In which US state is the source of the Missouri River located?',
 ARRAY['Wyoming','Colorado','Montana','South Dakota'],
 'Montana', 'Geography', 9),
('Which famous American landmark was completed in 1884 and stands at the center of Washington DC?',
 ARRAY['US Capitol Building','Lincoln Memorial','Washington Monument','Jefferson Memorial'],
 'Washington Monument', 'Landmarks', 1),
('In which city is the famous Pike Place Market located?',
 ARRAY['Portland','San Francisco','Seattle','Vancouver'],
 'Seattle', 'Landmarks', 1),
('What is the name of the historic street in New Orleans famous for its nightlife and jazz music?',
 ARRAY['Canal Street','Magazine Street','Bourbon Street','St. Charles Avenue'],
 'Bourbon Street', 'Landmarks', 2),
('Which famous bridge spans the San Francisco Bay between San Francisco and Oakland?',
 ARRAY['Golden Gate Bridge','Bay Bridge','Richmond Bridge','San Mateo Bridge'],
 'Bay Bridge', 'Landmarks', 2),
('In which state is the Alamo located?',
 ARRAY['Arizona','New Mexico','Texas','Louisiana'],
 'Texas', 'Landmarks', 3),
('What is the name of the large art museum located on Fifth Avenue in New York City?',
 ARRAY['Museum of Modern Art','Guggenheim Museum','Whitney Museum','Metropolitan Museum of Art'],
 'Metropolitan Museum of Art', 'Landmarks', 3),
('Which city is home to the famous French Quarter historic district?',
 ARRAY['Atlanta','Savannah','New Orleans','Charleston'],
 'New Orleans', 'Landmarks', 1),
('What is the name of the massive stone faces carved into Mount Rushmore in South Dakota?',
 ARRAY['Presidents'' Monument','Mount Rushmore National Memorial','Four Faces of Freedom','Presidential Sculpture'],
 'Mount Rushmore National Memorial', 'Landmarks', 4),
('In which state is the Rock and Roll Hall of Fame located?',
 ARRAY['Michigan','Ohio','Illinois','Pennsylvania'],
 'Ohio', 'Landmarks', 4),
('What is the name of the famous curved glass building that houses NASA''s Johnson Space Center visitor complex?',
 ARRAY['Space Center Houston','Kennedy Space Center','Astronaut Hall of Fame','NASA Visitor Center'],
 'Space Center Houston', 'Landmarks', 5),
('Which US landmark is known as the "Gateway to the West" and stands 630 feet tall?',
 ARRAY['Gateway Arch','St. Louis Cathedral','Sears Tower','Transamerica Pyramid'],
 'Gateway Arch', 'Landmarks', 5),
('In which city is the famous Riverwalk located along the San Antonio River?',
 ARRAY['Houston','Dallas','Austin','San Antonio'],
 'San Antonio', 'Landmarks', 5),
('What is the name of the historic fort in Charleston, South Carolina where the first shots of the Civil War were fired?',
 ARRAY['Fort Sumter','Fort Moultrie','Fort Johnson','Fort Wagner'],
 'Fort Sumter', 'Landmarks', 4),
('Which famous art deco skyscraper in New York City was the world''s tallest building when it opened in 1931?',
 ARRAY['Chrysler Building','Empire State Building','30 Rockefeller Plaza','One World Trade Center'],
 'Empire State Building', 'Landmarks', 6),
('What is the name of the large natural bridge in Virginia that was once owned by Thomas Jefferson?',
 ARRAY['Natural Bridge','Skyline Bridge','Jefferson Arch','Blue Ridge Bridge'],
 'Natural Bridge', 'Landmarks', 6),
('In which US city is the famous Fenway Park baseball stadium located?',
 ARRAY['New York','Chicago','Boston','Philadelphia'],
 'Boston', 'Landmarks', 6),
('What is the name of the historic trading post and military outpost established in 1833 that is now a national historic site in Colorado?',
 ARRAY['Bent''s Old Fort','Fort Union','Fort Laramie','Fort Vasquez'],
 'Bent''s Old Fort', 'Landmarks', 7),
('Which famous mansion in Newport, Rhode Island was built by the Vanderbilt family and is known as "The Breakers"?',
 ARRAY['Marble House','Rosecliff','Belcourt Castle','The Breakers'],
 'The Breakers', 'Landmarks', 7),
('In which US city is the famous Graceland mansion, home of Elvis Presley, located?',
 ARRAY['Nashville','Memphis','Birmingham','Atlanta'],
 'Memphis', 'Landmarks', 7),
('What is the name of the lighthouse at the tip of Cape Hatteras that is the tallest brick lighthouse in the US?',
 ARRAY['Cape Lookout Lighthouse','Ocracoke Lighthouse','Bodie Island Lighthouse','Cape Hatteras Lighthouse'],
 'Cape Hatteras Lighthouse', 'Landmarks', 8),
('Which famous building in Chicago was the world''s tallest from 1973 to 1998?',
 ARRAY['John Hancock Center','Aon Center','Willis Tower','Tribune Tower'],
 'Willis Tower', 'Landmarks', 8),
('What is the name of the historic cemetery in Gettysburg, Pennsylvania where Lincoln delivered the Gettysburg Address?',
 ARRAY['Gettysburg National Cemetery','Soldiers'' National Cemetery','Cemetery Hill','Evergreen Cemetery'],
 'Soldiers'' National Cemetery', 'Landmarks', 9),
('Which branch of the US military is the oldest?',
 ARRAY['Navy','Marine Corps','Army','Coast Guard'],
 'Army', 'Military', 1),
('What is the name of the highest military decoration awarded by the United States?',
 ARRAY['Distinguished Service Medal','Silver Star','Bronze Star','Medal of Honor'],
 'Medal of Honor', 'Military', 1),
('In which state is the US Naval Academy located?',
 ARRAY['Virginia','Georgia','South Carolina','Maryland'],
 'Maryland', 'Military', 2),
('What was the code name for the US military operation that began the Persian Gulf War in 1991?',
 ARRAY['Operation Desert Shield','Operation Desert Storm','Operation Desert Sabre','Operation Eagle Claw'],
 'Operation Desert Storm', 'Military', 2),
('Which famous battle of the Revolutionary War in 1777 is considered the turning point that brought France into the war?',
 ARRAY['Battle of Brandywine','Battle of Yorktown','Battle of Saratoga','Battle of Bunker Hill'],
 'Battle of Saratoga', 'Military', 3),
('How many branches make up the US Armed Forces?',
 ARRAY['4','5','6','7'],
 '6', 'Military', 3),
('Who commanded US forces at the Battle of Yorktown, which effectively ended the Revolutionary War?',
 ARRAY['Benjamin Franklin','Alexander Hamilton','George Washington','Nathanael Greene'],
 'George Washington', 'Military', 1),
('What was the name of the first US aircraft carrier commissioned, in 1927?',
 ARRAY['USS Ranger','USS Saratoga','USS Langley','USS Lexington'],
 'USS Langley', 'Military', 4),
('Which US military operation in 1983 was the invasion of the Caribbean island of Grenada?',
 ARRAY['Operation Just Cause','Operation Urgent Fury','Operation Eagle Claw','Operation Blue Spoon'],
 'Operation Urgent Fury', 'Military', 4),
('In which war did the US military first use paratroopers in large-scale combat operations?',
 ARRAY['World War I','World War II','Korean War','Vietnam War'],
 'World War II', 'Military', 5),
('What is the name of the military doctrine developed after Vietnam that required clear objectives before committing troops?',
 ARRAY['Eisenhower Doctrine','Truman Doctrine','Powell Doctrine','Reagan Doctrine'],
 'Powell Doctrine', 'Military', 5),
('Which US military branch was created as a separate service in 1947, previously part of the Army?',
 ARRAY['Marine Corps','Coast Guard','Air Force','Space Force'],
 'Air Force', 'Military', 5),
('What was the name of the US naval warship that exploded in Havana Harbor in 1898, helping trigger the Spanish-American War?',
 ARRAY['USS Maine','USS Arizona','USS Missouri','USS New York'],
 'USS Maine', 'Military', 4),
('Which battle in the Pacific during WWII is considered the largest naval battle in history?',
 ARRAY['Battle of Midway','Battle of the Coral Sea','Battle of Leyte Gulf','Battle of Guadalcanal'],
 'Battle of Leyte Gulf', 'Military', 6),
('What was the name of the covert US military operation during the Korean War that involved amphibious landings at Inchon?',
 ARRAY['Operation Chromite','Operation Ripper','Operation Killer','Operation Thunderbolt'],
 'Operation Chromite', 'Military', 6),
('Which military academy was established by Congress in 1802?',
 ARRAY['US Naval Academy','US Air Force Academy','US Military Academy at West Point','Virginia Military Institute'],
 'US Military Academy at West Point', 'Military', 6),
('What was the name of the US military''s strategic bombing campaign against North Vietnam in 1972?',
 ARRAY['Operation Rolling Thunder','Operation Arc Light','Operation Linebacker II','Operation Freedom Train'],
 'Operation Linebacker II', 'Military', 7),
('Which general led US forces during the Korean War before being relieved by President Truman?',
 ARRAY['Omar Bradley','Matthew Ridgway','Douglas MacArthur','Mark Clark'],
 'Douglas MacArthur', 'Military', 7),
('What is the name of the US Army''s elite airborne division known as the "Screaming Eagles"?',
 ARRAY['82nd Airborne Division','101st Airborne Division','173rd Airborne Brigade','10th Mountain Division'],
 '101st Airborne Division', 'Military', 8),
('Which US military operation in 1980 attempted to rescue American hostages in Iran but failed due to helicopter malfunctions?',
 ARRAY['Operation Eagle Claw','Operation Nimrod','Operation Rice Bowl','Operation Credible Sport'],
 'Operation Eagle Claw', 'Military', 8),
('What was the name of the US Navy''s classified intelligence program that detected Soviet submarine communications using underwater hydrophones?',
 ARRAY['Project SOSUS','Project CAESAR','Project Jennifer','Operation Ivy Bells'],
 'Project SOSUS', 'Military', 9),
('Which military branch''s motto is "Semper Fidelis" (Always Faithful)?',
 ARRAY['US Army','US Navy','US Marine Corps','US Coast Guard'],
 'US Marine Corps', 'Military', 9),
('What year was Yellowstone established as the first national park in the United States?',
 ARRAY['1865','1872','1880','1890'],
 '1872', 'National Parks', 1),
('In which state is Joshua Tree National Park located?',
 ARRAY['Nevada','Utah','Arizona','California'],
 'California', 'National Parks', 1),
('What is the name of the national park in Utah known for its red rock spires called "hoodoos"?',
 ARRAY['Zion','Capitol Reef','Bryce Canyon','Canyonlands'],
 'Bryce Canyon', 'National Parks', 2),
('Which national park is home to the world''s largest geyser field?',
 ARRAY['Lassen Volcanic','Craters of the Moon','Yellowstone','Hawaii Volcanoes'],
 'Yellowstone', 'National Parks', 2),
('In which state is Shenandoah National Park located?',
 ARRAY['West Virginia','North Carolina','Tennessee','Virginia'],
 'Virginia', 'National Parks', 3),
('What is the name of the national park that protects the largest temperate rainforest in the US?',
 ARRAY['Redwood National Park','Olympic National Park','Hoh Rainforest','Tongass National Forest'],
 'Olympic National Park', 'National Parks', 3),
('Which national park contains the lowest point in the Western Hemisphere?',
 ARRAY['Joshua Tree','Death Valley','Great Basin','Mojave'],
 'Death Valley', 'National Parks', 1),
('What is the name of the national park that spans the border between Wyoming and Montana and features a large caldera?',
 ARRAY['Grand Teton','Glacier','Yellowstone','Bighorn Canyon'],
 'Yellowstone', 'National Parks', 4),
('In which state is Cuyahoga Valley National Park located?',
 ARRAY['Michigan','Indiana','Pennsylvania','Ohio'],
 'Ohio', 'National Parks', 4),
('What is the name of the national park on a remote island in Lake Superior accessible only by boat or floatplane?',
 ARRAY['Pictured Rocks','Sleeping Bear Dunes','Apostle Islands','Isle Royale'],
 'Isle Royale', 'National Parks', 5),
('Which national park in Alaska is larger than the entire country of Switzerland?',
 ARRAY['Denali','Katmai','Wrangell-St. Elias','Gates of the Arctic'],
 'Wrangell-St. Elias', 'National Parks', 5),
('What is the name of the national park in New Mexico that contains one of the world''s largest cave systems?',
 ARRAY['White Sands','Guadalupe Mountains','Carlsbad Caverns','Big Bend'],
 'Carlsbad Caverns', 'National Parks', 5),
('Which national park is home to the ancient bristlecone pine trees, some of the oldest living organisms on Earth?',
 ARRAY['Great Basin','Sequoia','Kings Canyon','Joshua Tree'],
 'Great Basin', 'National Parks', 4),
('What is the name of the national park in North Dakota that preserves the area where Theodore Roosevelt ranched and developed his conservation philosophy?',
 ARRAY['Wind Cave','Badlands','Theodore Roosevelt','Knife River'],
 'Theodore Roosevelt', 'National Parks', 6),
('In which state is Everglades National Park located?',
 ARRAY['Georgia','Alabama','Mississippi','Florida'],
 'Florida', 'National Parks', 6),
('What national park along the Colorado River in Utah is known for its remarkable maze of canyons?',
 ARRAY['Arches','Zion','Canyonlands','Capitol Reef'],
 'Canyonlands', 'National Parks', 6),
('Which national park protects the largest remaining old-growth forest east of the Mississippi River?',
 ARRAY['Shenandoah','Great Smoky Mountains','Congaree','Mammoth Cave'],
 'Congaree', 'National Parks', 7),
('What is the name of the national park in Hawaii that is home to Kilauea, one of the world''s most active volcanoes?',
 ARRAY['Haleakala','Hawaii Volcanoes','Kaloko-Honokohau','Pu''uhonua o Honaunau'],
 'Hawaii Volcanoes', 'National Parks', 7),
('Which national park in Florida consists of 143 square miles of open water and coral reef and is only accessible by boat?',
 ARRAY['Everglades','Biscayne','Dry Tortugas','Big Cypress'],
 'Dry Tortugas', 'National Parks', 8),
('What is the name of the national park in South Dakota that contains fossil beds and rugged badlands formations?',
 ARRAY['Wind Cave','Jewel Cave','Badlands','Theodore Roosevelt'],
 'Badlands', 'National Parks', 8),
('Which national park shares its name with a mountain range and is the only national park in New Jersey?',
 ARRAY['Sandy Hook','Delaware Water Gap','Pinelands','Gateway'],
 'Delaware Water Gap', 'National Parks', 9),
('Who composed the famous patriotic song "God Bless America"?',
 ARRAY['John Philip Sousa','Stephen Foster','Irving Berlin','Cole Porter'],
 'Irving Berlin', 'American Culture', 1),
('What is the name of the annual horse race held on the first Saturday in May in Louisville, Kentucky?',
 ARRAY['Preakness Stakes','Belmont Stakes','Kentucky Derby','Breeders'' Cup'],
 'Kentucky Derby', 'American Culture', 1),
('Which American author wrote the novel "The Grapes of Wrath"?',
 ARRAY['Ernest Hemingway','William Faulkner','John Steinbeck','F. Scott Fitzgerald'],
 'John Steinbeck', 'American Culture', 2),
('What is the name of the famous festival held annually in Austin, Texas celebrating music, film, and interactive media?',
 ARRAY['Lollapalooza','Bonnaroo','Coachella','South by Southwest'],
 'South by Southwest', 'American Culture', 2),
('Which American holiday is celebrated on the fourth Thursday of November?',
 ARRAY['Labor Day','Columbus Day','Thanksgiving','Veterans Day'],
 'Thanksgiving', 'American Culture', 3),
('What is the name of the iconic American style of music that originated in the Mississippi Delta in the late 19th century?',
 ARRAY['Country music','Jazz','Blues','Gospel'],
 'Blues', 'American Culture', 3),
('Which famous American poet wrote "The Raven" in 1845?',
 ARRAY['Walt Whitman','Henry Wadsworth Longfellow','Edgar Allan Poe','Ralph Waldo Emerson'],
 'Edgar Allan Poe', 'American Culture', 1),
('What is the name of the annual awards ceremony that honors excellence in American film, hosted by the Academy of Motion Picture Arts and Sciences?',
 ARRAY['Emmy Awards','Grammy Awards','Tony Awards','Academy Awards'],
 'Academy Awards', 'American Culture', 4),
('Which famous American holiday is celebrated on July 4th?',
 ARRAY['Memorial Day','Flag Day','Independence Day','Constitution Day'],
 'Independence Day', 'American Culture', 4),
('What is the name of the cultural movement in the 1960s that emphasized peace, love, and social change?',
 ARRAY['Beat Generation','The New Deal','Counterculture movement','Civil Rights Movement'],
 'Counterculture movement', 'American Culture', 5),
('Which famous American comic strip featuring a beagle named Snoopy was created by Charles Schulz?',
 ARRAY['Garfield','Peanuts','Beetle Bailey','Blondie'],
 'Peanuts', 'American Culture', 5),
('What is the name of the style of American folk music originating in Appalachia that uses banjo, fiddle, and mandolin?',
 ARRAY['Zydeco','Bluegrass','Western swing','Cajun music'],
 'Bluegrass', 'American Culture', 5),
('What is the name of the famous street in Nashville, Tennessee known for its country music honky-tonks?',
 ARRAY['Music Row','Lower Broadway','The Strip','Printer''s Alley'],
 'Lower Broadway', 'American Culture', 6),
('Which American author wrote "The Catcher in the Rye" published in 1951?',
 ARRAY['Jack Kerouac','J.D. Salinger','Truman Capote','Norman Mailer'],
 'J.D. Salinger', 'American Culture', 6),
('What is the name of the traditional American pottery style developed by Native Americans in the Southwest?',
 ARRAY['Delftware','Pueblo pottery','Majolica','Bennington ware'],
 'Pueblo pottery', 'American Culture', 7),
('What is the name of the American artistic tradition of creating quilts that served as coded maps for escaping slaves on the Underground Railroad?',
 ARRAY['Freedom quilts','Liberty quilts','Underground quilts','Signal quilts'],
 'Freedom quilts', 'American Culture', 9),
('Which famous American inventor held over 1,000 patents and established the first industrial research laboratory?',
 ARRAY['Nikola Tesla','Thomas Edison','Alexander Graham Bell','George Westinghouse'],
 'Thomas Edison', 'Famous Americans', 1),
('Who was the first African American to win the Nobel Peace Prize?',
 ARRAY['Martin Luther King Jr.','Ralph Bunche','Barack Obama','Jesse Jackson'],
 'Ralph Bunche', 'Famous Americans', 2),
('Which famous American author wrote the adventure novel "Moby-Dick" published in 1851?',
 ARRAY['Nathaniel Hawthorne','Herman Melville','James Fenimore Cooper','Mark Twain'],
 'Herman Melville', 'Famous Americans', 2),
('Who was the first woman to serve as a US Supreme Court Justice?',
 ARRAY['Ruth Bader Ginsburg','Sonia Sotomayor','Sandra Day O''Connor','Elena Kagan'],
 'Sandra Day O''Connor', 'Famous Americans', 3),
('Which famous American physicist developed the theory of general relativity and won the Nobel Prize in Physics?',
 ARRAY['Nikola Tesla','Albert Einstein','Richard Feynman','Robert Oppenheimer'],
 'Albert Einstein', 'Famous Americans', 3),
('Who was the first Black woman to win an Academy Award for Best Actress?',
 ARRAY['Viola Davis','Angela Bassett','Whoopi Goldberg','Halle Berry'],
 'Halle Berry', 'Famous Americans', 1),
('Which famous American jazz musician was known as the "Duke" and led a famous orchestra for over 50 years?',
 ARRAY['Louis Armstrong','Miles Davis','Dizzy Gillespie','Duke Ellington'],
 'Duke Ellington', 'Famous Americans', 4),
('Who was the first US President to resign from office?',
 ARRAY['Bill Clinton','Richard Nixon','Andrew Johnson','Warren G. Harding'],
 'Richard Nixon', 'Famous Americans', 4),
('Which famous American athlete won four gold medals at the 1936 Berlin Olympics, embarrassing Adolf Hitler?',
 ARRAY['Jim Thorpe','Jesse Owens','Ralph Metcalfe','Eddie Tolan'],
 'Jesse Owens', 'Famous Americans', 5),
('Who founded the American Red Cross in 1881?',
 ARRAY['Florence Nightingale','Dorothea Dix','Clara Barton','Jane Addams'],
 'Clara Barton', 'Famous Americans', 5),
('Which American civil rights leader founded the Southern Christian Leadership Conference in 1957?',
 ARRAY['Thurgood Marshall','John Lewis','Ralph Abernathy','Martin Luther King Jr.'],
 'Martin Luther King Jr.', 'Famous Americans', 2),
('Who was the first American woman to travel to space?',
 ARRAY['Sally Ride','Christa McAuliffe','Judith Resnik','Mae Jemison'],
 'Sally Ride', 'Famous Americans', 6),
('Which famous American poet was known as the "Belle of Amherst" and rarely left her home in Massachusetts?',
 ARRAY['Sylvia Plath','Anne Sexton','Emily Dickinson','Edna St. Vincent Millay'],
 'Emily Dickinson', 'Famous Americans', 6),
('Who invented the cotton gin in 1793, revolutionizing cotton production in the South?',
 ARRAY['Eli Whitney','Cyrus McCormick','Robert Fulton','John Deere'],
 'Eli Whitney', 'Famous Americans', 6),
('Which famous American businessman founded Standard Oil in 1870 and became the wealthiest person in US history?',
 ARRAY['Andrew Carnegie','J.P. Morgan','Cornelius Vanderbilt','John D. Rockefeller'],
 'John D. Rockefeller', 'Famous Americans', 7),
('Who was the first African American to play in Major League Baseball''s modern era, breaking the color barrier in 1947?',
 ARRAY['Satchel Paige','Roy Campanella','Willie Mays','Jackie Robinson'],
 'Jackie Robinson', 'Famous Americans', 8),
('Which famous American architect designed the Vietnam Veterans Memorial in Washington DC?',
 ARRAY['I.M. Pei','Maya Lin','Robert Venturi','Eero Saarinen'],
 'Maya Lin', 'Famous Americans', 9),
('How many players are on a baseball team on the field at one time?',
 ARRAY['8','9','10','11'],
 '9', 'US Sports', 1),
('What is the name of the trophy awarded to the winner of the NHL championship?',
 ARRAY['Hart Trophy','Conn Smythe Trophy','Stanley Cup','Presidents'' Trophy'],
 'Stanley Cup', 'US Sports', 2),
('In which city is the headquarters of the National Football League located?',
 ARRAY['Chicago','New York City','Dallas','Los Angeles'],
 'New York City', 'US Sports', 2),
('Which famous horse racing event is held annually at Pimlico Race Course in Baltimore?',
 ARRAY['Kentucky Derby','Belmont Stakes','Preakness Stakes','Breeders'' Cup'],
 'Preakness Stakes', 'US Sports', 3),
('What is the name of the award given to the most outstanding player in the NFL each season?',
 ARRAY['Heisman Trophy','Lombardi Award','MVP Award','Walter Payton Award'],
 'MVP Award', 'US Sports', 3),
('In which city is the Basketball Hall of Fame located?',
 ARRAY['Chicago','New York City','Springfield','Indianapolis'],
 'Springfield', 'US Sports', 1),
('Which US city hosted the first modern Olympic Games held in America in 1904?',
 ARRAY['Chicago','New York City','St. Louis','Los Angeles'],
 'St. Louis', 'US Sports', 4),
('What is the name of the trophy awarded annually to the best college football player in the country?',
 ARRAY['Outland Trophy','Biletnikoff Award','Heisman Trophy','Butkus Award'],
 'Heisman Trophy', 'US Sports', 4),
('Which basketball player holds the record for most points scored in a single NBA game with 100 points?',
 ARRAY['Michael Jordan','Kobe Bryant','LeBron James','Wilt Chamberlain'],
 'Wilt Chamberlain', 'US Sports', 5),
('What is the name of the famous auto race held annually in Indianapolis on Memorial Day weekend?',
 ARRAY['Daytona 500','NASCAR Cup Series','Indianapolis 500','Formula One US Grand Prix'],
 'Indianapolis 500', 'US Sports', 5),
('Which US tennis player won 18 Grand Slam singles titles during his career?',
 ARRAY['Andre Agassi','Jim Courier','Pete Sampras','John McEnroe'],
 'Pete Sampras', 'US Sports', 6),
('What year did the United States host the FIFA World Cup soccer tournament?',
 ARRAY['1990','1994','1998','2002'],
 '1994', 'US Sports', 6),
('Which US swimmer won the most Olympic gold medals in history?',
 ARRAY['Mark Spitz','Gary Hall Jr.','Ryan Lochte','Michael Phelps'],
 'Michael Phelps', 'US Sports', 7),
('What is the name of the annual college football game held in Pasadena on New Year''s Day, known as the "Granddaddy of Them All"?',
 ARRAY['Orange Bowl','Sugar Bowl','Cotton Bowl','Rose Bowl'],
 'Rose Bowl', 'US Sports', 7),
('Which famous American boxer was known as "The Greatest" and refused induction into the Vietnam War draft?',
 ARRAY['Joe Frazier','George Foreman','Muhammad Ali','Joe Louis'],
 'Muhammad Ali', 'US Sports', 8),
('In which sport does the US national team compete for the Ryder Cup against Europe?',
 ARRAY['Tennis','Golf','Sailing','Polo'],
 'Golf', 'US Sports', 8),
('What was the name of the first professional baseball league in the United States, founded in 1871?',
 ARRAY['National Association of Professional Base Ball Players','National League','American League','Federal League'],
 'National Association of Professional Base Ball Players', 'US Sports', 9),
('Which US city''s NBA team is known as the "Jazz," despite the city not being associated with jazz music''s origins?',
 ARRAY['Denver','Salt Lake City','Oklahoma City','Memphis'],
 'Salt Lake City', 'US Sports', 9);