-- 400 additional questions across all 9 categories
-- Deduplicated against all prior migrations
-- Difficulty: 1-3 easy, 4-6 medium, 7-9 hard

-- American Culture (32 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which sport features a "bullpen" where relief pitchers warm up?', ARRAY['Football','Baseball','Basketball','Hockey'], 'Baseball', 'American Culture', 1),
('What American holiday celebrates workers and is observed on the first Monday of September?', ARRAY['Memorial Day','Labor Day','Flag Day','Presidents Day'], 'Labor Day', 'American Culture', 1),
('Which city is famous for its annual Mardi Gras celebration with parades and masquerade balls?', ARRAY['Atlanta','Miami','New Orleans','Savannah'], 'New Orleans', 'American Culture', 1),
('The famous Hollywood Walk of Fame is located on which street in Los Angeles?', ARRAY['Sunset Boulevard','Hollywood Boulevard','Vine Street','Santa Monica Boulevard'], 'Hollywood Boulevard', 'American Culture', 2),
('What American board game, invented in 1935 during the Great Depression, involves buying and trading properties?', ARRAY['Scrabble','Monopoly','Risk','Clue'], 'Monopoly', 'American Culture', 2),
('Which American city is nicknamed "The Windy City" and is famous for its deep dish pizza?', ARRAY['Detroit','Milwaukee','Chicago','Cleveland'], 'Chicago', 'American Culture', 2),
('The Harlem Globetrotters are a famous exhibition basketball team known for their comedic performances and incredible ball-handling skills. In what city were they founded?', ARRAY['New York','Chicago','Los Angeles','Philadelphia'], 'Chicago', 'American Culture', 3),
('Which famous American TV game show first aired in 1956 and has contestants answering questions to win prize money?', ARRAY['Wheel of Fortune','The Price Is Right','The $64,000 Question','Jeopardy!'], 'The $64,000 Question', 'American Culture', 3),
('What is the name of the iconic American music festival held annually in the California desert that features rock, pop, and electronic music?', ARRAY['Lollapalooza','Bonnaroo','Coachella','Glastonbury'], 'Coachella', 'American Culture', 3),
('Which American fast food chain invented the Egg McMuffin breakfast sandwich in 1972?', ARRAY['Burger King','Wendy''s','McDonald''s','Jack in the Box'], 'McDonald''s', 'American Culture', 4),
('The annual Tournament of Roses parade, better known as the Rose Parade, is held in which California city?', ARRAY['Los Angeles','San Diego','Pasadena','Long Beach'], 'Pasadena', 'American Culture', 4),
('What famous American pottery tradition originated in Roseville, Ohio in the late 19th century?', ARRAY['Roseville Pottery','Rookwood Pottery','Weller Pottery','Hull Pottery'], 'Roseville Pottery', 'American Culture', 4),
('Which annual music festival in Austin, Texas celebrates independent film, music, and emerging technologies?', ARRAY['ACL Festival','Fun Fun Fun Fest','South by Southwest','Austin City Limits'], 'South by Southwest', 'American Culture', 5),
('The "Rat Pack" was a famous entertainment group centered in Las Vegas in the 1950s and 60s. Who was its most prominent member?', ARRAY['Dean Martin','Sammy Davis Jr.','Peter Lawford','Frank Sinatra'], 'Frank Sinatra', 'American Culture', 5),
('Which American literary magazine, founded in 1953, is famous for publishing science fiction and fantasy short stories?', ARRAY['The Magazine of Fantasy & Science Fiction','Analog Science Fiction','Galaxy Science Fiction','Asimov''s Science Fiction'], 'The Magazine of Fantasy & Science Fiction', 'American Culture', 5),
('What style of music, originating in the Mississippi Delta, heavily influenced the development of rock and roll?', ARRAY['Gospel','Blues','Jazz','Country'], 'Blues', 'American Culture', 6),
('Which American folk art tradition involves creating large-scale decorative quilts with elaborate geometric patterns, particularly popular in Pennsylvania Dutch country?', ARRAY['Hmong embroidery','Amish quilting','Hawaiian quilting','Baltimore album quilts'], 'Amish quilting', 'American Culture', 6),
('The Great American Songbook refers to the canon of important American popular songs composed primarily between which decades?', ARRAY['1900s-1930s','1920s-1950s','1940s-1970s','1950s-1980s'], '1920s-1950s', 'American Culture', 6),
('Which American architect pioneered the Prairie Style of architecture with low-pitched roofs and horizontal lines emphasizing the flat landscape?', ARRAY['Louis Sullivan','Henry Hobson Richardson','Frank Lloyd Wright','Burnham and Root'], 'Frank Lloyd Wright', 'American Culture', 7),
('The term "Tin Pan Alley" refers to a collection of New York City music publishers and songwriters who dominated popular music in the late 19th and early 20th century. On which street was it primarily located?', ARRAY['Broadway','West 28th Street','West 52nd Street','Fifth Avenue'], 'West 28th Street', 'American Culture', 7),
('Which American literary movement of the 1830s-1840s, centered in New England, emphasized the inherent goodness of people and nature?', ARRAY['Romanticism','Transcendentalism','Realism','Naturalism'], 'Transcendentalism', 'American Culture', 7),
('The famous "I Love Lucy" television show debuted in 1951 and starred which actress?', ARRAY['Lucille Ball','Mary Tyler Moore','Donna Reed','Gracie Allen'], 'Lucille Ball', 'American Culture', 1),
('Which famous American circus, known as "The Greatest Show on Earth," performed its last show in 2017?', ARRAY['Barnum & Bailey','Ringling Bros.','Ringling Bros. and Barnum & Bailey','Cirque du Soleil'], 'Ringling Bros. and Barnum & Bailey', 'American Culture', 8),
('The "Second Harlem Renaissance" of the 1970s and 80s was characterized by the rise of which art form that originated in the South Bronx?', ARRAY['Jazz fusion','Hip-hop','Funk','Soul'], 'Hip-hop', 'American Culture', 8),
('Which uniquely American cultural institution, the Chautauqua, began in 1874 as a summer educational retreat for Sunday school teachers and grew into a national movement promoting what ideals?', ARRAY['Industrial innovation and progress','Arts, education, religion, and recreation','Temperance and women''s suffrage','Agriculture and rural self-sufficiency'], 'Arts, education, religion, and recreation', 'American Culture', 8),
('What is the name of the influential American art magazine, founded in 1913, that introduced European avant-garde art to American audiences through the famous Armory Show?', ARRAY['Art in America','Camera Work','The Dial','Arts and Decoration'], 'Arts and Decoration', 'American Culture', 9),
('The "Ashcan School" of American painting, active in the early 20th century, was known for depicting what subject matter?', ARRAY['Rural landscapes','Urban everyday life','Abstract patterns','Colonial history'], 'Urban everyday life', 'American Culture', 9),
('Which American literary prize, established in 1918, is awarded annually to authors of outstanding books on American history?', ARRAY['National Book Award','Pulitzer Prize for History','Francis Parkman Prize','Bancroft Prize'], 'Pulitzer Prize for History', 'American Culture', 9),
('What American dance form, combining African and European influences, developed in New Orleans in the late 19th century and featured improvisational footwork?', ARRAY['Tap dance','Cakewalk','Lindy Hop','Buck dancing'], 'Cakewalk', 'American Culture', 4),
('The famous Bread Loaf Writers'' Conference, one of America''s oldest literary conferences, is held annually in which state?', ARRAY['New Hampshire','Maine','Vermont','Massachusetts'], 'Vermont', 'American Culture', 7),
('Which American fashion designer is credited with creating the first mass-produced blue jeans in 1873?', ARRAY['Calvin Klein','Ralph Lauren','Levi Strauss','Brooks Brothers'], 'Levi Strauss', 'American Culture', 2),
('What is the name of the famous Appalachian folk song tradition that involves storytelling through music and has been called "the music that invented America"?', ARRAY['Shape-note singing','Old-time music','Bluegrass','Sacred Harp'], 'Old-time music', 'American Culture', 6);

-- Civics (71 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('How many branches does the United States federal government have?',
 ARRAY['Two','Three','Four','Five'],
 'Three', 'Civics', 1),
('What document established the framework for the U.S. government in 1787?',
 ARRAY['Declaration of Independence','Articles of Confederation','U.S. Constitution','Magna Carta'],
 'U.S. Constitution', 'Civics', 1),
('What is the term length for a U.S. House of Representatives member?',
 ARRAY['Two years','Four years','Six years','Eight years'],
 'Two years', 'Civics', 1),
('Which branch of government is responsible for making federal laws?',
 ARRAY['Executive','Legislative','Judicial','Administrative'],
 'Legislative', 'Civics', 1),
('What is the minimum age requirement to become a U.S. senator?',
 ARRAY['25 years old','30 years old','35 years old','40 years old'],
 '30 years old', 'Civics', 1),
('How many total U.S. senators are there?',
 ARRAY['50','75','100','150'],
 '100', 'Civics', 1),
('What are the first ten amendments to the U.S. Constitution collectively called?',
 ARRAY['The Bill of Rights','The Founding Amendments','The Civil Liberties Act','The Freedom Clauses'],
 'The Bill of Rights', 'Civics', 1),
('Which amendment to the Constitution guarantees freedom of speech and religion?',
 ARRAY['Second Amendment','First Amendment','Fourth Amendment','Fifth Amendment'],
 'First Amendment', 'Civics', 2),
('How many total electors are in the Electoral College?',
 ARRAY['435','500','538','535'],
 '538', 'Civics', 2),
('What is the term for the process by which a non-citizen becomes a U.S. citizen?',
 ARRAY['Naturalization','Immigration','Assimilation','Registration'],
 'Naturalization', 'Civics', 2),
('Which amendment prohibits the government from conducting unreasonable searches and seizures?',
 ARRAY['Third Amendment','Fourth Amendment','Fifth Amendment','Sixth Amendment'],
 'Fourth Amendment', 'Civics', 2),
('What is the role of the Vice President in the U.S. Senate?',
 ARRAY['Majority Leader','Speaker','President of the Senate','Senate Whip'],
 'President of the Senate', 'Civics', 2),
('Which article of the Constitution establishes the legislative branch?',
 ARRAY['Article I','Article II','Article III','Article IV'],
 'Article I', 'Civics', 2),
('How many amendments does the U.S. Constitution currently have?',
 ARRAY['10','20','27','35'],
 '27', 'Civics', 2),
('What is the term for a proposed law being considered by Congress?',
 ARRAY['Decree','Resolution','Bill','Mandate'],
 'Bill', 'Civics', 3),
('Which clause of the Constitution makes federal law supreme over state law?',
 ARRAY['Commerce Clause','Supremacy Clause','Elastic Clause','Full Faith Clause'],
 'Supremacy Clause', 'Civics', 3),
('What is the minimum number of senators needed to break a filibuster?',
 ARRAY['51','55','60','67'],
 '60', 'Civics', 3),
('Which amendment abolished poll taxes in federal elections?',
 ARRAY['22nd Amendment','23rd Amendment','24th Amendment','25th Amendment'],
 '24th Amendment', 'Civics', 3),
('What is the term for the power of Congress to override a presidential veto?',
 ARRAY['Judicial override','Senate review','Veto override','Legislative nullification'],
 'Veto override', 'Civics', 3),
('How many votes does the House need to impeach a president?',
 ARRAY['A unanimous vote','A two-thirds majority','A simple majority','A three-fourths majority'],
 'A simple majority', 'Civics', 3),
('Which amendment limits presidents to two terms in office?',
 ARRAY['20th Amendment','21st Amendment','22nd Amendment','23rd Amendment'],
 '22nd Amendment', 'Civics', 3),
('What does the 10th Amendment reserve to the states or the people?',
 ARRAY['Powers not delegated to the federal government','The right to bear arms','Freedom of religion','Powers of the judiciary'],
 'Powers not delegated to the federal government', 'Civics', 3),
('What is the name of the clause that allows Congress to make laws necessary to carry out its enumerated powers?',
 ARRAY['Commerce Clause','Supremacy Clause','Elastic Clause','Due Process Clause'],
 'Elastic Clause', 'Civics', 4),
('Which branch of government has the power to declare war?',
 ARRAY['Executive','Judicial','Legislative','Military'],
 'Legislative', 'Civics', 4),
('How many justices must agree for the Supreme Court to hear a case?',
 ARRAY['Three','Four','Five','Six'],
 'Four', 'Civics', 4),
('What is the term for the official count of the U.S. population taken every ten years?',
 ARRAY['National Survey','Federal Count','Census','Population Audit'],
 'Census', 'Civics', 4),
('Which amendment guarantees the right to a speedy and public trial?',
 ARRAY['Fifth Amendment','Sixth Amendment','Seventh Amendment','Eighth Amendment'],
 'Sixth Amendment', 'Civics', 4),
('How many representatives does each state have in the U.S. Senate?',
 ARRAY['One','Two','Three','Proportional to population'],
 'Two', 'Civics', 4),
('Which amendment granted citizenship to formerly enslaved people?',
 ARRAY['13th Amendment','14th Amendment','15th Amendment','16th Amendment'],
 '14th Amendment', 'Civics', 4),
('What is the term for the principle that no one, including the government, is above the law?',
 ARRAY['Separation of powers','Checks and balances','Rule of law','Popular sovereignty'],
 'Rule of law', 'Civics', 4),
('What is the title of the presiding officer of the U.S. House of Representatives?',
 ARRAY['Senate President','House Majority Leader','Speaker of the House','House Whip'],
 'Speaker of the House', 'Civics', 4),
('Which amendment protects citizens from being tried twice for the same crime?',
 ARRAY['Fourth Amendment','Fifth Amendment','Sixth Amendment','Seventh Amendment'],
 'Fifth Amendment', 'Civics', 5),
('What is the term for the constitutional principle that divides power between national and state governments?',
 ARRAY['Separation of powers','Federalism','Republicanism','Popular sovereignty'],
 'Federalism', 'Civics', 5),
('How many years must a person be a U.S. citizen before running for the Senate?',
 ARRAY['Five years','Seven years','Nine years','Fourteen years'],
 'Nine years', 'Civics', 5),
('Which Supreme Court case ruled that legislative districts must be roughly equal in population?',
 ARRAY['Baker v. Carr','Reynolds v. Sims','Wesberry v. Sanders','Shaw v. Reno'],
 'Reynolds v. Sims', 'Civics', 5),
('What is the term for a senator''s extended speech used to delay or block a vote?',
 ARRAY['Cloture','Filibuster','Quorum call','Point of order'],
 'Filibuster', 'Civics', 5),
('Which clause of Article IV of the Constitution requires states to honor each other''s laws?',
 ARRAY['Supremacy Clause','Commerce Clause','Full Faith and Credit Clause','Privileges and Immunities Clause'],
 'Full Faith and Credit Clause', 'Civics', 5),
('What is the formal term for a government in which citizens elect representatives to make laws?',
 ARRAY['Democracy','Republic','Oligarchy','Theocracy'],
 'Republic', 'Civics', 5),
('What fraction of states must ratify a constitutional amendment for it to be adopted?',
 ARRAY['A simple majority','Two-thirds','Three-fourths','All states'],
 'Three-fourths', 'Civics', 5),
('What does the phrase "habeas corpus" protect a citizen from?',
 ARRAY['Unlawful imprisonment without charge','Double jeopardy','Self-incrimination','Unreasonable searches'],
 'Unlawful imprisonment without charge', 'Civics', 5),
('Which Supreme Court case established that the Bill of Rights applies to state governments?',
 ARRAY['Marbury v. Madison','McCulloch v. Maryland','Gitlow v. New York','Gibbons v. Ogden'],
 'Gitlow v. New York', 'Civics', 6),
('What is the term for the process by which Congress can remove a federal judge from office?',
 ARRAY['Recall','Impeachment','Removal by vote','Judicial review'],
 'Impeachment', 'Civics', 6),
('Which amendment extended voting rights to residents of Washington, D.C., in presidential elections?',
 ARRAY['22nd Amendment','23rd Amendment','24th Amendment','25th Amendment'],
 '23rd Amendment', 'Civics', 6),
('What is the term for the informal group of advisors to the president made up of cabinet heads?',
 ARRAY['Senate caucus','Kitchen Cabinet','Executive Council','Advisory Board'],
 'Kitchen Cabinet', 'Civics', 6),
('Which constitutional provision prevents states from discriminating against citizens of other states?',
 ARRAY['Equal Protection Clause','Privileges and Immunities Clause','Due Process Clause','Commerce Clause'],
 'Privileges and Immunities Clause', 'Civics', 6),
('What is the minimum number of members needed for Congress to conduct official business?',
 ARRAY['A simple majority','One-third','Two-thirds','A unanimous quorum'],
 'A simple majority', 'Civics', 6),
('Which Supreme Court case ruled that burning the American flag is protected free speech?',
 ARRAY['Tinker v. Des Moines','Texas v. Johnson','Hazelwood v. Kuhlmeier','Brandenburg v. Ohio'],
 'Texas v. Johnson', 'Civics', 6),
('What does the "necessary and proper" clause give Congress the power to do?',
 ARRAY['Override Supreme Court decisions','Make all laws needed to carry out its powers','Impeach the president','Declare war'],
 'Make all laws needed to carry out its powers', 'Civics', 6),
('Which article of the Constitution establishes the judicial branch?',
 ARRAY['Article I','Article II','Article III','Article IV'],
 'Article III', 'Civics', 6),
('What is the term for the doctrine that the Supreme Court can strike down laws as unconstitutional?',
 ARRAY['Legislative review','Executive review','Judicial review','Constitutional review'],
 'Judicial review', 'Civics', 6),
('Which Supreme Court case held that the government cannot ban political spending by corporations?',
 ARRAY['Buckley v. Valeo','Citizens United v. FEC','McConnell v. FEC','First National Bank v. Bellotti'],
 'Citizens United v. FEC', 'Civics', 7),
('What is the formal title of the United States'' chief law enforcement officer?',
 ARRAY['Secretary of Law','Director of Justice','Attorney General','Chief Justice'],
 'Attorney General', 'Civics', 7),
('Which constitutional amendment provides for the direct election of U.S. senators by voters?',
 ARRAY['15th Amendment','16th Amendment','17th Amendment','18th Amendment'],
 '17th Amendment', 'Civics', 7),
('What is the term for the formal charge of misconduct against a public official by the House of Representatives?',
 ARRAY['Indictment','Arraignment','Impeachment','Censure'],
 'Impeachment', 'Civics', 7),
('Which Supreme Court case ruled that police must inform suspects of their rights before questioning?',
 ARRAY['Gideon v. Wainwright','Mapp v. Ohio','Miranda v. Arizona','Terry v. Ohio'],
 'Miranda v. Arizona', 'Civics', 7),
('What is the term for a direct vote by the people on a proposed law or constitutional amendment?',
 ARRAY['Referendum','Initiative','Recall','Plebiscite'],
 'Referendum', 'Civics', 7),
('Which clause of the 14th Amendment protects citizens from state violations of their rights?',
 ARRAY['Equal Protection Clause','Due Process Clause','Privileges or Immunities Clause','Citizenship Clause'],
 'Due Process Clause', 'Civics', 7),
('What is the name of the procedure used in the Senate to end debate and proceed to a vote?',
 ARRAY['Quorum','Cloture','Pocket veto','Filibuster'],
 'Cloture', 'Civics', 7),
('Which constitutional principle holds that government power comes from the consent of the governed?',
 ARRAY['Rule of law','Checks and balances','Popular sovereignty','Separation of powers'],
 'Popular sovereignty', 'Civics', 8),
('What is the term for the formal opinion written by a Supreme Court justice who disagrees with the majority?',
 ARRAY['Concurring opinion','Plurality opinion','Dissenting opinion','Per curiam opinion'],
 'Dissenting opinion', 'Civics', 8),
('Which Supreme Court case ruled that evidence obtained through illegal searches cannot be used in court?',
 ARRAY['Terry v. Ohio','Mapp v. Ohio','Katz v. United States','Weeks v. United States'],
 'Mapp v. Ohio', 'Civics', 8),
('What is the term for the process by which the president nominates and the Senate confirms federal judges?',
 ARRAY['Appointment process','Advice and consent','Judicial confirmation','Federal nomination'],
 'Advice and consent', 'Civics', 8),
('Which Supreme Court case extended the right to counsel to defendants in state criminal proceedings?',
 ARRAY['Powell v. Alabama','Gideon v. Wainwright','Escobedo v. Illinois','In re Gault'],
 'Gideon v. Wainwright', 'Civics', 8),
('What is the term for the constitutional limitation that prevents the government from passing laws punishing specific individuals without trial?',
 ARRAY['Habeas corpus','Ex post facto','Bill of attainder','Writ of mandamus'],
 'Bill of attainder', 'Civics', 8),
('Which amendment to the Constitution requires that criminal cases involving serious crimes be decided by a grand jury?',
 ARRAY['Fourth Amendment','Fifth Amendment','Sixth Amendment','Seventh Amendment'],
 'Fifth Amendment', 'Civics', 8),
('What constitutional principle requires each branch of government to limit the powers of the other branches?',
 ARRAY['Separation of powers','Rule of law','Checks and balances','Popular sovereignty'],
 'Checks and balances', 'Civics', 9),
('Which Supreme Court case held that the president cannot use executive privilege to withhold evidence in a criminal trial?',
 ARRAY['Clinton v. Jones','Morrison v. Olson','United States v. Nixon','Youngstown Sheet & Tube v. Sawyer'],
 'United States v. Nixon', 'Civics', 9),
('What is the term for the constitutional prohibition against laws that make previously legal conduct illegal after the fact?',
 ARRAY['Bill of attainder','Ex post facto law','Habeas corpus','Writ of prohibition'],
 'Ex post facto law', 'Civics', 9),
('Which 1952 Supreme Court case limited presidential power to seize private property without congressional authorization?',
 ARRAY['United States v. Nixon','Morrison v. Olson','Youngstown Sheet & Tube v. Sawyer','Dames & Moore v. Regan'],
 'Youngstown Sheet & Tube v. Sawyer', 'Civics', 9),
('What is the term for the constitutional guarantee that every person accused of a crime is entitled to a fair hearing?',
 ARRAY['Habeas corpus','Due process','Equal protection','Presumption of innocence'],
 'Due process', 'Civics', 9),
('Which Supreme Court case ruled that the Constitution''s commerce clause gave Congress broad power to regulate interstate commerce?',
 ARRAY['McCulloch v. Maryland','Fletcher v. Peck','Gibbons v. Ogden','Dartmouth College v. Woodward'],
 'Gibbons v. Ogden', 'Civics', 9);

-- Famous Americans (32 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which American inventor is credited with creating the first practical telephone in 1876?', ARRAY['Thomas Edison','Alexander Graham Bell','Nikola Tesla','Samuel Morse'], 'Alexander Graham Bell', 'Famous Americans', 1),
('Who was the first female astronaut from the United States to travel to space?', ARRAY['Valentina Tereshkova','Mae Jemison','Christa McAuliffe','Sally Ride'], 'Sally Ride', 'Famous Americans', 1),
('Which American author wrote the dystopian novel "1984"?', ARRAY['Ray Bradbury','George Orwell','Kurt Vonnegut','Aldous Huxley'], 'George Orwell', 'Famous Americans', 1),
('Who was the first American to win the Nobel Prize in Literature?', ARRAY['Ernest Hemingway','Sinclair Lewis','William Faulkner','John Steinbeck'], 'Sinclair Lewis', 'Famous Americans', 2),
('What American scientist developed the first successful polio vaccine in 1955?', ARRAY['Robert Gallo','Jonas Salk','Albert Sabin','Paul Offit'], 'Jonas Salk', 'Famous Americans', 2),
('Which American president is credited with establishing the National Park System with the Antiquities Act of 1906?', ARRAY['Grover Cleveland','William Howard Taft','Theodore Roosevelt','Woodrow Wilson'], 'Theodore Roosevelt', 'Famous Americans', 3),
('Who was the first Native American woman to win an Academy Award?', ARRAY['Wes Studi','Graham Greene','Sacheen Littlefeather','Irene Bedard'], 'Sacheen Littlefeather', 'Famous Americans', 3),
('Which American physicist developed the theory of quantum electrodynamics and was known for his colorful personality and bongo drums?', ARRAY['Murray Gell-Mann','Richard Feynman','Julian Schwinger','Freeman Dyson'], 'Richard Feynman', 'Famous Americans', 3),
('Who was the first American-born woman to win the Nobel Prize in Literature?', ARRAY['Toni Morrison','Eudora Welty','Pearl Buck','Joyce Carol Oates'], 'Pearl Buck', 'Famous Americans', 4),
('Which American labor leader co-founded the United Farm Workers union in 1962 alongside Dolores Huerta?', ARRAY['Samuel Gompers','Walter Reuther','Cesar Chavez','Eugene Debs'], 'Cesar Chavez', 'Famous Americans', 4),
('Who was the first African American woman to serve as a US Cabinet member, appointed as Secretary of Housing and Urban Development in 1966?', ARRAY['Patricia Roberts Harris','Constance Baker Motley','Shirley Chisholm','Barbara Jordan'], 'Patricia Roberts Harris', 'Famous Americans', 4),
('Which American architect designed the iconic Guggenheim Museum Bilbao in Spain?', ARRAY['I.M. Pei','Richard Meier','Frank Gehry','Renzo Piano'], 'Frank Gehry', 'Famous Americans', 5),
('Who was the first American woman to argue before the US Supreme Court, doing so in 1880?', ARRAY['Belva Lockwood','Myra Bradwell','Clara Shortridge Foltz','Arabella Mansfield'], 'Belva Lockwood', 'Famous Americans', 5),
('Which American biochemist won the Nobel Prize in 1958 for discovering that genes act by regulating definite chemical events?', ARRAY['Linus Pauling','James Watson','George Beadle','Wendell Stanley'], 'George Beadle', 'Famous Americans', 5),
('Who became the first African American to serve as Chairman of the Joint Chiefs of Staff in 1989?', ARRAY['Eric Shinseki','Colin Powell','Lloyd Austin','Charles Brown'], 'Colin Powell', 'Famous Americans', 6),
('Which American photographer is famous for her documentary work during the Great Depression, including the iconic "Migrant Mother" photograph?', ARRAY['Margaret Bourke-White','Berenice Abbott','Dorothea Lange','Diane Arbus'], 'Dorothea Lange', 'Famous Americans', 6),
('Who was the first person to swim across the English Channel from England to France and back non-stop?', ARRAY['Johnny Weissmuller','Mark Spitz','Gertrude Ederle','Florence Chadwick'], 'Gertrude Ederle', 'Famous Americans', 6),
('Which American mathematician and logician developed the concept of information theory in 1948?', ARRAY['John von Neumann','Norbert Wiener','Claude Shannon','Alan Turing'], 'Claude Shannon', 'Famous Americans', 7),
('Who was the first American woman to earn a PhD in mathematics, doing so at Johns Hopkins in 1886?', ARRAY['Emmy Noether','Mary Cartwright','Christine Ladd-Franklin','Grace Hopper'], 'Christine Ladd-Franklin', 'Famous Americans', 7),
('Which American artist created the massive earthwork sculpture "Spiral Jetty" in the Great Salt Lake in 1970?', ARRAY['Christo','Richard Serra','Robert Smithson','Andy Goldsworthy'], 'Robert Smithson', 'Famous Americans', 7),
('Who was the first American to win the Fields Medal in mathematics, considered the highest honor in the field?', ARRAY['John Milnor','John Tate','Steven Smale','Jesse Douglas'], 'Jesse Douglas', 'Famous Americans', 8),
('Which American composer wrote the opera "Nixon in China," which premiered in 1987 and depicted Richard Nixon''s historic 1972 visit?', ARRAY['Philip Glass','John Adams','Steve Reich','Laurie Anderson'], 'John Adams', 'Famous Americans', 8),
('Who was the first American to win the Wolf Prize in Physics, considered the most prestigious physics prize after the Nobel?', ARRAY['Murray Gell-Mann','Yoichiro Nambu','Robert Hofstadter','Chien-Shiung Wu'], 'Robert Hofstadter', 'Famous Americans', 8),
('Which American economist developed the Black-Scholes formula for pricing options contracts, revolutionizing financial markets?', ARRAY['Paul Samuelson','Milton Friedman','Myron Scholes','Robert Merton'], 'Myron Scholes', 'Famous Americans', 9),
('Who was the first Native American to serve as a US Senator, representing Kansas in 1907?', ARRAY['Carlos Montezuma','Charles Curtis','Jim Thorpe','Will Rogers'], 'Charles Curtis', 'Famous Americans', 9),
('Which American philosopher developed pragmatism and wrote "The Will to Believe" and "Pragmatism," influencing American intellectual life profoundly?', ARRAY['John Dewey','William James','Charles Sanders Peirce','Josiah Royce'], 'William James', 'Famous Americans', 9),
('Who was the first American woman to earn a law degree, doing so at the University of Iowa in 1869?', ARRAY['Belva Lockwood','Arabella Mansfield','Clara Foltz','Myra Bradwell'], 'Arabella Mansfield', 'Famous Americans', 7),
('Which American sociologist wrote "The Souls of Black Folk" in 1903, introducing the concept of "double consciousness"?', ARRAY['Booker T. Washington','Marcus Garvey','W.E.B. Du Bois','Carter G. Woodson'], 'W.E.B. Du Bois', 'Famous Americans', 5),
('Who was the first American to receive the Nobel Prize in Chemistry, in 1914?', ARRAY['Linus Pauling','Theodore Richards','Irving Langmuir','Harold Urey'], 'Theodore Richards', 'Famous Americans', 8),
('Which American journalist and muckraker wrote "The Jungle" in 1906, exposing unsanitary conditions in the meatpacking industry?', ARRAY['Ida Tarbell','Lincoln Steffens','Upton Sinclair','Jacob Riis'], 'Upton Sinclair', 'Famous Americans', 3),
('Who was the first African American woman elected to the US House of Representatives, serving from 1969 to 1983?', ARRAY['Barbara Jordan','Maxine Waters','Shirley Chisholm','Corrine Brown'], 'Shirley Chisholm', 'Famous Americans', 4),
('Which American scientist won the Nobel Prize in Physics in 1923 for measuring the charge of an electron?', ARRAY['Albert Michelson','Robert Millikan','Arthur Compton','Carl Anderson'], 'Robert Millikan', 'Famous Americans', 6);

-- Geography (59 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the capital city of California?',
 ARRAY['Los Angeles','San Diego','Sacramento','San Francisco'],
 'Sacramento', 'Geography', 1),
('Which state is known as the "Lone Star State"?',
 ARRAY['Arizona','New Mexico','Oklahoma','Texas'],
 'Texas', 'Geography', 1),
('What is the largest ocean bordering the United States to the west?',
 ARRAY['Atlantic Ocean','Arctic Ocean','Indian Ocean','Pacific Ocean'],
 'Pacific Ocean', 'Geography', 1),
('Which state contains Mount Rushmore?',
 ARRAY['Wyoming','Montana','North Dakota','South Dakota'],
 'South Dakota', 'Geography', 1),
('What is the capital of New York State?',
 ARRAY['New York City','Buffalo','Albany','Syracuse'],
 'Albany', 'Geography', 1),
('Which U.S. state is known as the "Sunshine State"?',
 ARRAY['California','Hawaii','Arizona','Florida'],
 'Florida', 'Geography', 1),
('What body of water borders the eastern coast of the United States?',
 ARRAY['Pacific Ocean','Caribbean Sea','Gulf of Mexico','Atlantic Ocean'],
 'Atlantic Ocean', 'Geography', 2),
('Which state is home to the Grand Canyon?',
 ARRAY['Utah','Nevada','Colorado','Arizona'],
 'Arizona', 'Geography', 2),
('What is the capital city of Florida?',
 ARRAY['Miami','Orlando','Tallahassee','Tampa'],
 'Tallahassee', 'Geography', 2),
('Which U.S. state contains Yellowstone National Park?',
 ARRAY['Montana','Colorado','Utah','Wyoming'],
 'Wyoming', 'Geography', 2),
('What is the name of the mountain range running along the eastern United States?',
 ARRAY['Rocky Mountains','Sierra Nevada','Cascades','Appalachian Mountains'],
 'Appalachian Mountains', 'Geography', 2),
('Which state is the southernmost in the contiguous United States?',
 ARRAY['Mississippi','Louisiana','Georgia','Florida'],
 'Florida', 'Geography', 2),
('What river forms the boundary between Texas and Mexico?',
 ARRAY['Colorado River','Pecos River','Rio Grande','Red River'],
 'Rio Grande', 'Geography', 3),
('Which U.S. state is home to the most active volcanoes?',
 ARRAY['Hawaii','California','Washington','Alaska'],
 'Alaska', 'Geography', 3),
('What is the capital city of Texas?',
 ARRAY['Dallas','Houston','San Antonio','Austin'],
 'Austin', 'Geography', 3),
('Which state is the smallest in the contiguous United States by area?',
 ARRAY['Delaware','Connecticut','New Jersey','Rhode Island'],
 'Rhode Island', 'Geography', 3),
('Which Great Lake is entirely within the United States?',
 ARRAY['Lake Superior','Lake Huron','Lake Michigan','Lake Ontario'],
 'Lake Michigan', 'Geography', 3),
('What mountain range runs along the Pacific Coast in Washington and Oregon?',
 ARRAY['Sierra Nevada','Rocky Mountains','Cascade Range','Coast Ranges'],
 'Cascade Range', 'Geography', 3),
('Which state is known for having the lowest point in North America, Death Valley?',
 ARRAY['Nevada','Arizona','New Mexico','California'],
 'California', 'Geography', 4),
('What is the capital city of Illinois?',
 ARRAY['Chicago','Rockford','Peoria','Springfield'],
 'Springfield', 'Geography', 4),
('Which U.S. state shares its northern border only with Canada and no other U.S. states?',
 ARRAY['Vermont','Maine','Minnesota','North Dakota'],
 'Maine', 'Geography', 4),
('What large body of water lies between Michigan''s two peninsulas?',
 ARRAY['Lake Superior','Lake Erie','Lake Huron','Lake Michigan'],
 'Lake Michigan', 'Geography', 4),
('Which state is home to Acadia National Park?',
 ARRAY['New Hampshire','Vermont','Massachusetts','Maine'],
 'Maine', 'Geography', 4),
('What is the capital city of Colorado?',
 ARRAY['Boulder','Colorado Springs','Fort Collins','Denver'],
 'Denver', 'Geography', 4),
('Which U.S. territory lies in the Caribbean Sea southeast of Florida?',
 ARRAY['U.S. Virgin Islands','Guam','American Samoa','Northern Mariana Islands'],
 'U.S. Virgin Islands', 'Geography', 4),
('What is the name of the large bay that indents the coast of Maryland and Virginia?',
 ARRAY['Delaware Bay','Pamlico Sound','Chesapeake Bay','Tampa Bay'],
 'Chesapeake Bay', 'Geography', 4),
('Which city is the most populous in Texas?',
 ARRAY['San Antonio','Dallas','Austin','Houston'],
 'Houston', 'Geography', 5),
('What is the name of the geographic region covering parts of western Pennsylvania, West Virginia, and eastern Kentucky?',
 ARRAY['Piedmont','Tidewater','Great Plains','Appalachia'],
 'Appalachia', 'Geography', 5),
('Which state is home to the most Native American reservations?',
 ARRAY['New Mexico','Oklahoma','Montana','Arizona'],
 'Arizona', 'Geography', 5),
('What is the name of the massive aquifer that supplies water to eight Great Plains states?',
 ARRAY['Missouri Aquifer','Floridan Aquifer','Ogallala Aquifer','Columbia Plateau Aquifer'],
 'Ogallala Aquifer', 'Geography', 5),
('Which U.S. state has the longest total coastline including islands and inlets?',
 ARRAY['Florida','California','Texas','Alaska'],
 'Alaska', 'Geography', 5),
('What is the name of the peninsula that separates the Chesapeake Bay from the Atlantic Ocean?',
 ARRAY['Cape Cod','Outer Banks','Delmarva Peninsula','Cape Hatteras'],
 'Delmarva Peninsula', 'Geography', 5),
('Which river forms part of the border between Illinois and Missouri?',
 ARRAY['Ohio River','Wabash River','Mississippi River','Missouri River'],
 'Mississippi River', 'Geography', 5),
('What is the capital of Alaska?',
 ARRAY['Anchorage','Fairbanks','Nome','Juneau'],
 'Juneau', 'Geography', 6),
('Which state is divided into two separate land areas by Lake Michigan?',
 ARRAY['Wisconsin','Indiana','Illinois','Michigan'],
 'Michigan', 'Geography', 6),
('What is the name of the fertile farming region in central California?',
 ARRAY['San Joaquin Valley','Napa Valley','Sacramento River Valley','Central Valley'],
 'Central Valley', 'Geography', 6),
('Which U.S. state has the largest land area?',
 ARRAY['Texas','Montana','California','Alaska'],
 'Alaska', 'Geography', 6),
('What is the name of the geographic area where Arkansas, Missouri, and Illinois rivers converge near Cairo?',
 ARRAY['River Junction','Lower Mississippi','American Bottom','Cairo Confluence'],
 'American Bottom', 'Geography', 6),
('Which state is home to the geographic center of the contiguous 48 states?',
 ARRAY['Nebraska','Oklahoma','Missouri','Kansas'],
 'Kansas', 'Geography', 6),
('What is the name of the large plateau region of the Pacific Northwest formed by ancient volcanic flows?',
 ARRAY['Snake River Plain','Colorado Plateau','Columbia Plateau','Great Basin'],
 'Columbia Plateau', 'Geography', 6),
('Which U.S. state contains the Ozark Mountains?',
 ARRAY['Arkansas','Tennessee','Kentucky','Alabama'],
 'Arkansas', 'Geography', 6),
('Which U.S. state is home to the Everglades National Park?',
 ARRAY['Georgia','South Carolina','Louisiana','Florida'],
 'Florida', 'Geography', 7),
('What is the name of the underground cave system in New Mexico that is a UNESCO World Heritage Site?',
 ARRAY['Wind Cave','Mammoth Cave','Luray Caverns','Carlsbad Caverns'],
 'Carlsbad Caverns', 'Geography', 7),
('Which U.S. state has the most counties?',
 ARRAY['California','New York','Ohio','Texas'],
 'Texas', 'Geography', 7),
('What is the name of the area where four states meet at a single point: Utah, Colorado, Arizona, and New Mexico?',
 ARRAY['Four Corners','Quad State Junction','Desert Crossroads','Southwest Nexus'],
 'Four Corners', 'Geography', 7),
('Which state contains the easternmost point in the contiguous United States?',
 ARRAY['Massachusetts','New Hampshire','Vermont','Maine'],
 'Maine', 'Geography', 7),
('What is the term for the imaginary line that separates rivers flowing toward the Pacific from those flowing toward the Atlantic?',
 ARRAY['Pacific Ridge','Great Divide','Continental Divide','Water Shed Line'],
 'Continental Divide', 'Geography', 7),
('Which river is the primary source of water for the Colorado River delta?',
 ARRAY['San Juan River','Green River','Gunnison River','Colorado River'],
 'Colorado River', 'Geography', 8),
('What is the name of the ancient volcanic crater that forms Crater Lake in Oregon?',
 ARRAY['Mount Rainier','Mount Hood','Mount Mazama','Mount St. Helens'],
 'Mount Mazama', 'Geography', 8),
('Which state has the largest percentage of its land protected as national forests and parks?',
 ARRAY['Wyoming','Montana','California','Alaska'],
 'Alaska', 'Geography', 8),
('What is the name of the submarine mountain chain that formed the Hawaiian Islands?',
 ARRAY['Pacific Ridge','Emperor Seamount Chain','Mid-Pacific Mountains','Hawaiian-Emperor Chain'],
 'Emperor Seamount Chain', 'Geography', 8),
('Which U.S. state shares a border with both Canada and the Atlantic Ocean?',
 ARRAY['New Hampshire','Vermont','Massachusetts','Maine'],
 'Maine', 'Geography', 8),
('What geographic term describes the flat, treeless plain in the interior of North America where the soil was formed by ancient glaciers?',
 ARRAY['Great Basin','Ozark Plateau','Prairie','Great Plains'],
 'Great Plains', 'Geography', 8),
('What is the name of the vast wetland region in southern Louisiana near the Gulf Coast?',
 ARRAY['Mississippi Delta','Louisiana Bayou','Atchafalaya Basin','Gulf Marsh'],
 'Atchafalaya Basin', 'Geography', 9),
('Which U.S. territory is closest to the Philippines?',
 ARRAY['Guam','American Samoa','Wake Island','Northern Mariana Islands'],
 'Guam', 'Geography', 9),
('What is the name of the rock formation in Wyoming that was the first U.S. national monument, designated in 1906?',
 ARRAY['Monument Valley','Chimney Rock','Devils Tower','Scotts Bluff'],
 'Devils Tower', 'Geography', 9),
('Which river drains the largest watershed in the continental United States?',
 ARRAY['Columbia River','Colorado River','Missouri River','Mississippi River'],
 'Mississippi River', 'Geography', 9),
('What is the name of the geographic phenomenon that causes the Great Plains to receive less rainfall than areas to the east?',
 ARRAY['Mountain shadow','Continental divide effect','Rain shadow','Orographic drying'],
 'Rain shadow', 'Geography', 9),
('Which U.S. island territory in the Pacific served as a critical refueling stop on trans-Pacific airline routes?',
 ARRAY['Johnston Atoll','Palmyra Atoll','Wake Island','Midway Atoll'],
 'Wake Island', 'Geography', 9);

-- Landmarks (39 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What city is the Statue of Liberty located in?',
 ARRAY['Washington D.C.','Boston','Philadelphia','New York City'],
 'New York City', 'Landmarks', 1),
('In which U.S. city is the Golden Gate Bridge located?',
 ARRAY['Seattle','Los Angeles','San Diego','San Francisco'],
 'San Francisco', 'Landmarks', 1),
('What is the name of the famous clock tower that is part of Independence Hall in Philadelphia?',
 ARRAY['Old State House','Carpenters Hall','Liberty Bell Tower','Congress Hall'],
 'Liberty Bell Tower', 'Landmarks', 2),
('In which state is Yellowstone National Park primarily located?',
 ARRAY['Montana','Idaho','Colorado','Wyoming'],
 'Wyoming', 'Landmarks', 2),
('What is the name of the famous arch monument in St. Louis, Missouri?',
 ARRAY['Freedom Arch','Continental Arch','Gateway Arch','Westward Arch'],
 'Gateway Arch', 'Landmarks', 2),
('Which American national park is home to the giant sequoia trees?',
 ARRAY['Yosemite','Kings Canyon','Redwood','Sequoia'],
 'Sequoia', 'Landmarks', 3),
('What is the name of the famous Vanderbilt mansion located in Newport, Rhode Island?',
 ARRAY['Vanderbilt Manor','The Breakers','Marble House','Biltmore'],
 'The Breakers', 'Landmarks', 3),
('Which landmark in San Antonio, Texas, is known as the "Cradle of Texas Liberty"?',
 ARRAY['San Fernando Cathedral','San Pedro Springs','The Alamo','Mission Concepción'],
 'The Alamo', 'Landmarks', 4),
('What is the name of the famous civil rights landmark in Montgomery, Alabama, where a bus boycott began in 1955?',
 ARRAY['Dexter Avenue King Memorial Baptist Church','16th Street Baptist Church','Ebenezer Baptist Church','First Baptist Church'],
 'Dexter Avenue King Memorial Baptist Church', 'Landmarks', 4),
('Which famous landmark was designed by architect Frank Lloyd Wright and is located in Pennsylvania?',
 ARRAY['Robie House','Fallingwater','Kaufmann House','Bear Run Estate'],
 'Fallingwater', 'Landmarks', 4),
('What is the name of the presidential home and estate of Thomas Jefferson near Charlottesville, Virginia?',
 ARRAY['Monticello','Montpelier','The Hermitage','Ash Lawn-Highland'],
 'Monticello', 'Landmarks', 5),
('Which American landmark is known as the first skyscraper in the world, built in Chicago in 1885?',
 ARRAY['Flatiron Building','Home Insurance Building','Tribune Tower','Reliance Building'],
 'Home Insurance Building', 'Landmarks', 5),
('In which U.S. city is Bourbon Street, famous for its nightlife and jazz music, located?',
 ARRAY['Memphis','Nashville','Atlanta','New Orleans'],
 'New Orleans', 'Landmarks', 5),
('What is the name of the famous Boston landmark where colonial protesters dumped British tea in 1773?',
 ARRAY['Old South Meeting House','Griffin''s Wharf','Boston Harbor','Faneuil Hall'],
 'Griffin''s Wharf', 'Landmarks', 6),
('Which landmark in Washington, D.C., was completed in 1884 and stands 555 feet tall?',
 ARRAY['Lincoln Memorial','Jefferson Memorial','Washington Monument','U.S. Capitol'],
 'Washington Monument', 'Landmarks', 6),
('What is the name of the famous lighthouse on the Outer Banks of North Carolina that is the tallest brick lighthouse in the United States?',
 ARRAY['Cape Lookout Lighthouse','Bodie Island Lighthouse','Cape Fear Lighthouse','Cape Hatteras Lighthouse'],
 'Cape Hatteras Lighthouse', 'Landmarks', 6),
('Which famous landmark sits atop the Rock of Gibraltar?', ARRAY['Tower of London','Pillars of Hercules','Upper Rock Nature Reserve','Great Siege Tunnels'], 'Upper Rock Nature Reserve', 'Landmarks', 1),
('What is the name of the iconic red barn complex at the Shelburne Museum in Vermont?', ARRAY['Round Barn','Circus Barn','Horseshoe Barn','Webb Gallery'], 'Horseshoe Barn', 'Landmarks', 2),
('The Chrysler Building in New York City is famous for its distinctive eagle gargoyles and what style of architecture?', ARRAY['Beaux-Arts','Gothic Revival','Art Deco','Modernist'], 'Art Deco', 'Landmarks', 3),
('Which suspension bridge, completed in 1937, connects the Upper Peninsula of Michigan to the Lower Peninsula?', ARRAY['Mackinac Bridge','Ambassador Bridge','Blue Water Bridge','Zilwaukee Bridge'], 'Mackinac Bridge', 'Landmarks', 1),
('The National Cathedral in Washington DC took how many years to complete construction?', ARRAY['43 years','63 years','83 years','103 years'], '83 years', 'Landmarks', 2),
('Which famous lighthouse in Maine is the most photographed in New England?', ARRAY['West Quoddy Head','Portland Head Light','Bass Harbor Head','Pemaquid Point'], 'Portland Head Light', 'Landmarks', 3),
('The Palace of Fine Arts in San Francisco was originally built for which event?', ARRAY['1939 Golden Gate International Exposition','1915 Panama-Pacific International Exposition','1906 San Francisco World''s Fair','1984 Democratic National Convention'], '1915 Panama-Pacific International Exposition', 'Landmarks', 4),
('What material was the Statue of Liberty constructed from?', ARRAY['Iron','Copper','Bronze','Steel'], 'Copper', 'Landmarks', 1),
('The Hearst Castle near San Simeon, California was the home of which American newspaper magnate?', ARRAY['Rupert Murdoch','Joseph Pulitzer','William Randolph Hearst','Ted Turner'], 'William Randolph Hearst', 'Landmarks', 2),
('What historic street in Charleston, South Carolina is famous for its colorful antebellum row houses?', ARRAY['Rainbow Row','Magnolia Lane','Pastel Row','Battery Street'], 'Rainbow Row', 'Landmarks', 3),
('The Erie Canal, completed in 1825, connected the Great Lakes to which river?', ARRAY['Mississippi River','Potomac River','Hudson River','Delaware River'], 'Hudson River', 'Landmarks', 4),
('Which famous arch monument in Washington Square Park marks the entrance to Greenwich Village in New York City?', ARRAY['Washington Square Arch','Greenwich Arch','Village Gate','Manhattan Arch'], 'Washington Square Arch', 'Landmarks', 5),
('The Menger Hotel in San Antonio, Texas, built in 1859, is reputedly the most haunted hotel in which state?', ARRAY['Louisiana','Texas','Florida','Georgia'], 'Texas', 'Landmarks', 5),
('Which iconic skyscraper in Chicago was designed by architect Ludwig Mies van der Rohe?', ARRAY['John Hancock Center','Tribune Tower','860-880 Lake Shore Drive','Wrigley Building'], '860-880 Lake Shore Drive', 'Landmarks', 6),
('What is the name of the large outdoor amphitheater carved into a sandstone hillside in Morrison, Colorado?', ARRAY['Red Rocks Amphitheatre','Sandia Amphitheater','Mesa Verde Bowl','Garden of the Gods Stage'], 'Red Rocks Amphitheatre', 'Landmarks', 4),
('The Breakers Palace in Newport, Rhode Island was built as a summer cottage for which family?', ARRAY['Astor','Carnegie','Morgan','Vanderbilt'], 'Vanderbilt', 'Landmarks', 5),
('Which famous road in Nashville is known for its honky-tonks, live music venues, and neon lights?', ARRAY['Music Row','Broadway','Printer''s Alley','Demonbreun Street'], 'Broadway', 'Landmarks', 6),
('The Biltmore Estate in Asheville, North Carolina, is the largest privately owned house in America. How many rooms does it have?', ARRAY['135 rooms','175 rooms','250 rooms','315 rooms'], '250 rooms', 'Landmarks', 7),
('Which cathedral in New York City took over 85 years to build and remains the largest Gothic cathedral in the world?', ARRAY['St. Patrick''s Cathedral','Cathedral of St. John the Divine','Riverside Church','Temple Emanu-El'], 'Cathedral of St. John the Divine', 'Landmarks', 7),
('The Longfellow Bridge in Boston spans the Charles River and is nicknamed for which architectural features?', ARRAY['Twin salt-and-pepper shakers','Four granite towers','Eight stone arches','Twin lighthouse towers'], 'Twin salt-and-pepper shakers', 'Landmarks', 8),
('Which historic mansion in Natchez, Mississippi, is considered the finest example of antebellum plantation architecture in the South?', ARRAY['Stanton Hall','Dunleith','Longwood','Melrose'], 'Longwood', 'Landmarks', 8),
('The Watts Towers in Los Angeles were constructed by Italian immigrant Simon Rodia over a period of how many years?', ARRAY['14 years','21 years','33 years','45 years'], '33 years', 'Landmarks', 9),
('Which famous steel-frame skyscraper in New York, completed in 1930, was briefly the world''s tallest building before being surpassed by the Empire State Building?', ARRAY['Chrysler Building','Bank of Manhattan Trust Building','40 Wall Street','RCA Building'], 'Chrysler Building', 'Landmarks', 9);

-- Military (41 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What branch of the US military is the youngest, established in 1947?', ARRAY['Marines','Air Force','Space Force','Coast Guard'], 'Air Force', 'Military', 1),
('Which war saw the US military deploy the first use of ironclad warships?', ARRAY['War of 1812','Mexican-American War','Civil War','Spanish-American War'], 'Civil War', 'Military', 1),
('What does the military acronym AWOL stand for?', ARRAY['Armed With Offensive Lethal','Absent Without Leave','Active War Operations Logistics','Armed Without Orders Limit'], 'Absent Without Leave', 'Military', 1),
('Which US military branch has the motto "Semper Paratus," meaning "Always Ready"?', ARRAY['Army','Navy','Coast Guard','Marine Corps'], 'Coast Guard', 'Military', 2),
('In what year did the United States officially enter World War I?', ARRAY['1914','1915','1917','1918'], '1917', 'Military', 2),
('What was the name of the US military operation that captured Saddam Hussein in 2003?', ARRAY['Operation Red Dawn','Operation Iraqi Freedom','Operation Desert Fox','Operation Telic'], 'Operation Red Dawn', 'Military', 2),
('The Battle of Bunker Hill in 1775 was actually fought primarily on which hill?', ARRAY['Dorchester Heights','Breed''s Hill','Prospect Hill','Copp''s Hill'], 'Breed''s Hill', 'Military', 3),
('Which American general was known as "Black Jack" during World War I?', ARRAY['Douglas MacArthur','John Pershing','Tasker Bliss','Peyton March'], 'John Pershing', 'Military', 3),
('The United States Marine Corps was founded in which year?', ARRAY['1772','1775','1798','1801'], '1775', 'Military', 3),
('What was the name of the massive Allied naval operation in the Pacific that targeted the Philippine Sea in June 1944?', ARRAY['Battle of the Coral Sea','Battle of the Philippine Sea','Operation Cartwheel','Battle of Saipan'], 'Battle of the Philippine Sea', 'Military', 4),
('Which US Army division earned the nickname "The Big Red One" during World War I?', ARRAY['3rd Infantry Division','10th Mountain Division','1st Infantry Division','82nd Airborne Division'], '1st Infantry Division', 'Military', 4),
('Operation Market Garden in 1944 was a massive Allied airborne assault in which country?', ARRAY['France','Belgium','Germany','Netherlands'], 'Netherlands', 'Military', 4),
('What was the primary US aircraft used for strategic bombing in the Pacific Theater during World War II?', ARRAY['B-17 Flying Fortress','B-24 Liberator','B-29 Superfortress','B-52 Stratofortress'], 'B-29 Superfortress', 'Military', 5),
('The Tuskegee Airmen were the first African American military aviators in the US Armed Forces, serving in which war?', ARRAY['World War I','World War II','Korean War','Vietnam War'], 'World War II', 'Military', 5),
('Which US Navy admiral led the Pacific Fleet to victory at the Battle of Leyte Gulf?', ARRAY['Chester Nimitz','William Halsey','Raymond Spruance','Ernest King'], 'William Halsey', 'Military', 5),
('What was the code name for the US invasion of North Africa in November 1942?', ARRAY['Operation Torch','Operation Husky','Operation Anvil','Operation Shingle'], 'Operation Torch', 'Military', 6),
('The US military''s Special Forces are commonly known by what nickname, derived from their distinctive headgear?', ARRAY['Rangers','Green Berets','Raiders','Night Stalkers'], 'Green Berets', 'Military', 6),
('In which year did the US military formally adopt the M16 rifle as its standard infantry weapon?', ARRAY['1959','1963','1969','1973'], '1969', 'Military', 6),
('What was the name of the classified Cold War program in which the US Air Force developed stealth aircraft technology?', ARRAY['Project Have Blue','Project Blue Book','Project Horizon','Project Sigma'], 'Project Have Blue', 'Military', 7),
('The Battle of Pork Chop Hill took place during which conflict?', ARRAY['World War II','Korean War','Vietnam War','Persian Gulf War'], 'Korean War', 'Military', 7),
('Which US military operation in 1991 rescued American citizens from Somalia amid civil war?', ARRAY['Operation Silver Anvil','Operation Restore Hope','Operation United Shield','Operation Gothic Serpent'], 'Operation Silver Anvil', 'Military', 7),
('The Doolittle Raid of April 1942 was the first aerial bombing attack on the Japanese home islands. The B-25 bombers launched from which aircraft carrier?', ARRAY['USS Hornet','USS Enterprise','USS Wasp','USS Yorktown'], 'USS Hornet', 'Military', 8),
('What was the codename for the US military''s deception operation prior to D-Day that used fake armies and inflatable tanks to mislead German forces?', ARRAY['Operation Bodyguard','Operation Fortitude','Operation Quicksilver','Operation Starkey'], 'Operation Fortitude', 'Military', 8),
('Which US general commanded the 8th Army during the successful Inchon landing and breakout from the Pusan Perimeter in the Korean War?', ARRAY['Matthew Ridgway','James Van Fleet','Walton Walker','Mark Clark'], 'Walton Walker', 'Military', 8),
('The Night Stalkers, officially the 160th Special Operations Aviation Regiment, are based at which US military installation?', ARRAY['Fort Bragg','Fort Campbell','Fort Benning','Fort Rucker'], 'Fort Campbell', 'Military', 9),
('Which classified US nuclear test series conducted in 1954 at Bikini Atoll resulted in the Castle Bravo explosion, the largest US nuclear detonation ever?', ARRAY['Operation Crossroads','Operation Ivy','Operation Castle','Operation Redwing'], 'Operation Castle', 'Military', 9),
('The US military''s famed code talkers in World War II primarily used which Native American language to transmit encrypted messages in the Pacific?', ARRAY['Apache','Cherokee','Comanche','Navajo'], 'Navajo', 'Military', 9),
('Operation Barbarossa, the German invasion of the Soviet Union in 1941, affected US military planning in what key way?', ARRAY['Led to the Lend-Lease Act expansion to the USSR','Caused the US to immediately declare war on Germany','Triggered the US Pacific Fleet redeployment','Led to the formation of NATO'], 'Led to the Lend-Lease Act expansion to the USSR', 'Military', 7),
('What is the name of the US military''s highest non-combat decoration, awarded for meritorious service?', ARRAY['Legion of Merit','Distinguished Service Medal','Meritorious Service Medal','Defense Superior Service Medal'], 'Legion of Merit', 'Military', 6),
('The famous "Frozen Chosin" refers to the brutal fighting retreat of US Marines at the Chosin Reservoir during which month and year?', ARRAY['November-December 1950','January-February 1951','October-November 1950','February-March 1951'], 'November-December 1950', 'Military', 8),
('Which US Navy destroyer was attacked in Yemen''s Aden Harbor in October 2000 by Al-Qaeda suicide bombers?', ARRAY['USS Cole','USS Stark','USS Samuel B. Roberts','USS Fitzgerald'], 'USS Cole', 'Military', 5),
('The US Marine Raiders of World War II were modeled after which special operations unit?', ARRAY['British Commandos','British SAS','Australian SAS','Canadian Rangers'], 'British Commandos', 'Military', 7),
('What year did the US Army officially abolish racial segregation in its ranks following President Truman''s Executive Order 9981?', ARRAY['1948','1950','1953','1955'], '1948', 'Military', 4),
('The famous battle cry "Remember the Alamo" was used during which war?', ARRAY['Mexican-American War','Texas Revolution','Civil War','Spanish-American War'], 'Texas Revolution', 'Military', 2),
('Which US military post in Virginia is the largest military installation in the world by population?', ARRAY['Fort Bragg','Fort Belvoir','Fort Lee','Fort Liberty (formerly Fort Bragg)'], 'Fort Liberty (formerly Fort Bragg)', 'Military', 3),
('The US Army''s Ranger School is located at which military installation in Georgia?', ARRAY['Fort Stewart','Fort Gordon','Fort Benning','Fort McPherson'], 'Fort Benning', 'Military', 4),
('What was the name of the US strategic bombing campaign against North Vietnam conducted between 1965 and 1968?', ARRAY['Operation Rolling Thunder','Operation Arc Light','Operation Linebacker','Operation Menu'], 'Operation Rolling Thunder', 'Military', 5),
('Which branch of the US military operates the Blue Angels flight demonstration squadron?', ARRAY['Air Force','Army','Navy','Marines'], 'Navy', 'Military', 1),
('The Battle of Chapultepec in 1847 during the Mexican-American War gave rise to which famous line in the Marine Corps Hymn?', ARRAY['"From the Halls of Montezuma"','"To the Shores of Tripoli"','"First to Fight for Right and Freedom"','"In the Air, on Land, and Sea"'], '"From the Halls of Montezuma"', 'Military', 6),
('What was the name of the US military''s classified program that flew U-2 spy planes over the Soviet Union during the Cold War?', ARRAY['Project Aquatone','Project Idealist','Project Dragon Lady','Project Chalice'], 'Project Aquatone', 'Military', 9),
('Which American general was nicknamed "Old Blood and Guts" during World War II?', ARRAY['Omar Bradley','George Patton','Dwight Eisenhower','Mark Clark'], 'George Patton', 'Military', 2);

-- National Parks (39 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which national park in Utah is known for its maze of narrow sandstone slot canyons?', ARRAY['Arches','Canyonlands','Capitol Reef','Bryce Canyon'], 'Capitol Reef', 'National Parks', 1),
('What is the name of the famous geyser basin road that runs through Yellowstone National Park?', ARRAY['Grand Loop Road','Firehole Canyon Drive','Norris Geyser Basin Road','Madison Road'], 'Grand Loop Road', 'National Parks', 1),
('Which national park in California protects the tallest trees on Earth?', ARRAY['Sequoia','Redwood','Kings Canyon','Muir Woods'], 'Redwood', 'National Parks', 1),
('Saguaro National Park, famous for its giant cacti, is located near which Arizona city?', ARRAY['Phoenix','Flagstaff','Tucson','Sedona'], 'Tucson', 'National Parks', 2),
('Which national park preserves a vast area of volcanic landscape in eastern Idaho and eastern Oregon?', ARRAY['Lassen Volcanic','Mount Rainier','Craters of the Moon','Newberry Volcano'], 'Lassen Volcanic', 'National Parks', 2),
('The Skyline Drive runs the entire length of which national park?', ARRAY['Blue Ridge Parkway','Shenandoah','Great Smoky Mountains','Appalachian National Scenic Trail'], 'Shenandoah', 'National Parks', 2),
('Which national park in Alaska contains the largest concentration of glaciers in North America?', ARRAY['Denali','Kenai Fjords','Glacier Bay','Katmai'], 'Glacier Bay', 'National Parks', 3),
('Mesa Verde National Park in Colorado preserves the ancient cliff dwellings of which indigenous people?', ARRAY['Navajo','Hopi','Ancestral Puebloans','Apache'], 'Ancestral Puebloans', 'National Parks', 3),
('What unique geological feature makes the Painted Desert in Petrified Forest National Park so colorful?', ARRAY['Volcanic ash layers with iron and manganese','Quartz crystal deposits','Ancient coral reef fossils','Copper oxide minerals'], 'Volcanic ash layers with iron and manganese', 'National Parks', 3),
('Which national park, established in 1980, is the largest in the US National Park System by land area?', ARRAY['Denali','Gates of the Arctic','Wrangell-St. Elias','Katmai'], 'Wrangell-St. Elias', 'National Parks', 4),
('The famous Going-to-the-Sun Road crosses which mountain pass in Glacier National Park?', ARRAY['Logan Pass','Triple Divide Pass','Marias Pass','Reynolds Pass'], 'Logan Pass', 'National Parks', 4),
('Which national park protects the largest temperate rainforest in the United States?', ARRAY['Redwood','Hoh Rainforest in Olympic','Tongass','Quinault'], 'Hoh Rainforest in Olympic', 'National Parks', 4),
('What is the name of the famous sandstone buttes formation in Monument Valley, which sits on the Navajo Nation?', ARRAY['The Mittens and Merrick Butte','The Totem Pole and Yei Bi Chei','The Three Sisters','The Thumb'], 'The Mittens and Merrick Butte', 'National Parks', 5),
('Katmai National Park in Alaska is famous for its bears gathering to catch which fish?', ARRAY['Salmon','Trout','Halibut','Char'], 'Salmon', 'National Parks', 5),
('Which national park in New Mexico protects the world''s largest gypsum dunefield?', ARRAY['Carlsbad Caverns','Guadalupe Mountains','White Sands','Petroglyph'], 'White Sands', 'National Parks', 5),
('The Narrows in Zion National Park is a hike through the slot canyon of which river?', ARRAY['Virgin River','Zion River','Colorado River','Sevier River'], 'Virgin River', 'National Parks', 6),
('Which national park protects the remains of a 49,000-year-old meteor impact crater in Arizona?', ARRAY['Petrified Forest','Walnut Canyon','Meteor Crater','Sunset Crater Volcano'], 'Meteor Crater', 'National Parks', 6),
('Rocky Mountain National Park straddles the Continental Divide. What is the elevation of its highest peak, Longs Peak?', ARRAY['13,455 feet','14,259 feet','12,740 feet','15,100 feet'], '14,259 feet', 'National Parks', 6),
('Which national park in the Virgin Islands is the only one in the US National Park System located in the Caribbean?', ARRAY['Buck Island Reef','Virgin Islands','Christiansted','Salt River Bay'], 'Virgin Islands', 'National Parks', 7),
('What rare geological phenomenon found in Death Valley causes rocks to move across a dried lakebed, leaving trails, without human or animal intervention?', ARRAY['Magnetic rock displacement','Sailing stones','Seismic rock migration','Desert varnish creep'], 'Sailing stones', 'National Parks', 7),
('The Wave, a famous sandstone rock formation, is located in which national monument adjacent to the Grand Canyon?', ARRAY['Vermilion Cliffs','Grand Staircase-Escalante','Paria Canyon','Coyote Buttes'], 'Vermilion Cliffs', 'National Parks', 7),
('Which national park in California protects the famous Half Dome granite formation?', ARRAY['Kings Canyon','Sequoia','Yosemite','Point Reyes'], 'Yosemite', 'National Parks', 1),
('Kobuk Valley National Park in Alaska is unique for containing what desert-like feature above the Arctic Circle?', ARRAY['Active hot springs','Sand dunes','Lava fields','Salt flats'], 'Sand dunes', 'National Parks', 8),
('Which national park preserves the site of a massive volcanic eruption in 1980 that reduced a mountaintop by 1,314 feet?', ARRAY['Lassen Volcanic','Crater Lake','Mount Rainier','Mount St. Helens'], 'Mount St. Helens', 'National Parks', 8),
('Pinnacles National Park in California protects the remnants of an ancient volcano that has moved 195 miles from its original location due to which geological process?', ARRAY['Continental drift','Plate subduction','San Andreas Fault movement','Pacific Plate rotation'], 'San Andreas Fault movement', 'National Parks', 9),
('Which national park in Utah is home to the Fiery Furnace, a labyrinth of narrow sandstone fins and passages?', ARRAY['Canyonlands','Zion','Capitol Reef','Arches'], 'Arches', 'National Parks', 9),
('What is the name of the supervolcano caldera that underlies most of Yellowstone National Park, last erupting approximately 640,000 years ago?', ARRAY['Yellowstone Caldera','Snake River Plain Caldera','Hebgen Lake Caldera','Island Park Caldera'], 'Yellowstone Caldera', 'National Parks', 9),
('Big Bend National Park in Texas sits along the border with which country?', ARRAY['Mexico','Guatemala','Belize','Honduras'], 'Mexico', 'National Parks', 2),
('Which national park in Virginia and West Virginia preserves the New River Gorge, one of the oldest rivers in North America?', ARRAY['Shenandoah','New River Gorge','Blue Ridge','Appalachian'], 'New River Gorge', 'National Parks', 3),
('Biscayne National Park in Florida protects the northernmost living coral reef in the continental US. What percentage of the park is water?', ARRAY['55%','72%','95%','38%'], '95%', 'National Parks', 7),
('Which national park in North Dakota was established in honor of the president who championed the conservation movement?', ARRAY['Theodore Roosevelt','Lincoln','Grant','Harrison'], 'Theodore Roosevelt', 'National Parks', 4),
('The famous Angel''s Landing trail in Zion National Park requires hikers to use chains anchored into the rock for the final stretch. How high above the canyon floor is the summit?', ARRAY['1,000 feet','1,488 feet','2,100 feet','850 feet'], '1,488 feet', 'National Parks', 6),
('Which national park in Michigan consists of an archipelago of 21 islands in Lake Superior?', ARRAY['Isle Royale','Pictured Rocks','Apostle Islands','Sleeping Bear Dunes'], 'Apostle Islands', 'National Parks', 5),
('Mammoth Cave National Park in Kentucky contains the world''s longest known cave system. Approximately how many miles of cave passages have been surveyed?', ARRAY['200 miles','400 miles','650 miles','900 miles'], '400 miles', 'National Parks', 5),
('Which national park in the Pacific Northwest is home to the Hoh Rain Forest and the Hurricane Ridge alpine area?', ARRAY['North Cascades','Olympic','Mount Rainier','Crater Lake'], 'Olympic', 'National Parks', 2),
('The famous Bright Angel Trail descends into the Grand Canyon from which rim?', ARRAY['North Rim','South Rim','East Rim','West Rim'], 'South Rim', 'National Parks', 3),
('Which national park preserves the largest remaining old-growth beech-maple forest in the eastern United States?', ARRAY['Cuyahoga Valley','Congaree','Mammoth Cave','Indiana Dunes'], 'Cuyahoga Valley', 'National Parks', 6),
('Great Basin National Park in Nevada is home to ancient bristlecone pines, some of which are over how many years old?', ARRAY['2,000 years','3,000 years','4,000 years','5,000 years'], '5,000 years', 'National Parks', 4),
('Which national park contains the highest road in North America, the Mount Evans Scenic Byway, reaching 14,130 feet?', ARRAY['Rocky Mountain','Arapaho','Pike','Jefferson'], 'Rocky Mountain', 'National Parks', 7);

-- US History (72 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which war was fought between the United States and Great Britain from 1812 to 1815?',
 ARRAY['The French and Indian War','The War of 1812','The Mexican-American War','The Spanish-American War'],
 'The War of 1812', 'US History', 1),
('Who was the primary author of the Declaration of Independence?',
 ARRAY['Benjamin Franklin','John Adams','Thomas Jefferson','James Madison'],
 'Thomas Jefferson', 'US History', 1),
('In what year did the United States officially declare independence from Great Britain?',
 ARRAY['1773','1775','1776','1781'],
 '1776', 'US History', 1),
('Which amendment to the Constitution abolished slavery throughout the United States?',
 ARRAY['11th Amendment','12th Amendment','13th Amendment','14th Amendment'],
 '13th Amendment', 'US History', 1),
('What was the name given to the nationwide economic collapse that began in 1929?',
 ARRAY['The Panic of 1893','The Great Recession','The Great Depression','Black Monday'],
 'The Great Depression', 'US History', 1),
('Who led American forces to victory at the Battle of Yorktown, ending the Revolutionary War?',
 ARRAY['George Washington','Nathanael Greene','Benedict Arnold','Horatio Gates'],
 'George Washington', 'US History', 1),
('What was the first permanent English settlement in America, founded in 1607?',
 ARRAY['Plymouth','Roanoke','Jamestown','Salem'],
 'Jamestown', 'US History', 2),
('Which president issued the Emancipation Proclamation in 1863?',
 ARRAY['Ulysses S. Grant','Andrew Johnson','Abraham Lincoln','James Buchanan'],
 'Abraham Lincoln', 'US History', 2),
('What was the name of the first successful powered airplane flight location in North Carolina?',
 ARRAY['Chapel Hill','Roanoke Island','Kitty Hawk','Kill Devil Hills'],
 'Kitty Hawk', 'US History', 2),
('Which American abolitionist led the raid on Harpers Ferry in 1859?',
 ARRAY['Frederick Douglass','Nat Turner','John Brown','William Lloyd Garrison'],
 'John Brown', 'US History', 2),
('What year did the United States purchase the Louisiana Territory from France?',
 ARRAY['1799','1803','1812','1815'],
 '1803', 'US History', 2),
('Who was the commanding general of Confederate forces during the Civil War?',
 ARRAY['Stonewall Jackson','James Longstreet','P.G.T. Beauregard','Robert E. Lee'],
 'Robert E. Lee', 'US History', 2),
('What was the name of the federal program created by FDR to combat the Great Depression?',
 ARRAY['The Fair Deal','The Square Deal','The New Deal','The Great Society'],
 'The New Deal', 'US History', 3),
('In which city did the first shots of the Civil War occur in April 1861?',
 ARRAY['Richmond','Charleston','Atlanta','Savannah'],
 'Charleston', 'US History', 3),
('Who was the first African American to serve as a justice on the U.S. Supreme Court?',
 ARRAY['Clarence Thomas','Thurgood Marshall','John Marshall Harlan','Charles Hamilton Houston'],
 'Thurgood Marshall', 'US History', 3),
('What was the name of the legislative compromise that admitted Missouri as a slave state and Maine as a free state?',
 ARRAY['Compromise of 1850','Missouri Compromise','Kansas-Nebraska Act','Crittenden Compromise'],
 'Missouri Compromise', 'US History', 3),
('Which Native American leader led the Shawnee Confederacy against American expansion in the early 1800s?',
 ARRAY['Tecumseh','Pontiac','Black Hawk','Red Cloud'],
 'Tecumseh', 'US History', 3),
('What landmark 1896 Supreme Court case established the "separate but equal" doctrine?',
 ARRAY['Dred Scott v. Sandford','Plessy v. Ferguson','Brown v. Board of Education','Civil Rights Cases'],
 'Plessy v. Ferguson', 'US History', 3),
('Which president authorized the dropping of atomic bombs on Japan in 1945?',
 ARRAY['Franklin D. Roosevelt','Dwight D. Eisenhower','Harry S. Truman','Herbert Hoover'],
 'Harry S. Truman', 'US History', 3),
('What major battle in 1777 is considered the turning point of the Revolutionary War?',
 ARRAY['Battle of Bunker Hill','Battle of Trenton','Battle of Saratoga','Battle of Brandywine'],
 'Battle of Saratoga', 'US History', 3),
('Which president was assassinated at Ford''s Theatre in Washington, D.C., in April 1865?',
 ARRAY['James Garfield','William McKinley','Abraham Lincoln','John F. Kennedy'],
 'Abraham Lincoln', 'US History', 4),
('What year did the United States enter World War I?',
 ARRAY['1914','1915','1916','1917'],
 '1917', 'US History', 4),
('Who was president of the United States during the Cuban Missile Crisis in 1962?',
 ARRAY['Dwight D. Eisenhower','John F. Kennedy','Lyndon B. Johnson','Richard Nixon'],
 'John F. Kennedy', 'US History', 4),
('What was the name of the 1944 operation for the Allied invasion of Normandy?',
 ARRAY['Operation Torch','Operation Barbarossa','Operation Overlord','Operation Market Garden'],
 'Operation Overlord', 'US History', 4),
('Which labor union leader founded the American Federation of Labor in 1886?',
 ARRAY['Eugene V. Debs','Samuel Gompers','John L. Lewis','César Chávez'],
 'Samuel Gompers', 'US History', 4),
('What was the name given to the forced relocation of Cherokee people in 1838–1839?',
 ARRAY['Long Walk','Trail of Tears','Sand Creek Removal','Wounded Knee March'],
 'Trail of Tears', 'US History', 4),
('Which treaty ended the Mexican-American War in 1848?',
 ARRAY['Treaty of Guadalupe Hidalgo','Treaty of Paris','Treaty of Cahuenga','Gadsden Purchase'],
 'Treaty of Guadalupe Hidalgo', 'US History', 4),
('What year was the U.S. Constitution ratified?',
 ARRAY['1776','1781','1788','1791'],
 '1788', 'US History', 4),
('What was the first capital of the United States under the Constitution?',
 ARRAY['Philadelphia','Boston','Washington D.C.','New York City'],
 'New York City', 'US History', 5),
('Who invented the cotton gin in 1793, transforming Southern agriculture?',
 ARRAY['Robert Fulton','Eli Whitney','James Watt','John Deere'],
 'Eli Whitney', 'US History', 5),
('Which amendment introduced the federal income tax in 1913?',
 ARRAY['14th Amendment','15th Amendment','16th Amendment','17th Amendment'],
 '16th Amendment', 'US History', 5),
('What was the name of the naval battle that secured American control of the Pacific in June 1942?',
 ARRAY['Battle of Midway','Battle of Coral Sea','Battle of Leyte Gulf','Battle of Guadalcanal'],
 'Battle of Midway', 'US History', 5),
('Which president delivered the "Gettysburg Address" in November 1863?',
 ARRAY['Ulysses S. Grant','Andrew Johnson','Abraham Lincoln','Millard Fillmore'],
 'Abraham Lincoln', 'US History', 5),
('Who was the American general who led the Allied forces in Europe during World War II?',
 ARRAY['Omar Bradley','George Patton','Dwight D. Eisenhower','Douglas MacArthur'],
 'Dwight D. Eisenhower', 'US History', 5),
('What was the name of the 1919 treaty that officially ended World War I?',
 ARRAY['Treaty of Versailles','Treaty of Brest-Litovsk','Treaty of Paris','Treaty of Ghent'],
 'Treaty of Versailles', 'US History', 5),
('Which American inventor is credited with developing a practical incandescent light bulb in 1879?',
 ARRAY['Alexander Graham Bell','Nikola Tesla','Thomas Edison','George Westinghouse'],
 'Thomas Edison', 'US History', 5),
('What was the name of the law that established the national park system in 1916?',
 ARRAY['Conservation Act','National Park Service Organic Act','Wilderness Act','Antiquities Act'],
 'National Park Service Organic Act', 'US History', 5),
('Which president signed the Homestead Act of 1862, granting free land to settlers?',
 ARRAY['James Buchanan','Abraham Lincoln','Andrew Johnson','Ulysses S. Grant'],
 'Abraham Lincoln', 'US History', 5),
('Who was the commander of American forces in the Pacific theater during World War II?',
 ARRAY['Chester Nimitz','George Patton','Dwight Eisenhower','Douglas MacArthur'],
 'Douglas MacArthur', 'US History', 6),
('What was the name of the 1803 Supreme Court case that established the principle of judicial review?',
 ARRAY['McCulloch v. Maryland','Marbury v. Madison','Gibbons v. Ogden','Fletcher v. Peck'],
 'Marbury v. Madison', 'US History', 6),
('Which act passed by Congress in 1830 authorized the forced relocation of Native American tribes?',
 ARRAY['Dawes Act','Indian Reorganization Act','Indian Removal Act','General Allotment Act'],
 'Indian Removal Act', 'US History', 6),
('What was the name of the secret government project to develop the first atomic bomb?',
 ARRAY['Project Manhattan','Operation Trinity','Manhattan Project','Operation Crossroads'],
 'Manhattan Project', 'US History', 6),
('Which abolitionist and former enslaved person published the "North Star" newspaper beginning in 1847?',
 ARRAY['Harriet Tubman','Sojourner Truth','Frederick Douglass','David Walker'],
 'Frederick Douglass', 'US History', 6),
('What year did the United States annex Texas, leading to war with Mexico?',
 ARRAY['1840','1843','1845','1848'],
 '1845', 'US History', 6),
('Who was the 26th president of the United States, known for trust-busting and conservation?',
 ARRAY['William Howard Taft','Woodrow Wilson','Theodore Roosevelt','William McKinley'],
 'Theodore Roosevelt', 'US History', 6),
('Which battle in 1836 became a rallying cry for Texan independence from Mexico?',
 ARRAY['Battle of San Jacinto','Battle of Goliad','Battle of the Alamo','Battle of Gonzales'],
 'Battle of the Alamo', 'US History', 6),
('What legislation passed in 1944 provided benefits to World War II veterans, including education and housing loans?',
 ARRAY['National Defense Act','Servicemen''s Readjustment Act','Veterans Benefits Act','Armed Forces Act'],
 'Servicemen''s Readjustment Act', 'US History', 6),
('Which president signed the Sherman Antitrust Act of 1890, the first federal law limiting monopolies?',
 ARRAY['Grover Cleveland','Benjamin Harrison','Theodore Roosevelt','William McKinley'],
 'Benjamin Harrison', 'US History', 6),
('What was the name of the 1961 failed invasion of Cuba backed by the U.S. government?',
 ARRAY['Operation Mongoose','Bay of Pigs Invasion','Operation Pluto','Operation Zapata'],
 'Bay of Pigs Invasion', 'US History', 7),
('Which Reconstruction-era amendment granted Black men the right to vote in 1870?',
 ARRAY['13th Amendment','14th Amendment','15th Amendment','16th Amendment'],
 '15th Amendment', 'US History', 7),
('Who was the first Black U.S. senator after Reconstruction, elected from Mississippi in 1966?',
 ARRAY['Edward Brooke','Hiram Revels','Blanche Bruce','John Lewis'],
 'Edward Brooke', 'US History', 7),
('What was the name of the 1973 law that limited the president''s ability to commit U.S. forces to combat?',
 ARRAY['National Security Act','War Powers Resolution','Military Authorization Act','Armed Forces Act'],
 'War Powers Resolution', 'US History', 7),
('Which series of essays written in 1787–1788 promoted ratification of the U.S. Constitution?',
 ARRAY['Common Sense','The Rights of Man','The Federalist Papers','Letters from a Farmer'],
 'The Federalist Papers', 'US History', 7),
('What was the name of the government program under which the U.S. lent military equipment to Allied nations in WWII before entering the war?',
 ARRAY['Marshall Plan','Lend-Lease Act','Arms for Allies Program','Defense Appropriations Act'],
 'Lend-Lease Act', 'US History', 7),
('Who was the first woman elected to the U.S. House of Representatives, in 1916?',
 ARRAY['Jeannette Rankin','Hattie Caraway','Clare Boothe Luce','Edith Nourse Rogers'],
 'Jeannette Rankin', 'US History', 7),
('Which 1944 Supreme Court case upheld the internment of Japanese Americans during WWII?',
 ARRAY['Ex parte Milligan','Hirabayashi v. United States','Korematsu v. United States','Ex parte Quirin'],
 'Korematsu v. United States', 'US History', 7),
('What was the name of the Pullman Strike of 1894 that prompted President Cleveland to deploy federal troops?',
 ARRAY['Railroad Workers Strike','American Railway Union Strike','Pullman Palace Car Strike','Interstate Commerce Strike'],
 'American Railway Union Strike', 'US History', 7),
('Which president established the Federal Reserve System in 1913?',
 ARRAY['William Howard Taft','Theodore Roosevelt','Woodrow Wilson','Warren G. Harding'],
 'Woodrow Wilson', 'US History', 8),
('What was the name of the 1787 compromise that counted enslaved people as three-fifths of a person for congressional representation?',
 ARRAY['Connecticut Compromise','Virginia Plan','Three-Fifths Compromise','Missouri Compromise'],
 'Three-Fifths Compromise', 'US History', 8),
('Who was the Sioux leader who defeated Custer at the Battle of Little Bighorn in 1876?',
 ARRAY['Geronimo','Chief Joseph','Sitting Bull','Red Cloud'],
 'Sitting Bull', 'US History', 8),
('Which political party was founded in 1854 primarily in opposition to the expansion of slavery?',
 ARRAY['Progressive Party','Know-Nothing Party','Republican Party','Free Soil Party'],
 'Republican Party', 'US History', 8),
('What was the name of the 1957 event in which federal troops were used to enforce school integration in Arkansas?',
 ARRAY['Montgomery Crisis','Little Rock Crisis','Birmingham Crisis','Selma Crisis'],
 'Little Rock Crisis', 'US History', 8),
('Which president introduced the "Square Deal" domestic program focusing on labor rights and consumer protection?',
 ARRAY['William Howard Taft','Woodrow Wilson','Theodore Roosevelt','Grover Cleveland'],
 'Theodore Roosevelt', 'US History', 8),
('What was the name of the Senate committee that investigated the Watergate scandal in 1973?',
 ARRAY['Church Committee','Pike Committee','Senate Watergate Committee','Senate Judiciary Committee'],
 'Senate Watergate Committee', 'US History', 8),
('Which 1890 massacre marked the end of the major Indian Wars on the Great Plains?',
 ARRAY['Battle of Little Bighorn','Sand Creek Massacre','Wounded Knee Massacre','Battle of Bear Paw'],
 'Wounded Knee Massacre', 'US History', 8),
('Who was the first president to be impeached by the House of Representatives?',
 ARRAY['Richard Nixon','Andrew Johnson','Bill Clinton','John Tyler'],
 'Andrew Johnson', 'US History', 9),
('What was the name of the underground network of safe houses that helped enslaved people escape to freedom before the Civil War?',
 ARRAY['Freedom Road','Liberty Line','Underground Railroad','Northern Star Network'],
 'Underground Railroad', 'US History', 9),
('Which 1798 Supreme Court precedent established that states cannot nullify federal law?',
 ARRAY['Chisholm v. Georgia','Calder v. Bull','Ware v. Hylton','Hylton v. United States'],
 'Ware v. Hylton', 'US History', 9),
('What was the name of the first American to orbit Earth, completing three orbits in February 1962?',
 ARRAY['Alan Shepard','Gus Grissom','Scott Carpenter','John Glenn'],
 'John Glenn', 'US History', 9),
('Which 1863 draft law caused riots in New York City because wealthy men could pay $300 to avoid service?',
 ARRAY['Enrollment Act','Militia Draft Act','Conscription Act','Federal Draft Law'],
 'Enrollment Act', 'US History', 9),
('Who was the first U.S. Secretary of the Treasury, who established the national banking system?',
 ARRAY['Robert Morris','Albert Gallatin','Thomas Jefferson','Alexander Hamilton'],
 'Alexander Hamilton', 'US History', 9),
('What was the name of the 1919 Red Scare raids authorized by Attorney General A. Mitchell Palmer?',
 ARRAY['Palmer Raids','Red Dragnet','Communist Roundups','Bolshevik Sweeps'],
 'Palmer Raids', 'US History', 9);

-- US Sports (33 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('How many innings are played in a standard baseball game?', ARRAY['7','8','9','10'], '9', 'US Sports', 1),
('Which city''s NBA team is known as the Lakers despite the city having no lakes?', ARRAY['Phoenix','Los Angeles','Miami','Houston'], 'Los Angeles', 'US Sports', 1),
('What is the maximum score a gymnast can achieve in an Olympic gymnastics event under the current Code of Points system?', ARRAY['10.0','15.0','No maximum','20.0'], 'No maximum', 'US Sports', 1),
('Which American tennis player won 18 Grand Slam singles titles between 1994 and 2002, including a record 6 consecutive US Opens?', ARRAY['Andre Agassi','Jim Courier','Pete Sampras','John McEnroe'], 'Pete Sampras', 'US Sports', 2),
('The Green Bay Packers are unique among major American sports teams for being owned by whom?', ARRAY['A billionaire family','The state of Wisconsin','The city of Green Bay','Their fans as a non-profit'], 'Their fans as a non-profit', 'US Sports', 2),
('In which sport would you find a "birdie," "eagle," and "albatross"?', ARRAY['Badminton','Golf','Cricket','Bowling'], 'Golf', 'US Sports', 2),
('Which American city hosts the annual Daytona 500 NASCAR race?', ARRAY['Charlotte','Talladega','Daytona Beach','Bristol'], 'Daytona Beach', 'US Sports', 3),
('What is the name of the annual charity basketball game between NBA stars from the Eastern and Western Conferences?', ARRAY['Celebrity Game','Rising Stars','NBA All-Star Game','Skills Challenge'], 'NBA All-Star Game', 'US Sports', 3),
('Which former NFL quarterback threw for 71,940 career passing yards, the most in NFL history at the time of his retirement?', ARRAY['Tom Brady','Peyton Manning','Brett Favre','Drew Brees'], 'Drew Brees', 'US Sports', 3),
('How many players are on the field for each team during a baseball game?', ARRAY['8','9','10','11'], '9', 'US Sports', 4),
('Which American swimmer won the most medals in a single Olympic Games, earning 8 gold medals at the 2008 Beijing Olympics?', ARRAY['Mark Spitz','Ryan Lochte','Michael Phelps','Nathan Adrian'], 'Michael Phelps', 'US Sports', 4),
('In American football, how many points is a safety worth?', ARRAY['1','2','3','6'], '2', 'US Sports', 4),
('Which Major League Baseball team has won the most World Series championships?', ARRAY['Boston Red Sox','Los Angeles Dodgers','New York Yankees','San Francisco Giants'], 'New York Yankees', 'US Sports', 5),
('What is the name of the trophy awarded to the winner of the NHL Stanley Cup playoffs?', ARRAY['Hart Trophy','Vezina Trophy','Conn Smythe Trophy','Stanley Cup'], 'Stanley Cup', 'US Sports', 5),
('Which university''s football team is known as the "Fighting Irish"?', ARRAY['Boston College','Villanova','Notre Dame','Fordham'], 'Notre Dame', 'US Sports', 5),
('Who holds the record for the most career home runs in Major League Baseball history?', ARRAY['Babe Ruth','Hank Aaron','Willie Mays','Barry Bonds'], 'Barry Bonds', 'US Sports', 6),
('Which boxing match in 1975, dubbed the "Thrilla in Manila," saw Muhammad Ali defeat which opponent?', ARRAY['George Foreman','Joe Frazier','Ken Norton','Earnie Shavers'], 'Joe Frazier', 'US Sports', 6),
('The America''s Cup yacht race is considered the oldest international sporting trophy, first contested in which year?', ARRAY['1851','1876','1900','1920'], '1851', 'US Sports', 6),
('Which American track and field athlete won four gold medals at the 1936 Berlin Olympics, embarrassing the Nazi regime?', ARRAY['Jim Thorpe','Jesse Owens','Ralph Metcalfe','Mack Robinson'], 'Jesse Owens', 'US Sports', 7),
('In which year did the NBA introduce the three-point line?', ARRAY['1977','1979','1981','1983'], '1979', 'US Sports', 7),
('Which American horse racing venue hosts the Preakness Stakes, the second leg of the Triple Crown?', ARRAY['Churchill Downs','Belmont Park','Pimlico Race Course','Keeneland'], 'Pimlico Race Course', 'US Sports', 7),
('Who won the first Masters Tournament in golf, held at Augusta National in 1934?', ARRAY['Bobby Jones','Walter Hagen','Gene Sarazen','Horton Smith'], 'Horton Smith', 'US Sports', 8),
('Which NBA team won the most consecutive championships, winning eight titles in a row from 1959 to 1966?', ARRAY['Chicago Bulls','Los Angeles Lakers','Boston Celtics','Golden State Warriors'], 'Boston Celtics', 'US Sports', 8),
('The "Immaculate Reception" in 1972, considered one of the greatest plays in NFL history, was made by which player?', ARRAY['Lynn Swann','John Stallworth','Terry Bradshaw','Franco Harris'], 'Franco Harris', 'US Sports', 8),
('Which American female gymnast is the most decorated in US history, winning 30 Olympic and World Championship medals?', ARRAY['Nadia Comaneci','Mary Lou Retton','Shannon Miller','Simone Biles'], 'Simone Biles', 'US Sports', 9),
('In which year did the AFL-NFL merger officially take effect, creating the modern NFL as we know it?', ARRAY['1966','1968','1970','1972'], '1970', 'US Sports', 9),
('Which American tennis player was the first to complete a Grand Slam, winning all four major titles in the same calendar year, in 1938?', ARRAY['Bill Tilden','Don Budge','Jack Kramer','Pancho Gonzales'], 'Don Budge', 'US Sports', 9),
('What is the name of the award given to the most outstanding player in the NCAA college basketball tournament?', ARRAY['Naismith Award','John Wooden Award','Most Outstanding Player','Chuck Taylor Award'], 'Most Outstanding Player', 'US Sports', 3),
('Which NFL team plays their home games at SoFi Stadium in Inglewood, California?', ARRAY['San Francisco 49ers','Las Vegas Raiders','Los Angeles Rams','Arizona Cardinals'], 'Los Angeles Rams', 'US Sports', 2),
('Who was the first pitcher in MLB history to win the Cy Young Award in both the American and National Leagues?', ARRAY['Gaylord Perry','Roger Clemens','Pedro Martinez','Randy Johnson'], 'Gaylord Perry', 'US Sports', 7),
('The "Dream Team," widely considered the greatest sports team ever assembled, represented the US in basketball at which Olympics?', ARRAY['1988 Seoul','1992 Barcelona','1996 Atlanta','2000 Sydney'], '1992 Barcelona', 'US Sports', 5),
('Which American college football bowl game is the oldest, first played in 1902?', ARRAY['Sugar Bowl','Orange Bowl','Cotton Bowl','Rose Bowl'], 'Rose Bowl', 'US Sports', 4),
('What is the nickname for the Toronto Blue Jays'' stadium, the Rogers Centre, before it was renamed in 2005?', ARRAY['Exhibition Stadium','SkyDome','Maple Leaf Stadium','Metro Dome'], 'SkyDome', 'US Sports', 6);

