-- Migration 014: Expand question bank (batch 5)
-- 384 questions across 8 categories

-- American Culture (50 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the most widely consumed fast-food item in the United States?',
 ARRAY['Fried chicken','The hamburger','French fries','Hot dogs'],
 'The hamburger', 'American Culture', 1),
('What sport is the Super Bowl associated with?',
 ARRAY['Baseball','Basketball','American Football','Ice Hockey'],
 'American Football', 'American Culture', 1),
('On which holiday do Americans traditionally carve jack-o''-lanterns?',
 ARRAY['Thanksgiving','Christmas','Fourth of July','Halloween'],
 'Halloween', 'American Culture', 1),
('What dance style became synonymous with teenagers in the 1950s, popularized by artists like Elvis Presley and Chuck Berry?',
 ARRAY['The Charleston','The Jive','Rock and Roll dancing','The Lindy Hop'],
 'Rock and Roll dancing', 'American Culture', 1),
('Which American city is known as the "Motor City" due to its history as the center of the US automobile industry?',
 ARRAY['Cleveland','Pittsburgh','Detroit','Cincinnati'],
 'Detroit', 'American Culture', 1),
('The Nobel Prize-winning novel "The Grapes of Wrath" depicts the struggles of families during which historical event?',
 ARRAY['The Civil War','The Great Depression','World War II','The Dust Bowl Migration'],
 'The Dust Bowl Migration', 'American Culture', 2),
('Which US city hosts the Rose Bowl parade and game on New Year''s Day?',
 ARRAY['Los Angeles','San Francisco','Pasadena','San Diego'],
 'Pasadena', 'American Culture', 2),
('What US holiday is celebrated on the second Monday of October?',
 ARRAY['Presidents'' Day','Columbus Day','Veterans Day','Patriot Day'],
 'Columbus Day', 'American Culture', 2),
('In what decade did drive-in movie theaters peak in popularity in the United States?',
 ARRAY['1940s','1950s','1960s','1970s'],
 '1950s', 'American Culture', 2),
('The "American Gothic" painting by Grant Wood depicts a farmer and his daughter in front of what type of building?',
 ARRAY['A red barn','A white farmhouse','A Gothic-windowed house','A church'],
 'A Gothic-windowed house', 'American Culture', 2),
('What is the traditional gift for a 25th wedding anniversary in American culture?',
 ARRAY['Gold','Diamond','Silver','Pearl'],
 'Silver', 'American Culture', 2),
('The TV show "I Love Lucy" starred which actress in its lead role?',
 ARRAY['Lucille Ball','Ethel Mertz','Vivian Vance','Carol Burnett'],
 'Lucille Ball', 'American Culture', 3),
('Which American author wrote "The Catcher in the Rye"?',
 ARRAY['John Updike','Norman Mailer','J.D. Salinger','Philip Roth'],
 'J.D. Salinger', 'American Culture', 3),
('What annual event held in Austin, Texas, is a major festival celebrating music, film, and interactive media?',
 ARRAY['Lollapalooza','Bonnaroo','SXSW','Austin City Limits'],
 'SXSW', 'American Culture', 3),
('What is the name of the dance popularized in the 1920s associated with flappers?',
 ARRAY['The Foxtrot','The Charleston','The Black Bottom','The Turkey Trot'],
 'The Charleston', 'American Culture', 3),
('Which American literary movement of the 1830s and 1840s emphasized the inherent goodness of people and nature?',
 ARRAY['Romanticism','Transcendentalism','Realism','Naturalism'],
 'Transcendentalism', 'American Culture', 3),
('What annual parade, held in New York City on Thanksgiving Day, is one of the world''s largest?',
 ARRAY['Fifth Avenue Easter Parade','Macy''s Thanksgiving Day Parade','Columbus Day Parade','St. Patrick''s Day Parade'],
 'Macy''s Thanksgiving Day Parade', 'American Culture', 3),
('Which New York City neighborhood became the center of the 1920s African American cultural renaissance?',
 ARRAY['Brooklyn','Bronx','Harlem','The Bronx'],
 'Harlem', 'American Culture', 4),
('The art style known as "Abstract Expressionism" was centered in which US city in the 1940s and 1950s?',
 ARRAY['Los Angeles','Chicago','San Francisco','New York City'],
 'New York City', 'American Culture', 4),
('What was the name of the California commune founded by Ken Kesey and his "Merry Pranksters" that became a symbol of 1960s counterculture?',
 ARRAY['Haight-Ashbury','La Honda','The Farm','The Diggers'],
 'La Honda', 'American Culture', 4),
('Which famous New York music venue, located on 52nd Street, became the center of the bebop jazz scene in the 1940s?',
 ARRAY['Carnegie Hall','The Apollo Theater','Birdland','The Village Vanguard'],
 'Birdland', 'American Culture', 4),
('The literary group known as the "Algonquin Round Table" met regularly at the Algonquin Hotel in which city?',
 ARRAY['Boston','New York City','Chicago','Philadelphia'],
 'New York City', 'American Culture', 4),
('What is the name of the traditional Native American art form practiced by the Navajo that involves creating intricate patterns with sand?',
 ARRAY['Totem carving','Sand painting','Kachina doll making','Beadwork'],
 'Sand painting', 'American Culture', 4),
('Which US city is credited as the birthplace of the "grunge" music movement in the late 1980s?',
 ARRAY['Portland','San Francisco','Seattle','Los Angeles'],
 'Seattle', 'American Culture', 5),
('The Chautauqua Institution, founded in 1874, was influential in providing what type of educational experience?',
 ARRAY['Technical and vocational training','Adult education in arts, religion, and recreation','Agricultural science education','Military officer training'],
 'Adult education in arts, religion, and recreation', 'American Culture', 5),
('What is the name of the annual arts festival held in the Nevada desert that emphasizes radical self-expression?',
 ARRAY['Coachella','Electric Daisy Carnival','Burning Man','Desert Trip'],
 'Burning Man', 'American Culture', 5),
('Which American novelist wrote "Beloved," a Pulitzer Prize-winning story about the legacy of slavery?',
 ARRAY['Alice Walker','Maya Angelou','Zora Neale Hurston','Toni Morrison'],
 'Toni Morrison', 'American Culture', 5),
('What architectural style, developed by Frank Lloyd Wright, was characterized by horizontal lines and integration with the landscape?',
 ARRAY['Art Deco','Bauhaus','Prairie Style','Craftsman'],
 'Prairie Style', 'American Culture', 5),
('Which American poet wrote "Song of Myself," part of the collection "Leaves of Grass"?',
 ARRAY['Emily Dickinson','Robert Frost','Walt Whitman','Edgar Allan Poe'],
 'Walt Whitman', 'American Culture', 5),
('What is the term for the improvisational art of spoken word poetry accompanied by jazz music, popular in Beat Generation coffeehouses?',
 ARRAY['Spoken jazz','Poetry slam','Beatnik verse','Jazz poetry'],
 'Jazz poetry', 'American Culture', 5),
('The "Ashcan School" of American art, formed in the early 20th century, was known for depicting what kind of subjects?',
 ARRAY['Rural landscapes','Pastoral scenes','Urban everyday life','Abstract forms'],
 'Urban everyday life', 'American Culture', 6),
('Which dance was popularized in Harlem ballrooms in the late 1920s, named after Charles Lindbergh''s transatlantic flight?',
 ARRAY['The Jitterbug','The Lindy Hop','The Big Apple','The Shag'],
 'The Lindy Hop', 'American Culture', 6),
('The "Black Arts Movement" of the 1960s and 70s was closely associated with which broader political movement?',
 ARRAY['The Civil Rights Movement','The Black Power Movement','The New Left','The Anti-War Movement'],
 'The Black Power Movement', 'American Culture', 6),
('Which American comic artist created "Maus," the Pulitzer Prize-winning graphic novel about the Holocaust?',
 ARRAY['R. Crumb','Will Eisner','Art Spiegelman','Harvey Pekar'],
 'Art Spiegelman', 'American Culture', 6),
('The "Bread Loaf Writers'' Conference," one of the oldest literary conferences in the United States, is held in which state?',
 ARRAY['Massachusetts','New Hampshire','Connecticut','Vermont'],
 'Vermont', 'American Culture', 6),
('In which decade did hip-hop music first emerge as a distinct genre in New York City?',
 ARRAY['1960s','1970s','1980s','1990s'],
 '1970s', 'American Culture', 6),
('What is the name of the influential 1913 art exhibition in New York City that introduced European modern art to American audiences?',
 ARRAY['The Metropolitan Exhibition','The Armory Show','The Salon of Modern Art','The New York Art Exposition'],
 'The Armory Show', 'American Culture', 7),
('Which American composer wrote "Rhapsody in Blue," blending classical music with jazz elements?',
 ARRAY['Duke Ellington','Cole Porter','Irving Berlin','George Gershwin'],
 'George Gershwin', 'American Culture', 7),
('The "Second Great Awakening" religious revival movement of the early 19th century significantly influenced which social reform movement?',
 ARRAY['Women''s suffrage','The abolitionist movement','Temperance','All of the above'],
 'All of the above', 'American Culture', 7),
('Which abstract painter is associated with the "drip painting" technique and became a central figure of the New York School?',
 ARRAY['Willem de Kooning','Franz Kline','Jackson Pollock','Robert Rauschenberg'],
 'Jackson Pollock', 'American Culture', 7),
('What is the name of the artistic movement in the 1960s that incorporated everyday commercial objects and popular imagery as subject matter?',
 ARRAY['Abstract Expressionism','Minimalism','Pop Art','Conceptual Art'],
 'Pop Art', 'American Culture', 7),
('Which American literary critic coined the term "Avant-Garde and Kitsch" in his influential 1939 essay?',
 ARRAY['Edmund Wilson','Lionel Trilling','Clement Greenberg','Harold Rosenberg'],
 'Clement Greenberg', 'American Culture', 7),
('The "Harlem Renaissance" of the 1920s is also sometimes called by what other name?',
 ARRAY['The New Negro Movement','The Black Renaissance','The Harlem Awakening','The Negro Renaissance'],
 'The New Negro Movement', 'American Culture', 8),
('Which American composer and music theorist wrote "4''33''," a piece in which performers do not play their instruments for the entire duration?',
 ARRAY['Philip Glass','Steve Reich','John Cage','La Monte Young'],
 'John Cage', 'American Culture', 8),
('The literary device of "stream of consciousness" writing was prominently used by which American author in novels like "The Sound and the Fury"?',
 ARRAY['Ernest Hemingway','F. Scott Fitzgerald','William Faulkner','John Dos Passos'],
 'William Faulkner', 'American Culture', 8),
('Which American urban planning theorist wrote "The Death and Life of Great American Cities" in 1961?',
 ARRAY['Lewis Mumford','Robert Moses','Jane Jacobs','Kevin Lynch'],
 'Jane Jacobs', 'American Culture', 8),
('What is the name of the avant-garde art movement associated with Marcel Duchamp that challenged conventional definitions of art with "readymades"?',
 ARRAY['Surrealism','Fluxus','Dadaism','Conceptualism'],
 'Dadaism', 'American Culture', 9),
('Which American postmodern novelist wrote "The Crying of Lot 49," exploring themes of paranoia and entropy?',
 ARRAY['Don DeLillo','William Gaddis','John Barth','Thomas Pynchon'],
 'Thomas Pynchon', 'American Culture', 9),
('The "Social Gospel" movement of the late 19th and early 20th centuries sought to apply what principles to social problems?',
 ARRAY['Libertarian economics','Christian ethics','Secular humanism','Progressive politics'],
 'Christian ethics', 'American Culture', 9),
('Which composer and musician is credited with the invention of "prepared piano," altering the instrument with bolts, screws, and other objects?',
 ARRAY['Henry Cowell','Conlon Nancarrow','John Cage','Harry Partch'],
 'John Cage', 'American Culture', 9);

-- Civics (29 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the minimum age requirement to serve as a US Senator?',
 ARRAY['25','28','30','35'],
 '30', 'Civics', 1),
('What is the term length for a member of the House of Representatives?',
 ARRAY['2 years','4 years','6 years','8 years'],
 '2 years', 'Civics', 2),
('Which amendment to the Constitution sets the presidential term limit at two terms?',
 ARRAY['20th Amendment','21st Amendment','22nd Amendment','23rd Amendment'],
 '22nd Amendment', 'Civics', 2),
('What is the total number of electors in the Electoral College?',
 ARRAY['435','500','538','600'],
 '538', 'Civics', 3),
('How many justices sit on the US Supreme Court?',
 ARRAY['7','8','9','11'],
 '9', 'Civics', 3),
('Which clause of the Constitution grants Congress the power to make laws necessary to carry out its duties?',
 ARRAY['Commerce Clause','Supremacy Clause','Necessary and Proper Clause','Full Faith and Credit Clause'],
 'Necessary and Proper Clause', 'Civics', 3),
('What is the process by which a bill becomes a law if the president neither signs nor vetoes it?',
 ARRAY['The bill automatically becomes law after 10 days if Congress is in session','The bill is sent back to committee','The bill is automatically vetoed','The bill must be re-voted on'],
 'The bill automatically becomes law after 10 days if Congress is in session', 'Civics', 4),
('Which constitutional amendment abolished the poll tax in federal elections?',
 ARRAY['21st Amendment','22nd Amendment','23rd Amendment','24th Amendment'],
 '24th Amendment', 'Civics', 4),
('What is the term for the president''s power to refuse to sign a bill into law?',
 ARRAY['Filibuster','Pocket veto','Cloture','Prorogation'],
 'Pocket veto', 'Civics', 4),
('How many states must ratify a constitutional amendment for it to be adopted?',
 ARRAY['2/3 of states','3/4 of states','4/5 of states','All 50 states'],
 '3/4 of states', 'Civics', 5),
('Which Supreme Court case ruled that political spending by corporations is protected free speech?',
 ARRAY['Buckley v Valeo','Citizens United v FEC','McCutcheon v FEC','First National Bank v Bellotti'],
 'Citizens United v FEC', 'Civics', 5),
('What constitutional principle prevents any one branch of government from becoming too powerful?',
 ARRAY['Federalism','Separation of powers','Judicial review','Popular sovereignty'],
 'Separation of powers', 'Civics', 5),
('Which amendment to the Constitution allows citizens of Washington, DC, to vote in presidential elections?',
 ARRAY['21st Amendment','22nd Amendment','23rd Amendment','24th Amendment'],
 '23rd Amendment', 'Civics', 6),
('What is the constitutional requirement for a president to be eligible for office?',
 ARRAY['Must be at least 30 years old','Must be a natural-born citizen','Must have served in Congress','Must have lived in the US for 10 years'],
 'Must be a natural-born citizen', 'Civics', 6),
('Which landmark case established the "one person, one vote" principle for legislative districting?',
 ARRAY['Baker v Carr','Reynolds v Sims','Wesberry v Sanders','Gray v Sanders'],
 'Reynolds v Sims', 'Civics', 6),
('What constitutional provision requires states to honor the laws and court decisions of other states?',
 ARRAY['Supremacy Clause','Commerce Clause','Full Faith and Credit Clause','Privileges and Immunities Clause'],
 'Full Faith and Credit Clause', 'Civics', 7),
('What is the legal term for a court order requiring a person to be brought before a judge?',
 ARRAY['Subpoena','Habeas corpus','Certiorari','Injunction'],
 'Habeas corpus', 'Civics', 7),
('Which Supreme Court case held that the exclusionary rule applies to state courts?',
 ARRAY['Weeks v United States','Mapp v Ohio','Terry v Ohio','Katz v United States'],
 'Mapp v Ohio', 'Civics', 7),
('What is an ex post facto law?',
 ARRAY['A law that takes effect immediately','A law that punishes actions that were legal when committed','A law passed without debate','A law overturning a court decision'],
 'A law that punishes actions that were legal when committed', 'Civics', 8),
('Which Supreme Court case limited presidential power during the Korean War steel seizure crisis?',
 ARRAY['Youngstown Sheet & Tube Co v Sawyer','United States v Nixon','Dames & Moore v Regan','Hamdi v Rumsfeld'],
 'Youngstown Sheet & Tube Co v Sawyer', 'Civics', 8),
('What is the constitutional term for a law that singles out an individual for punishment without a trial?',
 ARRAY['Ex post facto law','Bill of attainder','Writ of mandamus','Nolle prosequi'],
 'Bill of attainder', 'Civics', 8),
('Which Supreme Court case established that defendants in criminal cases have a right to appointed counsel?',
 ARRAY['Miranda v Arizona','Gideon v Wainwright','Powell v Alabama','Escobedo v Illinois'],
 'Gideon v Wainwright', 'Civics', 9),
('What doctrine, established in Gibbons v Ogden, gave Congress broad power to regulate interstate commerce?',
 ARRAY['Necessary and Proper Clause','Commerce Clause','Supremacy Clause','Elastic Clause'],
 'Commerce Clause', 'Civics', 9),
('Which case ruled that Congress could create a national bank under the Necessary and Proper Clause?',
 ARRAY['Gibbons v Ogden','Fletcher v Peck','McCulloch v Maryland','Cohens v Virginia'],
 'McCulloch v Maryland', 'Civics', 9),
('What is the constitutional significance of United States v Nixon (1974)?',
 ARRAY['It established executive privilege has limits','It allowed a sitting president to be indicted','It ruled the president could pardon himself','It required presidential financial disclosures'],
 'It established executive privilege has limits', 'Civics', 9),
('In what year was the US Constitution ratified?',
 ARRAY['1776','1781','1788','1791'],
 '1788', 'Civics', 1),
('Which amendment gave 18-year-olds the right to vote?',
 ARRAY['24th Amendment','25th Amendment','26th Amendment','27th Amendment'],
 '26th Amendment', 'Civics', 1),
('What are the first three words of the US Constitution?',
 ARRAY['Congress shall make','We hold these','We the People','In Congress assembled'],
 'We the People', 'Civics', 1),
('How many senators does each state send to the US Senate?',
 ARRAY['1','2','3','4'],
 '2', 'Civics', 2);

-- Famous Americans (42 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which inventor is credited with creating the first practical light bulb?',
 ARRAY['Nikola Tesla','Benjamin Franklin','Thomas Edison','Alexander Graham Bell'],
 'Thomas Edison', 'Famous Americans', 1),
('Which civil rights leader delivered the famous "I Have a Dream" speech in Washington, D.C. in 1963?',
 ARRAY['Malcolm X','Thurgood Marshall','John Lewis','Martin Luther King Jr.'],
 'Martin Luther King Jr.', 'Famous Americans', 1),
('Which American author wrote "The Adventures of Tom Sawyer" and "Adventures of Huckleberry Finn"?',
 ARRAY['Jack London','Nathaniel Hawthorne','Herman Melville','Mark Twain'],
 'Mark Twain', 'Famous Americans', 1),
('Which president issued the Emancipation Proclamation during the Civil War?',
 ARRAY['Ulysses S. Grant','Andrew Johnson','James Buchanan','Abraham Lincoln'],
 'Abraham Lincoln', 'Famous Americans', 2),
('Who is known as the "Father of the Constitution" for his role in drafting the US Constitution?',
 ARRAY['Alexander Hamilton','John Jay','Benjamin Franklin','James Madison'],
 'James Madison', 'Famous Americans', 2),
('Which American aviator became the first person to break the sound barrier in 1947?',
 ARRAY['Jimmy Doolittle','Bob Hoover','Charles Lindbergh','Chuck Yeager'],
 'Chuck Yeager', 'Famous Americans', 2),
('Who founded Standard Oil in 1870 and became America''s first billionaire?',
 ARRAY['Andrew Carnegie','J.P. Morgan','Cornelius Vanderbilt','John D. Rockefeller'],
 'John D. Rockefeller', 'Famous Americans', 2),
('Which Supreme Court Justice became the first African American to serve on the Court?',
 ARRAY['Clarence Thomas','John Marshall Harlan','William O. Douglas','Thurgood Marshall'],
 'Thurgood Marshall', 'Famous Americans', 2),
('Which poet wrote "The Road Not Taken" and is associated with the rural landscapes of New England?',
 ARRAY['Carl Sandburg','Edwin Arlington Robinson','Wallace Stevens','Robert Frost'],
 'Robert Frost', 'Famous Americans', 2),
('Who led the Lewis and Clark Expedition along with William Clark?',
 ARRAY['John C. Frémont','Zebulon Pike','Meriwether Lewis','Stephen Long'],
 'Meriwether Lewis', 'Famous Americans', 3),
('Which African American abolitionist escaped slavery and became a leading voice against the institution, writing "Narrative of the Life of Frederick Douglass"?',
 ARRAY['Nat Turner','Denmark Vesey','Sojourner Truth','Frederick Douglass'],
 'Frederick Douglass', 'Famous Americans', 3),
('Which American author wrote "The Old Man and the Sea," for which he won the Nobel Prize in Literature?',
 ARRAY['John Steinbeck','William Faulkner','Sinclair Lewis','Ernest Hemingway'],
 'Ernest Hemingway', 'Famous Americans', 3),
('Who co-founded Apple Inc. with Steve Jobs in 1976?',
 ARRAY['Bill Gates','Paul Allen','Steve Wozniak','Jonathan Ive'],
 'Steve Wozniak', 'Famous Americans', 3),
('Which American photographer is renowned for his large-format black-and-white photographs of the American West and Yosemite?',
 ARRAY['Dorothea Lange','Edward Weston','Alfred Stieglitz','Ansel Adams'],
 'Ansel Adams', 'Famous Americans', 3),
('Which labor leader co-founded the United Farm Workers union in 1962 and led campaigns for better working conditions for agricultural laborers?',
 ARRAY['Eugene V. Debs','Samuel Gompers','Jimmy Hoffa','Cesar Chavez'],
 'Cesar Chavez', 'Famous Americans', 4),
('Which American physicist is considered the "Father of the Hydrogen Bomb"?',
 ARRAY['J. Robert Oppenheimer','Enrico Fermi','Hans Bethe','Edward Teller'],
 'Edward Teller', 'Famous Americans', 4),
('Who was the first African American woman to be elected to the US House of Representatives?',
 ARRAY['Barbara Jordan','Maxine Waters','Shirley Chisholm','Corrine Brown'],
 'Shirley Chisholm', 'Famous Americans', 4),
('Which pioneering American environmentalist wrote "A Sand County Almanac," laying the foundation for modern environmental ethics?',
 ARRAY['John Muir','David Thoreau','Aldo Leopold','Edward Abbey'],
 'Aldo Leopold', 'Famous Americans', 4),
('Which American architect designed the Fallingwater house in Pennsylvania, considered a masterpiece of organic architecture?',
 ARRAY['Louis Sullivan','Mies van der Rohe','Frank Lloyd Wright','Philip Johnson'],
 'Frank Lloyd Wright', 'Famous Americans', 4),
('Who designed the Vietnam Veterans Memorial in Washington, D.C.?',
 ARRAY['I.M. Pei','Frank Gehry','Eero Saarinen','Maya Lin'],
 'Maya Lin', 'Famous Americans', 4),
('Which American mathematician is credited with developing information theory in 1948?',
 ARRAY['Norbert Wiener','John von Neumann','Alan Turing','Claude Shannon'],
 'Claude Shannon', 'Famous Americans', 5),
('Which writer and social activist wrote "The Jungle" in 1906, exposing unsanitary conditions in the meatpacking industry?',
 ARRAY['Lincoln Steffens','Ida Tarbell','Jacob Riis','Upton Sinclair'],
 'Upton Sinclair', 'Famous Americans', 5),
('Who was the first African American woman to win the Academy Award for Best Actress?',
 ARRAY['Whoopi Goldberg','Angela Bassett','Viola Davis','Halle Berry'],
 'Halle Berry', 'Famous Americans', 5),
('Which pioneering female pilot was the first African American woman to earn a pilot''s license?',
 ARRAY['Harriet Quimby','Amelia Earhart','Ruth Elder','Bessie Coleman'],
 'Bessie Coleman', 'Famous Americans', 5),
('Which American economist developed the theory of "creative destruction" to explain the process of industrial mutation?',
 ARRAY['Milton Friedman','John Kenneth Galbraith','Paul Samuelson','Joseph Schumpeter'],
 'Joseph Schumpeter', 'Famous Americans', 5),
('Which African American intellectual wrote "The Souls of Black Folk" and co-founded the NAACP?',
 ARRAY['Booker T. Washington','Marcus Garvey','Carter G. Woodson','W.E.B. Du Bois'],
 'W.E.B. Du Bois', 'Famous Americans', 5),
('Who was the first woman to argue a case before the US Supreme Court, in 1880?',
 ARRAY['Arabella Mansfield','Myra Bradwell','Belva Lockwood','Catharine Waugh McCulloch'],
 'Belva Lockwood', 'Famous Americans', 6),
('Which American inventor and entrepreneur co-founded Tesla, Inc. and SpaceX?',
 ARRAY['Jeff Bezos','Larry Page','Peter Thiel','Elon Musk'],
 'Elon Musk', 'Famous Americans', 6),
('Which American biologist and conservationist wrote "Silent Spring," which helped launch the modern environmental movement?',
 ARRAY['Rachel Carson','Margaret Mead','Barbara McClintock','Lynn Margulis'],
 'Rachel Carson', 'Famous Americans', 6),
('Which Native American athlete won gold medals in both the pentathlon and decathlon at the 1912 Stockholm Olympics?',
 ARRAY['Billy Mills','Louis Tewanima','Jim Thorpe','Duke Kahanamoku'],
 'Jim Thorpe', 'Famous Americans', 6),
('Which mathematician''s work on game theory, the subject of the film "A Beautiful Mind," earned him the Nobel Prize in Economics?',
 ARRAY['John von Neumann','Kenneth Arrow','Lloyd Shapley','John Nash'],
 'John Nash', 'Famous Americans', 7),
('Which African American poet and novelist wrote "I Know Why the Caged Bird Sings"?',
 ARRAY['Gwendolyn Brooks','Nikki Giovanni','Sonia Sanchez','Maya Angelou'],
 'Maya Angelou', 'Famous Americans', 7),
('Which American linguist is often called the "Father of Modern Linguistics" and is also known for his political writings?',
 ARRAY['Steven Pinker','Leonard Bloomfield','Edward Sapir','Noam Chomsky'],
 'Noam Chomsky', 'Famous Americans', 7),
('Which American physicist won the Nobel Prize in 1965 for his work on quantum electrodynamics?',
 ARRAY['Murray Gell-Mann','Julian Schwinger','J. Robert Oppenheimer','Richard Feynman'],
 'Richard Feynman', 'Famous Americans', 8),
('Who was the first American woman to earn a Nobel Prize in Literature?',
 ARRAY['Toni Morrison','Harper Lee','Edith Wharton','Pearl Buck'],
 'Pearl Buck', 'Famous Americans', 8),
('Which American civil engineer designed the Brooklyn Bridge, completing construction in 1883?',
 ARRAY['Gustave Eiffel','John Roebling','James Eads','George Washington Goethals'],
 'John Roebling', 'Famous Americans', 8),
('Which African American inventor received over 50 patents and is best known for developing the gas mask and traffic signal?',
 ARRAY['Lewis Latimer','Granville T. Woods','Elijah McCoy','Garrett Morgan'],
 'Garrett Morgan', 'Famous Americans', 8),
('Who was the first female doctor in the United States, receiving her medical degree in 1849?',
 ARRAY['Mary Putnam Jacobi','Elizabeth Blackwell','Mary Walker','Emily Blackwell'],
 'Elizabeth Blackwell', 'Famous Americans', 9),
('Which American microbiologist discovered streptomycin, the first antibiotic effective against tuberculosis?',
 ARRAY['René Dubos','Ernst Chain','Howard Florey','Selman Waksman'],
 'Selman Waksman', 'Famous Americans', 9),
('Which American sculptor created the "Spiral Jetty," a monumental earthwork in the Great Salt Lake?',
 ARRAY['Donald Judd','Carl Andre','Dan Flavin','Robert Smithson'],
 'Robert Smithson', 'Famous Americans', 9),
('Who was the first African American woman to serve in a US presidential Cabinet, appointed as Secretary of Housing and Urban Development in 1977?',
 ARRAY['Alexis Herman','Hazel O''Leary','Condoleezza Rice','Patricia Roberts Harris'],
 'Patricia Roberts Harris', 'Famous Americans', 9),
('Which American chemist at DuPont invented nylon in 1935, revolutionizing the textile industry?',
 ARRAY['Charles Goodyear','Leo Baekeland','Roy Plunkett','Wallace Carothers'],
 'Wallace Carothers', 'Famous Americans', 9);

-- Geography (47 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What river forms the border between Texas and Mexico?',
 ARRAY['Colorado River','Pecos River','Rio Grande','Brazos River'],
 'Rio Grande', 'Geography', 1),
('Which US state is the largest by total area?',
 ARRAY['Texas','California','Montana','Alaska'],
 'Alaska', 'Geography', 1),
('What is the capital city of the United States?',
 ARRAY['New York City','Boston','Washington DC','Philadelphia'],
 'Washington DC', 'Geography', 1),
('What is the smallest state in the United States by area?',
 ARRAY['Connecticut','Delaware','New Hampshire','Rhode Island'],
 'Rhode Island', 'Geography', 1),
('Which state is made up entirely of islands?',
 ARRAY['Florida','Puerto Rico','Hawaii','Alaska'],
 'Hawaii', 'Geography', 1),
('What mountain range runs along the eastern United States?',
 ARRAY['Rocky Mountains','Sierra Nevada','Cascade Range','Appalachian Mountains'],
 'Appalachian Mountains', 'Geography', 2),
('Which US state borders only one other US state?',
 ARRAY['Florida','Maine','California','Oregon'],
 'Maine', 'Geography', 2),
('Which state contains the Grand Canyon?',
 ARRAY['Utah','Nevada','Arizona','New Mexico'],
 'Arizona', 'Geography', 2),
('What is the capital of Texas?',
 ARRAY['Houston','Dallas','San Antonio','Austin'],
 'Austin', 'Geography', 2),
('What is the deepest lake in the United States?',
 ARRAY['Lake Tahoe','Crater Lake','Lake Superior','Flathead Lake'],
 'Crater Lake', 'Geography', 3),
('Which state has the most active volcanoes?',
 ARRAY['Hawaii','Washington','Oregon','Alaska'],
 'Alaska', 'Geography', 3),
('What is the capital of California?',
 ARRAY['Los Angeles','San Francisco','San Diego','Sacramento'],
 'Sacramento', 'Geography', 3),
('Which US territory is located in the Caribbean Sea?',
 ARRAY['Guam','American Samoa','US Virgin Islands','Northern Mariana Islands'],
 'US Virgin Islands', 'Geography', 3),
('What geographic feature divides North America into two drainage basins, flowing to either the Atlantic or Pacific?',
 ARRAY['Sierra Nevada','Rocky Mountains','Continental Divide','Appalachian Mountains'],
 'Continental Divide', 'Geography', 3),
('Which state is the largest in the contiguous United States by area?',
 ARRAY['California','Montana','Nevada','Texas'],
 'Texas', 'Geography', 4),
('Which US state capital shares a name with a famous English explorer?',
 ARRAY['Jackson','Lincoln','Columbus','Raleigh'],
 'Raleigh', 'Geography', 4),
('The Four Corners monument marks the intersection of which four states?',
 ARRAY['Arizona, Colorado, New Mexico, and Utah','Arizona, Nevada, Utah, and Colorado','New Mexico, Texas, Oklahoma, and Colorado','Utah, Wyoming, Colorado, and Idaho'],
 'Arizona, Colorado, New Mexico, and Utah', 'Geography', 4),
('What is the capital of Colorado?',
 ARRAY['Colorado Springs','Boulder','Fort Collins','Denver'],
 'Denver', 'Geography', 4),
('Which large wetland ecosystem is found in southern Florida?',
 ARRAY['Okefenokee Swamp','Big Cypress Swamp','Florida Everglades','Atchafalaya Basin'],
 'Florida Everglades', 'Geography', 4),
('What is the name of the narrow body of water separating Alaska from Russia?',
 ARRAY['Davis Strait','Bering Strait','Cook Inlet','Prince William Sound'],
 'Bering Strait', 'Geography', 4),
('Which state contains the geographic center of the contiguous 48 states?',
 ARRAY['Nebraska','Missouri','Oklahoma','Kansas'],
 'Kansas', 'Geography', 5),
('What is the name of the large underground water reserve that underlies much of the Great Plains?',
 ARRAY['Columbia Aquifer','Floridan Aquifer','Edwards Aquifer','Ogallala Aquifer'],
 'Ogallala Aquifer', 'Geography', 5),
('Which mountain range dominates the Pacific Northwest states of Washington and Oregon?',
 ARRAY['Sierra Nevada','Rocky Mountains','Cascade Range','Coast Range'],
 'Cascade Range', 'Geography', 5),
('What is the name of the fertile agricultural valley in the center of California?',
 ARRAY['San Joaquin Valley','Napa Valley','Salinas Valley','Central Valley'],
 'Central Valley', 'Geography', 5),
('Which US state contains the most counties?',
 ARRAY['California','New York','Georgia','Texas'],
 'Texas', 'Geography', 5),
('What is the name of the large estuary formed by the Susquehanna River on the mid-Atlantic coast?',
 ARRAY['Delaware Bay','Albemarle Sound','Chesapeake Bay','Pamlico Sound'],
 'Chesapeake Bay', 'Geography', 5),
('Which state capital sits at the highest elevation in the United States?',
 ARRAY['Denver','Boise','Salt Lake City','Santa Fe'],
 'Santa Fe', 'Geography', 5),
('What peninsula separates the Chesapeake Bay from the Atlantic Ocean, spanning Maryland, Delaware, and Virginia?',
 ARRAY['Cape Cod','Outer Banks','Delmarva Peninsula','Virginia Peninsula'],
 'Delmarva Peninsula', 'Geography', 6),
('Which US state contains more Native American reservations than any other state?',
 ARRAY['New Mexico','South Dakota','Montana','Arizona'],
 'Arizona', 'Geography', 6),
('What is the name of the volcanic plateau covering parts of Washington, Oregon, and Idaho?',
 ARRAY['Great Basin','Colorado Plateau','Snake River Plain','Columbia Plateau'],
 'Columbia Plateau', 'Geography', 6),
('Which state is entirely contained within the Appalachian Mountains and has no large cities?',
 ARRAY['Vermont','Kentucky','West Virginia','Tennessee'],
 'West Virginia', 'Geography', 6),
('What is the name of the large river basin and wetland system in southern Louisiana formed by the Mississippi River?',
 ARRAY['Pearl River Basin','Red River Delta','Tensas Basin','Atchafalaya Basin'],
 'Atchafalaya Basin', 'Geography', 6),
('Which US territory is located closest to the Philippines in the western Pacific?',
 ARRAY['American Samoa','Wake Island','Northern Mariana Islands','Guam'],
 'Guam', 'Geography', 6),
('What is the name of the ancient volcanic crater in Oregon that now holds the nation''s deepest lake?',
 ARRAY['Mount Hood','Mount Mazama','Mount Bachelor','Mount Thielsen'],
 'Mount Mazama', 'Geography', 7),
('Which region of the upper Midwest was largely unaffected by glaciation and retains a distinctive hilly topography?',
 ARRAY['Great Lakes Plain','Till Plain','Prairie Peninsula','Driftless Area'],
 'Driftless Area', 'Geography', 7),
('What is the name of the undersea mountain chain in the Pacific Ocean that traces the Hawaiian Islands'' volcanic origin?',
 ARRAY['Aleutian Arc','Mid-Pacific Mountains','Emperor Seamount Chain','Mariana Arc'],
 'Emperor Seamount Chain', 'Geography', 7),
('Which confluence near Cairo, Illinois, is one of the most significant river junctions in North America?',
 ARRAY['Missouri and Mississippi Rivers','Tennessee and Ohio Rivers','Ohio and Mississippi Rivers','Arkansas and Mississippi Rivers'],
 'Ohio and Mississippi Rivers', 'Geography', 7),
('What is the name of the offshore tectonic boundary responsible for volcanic activity along the Oregon coast?',
 ARRAY['San Andreas Fault','Ring of Fire','Juan de Fuca Ridge','Cascadia Subduction Zone'],
 'Juan de Fuca Ridge', 'Geography', 7),
('Which state has the most federally protected land as a percentage of its total area?',
 ARRAY['Wyoming','California','Idaho','Alaska'],
 'Alaska', 'Geography', 7),
('What is the name of the inland sea in Southern California created accidentally by a 1905 engineering failure?',
 ARRAY['Mono Lake','Lake Havasu','Salton Sea','Clear Lake'],
 'Salton Sea', 'Geography', 8),
('What geographic term describes the narrow lowland region between the Appalachian Mountains and the Atlantic Coastal Plain?',
 ARRAY['Tidewater','Fall Line','Piedmont','Blue Ridge'],
 'Piedmont', 'Geography', 8),
('Which state contains the point farthest from any ocean or sea coast in the contiguous United States?',
 ARRAY['Nebraska','Kansas','Wyoming','South Dakota'],
 'South Dakota', 'Geography', 8),
('What is the name of the ancient glacial lake whose bed now forms the flat terrain of much of the Red River Valley along the Minnesota-North Dakota border?',
 ARRAY['Lake Agassiz','Lake Bonneville','Lake Lahontan','Lake Duluth'],
 'Lake Agassiz', 'Geography', 8),
('Which US state has the longest total coastline, including all bays and inlets?',
 ARRAY['California','Florida','Texas','Alaska'],
 'Alaska', 'Geography', 8),
('What is the name of the volcanic island chain in the Pacific that forms the western boundary of the Bering Sea?',
 ARRAY['Hawaiian Islands','Mariana Islands','Aleutian Islands','Line Islands'],
 'Aleutian Islands', 'Geography', 9),
('What geographic feature known as the "rain shadow effect" makes eastern Washington significantly drier than western Washington?',
 ARRAY['Rocky Mountains','Sierra Nevada','Cascade Range','Blue Mountains'],
 'Cascade Range', 'Geography', 9),
('Which landlocked body of water in Utah is the remnant of ancient Lake Bonneville, once covering much of the Great Basin?',
 ARRAY['Utah Lake','Bear Lake','Sevier Lake','Great Salt Lake'],
 'Great Salt Lake', 'Geography', 9);

-- Landmarks (51 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('In which city is the Statue of Liberty located?',
 ARRAY['Boston','Philadelphia','Washington DC','New York City'],
 'New York City', 'Landmarks', 1),
('What city is home to the Golden Gate Bridge?',
 ARRAY['Los Angeles','Seattle','San Francisco','Portland'],
 'San Francisco', 'Landmarks', 1),
('In which city is the Liberty Bell displayed?',
 ARRAY['Boston','New York City','Washington DC','Philadelphia'],
 'Philadelphia', 'Landmarks', 1),
('What famous monument in Washington DC depicts four US presidents carved into granite?',
 ARRAY['Lincoln Memorial','Washington Monument','Mount Rushmore','Jefferson Memorial'],
 'Mount Rushmore', 'Landmarks', 1),
('What is the name of the iconic arch-shaped monument in St. Louis, Missouri?',
 ARRAY['Independence Arch','Jefferson Arch','Freedom Arch','Gateway Arch'],
 'Gateway Arch', 'Landmarks', 1),
('Which famous memorial in Washington DC honors soldiers who died in the Vietnam War?',
 ARRAY['Korean War Veterans Memorial','World War II Memorial','Vietnam Veterans Memorial','Arlington National Cemetery'],
 'Vietnam Veterans Memorial', 'Landmarks', 1),
('What is the name of the famous clock tower at the top of Independence Hall in Philadelphia?',
 ARRAY['Bell Tower','Liberty Tower','Congress Hall','Independence Hall Tower'],
 'Independence Hall Tower', 'Landmarks', 2),
('Which famous dam on the Colorado River was completed in 1936 and sits on the Nevada-Arizona border?',
 ARRAY['Glen Canyon Dam','Boulder Dam','Shasta Dam','Hoover Dam'],
 'Hoover Dam', 'Landmarks', 2),
('What is the name of the famous historic street in New Orleans known for its nightlife and Mardi Gras celebrations?',
 ARRAY['Canal Street','Magazine Street','Bourbon Street','Frenchmen Street'],
 'Bourbon Street', 'Landmarks', 2),
('Which famous outdoor music venue near Denver, Colorado, is carved into a natural red rock formation?',
 ARRAY['Fiddler''s Green','Red Rocks Amphitheatre','Chautauqua Auditorium','Pepsi Center'],
 'Red Rocks Amphitheatre', 'Landmarks', 2),
('What is the name of the tallest monument in the United States, located in Washington DC?',
 ARRAY['Lincoln Memorial','Jefferson Memorial','Capitol Dome','Washington Monument'],
 'Washington Monument', 'Landmarks', 2),
('Which San Francisco island served as a federal penitentiary from 1934 to 1963?',
 ARRAY['Angel Island','Treasure Island','Yerba Buena Island','Alcatraz'],
 'Alcatraz', 'Landmarks', 3),
('What is the name of the famous baseball stadium in Boston, one of the oldest in Major League Baseball?',
 ARRAY['Wrigley Field','Yankee Stadium','Camden Yards','Fenway Park'],
 'Fenway Park', 'Landmarks', 3),
('In which city is the Space Needle located?',
 ARRAY['Portland','Vancouver','Seattle','Tacoma'],
 'Seattle', 'Landmarks', 3),
('What famous estate and museum in Asheville, North Carolina, was built by George Vanderbilt in the 1890s?',
 ARRAY['Marble House','The Breakers','Biltmore Estate','Vanderbilt Mansion'],
 'Biltmore Estate', 'Landmarks', 3),
('Which famous open-air market in Seattle has operated continuously since 1907?',
 ARRAY['Fremont Market','University District Farmers Market','Capitol Hill Market','Pike Place Market'],
 'Pike Place Market', 'Landmarks', 3),
('What famous church in Montgomery, Alabama, was the congregation of Martin Luther King Jr. during the Civil Rights Movement?',
 ARRAY['16th Street Baptist Church','Ebenezer Baptist Church','First Baptist Church','Dexter Avenue King Memorial Baptist Church'],
 'Dexter Avenue King Memorial Baptist Church', 'Landmarks', 3),
('Which US national park in California is famous for its giant sequoia trees?',
 ARRAY['Yosemite','Kings Canyon','Joshua Tree','Sequoia National Park'],
 'Sequoia National Park', 'Landmarks', 4),
('What famous mansion in Newport, Rhode Island, was built by Cornelius Vanderbilt II and features 70 rooms?',
 ARRAY['Marble House','Rosecliff','Belcourt Castle','The Breakers'],
 'The Breakers', 'Landmarks', 4),
('What is the name of the suspension bridge that connects Michigan''s two peninsulas?',
 ARRAY['Ambassador Bridge','Blue Water Bridge','Mackinac Bridge','International Bridge'],
 'Mackinac Bridge', 'Landmarks', 4),
('Which Frank Lloyd Wright masterpiece in rural Pennsylvania is built over a waterfall?',
 ARRAY['Taliesin','Unity Temple','Fallingwater','Guggenheim Museum'],
 'Fallingwater', 'Landmarks', 4),
('What is the name of the famous Civil War battlefield cemetery in Pennsylvania where Lincoln delivered the Gettysburg Address?',
 ARRAY['Antietam National Cemetery','Arlington National Cemetery','Soldiers'' National Cemetery','Cold Harbor National Cemetery'],
 'Soldiers'' National Cemetery', 'Landmarks', 4),
('What famous castle built by newspaper magnate William Randolph Hearst sits along the California coast?',
 ARRAY['Vanderbilt Castle','Winchester Mystery House','Hearst Castle','Mission Inn'],
 'Hearst Castle', 'Landmarks', 4),
('Which landmark tower in Seattle was built for the 1962 World''s Fair?',
 ARRAY['Columbia Center','Smith Tower','Space Needle','Seattle Tower'],
 'Space Needle', 'Landmarks', 5),
('In which Ohio city is the Rock and Roll Hall of Fame located?',
 ARRAY['Columbus','Cincinnati','Akron','Cleveland'],
 'Cleveland', 'Landmarks', 5),
('What is the name of the famous pastel-painted row of historic houses in Charleston, South Carolina?',
 ARRAY['Rainbow Row','Antebellum Row','Preservation Row','Battery Row'],
 'Rainbow Row', 'Landmarks', 5),
('Which historic fort in Charleston Harbor was the site of the first shots of the Civil War in 1861?',
 ARRAY['Fort Moultrie','Fort Wagner','Fort Johnson','Fort Sumter'],
 'Fort Sumter', 'Landmarks', 5),
('What is the name of the famous Gothic Revival cathedral in New York City that took 83 years to build?',
 ARRAY['Trinity Church','St. Patrick''s Cathedral','Cathedral of St. John the Divine','Riverside Church'],
 'Cathedral of St. John the Divine', 'Landmarks', 5),
('Which famous art museum occupies a building on Fifth Avenue in New York City?',
 ARRAY['Museum of Modern Art','Whitney Museum','Guggenheim Museum','Metropolitan Museum of Art'],
 'Metropolitan Museum of Art', 'Landmarks', 5),
('What famous Los Angeles landmark was originally built in 1923 as a real estate advertisement?',
 ARRAY['Griffith Observatory','Getty Center','Hollywood Sign','Watts Towers'],
 'Hollywood Sign', 'Landmarks', 6),
('Which bridge connects San Francisco to Oakland across San Francisco Bay?',
 ARRAY['Golden Gate Bridge','Richmond-San Rafael Bridge','San Mateo Bridge','Bay Bridge'],
 'Bay Bridge', 'Landmarks', 6),
('What is the name of the famous estate in Charlottesville, Virginia, designed and built by Thomas Jefferson?',
 ARRAY['Montpelier','Mount Vernon','Poplar Forest','Monticello'],
 'Monticello', 'Landmarks', 6),
('Which building in Chicago, completed in 1885, is considered the first modern skyscraper?',
 ARRAY['Monadnock Building','Rookery Building','Reliance Building','Home Insurance Building'],
 'Home Insurance Building', 'Landmarks', 6),
('What is the name of the famous outdoor sculpture towers in Los Angeles built over 33 years by a single Italian immigrant?',
 ARRAY['Griffith Towers','Boyle Heights Towers','East LA Towers','Watts Towers'],
 'Watts Towers', 'Landmarks', 6),
('Which historic hotel in San Antonio, Texas, opened in 1859 and hosted figures like Robert E. Lee and Ulysses S. Grant?',
 ARRAY['St. Anthony Hotel','Gunter Hotel','La Mansion del Rio','Menger Hotel'],
 'Menger Hotel', 'Landmarks', 6),
('What palace-like building in San Francisco was originally constructed for the 1915 Panama-Pacific International Exposition?',
 ARRAY['War Memorial Opera House','Civic Center Auditorium','City Hall','Palace of Fine Arts'],
 'Palace of Fine Arts', 'Landmarks', 7),
('Which residential towers at 860-880 Lake Shore Drive in Chicago are considered masterpieces of modernist architecture designed by Mies van der Rohe?',
 ARRAY['Marina City Towers','John Hancock Center','Inland Steel Building','860-880 Lake Shore Drive Apartments'],
 '860-880 Lake Shore Drive Apartments', 'Landmarks', 7),
('What is the name of the oldest lighthouse in Maine, perched on a rocky promontory at the entrance to Portland Harbor?',
 ARRAY['Pemaquid Point Light','West Quoddy Head Light','Owls Head Light','Portland Head Light'],
 'Portland Head Light', 'Landmarks', 7),
('Which Art Deco skyscraper in New York City briefly held the title of world''s tallest building in 1930?',
 ARRAY['Empire State Building','30 Rockefeller Plaza','One Wall Street','Chrysler Building'],
 'Chrysler Building', 'Landmarks', 7),
('What is the name of the canal completed in 1825 that connected the Hudson River to the Great Lakes, transforming New York City into a commercial hub?',
 ARRAY['Champlain Canal','Chesapeake and Ohio Canal','Delaware Canal','Erie Canal'],
 'Erie Canal', 'Landmarks', 7),
('What historic trading post in Colorado, reconstructed by the National Park Service, was a key center of the Rocky Mountain fur trade in the 1830s?',
 ARRAY['Fort Laramie','Bent''s Old Fort','Fort Union','Fort Benton'],
 'Bent''s Old Fort', 'Landmarks', 7),
('What is the name of the famous Victorian mansion complex in Newport, Rhode Island, built by William Vanderbilt and known for its marble entrance hall?',
 ARRAY['The Elms','Marble House','Kingscote','Chateau-sur-Mer'],
 'Marble House', 'Landmarks', 8),
('Which museum in Vermont is famous for its Horseshoe Barn and enormous collection of American folk art and architecture?',
 ARRAY['Vermont History Museum','Billings Farm Museum','ECHO Science Center','Shelburne Museum'],
 'Shelburne Museum', 'Landmarks', 8),
('What is the name of the ornate bridge in Boston known as the "salt-and-pepper shakers bridge" for its distinctive towers?',
 ARRAY['Charles River Dam Bridge','North Washington Street Bridge','Bunker Hill Bridge','Longfellow Bridge'],
 'Longfellow Bridge', 'Landmarks', 8),
('Which grand plantation home in Natchez, Mississippi, is considered one of the finest examples of Greek Revival architecture in the South?',
 ARRAY['Oak Alley Plantation','Stanton Hall','Dunleith','Longwood'],
 'Longwood', 'Landmarks', 8),
('What is the name of the first national monument in the United States, designated by Theodore Roosevelt in 1906?',
 ARRAY['Muir Woods','Natural Bridges','Petrified Forest','Devils Tower'],
 'Devils Tower', 'Landmarks', 8),
('Which limestone cavern system in New Mexico, designated a UNESCO World Heritage Site, contains one of the largest cave chambers in North America?',
 ARRAY['Mammoth Cave','Wind Cave','Luray Caverns','Carlsbad Caverns'],
 'Carlsbad Caverns', 'Landmarks', 9),
('What is the name of the partially completed memorial in South Dakota depicting a Lakota warrior on horseback that has been under construction since 1948?',
 ARRAY['Sitting Bull Memorial','Red Cloud Memorial','Crazy Horse Memorial','Spotted Tail Memorial'],
 'Crazy Horse Memorial', 'Landmarks', 9),
('Which historic inn and marketplace in Boston, established in 1742, served as a center of colonial commerce and Revolutionary-era debate?',
 ARRAY['Old South Meeting House','Paul Revere House','Old State House','Faneuil Hall'],
 'Faneuil Hall', 'Landmarks', 9),
('What is the name of the Gilded Age mansion in Lenox, Massachusetts, that was the summer home of novelist Edith Wharton?',
 ARRAY['Naumkeag','Bellefontaine','Elm Court','The Mount'],
 'The Mount', 'Landmarks', 9),
('Which early 20th-century bridge in Boston''s Charles River basin was designated a Boston Landmark for its distinctive granite towers with ornamental urns?',
 ARRAY['Anderson Bridge','River Street Bridge','Western Avenue Bridge','Longfellow Bridge'],
 'Longfellow Bridge', 'Landmarks', 9);

-- Military (51 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which branch of the US military is responsible for operating submarines?',
 ARRAY['US Army','US Navy','US Marine Corps','US Coast Guard'],
 'US Navy', 'Military', 1),
('What does the acronym "NATO" stand for?',
 ARRAY['North American Treaty Organization','North Atlantic Treaty Organization','National Allied Tactical Operations','Northern Atlantic Territorial Order'],
 'North Atlantic Treaty Organization', 'Military', 1),
('What color beret do US Army Rangers wear?',
 ARRAY['Green','Red','Tan','Black'],
 'Tan', 'Military', 1),
('Which US military branch uses the motto "Semper Fidelis"?',
 ARRAY['US Army','US Navy','US Marine Corps','US Air Force'],
 'US Marine Corps', 'Military', 1),
('What is the highest rank in the US Army?',
 ARRAY['General of the Army (five-star)','General (four-star)','Lieutenant General','Field Marshal'],
 'General of the Army (five-star)', 'Military', 1),
('Which war resulted in the US acquiring Puerto Rico, Guam, and the Philippines?',
 ARRAY['World War I','The Mexican-American War','The Spanish-American War','The War of 1812'],
 'The Spanish-American War', 'Military', 2),
('What was the name of the US military operation to liberate Kuwait in 1991?',
 ARRAY['Operation Desert Shield','Operation Desert Storm','Operation Desert Fox','Operation Iraqi Freedom'],
 'Operation Desert Storm', 'Military', 2),
('Fort Knox, the US gold bullion depository, is located in which state?',
 ARRAY['Virginia','Ohio','Kentucky','Tennessee'],
 'Kentucky', 'Military', 2),
('The "Huey" helicopter was officially designated by what name during the Vietnam War?',
 ARRAY['UH-1 Iroquois','CH-47 Chinook','OH-6 Cayuse','AH-1 Cobra'],
 'UH-1 Iroquois', 'Military', 2),
('Which battle of the American Civil War resulted in Pickett''s Charge?',
 ARRAY['Battle of Antietam','Battle of Bull Run','Battle of Fredericksburg','Battle of Gettysburg'],
 'Battle of Gettysburg', 'Military', 2),
('In what year was the US Marine Corps founded?',
 ARRAY['1776','1775','1798','1801'],
 '1775', 'Military', 2),
('Which US Navy vessel was the first nuclear-powered aircraft carrier?',
 ARRAY['USS Nimitz','USS Enterprise','USS Kitty Hawk','USS Forrestal'],
 'USS Enterprise', 'Military', 3),
('What US military decoration is awarded for wounds received in combat?',
 ARRAY['Bronze Star','Silver Star','Purple Heart','Distinguished Service Medal'],
 'Purple Heart', 'Military', 3),
('The Doolittle Raid of April 1942 targeted which country?',
 ARRAY['Germany','Italy','Japan','Philippines'],
 'Japan', 'Military', 3),
('Which conflict is known as the "First Modern War" due to the use of railroads, telegraphs, and ironclads?',
 ARRAY['The Mexican-American War','The War of 1812','The American Civil War','The Spanish-American War'],
 'The American Civil War', 'Military', 3),
('What was the name of the covert CIA-led invasion of Cuba in 1961?',
 ARRAY['Operation Mongoose','Bay of Pigs Invasion','Operation JMWAVE','Operation Pluto'],
 'Bay of Pigs Invasion', 'Military', 3),
('Which US military academy is located in Annapolis, Maryland?',
 ARRAY['US Military Academy','US Air Force Academy','US Naval Academy','US Coast Guard Academy'],
 'US Naval Academy', 'Military', 3),
('What was the primary US fighter jet used during the Korean War?',
 ARRAY['F-86 Sabre','F-80 Shooting Star','P-51 Mustang','F-94 Starfire'],
 'F-86 Sabre', 'Military', 4),
('Operation Barbarossa was the German code name for the invasion of the Soviet Union. Which US lend-lease program supplied the Soviets during WWII?',
 ARRAY['Operation Bolero','Lend-Lease Act','Marshall Plan','Atlantic Charter'],
 'Lend-Lease Act', 'Military', 4),
('The USS Arizona memorial is located at which harbor?',
 ARRAY['San Diego Bay','Pearl Harbor','Hampton Roads','Puget Sound'],
 'Pearl Harbor', 'Military', 4),
('Which US general commanded forces at the Battle of New Orleans in 1815?',
 ARRAY['William Henry Harrison','Zachary Taylor','Andrew Jackson','Winfield Scott'],
 'Andrew Jackson', 'Military', 4),
('The US military''s "Bradley" is what type of vehicle?',
 ARRAY['Main battle tank','Infantry fighting vehicle','Self-propelled howitzer','Armored personnel carrier'],
 'Infantry fighting vehicle', 'Military', 4),
('What was the official name of the US military strategy of gradually increasing troop levels in Vietnam?',
 ARRAY['Vietnamization','Escalation Doctrine','Rolling Thunder','Graduated Pressure'],
 'Graduated Pressure', 'Military', 4),
('Which WWII battle was also known as the "Battle of the Bulge"?',
 ARRAY['Battle of Hurtgen Forest','Battle of the Ardennes','Battle of Remagen','Operation Market Garden'],
 'Battle of the Ardennes', 'Military', 4),
('What is the name of the US Air Force''s primary stealth bomber?',
 ARRAY['B-52 Stratofortress','B-1B Lancer','B-2 Spirit','F-117 Nighthawk'],
 'B-2 Spirit', 'Military', 5),
('Which war produced the US military doctrine known as "AirLand Battle"?',
 ARRAY['Vietnam War','Cold War','Gulf War','Korean War'],
 'Cold War', 'Military', 5),
('The Battle of Ia Drang Valley in 1965 was significant as the first major engagement between what two forces?',
 ARRAY['US Marines and Viet Cong','US Army and North Vietnamese Army regulars','US Air Force and North Vietnamese Air Force','US Navy SEALs and Viet Cong'],
 'US Army and North Vietnamese Army regulars', 'Military', 5),
('What US Navy program developed the first ballistic missile submarine in 1959?',
 ARRAY['Project Sea Launch','USS George Washington program','Polaris program','Trident program'],
 'Polaris program', 'Military', 5),
('Which Army division was known as the "Big Red One"?',
 ARRAY['3rd Infantry Division','4th Infantry Division','1st Infantry Division','2nd Infantry Division'],
 '1st Infantry Division', 'Military', 5),
('The USAF''s "Thunderbirds" flight demonstration team flies which aircraft?',
 ARRAY['F-15 Eagle','F-16 Fighting Falcon','F-22 Raptor','T-38 Talon'],
 'F-16 Fighting Falcon', 'Military', 5),
('What was the name of the US operation to rescue American hostages in Iran in 1980?',
 ARRAY['Operation Eagle Claw','Operation Nimble Archer','Operation Credible Sport','Operation Ivory Coast'],
 'Operation Eagle Claw', 'Military', 5),
('Which naval battle of the War of 1812 gave the US control of Lake Erie?',
 ARRAY['Battle of Lake Champlain','Battle of Put-in-Bay','Battle of Lake Ontario','Battle of Queenston Heights'],
 'Battle of Put-in-Bay', 'Military', 6),
('The USMC''s Force Reconnaissance units were the forerunners of which special operations force?',
 ARRAY['USMC Raiders','Marine Special Operations Command','Delta Force','SEAL Team 6'],
 'Marine Special Operations Command', 'Military', 6),
('What was the code name for the US plan to invade Japan in WWII?',
 ARRAY['Operation Downfall','Operation Sea Lion','Operation Coronet','Operation Olympic'],
 'Operation Downfall', 'Military', 6),
('Which US general earned the nickname "Blood and Guts" during WWII?',
 ARRAY['Omar Bradley','Dwight Eisenhower','George Patton','Douglas MacArthur'],
 'George Patton', 'Military', 6),
('The AGM-114 Hellfire missile was originally designed to destroy what type of target?',
 ARRAY['Aircraft','Submarines','Tanks','Bunkers'],
 'Tanks', 'Military', 7),
('Which US Navy admiral was in command at the Battle of Manila Bay in 1898?',
 ARRAY['William Sampson','George Dewey','Winfield Schley','Richmond Hobson'],
 'George Dewey', 'Military', 7),
('What was the primary mission of the US Army''s "Long Range Reconnaissance Patrols" (LRRPs) in Vietnam?',
 ARRAY['Direct assault raids','Gathering intelligence behind enemy lines','Providing fire support','Rescuing POWs'],
 'Gathering intelligence behind enemy lines', 'Military', 7),
('The US military''s MOAB — "Massive Ordnance Air Blast" — was first used in combat in which country?',
 ARRAY['Iraq','Syria','Libya','Afghanistan'],
 'Afghanistan', 'Military', 7),
('Which US Army unit was responsible for training the South Vietnamese Army under the CORDS program?',
 ARRAY['Special Forces A-Teams','101st Airborne Division','1st Cavalry Division','173rd Airborne Brigade'],
 'Special Forces A-Teams', 'Military', 7),
('The F-117 Nighthawk stealth aircraft was first used in combat during which operation?',
 ARRAY['Operation Desert Storm','Operation Just Cause','Operation Urgent Fury','Operation El Dorado Canyon'],
 'Operation Just Cause', 'Military', 7),
('Which general commanded the US Eighth Army during the Inchon-Seoul campaign of the Korean War?',
 ARRAY['Matthew Ridgway','James Van Fleet','Walton Walker','Mark Clark'],
 'Walton Walker', 'Military', 8),
('What was the name of the WWII-era US program that trained African American pilots at Tuskegee Institute?',
 ARRAY['Project Equality','Tuskegee Airmen Program','Negro Pilot Training Program','Military Aviation Project'],
 'Tuskegee Airmen Program', 'Military', 8),
('The US military''s Joint Direct Attack Munition (JDAM) converts unguided bombs into precision weapons using what guidance system?',
 ARRAY['Laser guidance','Infrared guidance','GPS guidance','Radar guidance'],
 'GPS guidance', 'Military', 8),
('Which battle of the Philippine-American War saw US forces under General Frederick Funston capture Emilio Aguinaldo in 1901?',
 ARRAY['Battle of Manila','Battle of Palanan','Battle of Tirad Pass','Battle of Macabebe'],
 'Battle of Palanan', 'Military', 8),
('The USAF''s 509th Bomb Wing, based at Whiteman AFB, operates which aircraft?',
 ARRAY['B-52 Stratofortress','B-1B Lancer','B-2 Spirit','F-22 Raptor'],
 'B-2 Spirit', 'Military', 8),
('Which US Navy admiral commanded the Pacific Fleet at the time of the attack on Pearl Harbor?',
 ARRAY['Chester Nimitz','Ernest King','William Halsey','Husband Kimmel'],
 'Husband Kimmel', 'Military', 9),
('The US Army''s "Yellow Ribbon Reintegration Program" was established to assist which group?',
 ARRAY['Veterans with PTSD','Reserve component soldiers and their families after deployment','Wounded warriors in rehabilitation','Soldiers transitioning to civilian employment'],
 'Reserve component soldiers and their families after deployment', 'Military', 9),
('What classified program resulted in the development of the U-2 spy plane at the "Skunk Works" facility?',
 ARRAY['Project Oxcart','Project Aquatone','Project Rainbow','Project Genetrix'],
 'Project Aquatone', 'Military', 9),
('Which US Army general developed the "Active Defense" doctrine that later evolved into AirLand Battle?',
 ARRAY['William DePuy','Donn Starry','John Galvin','Edward Meyer'],
 'William DePuy', 'Military', 9),
('The military concept of "Effects-Based Operations" was first formally applied during which US-led campaign?',
 ARRAY['Operation Enduring Freedom','Operation Iraqi Freedom','Operation Desert Storm','Operation Allied Force'],
 'Operation Desert Storm', 'Military', 9);

-- National Parks (53 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which national park is home to the famous geyser known as "Old Faithful"?',
 ARRAY['Grand Teton','Yellowstone','Crater Lake','Lassen Volcanic'],
 'Yellowstone', 'National Parks', 1),
('In which state is the Grand Canyon National Park located?',
 ARRAY['Utah','Nevada','New Mexico','Arizona'],
 'Arizona', 'National Parks', 1),
('Which national park is the largest in the United States by area?',
 ARRAY['Denali','Glacier Bay','Wrangell-St. Elias','Katmai'],
 'Wrangell-St. Elias', 'National Parks', 1),
('Yosemite National Park is located in which state?',
 ARRAY['Oregon','Washington','California','Nevada'],
 'California', 'National Parks', 1),
('Which national park is famous for its large arch rock formations in Utah?',
 ARRAY['Zion','Canyonlands','Bryce Canyon','Arches'],
 'Arches', 'National Parks', 1),
('Mount Rushmore features the faces of how many US presidents?',
 ARRAY['Three','Four','Five','Six'],
 'Four', 'National Parks', 1),
('Everglades National Park is located at the southern tip of which state?',
 ARRAY['Georgia','Louisiana','Florida','Alabama'],
 'Florida', 'National Parks', 2),
('Which national park contains the deepest lake in the United States?',
 ARRAY['Lake Mead','Crater Lake','Lake Tahoe','Glacier National Park'],
 'Crater Lake', 'National Parks', 2),
('The Appalachian National Scenic Trail begins at Springer Mountain in Georgia and ends in which state?',
 ARRAY['New Hampshire','Vermont','New York','Maine'],
 'Maine', 'National Parks', 2),
('Which national park in Alaska is known as the "Valley of Ten Thousand Smokes"?',
 ARRAY['Wrangell-St. Elias','Denali','Katmai','Lake Clark'],
 'Katmai', 'National Parks', 2),
('Rocky Mountain National Park is located in which state?',
 ARRAY['Wyoming','Montana','Colorado','Idaho'],
 'Colorado', 'National Parks', 2),
('Which national park contains the highest point in North America?',
 ARRAY['Glacier Bay','Wrangell-St. Elias','Denali','Kenai Fjords'],
 'Denali', 'National Parks', 2),
('Shenandoah National Park is located in which state?',
 ARRAY['West Virginia','North Carolina','Maryland','Virginia'],
 'Virginia', 'National Parks', 3),
('The Painted Desert is found within which national park?',
 ARRAY['Grand Canyon','Petrified Forest','Canyonlands','Capitol Reef'],
 'Petrified Forest', 'National Parks', 3),
('Which national park is known for its "hoodoo" rock formations?',
 ARRAY['Zion','Bryce Canyon','Capitol Reef','Canyonlands'],
 'Bryce Canyon', 'National Parks', 3),
('Death Valley National Park holds the record for the highest reliably recorded air temperature on Earth. What is that temperature?',
 ARRAY['126°F','130°F','134°F','138°F'],
 '134°F', 'National Parks', 3),
('Which national park straddles the border between the US and Canada?',
 ARRAY['North Cascades','Olympic','Glacier','Waterton-Glacier International Peace Park'],
 'Waterton-Glacier International Peace Park', 'National Parks', 3),
('Great Smoky Mountains National Park straddles the border of Tennessee and which other state?',
 ARRAY['Virginia','Georgia','South Carolina','North Carolina'],
 'North Carolina', 'National Parks', 4),
('Which national park contains the Narrows, a slot canyon carved by the Virgin River?',
 ARRAY['Capitol Reef','Bryce Canyon','Zion','Canyonlands'],
 'Zion', 'National Parks', 4),
('Mammoth Cave National Park, the world''s longest known cave system, is located in which state?',
 ARRAY['Tennessee','Missouri','Virginia','Kentucky'],
 'Kentucky', 'National Parks', 4),
('Which national park is located entirely on islands off the coast of California?',
 ARRAY['Point Reyes','Channel Islands','Golden Gate','Redwood'],
 'Channel Islands', 'National Parks', 4),
('What is the name of the iconic road that runs through Glacier National Park and crosses the Continental Divide?',
 ARRAY['Trail Ridge Road','Blue Ridge Parkway','Going-to-the-Sun Road','Beartooth Highway'],
 'Going-to-the-Sun Road', 'National Parks', 4),
('Which national park contains Mesa Verde, famous for its Ancestral Puebloan cliff dwellings?',
 ARRAY['Canyonlands','Grand Canyon','Mesa Verde','Capitol Reef'],
 'Mesa Verde', 'National Parks', 4),
('Isle Royale National Park is located in which Great Lake?',
 ARRAY['Lake Michigan','Lake Huron','Lake Erie','Lake Superior'],
 'Lake Superior', 'National Parks', 4),
('Which national park is known for protecting the largest old-growth temperate rainforest in the US?',
 ARRAY['Redwood','Olympic','North Cascades','Tongass'],
 'Olympic', 'National Parks', 5),
('The "Tall Grass Prairie" ecosystem is preserved in which national park in Kansas?',
 ARRAY['Flint Hills','Tallgrass Prairie','Great Plains','Konza Prairie'],
 'Tallgrass Prairie', 'National Parks', 5),
('Congaree National Park in South Carolina protects the largest intact expanse of what kind of forest?',
 ARRAY['Old-growth longleaf pine','Old-growth bottomland hardwood','Old-growth cypress swamp','Old-growth beech-maple'],
 'Old-growth bottomland hardwood', 'National Parks', 5),
('Which national park in the Virgin Islands is the only one located in a tropical environment in the Caribbean?',
 ARRAY['Buck Island','Virgin Islands','Salt River','Christiansted'],
 'Virgin Islands', 'National Parks', 5),
('Big Bend National Park in Texas borders which country?',
 ARRAY['Guatemala','Cuba','Mexico','Canada'],
 'Mexico', 'National Parks', 5),
('White Sands National Park in New Mexico features the world''s largest gypsum dunefield. In which mountain range is it located?',
 ARRAY['Sacramento Mountains','San Andres Mountains','Guadalupe Mountains','Organ Mountains'],
 'San Andres Mountains', 'National Parks', 5),
('Which national park contains Carlsbad Caverns, home to one of the largest bat colonies in North America?',
 ARRAY['Guadalupe Mountains','Carlsbad Caverns','White Sands','Big Bend'],
 'Carlsbad Caverns', 'National Parks', 5),
('New River Gorge became a national park in which year?',
 ARRAY['2015','2018','2020','2022'],
 '2020', 'National Parks', 6),
('The Haleakala volcano, a dormant shield volcano, is found in which national park?',
 ARRAY['Hawaii Volcanoes','Haleakala','Maui Islands','Pacific Rim'],
 'Haleakala', 'National Parks', 6),
('Pinnacles National Park in California was formed by what geological process?',
 ARRAY['Glacial carving','Volcanic activity along the San Andreas Fault','Wind erosion','Meteor impact'],
 'Volcanic activity along the San Andreas Fault', 'National Parks', 6),
('Which national park in Alaska lies entirely north of the Arctic Circle?',
 ARRAY['Gates of the Arctic','Kobuk Valley','Noatak','Bering Land Bridge'],
 'Kobuk Valley', 'National Parks', 6),
('Theodore Roosevelt National Park is located in the Badlands of which state?',
 ARRAY['South Dakota','Wyoming','Montana','North Dakota'],
 'North Dakota', 'National Parks', 6),
('The "Wave" formation, a famous sandstone rock formation, is located in which national monument near the Arizona-Utah border?',
 ARRAY['Monument Valley','Vermilion Cliffs','Grand Staircase-Escalante','Kanab Canyon'],
 'Vermilion Cliffs', 'National Parks', 6),
('Biscayne National Park in Florida is unique because approximately what percentage of the park is underwater?',
 ARRAY['65%','75%','85%','95%'],
 '95%', 'National Parks', 7),
('Which national park was established to protect the last significant breeding ground of the Florida panther?',
 ARRAY['Big Cypress','Everglades','Biscayne','Dry Tortugas'],
 'Big Cypress', 'National Parks', 7),
('Glacier Bay National Park in Alaska is known for its rapid glacial retreat. Approximately how many glaciers does it contain?',
 ARRAY['Over 100','Over 200','Over 1000','Over 500'],
 'Over 1000', 'National Parks', 7),
('Which national park contains the Fiery Furnace, a maze of narrow sandstone canyons?',
 ARRAY['Canyonlands','Capitol Reef','Arches','Zion'],
 'Arches', 'National Parks', 7),
('The "Maze" district of Canyonlands National Park is considered one of the most remote areas in the lower 48. Which river forms its western boundary?',
 ARRAY['San Juan River','Green River','Escalante River','Dirty Devil River'],
 'Green River', 'National Parks', 7),
('Lassen Volcanic National Park in California contains all four types of volcanoes. Which type is Lassen Peak itself?',
 ARRAY['Shield volcano','Cinder cone','Composite volcano (stratovolcano)','Plug dome volcano'],
 'Plug dome volcano', 'National Parks', 7),
('Great Basin National Park in Nevada is home to some of the oldest living organisms on Earth. What are they?',
 ARRAY['Saguaro cacti','Bristlecone pines','Giant sequoias','Whitebark pines'],
 'Bristlecone pines', 'National Parks', 8),
('Which national park in Alaska protects more than 9 million acres, making it one of the largest protected areas in the world?',
 ARRAY['Katmai','Denali','Gates of the Arctic','Wrangell-St. Elias'],
 'Wrangell-St. Elias', 'National Parks', 8),
('The "Narrows" hike in Zion National Park requires hikers to wade through which river?',
 ARRAY['Colorado River','Zion River','Virgin River','Paria River'],
 'Virgin River', 'National Parks', 8),
('Which national park contains the highest paved road in the United States, reaching over 14,000 feet?',
 ARRAY['Rocky Mountain','Great Sand Dunes','Mesa Verde','Black Canyon of the Gunnison'],
 'Rocky Mountain', 'National Parks', 8),
('Dry Tortugas National Park is accessible only by boat or seaplane and contains Fort Jefferson, the largest 19th-century coastal fort in the US. In which body of water does it lie?',
 ARRAY['Gulf of Mexico','Atlantic Ocean','Florida Straits','Caribbean Sea'],
 'Gulf of Mexico', 'National Parks', 8),
('The Guadalupe Mountains National Park in Texas contains Guadalupe Peak, the highest point in the state. What is its elevation?',
 ARRAY['7,825 feet','8,251 feet','8,749 feet','9,131 feet'],
 '8,749 feet', 'National Parks', 9),
('Which national park was the site of a major volcanic eruption in 1980 that reduced its summit elevation by 1,314 feet?',
 ARRAY['Lassen Volcanic','Mount Rainier','North Cascades','No eruption occurred in a current national park'],
 'No eruption occurred in a current national park', 'National Parks', 9),
('The "Sailing Stones" phenomenon, where rocks appear to move on their own across a dry lake bed, occurs in which national park?',
 ARRAY['Joshua Tree','Mojave','Death Valley','Great Basin'],
 'Death Valley', 'National Parks', 9),
('Craters of the Moon National Monument and Preserve in Idaho is composed primarily of what type of volcanic rock?',
 ARRAY['Granite','Rhyolite','Basalt','Obsidian'],
 'Basalt', 'National Parks', 9),
('Which national park protects the Hoh Rain Forest, one of the largest temperate rainforests in the US, receiving up to 14 feet of rain annually?',
 ARRAY['North Cascades','Redwood','Tongass','Olympic'],
 'Olympic', 'National Parks', 9);

-- US History (61 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which amendment to the US Constitution abolished the poll tax in federal elections?',
 ARRAY['21st Amendment','22nd Amendment','23rd Amendment','24th Amendment'],
 '24th Amendment', 'US History', 1),
('What was the name of the first successful English colony in North America, founded in 1607?',
 ARRAY['Plymouth','Roanoke','Jamestown','Salem'],
 'Jamestown', 'US History', 1),
('What document, issued in 1863, declared enslaved people in Confederate states to be free?',
 ARRAY['Emancipation Proclamation','13th Amendment','Reconstruction Act','Freedmen''s Bureau Act'],
 'Emancipation Proclamation', 'US History', 1),
('Who delivered the "I Have a Dream" speech during the March on Washington in 1963?',
 ARRAY['Malcolm X','Thurgood Marshall','Martin Luther King Jr.','John Lewis'],
 'Martin Luther King Jr.', 'US History', 1),
('What event on December 7, 1941, led the United States to enter World War II?',
 ARRAY['Sinking of the Lusitania','Attack on Pearl Harbor','Battle of Midway','D-Day invasion'],
 'Attack on Pearl Harbor', 'US History', 1),
('Which amendment to the US Constitution granted women the right to vote?',
 ARRAY['15th Amendment','17th Amendment','18th Amendment','19th Amendment'],
 '19th Amendment', 'US History', 2),
('What was the name of the US space program that first landed humans on the Moon?',
 ARRAY['Gemini','Mercury','Apollo','Skylab'],
 'Apollo', 'US History', 2),
('Which president issued Executive Order 9066, authorizing Japanese American internment during World War II?',
 ARRAY['Harry Truman','Dwight Eisenhower','Franklin D. Roosevelt','Herbert Hoover'],
 'Franklin D. Roosevelt', 'US History', 2),
('What was the main purpose of the Marshall Plan, enacted in 1948?',
 ARRAY['Rebuild war-torn European nations','Contain Soviet nuclear expansion','Fund the Korean War','Create the United Nations'],
 'Rebuild war-torn European nations', 'US History', 2),
('Which senator led anti-Communist hearings in the early 1950s that became known as McCarthyism?',
 ARRAY['Strom Thurmond','Joseph McCarthy','Barry Goldwater','Hubert Humphrey'],
 'Joseph McCarthy', 'US History', 2),
('What 1944 legislation provided veterans with education, housing, and employment benefits?',
 ARRAY['Social Security Act','Lend-Lease Act','GI Bill','National Security Act'],
 'GI Bill', 'US History', 2),
('In what year did Neil Armstrong become the first person to walk on the Moon?',
 ARRAY['1967','1968','1969','1970'],
 '1969', 'US History', 2),
('Which African American leader co-founded the NAACP in 1909?',
 ARRAY['Booker T. Washington','W.E.B. Du Bois','Marcus Garvey','Frederick Douglass'],
 'W.E.B. Du Bois', 'US History', 3),
('What was the purpose of the Lend-Lease Act of 1941?',
 ARRAY['Supply Allied nations with war materials','Draft American soldiers','Fund the atomic bomb','Create military alliances'],
 'Supply Allied nations with war materials', 'US History', 3),
('Which 1954 Supreme Court case declared racial segregation in public schools unconstitutional?',
 ARRAY['Plessy v Ferguson','Marbury v Madison','Brown v Board of Education','Korematsu v United States'],
 'Brown v Board of Education', 'US History', 3),
('What was the name of the 1794 rebellion of Pennsylvania farmers against a federal whiskey tax?',
 ARRAY['Shays'' Rebellion','Whiskey Rebellion','Fries'' Rebellion','Nullification Crisis'],
 'Whiskey Rebellion', 'US History', 3),
('Which abolitionist led a failed raid on the federal arsenal at Harpers Ferry in 1859?',
 ARRAY['Nat Turner','Denmark Vesey','John Brown','Frederick Douglass'],
 'John Brown', 'US History', 3),
('Who was the first African American to serve as US Secretary of State?',
 ARRAY['Colin Powell','Condoleezza Rice','Eric Holder','Barack Obama'],
 'Colin Powell', 'US History', 3),
('What was the name given to the forced relocation of the Cherokee Nation to Oklahoma in 1838?',
 ARRAY['Indian Removal Act','Trail of Tears','Dawes Severalty Act','Long Walk'],
 'Trail of Tears', 'US History', 3),
('Which president oversaw the Louisiana Purchase in 1803?',
 ARRAY['John Adams','James Madison','Thomas Jefferson','James Monroe'],
 'Thomas Jefferson', 'US History', 3),
('What was the significance of the Battle of Yorktown in 1781?',
 ARRAY['It ended the French and Indian War','It was the last major battle of the American Revolution','It began the War of 1812','It ended the Civil War'],
 'It was the last major battle of the American Revolution', 'US History', 4),
('Which 1820 agreement admitted Missouri as a slave state and Maine as a free state?',
 ARRAY['Kansas-Nebraska Act','Compromise of 1850','Missouri Compromise','Crittenden Compromise'],
 'Missouri Compromise', 'US History', 4),
('Who was president during the Cuban Missile Crisis of 1962?',
 ARRAY['Dwight Eisenhower','Lyndon B. Johnson','Richard Nixon','John F. Kennedy'],
 'John F. Kennedy', 'US History', 4),
('What event in 1955 sparked the Montgomery Bus Boycott?',
 ARRAY['Rosa Parks refused to give up her seat','Martin Luther King Jr. was arrested','A bus driver was attacked','The Supreme Court ruled on bus segregation'],
 'Rosa Parks refused to give up her seat', 'US History', 4),
('Which amendment established Prohibition, banning the manufacture and sale of alcohol?',
 ARRAY['16th Amendment','17th Amendment','18th Amendment','19th Amendment'],
 '18th Amendment', 'US History', 4),
('Which president sent federal troops to enforce desegregation at Little Rock Central High School in 1957?',
 ARRAY['Harry Truman','Dwight Eisenhower','John F. Kennedy','Lyndon B. Johnson'],
 'Dwight Eisenhower', 'US History', 4),
('What name was given to the secret US government program that recruited Nazi scientists after World War II?',
 ARRAY['Operation Paperclip','Operation Overlord','Operation Just Cause','Project Blue Book'],
 'Operation Paperclip', 'US History', 4),
('Which legislative act of 1887 broke up Native American tribal lands into individual allotments?',
 ARRAY['Indian Removal Act','Homestead Act','Dawes Act','Indian Reorganization Act'],
 'Dawes Act', 'US History', 4),
('What was the name of the 1846-1848 war fought between the United States and Mexico?',
 ARRAY['Spanish-American War','Texas Revolution','Mexican-American War','Gadsden War'],
 'Mexican-American War', 'US History', 4),
('Which US president ordered the desegregation of the US military by executive order in 1948?',
 ARRAY['Franklin D. Roosevelt','Harry Truman','Dwight Eisenhower','John F. Kennedy'],
 'Harry Truman', 'US History', 5),
('What was the name of the controversial 1857 Supreme Court case ruling that African Americans were not citizens?',
 ARRAY['Plessy v Ferguson','Marbury v Madison','Dred Scott v Sandford','Scott v Emerson'],
 'Dred Scott v Sandford', 'US History', 5),
('Which president initiated the New Deal in response to the Great Depression?',
 ARRAY['Herbert Hoover','Franklin D. Roosevelt','Harry Truman','Woodrow Wilson'],
 'Franklin D. Roosevelt', 'US History', 5),
('What agreement ended the Korean War in 1953?',
 ARRAY['Treaty of Panmunjom','Korean Armistice Agreement','Treaty of Seoul','Inchon Accord'],
 'Korean Armistice Agreement', 'US History', 5),
('Which organization, founded by Marcus Garvey in 1914, promoted Black nationalism and Pan-Africanism?',
 ARRAY['NAACP','Universal Negro Improvement Association','Black Panther Party','Nation of Islam'],
 'Universal Negro Improvement Association', 'US History', 5),
('What was the Homestead Act of 1862?',
 ARRAY['A law granting 160 acres to settlers who improved the land','A law protecting Native American land rights','A law creating national parks','A law regulating railroad construction'],
 'A law granting 160 acres to settlers who improved the land', 'US History', 5),
('Which 1973 agreement formally ended direct US military involvement in the Vietnam War?',
 ARRAY['Geneva Accords','Paris Peace Accords','Saigon Treaty','Ho Chi Minh Accord'],
 'Paris Peace Accords', 'US History', 5),
('What scandal led to President Nixon''s resignation in 1974?',
 ARRAY['Iran-Contra Affair','Watergate','Teapot Dome','Pentagon Papers'],
 'Watergate', 'US History', 5),
('Which Supreme Court case established the principle of judicial review in 1803?',
 ARRAY['McCulloch v Maryland','Marbury v Madison','Gibbons v Ogden','Fletcher v Peck'],
 'Marbury v Madison', 'US History', 6),
('What was the purpose of the War Powers Resolution of 1973?',
 ARRAY['Limit the president''s ability to commit troops without congressional approval','Increase military spending','Create the Department of Defense','Establish the draft'],
 'Limit the president''s ability to commit troops without congressional approval', 'US History', 6),
('Who was the first woman to serve as a US Cabinet member?',
 ARRAY['Frances Perkins','Madeleine Albright','Hillary Clinton','Condoleezza Rice'],
 'Frances Perkins', 'US History', 6),
('What was the primary purpose of the Underground Railroad before the Civil War?',
 ARRAY['Transport troops to battle','Help enslaved people escape to freedom','Ship goods north to south','Connect telegraph lines'],
 'Help enslaved people escape to freedom', 'US History', 6),
('Which 1898 treaty ended the Spanish-American War and ceded Puerto Rico, Guam, and the Philippines to the US?',
 ARRAY['Treaty of Paris','Treaty of Versailles','Treaty of Guadalupe Hidalgo','Treaty of San Francisco'],
 'Treaty of Paris', 'US History', 6),
('What was the Zimmermann Telegram of 1917?',
 ARRAY['A German proposal for a military alliance with Mexico against the US','A British request for US troops','A secret peace offer from Germany to France','A warning to US ships about submarines'],
 'A German proposal for a military alliance with Mexico against the US', 'US History', 7),
('Which act of 1798 made it illegal to criticize the US government and was seen as an attack on free speech?',
 ARRAY['Whiskey Act','Alien and Sedition Acts','Sedition Act of 1918','Logan Act'],
 'Alien and Sedition Acts', 'US History', 7),
('What was the XYZ Affair of 1797-1798?',
 ARRAY['A French demand for bribes before diplomatic negotiations','A British seizure of American sailors','A Spanish treaty dispute over Florida','A secret German espionage operation'],
 'A French demand for bribes before diplomatic negotiations', 'US History', 7),
('Which battle of the Revolutionary War is considered the turning point that brought France into the conflict?',
 ARRAY['Battle of Bunker Hill','Battle of Trenton','Battle of Saratoga','Battle of Yorktown'],
 'Battle of Saratoga', 'US History', 7),
('What did the Taft-Hartley Act of 1947 do?',
 ARRAY['Expanded union rights','Restricted certain union activities','Created the minimum wage','Established workplace safety laws'],
 'Restricted certain union activities', 'US History', 7),
('Which president signed the National Security Act of 1947, creating the CIA and the modern military structure?',
 ARRAY['Franklin D. Roosevelt','Harry Truman','Dwight Eisenhower','John F. Kennedy'],
 'Harry Truman', 'US History', 7),
('What was the Pullman Strike of 1894?',
 ARRAY['A nationwide railroad workers'' strike that President Cleveland broke with federal troops','A coal miners'' strike in Pennsylvania','A steel workers'' strike in Pittsburgh','A protest against railroad monopolies'],
 'A nationwide railroad workers'' strike that President Cleveland broke with federal troops', 'US History', 8),
('Which federal law of 1890 sought to break up monopolies and trusts restraining trade?',
 ARRAY['Interstate Commerce Act','Clayton Antitrust Act','Sherman Antitrust Act','Federal Trade Commission Act'],
 'Sherman Antitrust Act', 'US History', 8),
('What was the Compromise of 1877?',
 ARRAY['An agreement ending Reconstruction in exchange for the presidency','A deal settling territorial disputes in the West','A treaty ending the Mexican-American War','An agreement on railroad subsidies'],
 'An agreement ending Reconstruction in exchange for the presidency', 'US History', 8),
('Who was the primary author of the Federalist Papers, contributing over half of the essays?',
 ARRAY['James Madison','Alexander Hamilton','John Jay','Thomas Jefferson'],
 'Alexander Hamilton', 'US History', 8),
('What was the Palmer Raids of 1919-1920?',
 ARRAY['Mass arrests of suspected anarchists and Communists ordered by Attorney General Mitchell Palmer','Military raids on German-American communities','Police crackdowns on Prohibition violators','Government seizure of striking workers'' property'],
 'Mass arrests of suspected anarchists and Communists ordered by Attorney General Mitchell Palmer', 'US History', 8),
('Which 1965 legislation eliminated national-origin immigration quotas established in the 1920s?',
 ARRAY['Immigration Reform Act','Hart-Celler Act','Nationality Act','Refugee Act'],
 'Hart-Celler Act', 'US History', 8),
('What was the Three-Fifths Compromise of the Constitutional Convention?',
 ARRAY['Enslaved people counted as three-fifths of a person for representation and taxation','Three-fifths of states needed to ratify laws','Three-fifths of Congress could override a veto','Three-fifths of territory could petition for statehood'],
 'Enslaved people counted as three-fifths of a person for representation and taxation', 'US History', 9),
('Which legal doctrine, established in Ware v Hylton (1796), affirmed that federal law supersedes state law?',
 ARRAY['Judicial review','Supremacy of federal treaties over state laws','Commerce Clause','Necessary and Proper Clause'],
 'Supremacy of federal treaties over state laws', 'US History', 9),
('What was the significance of the Enrollment Act of 1863?',
 ARRAY['It authorized the first military draft in US history during the Civil War','It freed enslaved people in the border states','It expanded the Union Army''s officer corps','It created the Bureau of Colored Troops'],
 'It authorized the first military draft in US history during the Civil War', 'US History', 9),
('Which 1919 Supreme Court case established the "clear and present danger" test for limiting free speech?',
 ARRAY['Schenck v United States','Gitlow v New York','Brandenburg v Ohio','Abrams v United States'],
 'Schenck v United States', 'US History', 9),
('What was the significance of the INF Treaty of 1987?',
 ARRAY['It eliminated an entire class of nuclear weapons between the US and USSR','It ended the Vietnam War','It established arms reduction in Europe','It created nuclear inspection protocols'],
 'It eliminated an entire class of nuclear weapons between the US and USSR', 'US History', 9),
('Which president authorized Operation Just Cause, the 1989 US invasion of Panama?',
 ARRAY['Ronald Reagan','George H.W. Bush','Bill Clinton','Jimmy Carter'],
 'George H.W. Bush', 'US History', 9),
('What was the primary goal of the American Expeditionary Forces in World War I?',
 ARRAY['Defend the continental United States','Fight alongside Allied forces on the Western Front','Occupy German territories','Block German naval trade'],
 'Fight alongside Allied forces on the Western Front', 'US History', 9);

