-- Migration 015: Expand question bank (batch 6)
-- 439 questions across 8 categories

-- Civics (54 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('How many articles does the U.S. Constitution contain?',
 ARRAY['5','7','9','12'],
 '7', 'Civics', 1),
('What is the term for the first ten amendments to the U.S. Constitution?',
 ARRAY['The Magna Carta','The Bill of Rights','The Articles of Confederation','The Declaration of Rights'],
 'The Bill of Rights', 'Civics', 1),
('Which branch of the U.S. government is responsible for enforcing the law?',
 ARRAY['Legislative','Judicial','Executive','Administrative'],
 'Executive', 'Civics', 1),
('How many U.S. senators does each state send to Congress?',
 ARRAY['1','2','3','4'],
 '2', 'Civics', 1),
('Which document originally established the structure of the U.S. government before the Constitution?',
 ARRAY['The Declaration of Independence','The Federalist Papers','The Articles of Confederation','The Magna Carta'],
 'The Articles of Confederation', 'Civics', 1),
('What is the official title of the head of the U.S. Supreme Court?',
 ARRAY['Chief Judge','Supreme Justice','Chief Justice','Senior Associate Justice'],
 'Chief Justice', 'Civics', 2),
('Which amendment grants citizenship to all persons born on U.S. soil?',
 ARRAY['13th Amendment','14th Amendment','15th Amendment','16th Amendment'],
 '14th Amendment', 'Civics', 2),
('What term describes the power of the Supreme Court to review and overturn laws as unconstitutional?',
 ARRAY['Legislative review','Judicial review','Executive review','Constitutional oversight'],
 'Judicial review', 'Civics', 2),
('How often does the U.S. Census Bureau conduct a national census?',
 ARRAY['Every 5 years','Every 8 years','Every 10 years','Every 12 years'],
 'Every 10 years', 'Civics', 2),
('What is the name of the constitutional provision that gives Congress broad authority to pass laws "necessary and proper" to execute its powers?',
 ARRAY['Commerce Clause','Supremacy Clause','Elastic Clause','Establishment Clause'],
 'Elastic Clause', 'Civics', 2),
('Which constitutional amendment grants the President a two-term limit?',
 ARRAY['20th Amendment','21st Amendment','22nd Amendment','25th Amendment'],
 '22nd Amendment', 'Civics', 2),
('What is the total number of Electoral College votes needed to win the presidency?',
 ARRAY['250','270','290','300'],
 '270', 'Civics', 2),
('Which clause of the Constitution requires states to honor the legal decisions of other states?',
 ARRAY['Commerce Clause','Supremacy Clause','Full Faith and Credit Clause','Privileges and Immunities Clause'],
 'Full Faith and Credit Clause', 'Civics', 3),
('How long is a U.S. Senator''s term in office?',
 ARRAY['2 years','4 years','6 years','8 years'],
 '6 years', 'Civics', 3),
('What is the name of the process by which a foreign-born person becomes a U.S. citizen?',
 ARRAY['Naturalization','Immigration','Assimilation','Citizenship'],
 'Naturalization', 'Civics', 3),
('What term describes a president''s refusal to spend money that has been appropriated by Congress?',
 ARRAY['Pocket veto','Sequestration','Impoundment','Filibuster'],
 'Impoundment', 'Civics', 4),
('Which constitutional amendment establishes due process requirements for the federal government?',
 ARRAY['4th Amendment','5th Amendment','6th Amendment','7th Amendment'],
 '5th Amendment', 'Civics', 4),
('What is the term for a writ that requires a government official to explain why a person is being held in custody?',
 ARRAY['Writ of mandamus','Habeas corpus','Writ of certiorari','Injunction'],
 'Habeas corpus', 'Civics', 4),
('Which constitutional clause gives the federal government supremacy over state laws?',
 ARRAY['Commerce Clause','Necessary and Proper Clause','Supremacy Clause','Preemption Clause'],
 'Supremacy Clause', 'Civics', 4),
('What percentage of Congress must vote to override a presidential veto?',
 ARRAY['50%','60%','Two-thirds','Three-quarters'],
 'Two-thirds', 'Civics', 4),
('Which amendment to the Constitution prohibits excessive bail and fines?',
 ARRAY['6th Amendment','7th Amendment','8th Amendment','9th Amendment'],
 '8th Amendment', 'Civics', 4),
('What is the official term for the process by which the Supreme Court agrees to hear an appeal?',
 ARRAY['Judicial appeal','Writ of certiorari','En banc review','Appellate review'],
 'Writ of certiorari', 'Civics', 4),
('Which provision of the Constitution allows Congress to regulate trade between states?',
 ARRAY['Supremacy Clause','Commerce Clause','Privileges Clause','Contract Clause'],
 'Commerce Clause', 'Civics', 4),
('What is the term for the number of members required to be present before Congress can conduct business?',
 ARRAY['Majority','Quorum','Plurality','Caucus'],
 'Quorum', 'Civics', 5),
('Which constitutional amendment prohibits the government from taking private property without just compensation?',
 ARRAY['4th Amendment','5th Amendment','6th Amendment','7th Amendment'],
 '5th Amendment', 'Civics', 5),
('What is the name of the process by which Congress can remove a federal judge from office?',
 ARRAY['Recall','Removal','Impeachment','Censure'],
 'Impeachment', 'Civics', 5),
('Which Supreme Court case established that the exclusionary rule applies to state courts as well as federal courts?',
 ARRAY['Miranda v. Arizona','Mapp v. Ohio','Katz v. United States','Terry v. Ohio'],
 'Mapp v. Ohio', 'Civics', 5),
('What is the term for the constitutional provision that allows the president to appoint officials during a congressional recess?',
 ARRAY['Recess appointment','Emergency appointment','Interim appointment','Temporary appointment'],
 'Recess appointment', 'Civics', 5),
('Which amendment to the Constitution addresses presidential succession in the event of death or incapacity?',
 ARRAY['22nd Amendment','23rd Amendment','24th Amendment','25th Amendment'],
 '25th Amendment', 'Civics', 5),
('What is the name of the constitutional provision that prevents Congress from passing laws punishing specific individuals without a trial?',
 ARRAY['Ex post facto clause','Bill of attainder prohibition','Due process clause','Equal protection clause'],
 'Bill of attainder prohibition', 'Civics', 5),
('Which Supreme Court case held that the government cannot impose racial quotas in university admissions?',
 ARRAY['Regents of University of California v. Bakke','Grutter v. Bollinger','Fisher v. University of Texas','Parents Involved v. Seattle'],
 'Regents of University of California v. Bakke', 'Civics', 6),
('What constitutional provision prohibits the federal government from criminalizing an act that was legal when it was committed?',
 ARRAY['Bill of attainder clause','Ex post facto clause','Due process clause','Equal protection clause'],
 'Ex post facto clause', 'Civics', 6),
('Which amendment grants the District of Columbia electoral votes in presidential elections?',
 ARRAY['21st Amendment','22nd Amendment','23rd Amendment','24th Amendment'],
 '23rd Amendment', 'Civics', 6),
('What is the term for the principle that the government must follow established legal procedures before depriving someone of life, liberty, or property?',
 ARRAY['Substantive due process','Equal protection','Procedural due process','Selective incorporation'],
 'Procedural due process', 'Civics', 6),
('Which constitutional clause prevents the states from impairing contracts that have already been made?',
 ARRAY['Takings Clause','Contracts Clause','Commerce Clause','Obligation Clause'],
 'Contracts Clause', 'Civics', 6),
('What is the term for the doctrine that certain fundamental rights are incorporated into the 14th Amendment and apply to states?',
 ARRAY['Selective incorporation','Total incorporation','Substantive due process','Judicial federalism'],
 'Selective incorporation', 'Civics', 6),
('Which Supreme Court case established that school-sponsored prayer is unconstitutional?',
 ARRAY['Lee v. Weisman','Engel v. Vitale','Abington School District v. Schempp','Wallace v. Jaffree'],
 'Engel v. Vitale', 'Civics', 7),
('What is the legal term for the requirement that a grand jury issue a formal accusation before a federal criminal trial?',
 ARRAY['Information','Indictment','Arraignment','Charge'],
 'Indictment', 'Civics', 7),
('Which constitutional amendment requires the government to compensate landowners when it takes private property for public use?',
 ARRAY['4th Amendment','5th Amendment','6th Amendment','8th Amendment'],
 '5th Amendment', 'Civics', 7),
('What is the name of the constitutional requirement that Congress declare war before the president can commit troops to combat?',
 ARRAY['Commander-in-chief clause','War Powers Clause','Declare War Clause','Military Authorization Clause'],
 'Declare War Clause', 'Civics', 7),
('Which Supreme Court ruling in 2010 held that corporations have the same free speech rights as individuals in campaign finance?',
 ARRAY['McCutcheon v. FEC','Buckley v. Valeo','Citizens United v. FEC','First National Bank v. Bellotti'],
 'Citizens United v. FEC', 'Civics', 7),
('What term refers to the constitutional guarantee that courts in one state must recognize judicial decisions from courts in another state?',
 ARRAY['Full Faith and Credit','Comity','Horizontal federalism','Interstate recognition'],
 'Full Faith and Credit', 'Civics', 7),
('Which Supreme Court case first established that the Bill of Rights protects individuals against state as well as federal government actions?',
 ARRAY['Gitlow v. New York','Palko v. Connecticut','Barron v. Baltimore','Near v. Minnesota'],
 'Gitlow v. New York', 'Civics', 8),
('What constitutional provision allows the president to withhold information from Congress on grounds of national security?',
 ARRAY['National Security Privilege','State Secrets Privilege','Executive Privilege','Commander-in-Chief Power'],
 'Executive Privilege', 'Civics', 8),
('Which Supreme Court ruling established the "clear and present danger" test for limiting free speech?',
 ARRAY['Abrams v. United States','Dennis v. United States','Schenck v. United States','Whitney v. California'],
 'Schenck v. United States', 'Civics', 8),
('What is the constitutional term for the legislature''s power to investigate and oversee the executive branch?',
 ARRAY['Advice and consent','Legislative oversight','Separation of powers','Checks and balances'],
 'Legislative oversight', 'Civics', 8),
('Which Supreme Court case held that the Second Amendment protects an individual''s right to possess a firearm for traditionally lawful purposes?',
 ARRAY['McDonald v. Chicago','District of Columbia v. Heller','United States v. Miller','Caetano v. Massachusetts'],
 'District of Columbia v. Heller', 'Civics', 8),
('What constitutional doctrine holds that the federal government has certain implied powers not expressly stated in the Constitution?',
 ARRAY['Inherent powers','Implied powers','Reserved powers','Concurrent powers'],
 'Implied powers', 'Civics', 8),
('Which Supreme Court case ruled that juveniles have due process rights in delinquency proceedings?',
 ARRAY['In re Winship','In re Gault','Schall v. Martin','Breed v. Jones'],
 'In re Gault', 'Civics', 9),
('What is the name of the constitutional doctrine that allows courts to refuse to decide political questions best resolved by other branches?',
 ARRAY['Standing doctrine','Political question doctrine','Ripeness doctrine','Mootness doctrine'],
 'Political question doctrine', 'Civics', 9),
('Which constitutional provision specifies that the rights listed in the Constitution shall not be interpreted to deny other rights retained by the people?',
 ARRAY['9th Amendment','10th Amendment','11th Amendment','14th Amendment'],
 '9th Amendment', 'Civics', 9),
('What is the name of the legal doctrine that prevents someone from being tried twice for the same crime after an acquittal?',
 ARRAY['Res judicata','Double jeopardy','Collateral estoppel','Stare decisis'],
 'Double jeopardy', 'Civics', 9),
('Which constitutional clause establishes that the federal government cannot be sued by a state without its consent?',
 ARRAY['Sovereign immunity','11th Amendment','State Immunity Clause','Due process clause'],
 '11th Amendment', 'Civics', 9),
('What is the term for the Supreme Court''s power to review the constitutionality of federal laws?',
 ARRAY['Certiorari','Judicial review','Appellate jurisdiction','Constitutional adjudication'],
 'Judicial review', 'Civics', 9);

-- Famous Americans (48 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which inventor is credited with creating the practical light bulb and the phonograph?',
 ARRAY['Thomas Edison','Nikola Tesla','Alexander Graham Bell','George Westinghouse'],
 'Thomas Edison', 'Famous Americans', 1),
('Who wrote the novel "To Kill a Mockingbird"?',
 ARRAY['Harper Lee','Flannery O''Connor','Truman Capote','Carson McCullers'],
 'Harper Lee', 'Famous Americans', 1),
('George Washington served as the first President of the United States. Who was his Vice President?',
 ARRAY['John Adams','Thomas Jefferson','Alexander Hamilton','James Madison'],
 'John Adams', 'Famous Americans', 1),
('Which suffragette appeared on a U.S. dollar coin in 1979?',
 ARRAY['Susan B. Anthony','Sojourner Truth','Elizabeth Cady Stanton','Lucretia Mott'],
 'Susan B. Anthony', 'Famous Americans', 2),
('Neil Armstrong was the first human to walk on the Moon. Who was the second astronaut to step onto the lunar surface on the same mission?',
 ARRAY['Buzz Aldrin','Michael Collins','Pete Conrad','Alan Bean'],
 'Buzz Aldrin', 'Famous Americans', 2),
('Which American author wrote "The Grapes of Wrath"?',
 ARRAY['John Steinbeck','Ernest Hemingway','William Faulkner','Sinclair Lewis'],
 'John Steinbeck', 'Famous Americans', 2),
('Who founded Amazon in 1994?',
 ARRAY['Jeff Bezos','Elon Musk','Bill Gates','Steve Jobs'],
 'Jeff Bezos', 'Famous Americans', 2),
('Clara Barton founded which humanitarian organization in 1881?',
 ARRAY['American Red Cross','Salvation Army','CARE','United Way'],
 'American Red Cross', 'Famous Americans', 2),
('Which American poet wrote "Song of Myself" as part of "Leaves of Grass"?',
 ARRAY['Walt Whitman','Ralph Waldo Emerson','Henry Wadsworth Longfellow','Emily Dickinson'],
 'Walt Whitman', 'Famous Americans', 3),
('Eli Whitney invented the cotton gin in what year?',
 ARRAY['1793','1786','1800','1810'],
 '1793', 'Famous Americans', 3),
('Which American scientist developed the polio vaccine in 1955?',
 ARRAY['Jonas Salk','Albert Sabin','Alexander Fleming','Howard Florey'],
 'Jonas Salk', 'Famous Americans', 3),
('Jackie Robinson broke the Major League Baseball color barrier in 1947 playing for which team?',
 ARRAY['Brooklyn Dodgers','New York Giants','Cincinnati Reds','Cleveland Indians'],
 'Brooklyn Dodgers', 'Famous Americans', 3),
('Who was the first African American woman elected to the U.S. House of Representatives?',
 ARRAY['Shirley Chisholm','Patsy Mink','Barbara Jordan','Maxine Waters'],
 'Shirley Chisholm', 'Famous Americans', 3),
('Jim Thorpe won Olympic gold medals in which two events at the 1912 Stockholm Olympics?',
 ARRAY['Pentathlon and decathlon','Long jump and hurdles','Shot put and discus','High jump and pole vault'],
 'Pentathlon and decathlon', 'Famous Americans', 3),
('Which American author wrote "The Jungle," exposing unsanitary conditions in the meatpacking industry in 1906?',
 ARRAY['Upton Sinclair','Jack London','Frank Norris','Theodore Dreiser'],
 'Upton Sinclair', 'Famous Americans', 4),
('Garrett Morgan, an African American inventor, is credited with inventing the gas mask and which other commonly used device?',
 ARRAY['Traffic signal','Elevator','Fire hydrant','Air conditioner'],
 'Traffic signal', 'Famous Americans', 4),
('Elizabeth Blackwell became the first woman to receive a medical degree in the United States in what year?',
 ARRAY['1849','1861','1837','1875'],
 '1849', 'Famous Americans', 4),
('Which African American mathematician and NASA scientist was portrayed in the film "Hidden Figures"?',
 ARRAY['Katherine Johnson','Dorothy Vaughan','Mary Jackson','Christine Darden'],
 'Katherine Johnson', 'Famous Americans', 4),
('Arabella Mansfield became the first American woman to receive a law degree, earning it in Iowa in what year?',
 ARRAY['1869','1880','1855','1890'],
 '1869', 'Famous Americans', 4),
('The Black-Scholes formula for options pricing was co-developed by which American economist?',
 ARRAY['Myron Scholes','Milton Friedman','Paul Samuelson','Kenneth Arrow'],
 'Myron Scholes', 'Famous Americans', 5),
('Gertrude Ederle was the first person to swim the English Channel non-stop in 1926, breaking the men''s record by how many hours?',
 ARRAY['Two hours','One hour','Three hours','Four hours'],
 'Two hours', 'Famous Americans', 5),
('Which American composer wrote the opera "Nixon in China" in 1987?',
 ARRAY['John Adams','Philip Glass','Steve Reich','Leonard Bernstein'],
 'John Adams', 'Famous Americans', 5),
('Charles Curtis became the first Native American elected to the U.S. Senate, representing which state in 1907?',
 ARRAY['Kansas','Oklahoma','South Dakota','Nebraska'],
 'Kansas', 'Famous Americans', 5),
('Claude Shannon, known as the father of information theory, published his landmark paper in what year?',
 ARRAY['1948','1943','1952','1956'],
 '1948', 'Famous Americans', 5),
('Theodore Richards became the first American to win the Nobel Prize in Chemistry in what year?',
 ARRAY['1914','1907','1920','1925'],
 '1914', 'Famous Americans', 5),
('Which American choreographer and dancer is considered the "Mother of Modern Dance"?',
 ARRAY['Isadora Duncan','Martha Graham','Ruth St. Denis','Doris Humphrey'],
 'Isadora Duncan', 'Famous Americans', 5),
('Belva Lockwood was the first woman to argue before the U.S. Supreme Court, achieving this in what year?',
 ARRAY['1880','1872','1895','1865'],
 '1880', 'Famous Americans', 6),
('Albert Michelson was the first American to win the Nobel Prize in Physics. He won it for measuring the speed of light. In what year?',
 ARRAY['1907','1901','1912','1920'],
 '1907', 'Famous Americans', 6),
('Christine Ladd-Franklin became the first American woman to complete a PhD in mathematics at Johns Hopkins in 1886, though the degree was withheld for decades. Her later work was in which scientific field?',
 ARRAY['Color vision theory','Electromagnetic theory','Atomic physics','Organic chemistry'],
 'Color vision theory', 'Famous Americans', 6),
('William James, the philosopher and psychologist, is considered a founder of which philosophical movement?',
 ARRAY['Pragmatism','Transcendentalism','Logical positivism','Functionalism'],
 'Pragmatism', 'Famous Americans', 6),
('Robert Smithson created the famous earthwork "Spiral Jetty" in 1970 on the shore of which Utah lake?',
 ARRAY['Great Salt Lake','Utah Lake','Bear Lake','Sevier Lake'],
 'Great Salt Lake', 'Famous Americans', 6),
('Jesse Douglas became the first American to win the Fields Medal in mathematics in 1936 for solving which problem?',
 ARRAY['Plateau''s problem','Fermat''s Last Theorem','Riemann Hypothesis','Four Color Theorem'],
 'Plateau''s problem', 'Famous Americans', 6),
('Selman Waksman won the Nobel Prize in Physiology or Medicine for discovering streptomycin, an antibiotic effective against which disease?',
 ARRAY['Tuberculosis','Typhoid fever','Pneumonia','Malaria'],
 'Tuberculosis', 'Famous Americans', 7),
('Patricia Roberts Harris was the first African American woman appointed to a U.S. Cabinet position, serving as Secretary of which department in 1977?',
 ARRAY['Housing and Urban Development','Health, Education, and Welfare','Labor','Commerce'],
 'Housing and Urban Development', 'Famous Americans', 7),
('Aldo Leopold''s "A Sand County Almanac," a foundational text of environmental ethics, was published in what year?',
 ARRAY['1949','1935','1962','1956'],
 '1949', 'Famous Americans', 7),
('George Beadle won the Nobel Prize in Physiology or Medicine in 1958 for discovering that genes regulate what?',
 ARRAY['Specific chemical reactions','Cell division','DNA replication','Protein folding'],
 'Specific chemical reactions', 'Famous Americans', 7),
('Wallace Carothers, who invented nylon at DuPont, completed this work in which year?',
 ARRAY['1935','1928','1942','1930'],
 '1935', 'Famous Americans', 7),
('Robert Millikan won the 1923 Nobel Prize in Physics for measuring the charge of which subatomic particle?',
 ARRAY['Electron','Proton','Neutron','Photon'],
 'Electron', 'Famous Americans', 7),
('Edward Teller, known as the Father of the Hydrogen Bomb, worked at which national laboratory he co-founded in California?',
 ARRAY['Lawrence Livermore National Laboratory','Los Alamos National Laboratory','Sandia National Laboratory','Argonne National Laboratory'],
 'Lawrence Livermore National Laboratory', 'Famous Americans', 8),
('Jesse Douglas''s 1936 Fields Medal solution to Plateau''s problem involved the mathematics of what geometric object?',
 ARRAY['Minimal surfaces','Knot theory','Fractal geometry','Non-Euclidean spaces'],
 'Minimal surfaces', 'Famous Americans', 8),
('Joseph Schumpeter, who coined the term "creative destruction," taught at which American university for the last 18 years of his life?',
 ARRAY['Harvard','Columbia','Chicago','Princeton'],
 'Harvard', 'Famous Americans', 8),
('John Roebling designed the Brooklyn Bridge before dying from an injury sustained during a survey of the site. What type of injury killed him?',
 ARRAY['Crushed toes from a ferry accident','A fall from scaffolding','A cable snapping during construction','A steam engine explosion'],
 'Crushed toes from a ferry accident', 'Famous Americans', 8),
('Sacheen Littlefeather refused the Academy Award on Marlon Brando''s behalf in 1973 in protest of Hollywood''s depiction of Native Americans. She was a member of which tribe?',
 ARRAY['White Mountain Apache','Yaqui','Lakota Sioux','Cherokee'],
 'White Mountain Apache', 'Famous Americans', 8),
('Ralph Bunche became the first African American to win the Nobel Peace Prize in 1950 for mediating which conflict?',
 ARRAY['1948 Arab-Israeli War','Korean War','Suez Crisis','Congo Crisis'],
 '1948 Arab-Israeli War', 'Famous Americans', 9),
('Charles Curtis, the first Native American to serve as U.S. Vice President, served under which president?',
 ARRAY['Herbert Hoover','Calvin Coolidge','Warren Harding','Woodrow Wilson'],
 'Herbert Hoover', 'Famous Americans', 9),
('Jesse Owens'' four gold medals at the 1936 Berlin Olympics were won in which events?',
 ARRAY['100m, 200m, long jump, 4x100m relay','100m, 200m, 110m hurdles, long jump','100m, long jump, triple jump, 4x100m relay','200m, 400m, long jump, 4x400m relay'],
 '100m, 200m, long jump, 4x100m relay', 'Famous Americans', 9),
('Claude Shannon''s 1948 information theory paper introduced which fundamental concept that measures the amount of uncertainty in a message?',
 ARRAY['Entropy','Bandwidth','Redundancy','Signal-to-noise ratio'],
 'Entropy', 'Famous Americans', 9),
('Christine Ladd-Franklin developed her theory of color vision in the 1890s, proposing that color vision evolved in three stages. Her work challenged which contemporary scientist''s trichromatic theory?',
 ARRAY['Hermann von Helmholtz','James Clerk Maxwell','Ernst Mach','Wilhelm Wundt'],
 'Hermann von Helmholtz', 'Famous Americans', 9);

-- Geography (53 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the largest ocean bordering the United States?',
 ARRAY['Arctic Ocean','Atlantic Ocean','Indian Ocean','Pacific Ocean'],
 'Pacific Ocean', 'Geography', 1),
('What is the capital city of New York state?',
 ARRAY['New York City','Buffalo','Rochester','Albany'],
 'Albany', 'Geography', 1),
('Which U.S. mountain range runs along the eastern coast of the country?',
 ARRAY['Rocky Mountains','Sierra Nevada','Cascade Range','Appalachian Mountains'],
 'Appalachian Mountains', 'Geography', 1),
('Which U.S. state borders both the Atlantic Ocean and the Gulf of Mexico?',
 ARRAY['Georgia','South Carolina','Alabama','Florida'],
 'Florida', 'Geography', 1),
('What is the tallest mountain in the United States?',
 ARRAY['Mount Rainier','Mount Whitney','Denali','Mount McKinley'],
 'Denali', 'Geography', 2),
('Which Great Lake is entirely within the borders of the United States?',
 ARRAY['Lake Ontario','Lake Erie','Lake Huron','Lake Michigan'],
 'Lake Michigan', 'Geography', 2),
('What is the name of the canyon in Arizona carved by the Colorado River?',
 ARRAY['Bryce Canyon','Zion Canyon','Grand Canyon','Antelope Canyon'],
 'Grand Canyon', 'Geography', 2),
('Which U.S. state contains the city of New Orleans?',
 ARRAY['Mississippi','Alabama','Louisiana','Texas'],
 'Louisiana', 'Geography', 2),
('What is the capital of the state of Illinois?',
 ARRAY['Chicago','Rockford','Peoria','Springfield'],
 'Springfield', 'Geography', 2),
('Which U.S. territory in the Pacific is closest to Asia?',
 ARRAY['American Samoa','Hawaii','Guam','Northern Mariana Islands'],
 'Guam', 'Geography', 2),
('Which U.S. state is known as the "Lone Star State"?',
 ARRAY['Oklahoma','New Mexico','Arizona','Texas'],
 'Texas', 'Geography', 2),
('What is the name of the famous geyser in Yellowstone National Park that erupts regularly?',
 ARRAY['Old Reliable','Giant Geyser','Old Faithful','Steamboat Geyser'],
 'Old Faithful', 'Geography', 3),
('Which U.S. state contains the most miles of coastline?',
 ARRAY['California','Texas','Florida','Alaska'],
 'Alaska', 'Geography', 3),
('What is the capital of the state of Georgia?',
 ARRAY['Savannah','Columbus','Augusta','Atlanta'],
 'Atlanta', 'Geography', 3),
('Which U.S. river forms much of the border between Illinois and Missouri?',
 ARRAY['Ohio River','Missouri River','Illinois River','Mississippi River'],
 'Mississippi River', 'Geography', 3),
('What is the name of the peninsula that makes up the lower portion of the state of Michigan?',
 ARRAY['Upper Peninsula','Lower Peninsula','Thumb Peninsula','Great Lakes Peninsula'],
 'Lower Peninsula', 'Geography', 4),
('Which U.S. national park contains the largest cave system in the Western Hemisphere?',
 ARRAY['Mammoth Cave','Wind Cave','Carlsbad Caverns','Jewel Cave'],
 'Mammoth Cave', 'Geography', 4),
('What is the name of the strait that connects the Pacific Ocean to the Puget Sound in Washington state?',
 ARRAY['Juan de Fuca Strait','Georgia Strait','Strait of Juan de Fuca','Rosario Strait'],
 'Strait of Juan de Fuca', 'Geography', 4),
('Which U.S. state has the highest average elevation?',
 ARRAY['Montana','Wyoming','Utah','Colorado'],
 'Colorado', 'Geography', 4),
('What is the name of the famous hot springs resort area in Arkansas?',
 ARRAY['Hot Springs','Mineral Wells','Warm Springs','Eureka Springs'],
 'Hot Springs', 'Geography', 4),
('Which U.S. state contains the Outer Banks, a chain of barrier islands along its coast?',
 ARRAY['Virginia','Georgia','South Carolina','North Carolina'],
 'North Carolina', 'Geography', 4),
('What is the name of the body of water that separates the upper and lower peninsulas of Michigan?',
 ARRAY['Lake St. Clair','Straits of Mackinac','Green Bay','Georgian Bay'],
 'Straits of Mackinac', 'Geography', 4),
('What is the term for the geographic region of the central United States known for its flat, fertile farmland?',
 ARRAY['Great Basin','Great Plains','Central Lowlands','Interior Plains'],
 'Great Plains', 'Geography', 5),
('Which U.S. state contains the Okefenokee Swamp, one of the largest freshwater wetlands in North America?',
 ARRAY['Florida','South Carolina','Alabama','Georgia'],
 'Georgia', 'Geography', 5),
('What is the name of the mountain range that forms the border between California and Nevada?',
 ARRAY['Cascade Range','Coast Ranges','Sierra Nevada','Transverse Ranges'],
 'Sierra Nevada', 'Geography', 5),
('Which U.S. state is home to the Ozark Plateau, a highland region of forests and caves?',
 ARRAY['Kansas','Iowa','Missouri','Illinois'],
 'Missouri', 'Geography', 5),
('What is the name of the largest coral reef system in the continental United States?',
 ARRAY['Florida Reef','Dry Tortugas Reef','Florida Keys National Marine Sanctuary','Great Florida Reef'],
 'Florida Keys National Marine Sanctuary', 'Geography', 5),
('Which U.S. state contains the Mariana Trench, the deepest known point on Earth?',
 ARRAY['Hawaii','Guam','Northern Mariana Islands','American Samoa'],
 'Northern Mariana Islands', 'Geography', 5),
('What is the name of the large bay on the coast of Alaska that was the site of the Exxon Valdez oil spill in 1989?',
 ARRAY['Cook Inlet','Bristol Bay','Kachemak Bay','Prince William Sound'],
 'Prince William Sound', 'Geography', 5),
('Which U.S. state is home to the Tallgrass Prairie National Preserve, one of the last remaining tallgrass prairies?',
 ARRAY['Nebraska','Iowa','Oklahoma','Kansas'],
 'Kansas', 'Geography', 6),
('What is the name of the large lake on the border between Utah and Nevada?',
 ARRAY['Utah Lake','Bear Lake','Pyramid Lake','Great Salt Lake'],
 'Great Salt Lake', 'Geography', 6),
('Which U.S. city sits at the confluence of the Allegheny and Monongahela rivers, forming the Ohio River?',
 ARRAY['Cincinnati','Pittsburgh','Cleveland','Wheeling'],
 'Pittsburgh', 'Geography', 6),
('What is the name of the narrow strip of land connecting Florida to the rest of the continental United States?',
 ARRAY['Florida Panhandle','Florida Neck','Florida Isthmus','Florida Bridge'],
 'Florida Panhandle', 'Geography', 6),
('Which U.S. state contains the Shenandoah National Park and its famous Skyline Drive?',
 ARRAY['West Virginia','Maryland','Pennsylvania','Virginia'],
 'Virginia', 'Geography', 6),
('What is the name of the river that forms the border between Oregon and Washington state?',
 ARRAY['Snake River','Willamette River','Columbia River','Deschutes River'],
 'Columbia River', 'Geography', 6),
('Which U.S. state contains the famous Carlsbad Caverns National Park?',
 ARRAY['Arizona','Texas','Colorado','New Mexico'],
 'New Mexico', 'Geography', 7),
('What is the name of the volcanic island chain that extends southwest from Alaska into the Pacific?',
 ARRAY['Kodiak Island Chain','Kenai Islands','Aleutian Islands','Pribilof Islands'],
 'Aleutian Islands', 'Geography', 7),
('Which U.S. state contains the Flint Hills, the largest remaining intact tallgrass prairie ecosystem?',
 ARRAY['Nebraska','Iowa','Missouri','Kansas'],
 'Kansas', 'Geography', 7),
('What is the name of the large underground aquifer that provides water to much of the Great Plains?',
 ARRAY['Missouri Aquifer','Central Plains Aquifer','Ogallala Aquifer','Midwest Water Table'],
 'Ogallala Aquifer', 'Geography', 7),
('Which U.S. state is home to the Boundary Waters Canoe Area Wilderness, the most visited wilderness in the United States?',
 ARRAY['Wisconsin','Michigan','Minnesota','Maine'],
 'Minnesota', 'Geography', 7),
('What is the name of the geographic region in the Pacific Northwest characterized by rain shadows east of the Cascades?',
 ARRAY['Columbia Plateau','Oregon Plateau','High Desert','Interior Northwest'],
 'Columbia Plateau', 'Geography', 7),
('Which U.S. state contains the Sandhills, a large region of grass-stabilized sand dunes?',
 ARRAY['Kansas','South Dakota','Wyoming','Nebraska'],
 'Nebraska', 'Geography', 8),
('What is the name of the largest river system in the eastern United States, draining about 40% of the continent?',
 ARRAY['Missouri River System','Ohio River System','Mississippi-Missouri River System','Tennessee-Ohio System'],
 'Mississippi-Missouri River System', 'Geography', 8),
('Which U.S. territory in the Caribbean consists of three main islands: St. Croix, St. Thomas, and St. John?',
 ARRAY['Puerto Rico','U.S. Virgin Islands','American Samoa','Northern Mariana Islands'],
 'U.S. Virgin Islands', 'Geography', 8),
('What is the name of the ancient seaway that once covered the central United States, evidence of which is seen in chalk beds in Kansas?',
 ARRAY['Interior Seaway','Western Inland Sea','Central American Seaway','Cretaceous Seaway'],
 'Western Inland Sea', 'Geography', 8),
('Which U.S. state contains the only active diamond mine in North America, open to the public?',
 ARRAY['Colorado','Wyoming','Montana','Arkansas'],
 'Arkansas', 'Geography', 8),
('What is the name of the geographic formation in South Dakota featuring the eroded badlands and prairie?',
 ARRAY['Black Hills','Badlands','Pine Ridge','White River Formation'],
 'Badlands', 'Geography', 8),
('Which U.S. state contains the Haleakala volcano, one of the world''s largest dormant volcanoes by volume?',
 ARRAY['Alaska','Washington','Oregon','Hawaii'],
 'Hawaii', 'Geography', 9),
('What is the name of the narrow underwater ridge connecting the Atlantic and Pacific oceans beneath Cape Cod?',
 ARRAY['Georges Bank','Grand Banks','Cape Cod Bay Ridge','New England Seamounts'],
 'Georges Bank', 'Geography', 9),
('Which U.S. state contains the Porcupine Mountains, an ancient mountain range older than the Appalachians?',
 ARRAY['Wisconsin','Minnesota','Michigan','Wisconsin'],
 'Michigan', 'Geography', 9),
('What is the name of the geological feature in Wyoming where hot springs and geysers indicate ongoing volcanic activity beneath Yellowstone?',
 ARRAY['Yellowstone Supervolcano','Yellowstone Caldera','Yellowstone Hot Spot','Yellowstone Magma Chamber'],
 'Yellowstone Caldera', 'Geography', 9),
('Which U.S. state is home to the ancient sand dunes of the Great Sand Dunes National Park, the tallest in North America?',
 ARRAY['Arizona','Utah','New Mexico','Colorado'],
 'Colorado', 'Geography', 9),
('What is the name of the underwater canyon off the coast of California that rivals the Grand Canyon in depth?',
 ARRAY['Monterey Canyon','Santa Barbara Canyon','Point Sur Canyon','Carmel Canyon'],
 'Monterey Canyon', 'Geography', 9);

-- Landmarks (57 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which famous bridge connects the upper and lower peninsulas of Michigan?',
 ARRAY['Mackinac Bridge','Chesapeake Bay Bridge','Verrazano-Narrows Bridge','Lake Pontchartrain Causeway'],
 'Mackinac Bridge', 'Landmarks', 1),
('What is the name of the large steel sculpture in Chicago''s Millennium Park that reflects the city skyline?',
 ARRAY['The Bean','The Arch','The Wave','The Crown'],
 'The Bean', 'Landmarks', 1),
('In which city is the French Quarter neighborhood located?',
 ARRAY['New Orleans','Savannah','Charleston','Mobile'],
 'New Orleans', 'Landmarks', 1),
('The Alamo is located in which Texas city?',
 ARRAY['San Antonio','Houston','Dallas','Austin'],
 'San Antonio', 'Landmarks', 1),
('What is the name of the large geyser in Yellowstone National Park that erupts predictably?',
 ARRAY['Old Faithful','Grand Prismatic','Steamboat','Castle'],
 'Old Faithful', 'Landmarks', 1),
('What type of building is the Chrysler Building in New York City?',
 ARRAY['Skyscraper','Museum','Government building','Cathedral'],
 'Skyscraper', 'Landmarks', 2),
('In which city is Faneuil Hall located?',
 ARRAY['Boston','Philadelphia','New York','Baltimore'],
 'Boston', 'Landmarks', 2),
('The Hoover Dam was completed in which decade?',
 ARRAY['1930s','1920s','1940s','1950s'],
 '1930s', 'Landmarks', 2),
('Which city is home to the Rock and Roll Hall of Fame?',
 ARRAY['Cleveland','Detroit','Nashville','Memphis'],
 'Cleveland', 'Landmarks', 2),
('The Gateway Arch in St. Louis, Missouri is made of what material?',
 ARRAY['Stainless steel','Granite','Concrete','Aluminum'],
 'Stainless steel', 'Landmarks', 3),
('Which landmark served as a federal penitentiary from 1934 to 1963?',
 ARRAY['Alcatraz','Eastern State Penitentiary','Fort Leavenworth','McNeil Island'],
 'Alcatraz', 'Landmarks', 3),
('The Biltmore Estate in Asheville, North Carolina was built for which family?',
 ARRAY['Vanderbilt','Rockefeller','Carnegie','Morgan'],
 'Vanderbilt', 'Landmarks', 3),
('Which famous American road stretches from Chicago to Santa Monica, California?',
 ARRAY['Route 66','US-1','Highway 101','The Lincoln Highway'],
 'Route 66', 'Landmarks', 3),
('Fallingwater, the famous house designed by Frank Lloyd Wright, is built over what natural feature?',
 ARRAY['A waterfall','A canyon','A lake','A forest'],
 'A waterfall', 'Landmarks', 3),
('Which bridge in New York City was the longest suspension bridge in the world when it opened in 1883?',
 ARRAY['Brooklyn Bridge','Manhattan Bridge','Williamsburg Bridge','Queensboro Bridge'],
 'Brooklyn Bridge', 'Landmarks', 3),
('The Watts Towers in Los Angeles were built by a single Italian immigrant over how many years?',
 ARRAY['33 years','20 years','45 years','10 years'],
 '33 years', 'Landmarks', 3),
('Millard Fillmore''s historic home, the oldest surviving presidential birthplace in New York, is located in which county?',
 ARRAY['Cayuga','Erie','Monroe','Albany'],
 'Cayuga', 'Landmarks', 4),
('The Tribune Tower in Chicago is constructed with fragments of historic buildings embedded in its base. Which of these is NOT one of them?',
 ARRAY['The Colosseum in Rome','The Parthenon in Athens','The Taj Mahal in India','The Great Wall of China'],
 'The Taj Mahal in India', 'Landmarks', 4),
('The Woolworth Building in New York City was nicknamed what when it opened in 1913?',
 ARRAY['Cathedral of Commerce','Temple of Trade','Palace of Progress','Tower of Power'],
 'Cathedral of Commerce', 'Landmarks', 4),
('In what city is the Painted Ladies row of Victorian houses located?',
 ARRAY['San Francisco','Portland','Seattle','Denver'],
 'San Francisco', 'Landmarks', 4),
('Graceland, the former home of Elvis Presley, is located in which Tennessee city?',
 ARRAY['Memphis','Nashville','Knoxville','Chattanooga'],
 'Memphis', 'Landmarks', 4),
('The ancient Cahokia Mounds State Historic Site, once home to a pre-Columbian city, is located in which state?',
 ARRAY['Illinois','Missouri','Ohio','Indiana'],
 'Illinois', 'Landmarks', 4),
('The Corn Palace, an arena decorated each year with thousands of bushels of corn, is located in which city?',
 ARRAY['Mitchell, South Dakota','Sioux Falls, South Dakota','Des Moines, Iowa','Omaha, Nebraska'],
 'Mitchell, South Dakota', 'Landmarks', 4),
('Which historic hotel in San Antonio, Texas opened in 1859 and hosted both Robert E. Lee and Ulysses S. Grant?',
 ARRAY['Menger Hotel','Emily Morgan Hotel','Gunter Hotel','St. Anthony Hotel'],
 'Menger Hotel', 'Landmarks', 4),
('The Palace of Fine Arts in San Francisco was originally built for which exposition?',
 ARRAY['Panama-Pacific International Exposition','Lewis and Clark Centennial Exposition','Trans-Mississippi Exposition','Cotton States Exposition'],
 'Panama-Pacific International Exposition', 'Landmarks', 5),
('The Cathedral of Saint Patrick in New York City is built in which architectural style?',
 ARRAY['Gothic Revival','Romanesque','Baroque','Byzantine'],
 'Gothic Revival', 'Landmarks', 5),
('What is the name of the famous curved concert hall designed by Frank Gehry in Los Angeles?',
 ARRAY['Walt Disney Concert Hall','Hollywood Bowl','Staples Center','Dorothy Chandler Pavilion'],
 'Walt Disney Concert Hall', 'Landmarks', 5),
('Union Station in Washington, DC was designed in what architectural style?',
 ARRAY['Beaux-Arts','Art Deco','Gothic Revival','Neoclassical'],
 'Beaux-Arts', 'Landmarks', 5),
('The Breakers, the 70-room Newport mansion, was built for which member of the Vanderbilt family?',
 ARRAY['Cornelius Vanderbilt II','William Kissam Vanderbilt','George Washington Vanderbilt II','Frederick William Vanderbilt'],
 'Cornelius Vanderbilt II', 'Landmarks', 5),
('Fort Sumter, where the first shots of the Civil War were fired, is located in the harbor of which city?',
 ARRAY['Charleston','Savannah','Wilmington','Mobile'],
 'Charleston', 'Landmarks', 5),
('What famous Seattle landmark was built for the 1962 World''s Fair and stands 605 feet tall?',
 ARRAY['Space Needle','Columbia Center','Smith Tower','Seattle Tower'],
 'Space Needle', 'Landmarks', 5),
('Rainbow Row in Charleston, South Carolina is famous for its row of pastel-painted what?',
 ARRAY['Georgian houses','Victorian homes','Antebellum mansions','Colonial cottages'],
 'Georgian houses', 'Landmarks', 5),
('In what year did the Home Insurance Building in Chicago, considered the world''s first modern skyscraper, open?',
 ARRAY['1885','1871','1893','1900'],
 '1885', 'Landmarks', 6),
('The Soldiers'' National Cemetery at Gettysburg is famous as the site where Lincoln delivered which speech?',
 ARRAY['Gettysburg Address','Emancipation Proclamation','Second Inaugural Address','House Divided Speech'],
 'Gettysburg Address', 'Landmarks', 6),
('The Erie Canal, completed in 1825, connected which two bodies of water?',
 ARRAY['Hudson River and the Great Lakes','Mississippi River and Lake Michigan','Ohio River and Lake Erie','St. Lawrence River and Lake Ontario'],
 'Hudson River and the Great Lakes', 'Landmarks', 6),
('Devils Tower in Wyoming was designated the first U.S. national monument by which president?',
 ARRAY['Theodore Roosevelt','William Howard Taft','Woodrow Wilson','Calvin Coolidge'],
 'Theodore Roosevelt', 'Landmarks', 6),
('Crazy Horse Memorial in South Dakota depicts the Lakota warrior on a horse and has been under construction since what year?',
 ARRAY['1948','1927','1963','1935'],
 '1948', 'Landmarks', 6),
('The 860-880 Lake Shore Drive Apartments in Chicago were designed by which famous architect?',
 ARRAY['Mies van der Rohe','Frank Lloyd Wright','Louis Sullivan','Helmut Jahn'],
 'Mies van der Rohe', 'Landmarks', 6),
('Carlsbad Caverns National Park in New Mexico is recognized as a UNESCO World Heritage Site for its remarkable what?',
 ARRAY['Cave formations','Ancient rock art','Fossil deposits','Underground rivers'],
 'Cave formations', 'Landmarks', 6),
('The historic Portland Head Light in Maine guards the entrance to what harbor?',
 ARRAY['Portland Harbor','Penobscot Bay','Casco Bay','Kennebec River'],
 'Portland Harbor', 'Landmarks', 7),
('The Shelburne Museum in Vermont is known for its collection of what type of art and objects?',
 ARRAY['American folk art and architecture','European Impressionist paintings','Native American artifacts','Colonial silver and ceramics'],
 'American folk art and architecture', 'Landmarks', 7),
('The Longfellow Bridge in Boston connecting Back Bay to Cambridge is nicknamed for what architectural features?',
 ARRAY['Salt-and-pepper shakers','Turrets and towers','Viking ships','Stone arches'],
 'Salt-and-pepper shakers', 'Landmarks', 7),
('What was the original purpose of the Hollywood Sign when it was erected in 1923?',
 ARRAY['Real estate advertisement','Film studio marker','Welcome sign for newcomers','Tourist attraction'],
 'Real estate advertisement', 'Landmarks', 7),
('Hearst Castle on the California coast was built by newspaper magnate William Randolph Hearst as his private estate. It is located near which town?',
 ARRAY['San Simeon','Big Sur','Cambria','Morro Bay'],
 'San Simeon', 'Landmarks', 7),
('The Marble House in Newport, Rhode Island was built for which Vanderbilt and features a famous marble entrance hall?',
 ARRAY['William Kissam Vanderbilt','Cornelius Vanderbilt II','Frederick William Vanderbilt','Harold Stirling Vanderbilt'],
 'William Kissam Vanderbilt', 'Landmarks', 7),
('The Longwood estate in Natchez, Mississippi is built in which architectural style?',
 ARRAY['Moorish Revival','Greek Revival','Gothic Revival','Italianate'],
 'Moorish Revival', 'Landmarks', 7),
('Bent''s Old Fort in Colorado was a major hub of what trade during the 1830s?',
 ARRAY['Rocky Mountain fur trade','Santa Fe Trail commerce','Plains buffalo trade','Gold prospecting supply'],
 'Rocky Mountain fur trade', 'Landmarks', 8),
('The Dexter Avenue King Memorial Baptist Church in Montgomery, Alabama was the congregation of which civil rights leader?',
 ARRAY['Martin Luther King Jr.','Ralph Abernathy','Fred Shuttlesworth','Hosea Williams'],
 'Martin Luther King Jr.', 'Landmarks', 8),
('The Mount, the historic home of author Edith Wharton, is located in which Massachusetts town?',
 ARRAY['Lenox','Stockbridge','Great Barrington','Pittsfield'],
 'Lenox', 'Landmarks', 8),
('What is the name of the historic Pike Place Market in Seattle, which opened in what year?',
 ARRAY['1907','1899','1915','1922'],
 '1907', 'Landmarks', 8),
('The Cathedral of St. John the Divine in New York City is built in what architectural style and took how many decades to construct?',
 ARRAY['Gothic Revival, over 83 years','Romanesque, over 50 years','Byzantine, over 40 years','Neoclassical, over 30 years'],
 'Gothic Revival, over 83 years', 'Landmarks', 8),
('Which Chicago building, designed by Mies van der Rohe, pioneered the all-glass residential tower concept in 1951?',
 ARRAY['860-880 Lake Shore Drive','Promontory Apartments','Illinois Institute of Technology Crown Hall','Farnsworth House'],
 '860-880 Lake Shore Drive', 'Landmarks', 9),
('The Palace of Fine Arts in San Francisco was designed by which architect for the 1915 exposition?',
 ARRAY['Bernard Maybeck','Daniel Burnham','Willis Polk','Arthur Brown Jr.'],
 'Bernard Maybeck', 'Landmarks', 9),
('The Woolworth Building''s Gothic terra-cotta facade was designed by which architect?',
 ARRAY['Cass Gilbert','Daniel Burnham','McKim Mead & White','Louis Sullivan'],
 'Cass Gilbert', 'Landmarks', 9),
('The Marble House in Newport was completed in 1892 at a cost of roughly how much, making it one of the most expensive private homes ever built at that time?',
 ARRAY['$11 million','$5 million','$20 million','$3 million'],
 '$11 million', 'Landmarks', 9),
('Fort Sumter was originally built as a harbor defense after which earlier conflict prompted a coastal fortification program?',
 ARRAY['War of 1812','American Revolution','Quasi-War with France','Mexican-American War'],
 'War of 1812', 'Landmarks', 9),
('The Tribune Tower in Chicago was completed after a 1922 international architecture competition. Who won that competition?',
 ARRAY['John Mead Howells and Raymond Hood','Eliel Saarinen','Walter Gropius','Adolf Loos'],
 'John Mead Howells and Raymond Hood', 'Landmarks', 9);

-- Military (55 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which branch of the U.S. military is the oldest, established in 1775?',
 ARRAY['Army','Navy','Marines','Coast Guard'],
 'Army', 'Military', 1),
('What does the acronym MIA stand for in military context?',
 ARRAY['Missing In Action','Military Intelligence Agency','Marine Infantry Assignment','Mobilized Infantry Artillery'],
 'Missing In Action', 'Military', 1),
('The Purple Heart medal is awarded for what reason?',
 ARRAY['Being wounded or killed in combat','Acts of extraordinary valor','Distinguished service','Meritorious non-combat achievement'],
 'Being wounded or killed in combat', 'Military', 1),
('Which branch of the U.S. military uses the motto "Semper Fidelis"?',
 ARRAY['Marine Corps','Army','Navy','Air Force'],
 'Marine Corps', 'Military', 1),
('What famous U.S. military installation in Kentucky stores the nation''s gold bullion reserves?',
 ARRAY['Fort Knox','Fort Campbell','Fort Bragg','Fort Benning'],
 'Fort Knox', 'Military', 2),
('What is the highest military rank in the U.S. Army?',
 ARRAY['General of the Army','General','Field Marshal','Commander in Chief'],
 'General of the Army', 'Military', 2),
('The Battle of Bunker Hill in 1775 was actually fought mostly on which hill?',
 ARRAY['Breed''s Hill','Dorchester Heights','Copp''s Hill','Fort Hill'],
 'Breed''s Hill', 'Military', 2),
('What military operation resulted in the capture of Saddam Hussein in December 2003?',
 ARRAY['Operation Red Dawn','Operation Iron Hammer','Operation Peninsula Strike','Operation Ivy Cyclone'],
 'Operation Red Dawn', 'Military', 2),
('Which Navy flight demonstration squadron is known as the Blue Angels?',
 ARRAY['U.S. Navy','U.S. Air Force','U.S. Marine Corps','U.S. Army'],
 'U.S. Navy', 'Military', 2),
('What was the name of the strategic bombing campaign of North Vietnam conducted in December 1972?',
 ARRAY['Operation Linebacker II','Operation Rolling Thunder','Operation Arc Light','Operation Freedom Train'],
 'Operation Linebacker II', 'Military', 3),
('The Battle of New Orleans in 1815 was commanded by which American general?',
 ARRAY['Andrew Jackson','William Henry Harrison','Winfield Scott','Jacob Brown'],
 'Andrew Jackson', 'Military', 3),
('The 101st Airborne Division is nicknamed what?',
 ARRAY['Screaming Eagles','All-American','Rock of the Marne','Big Red One'],
 'Screaming Eagles', 'Military', 3),
('During the Civil War, which battle was the bloodiest single day in American military history?',
 ARRAY['Battle of Antietam','Battle of Gettysburg','Battle of Shiloh','Battle of Bull Run'],
 'Battle of Antietam', 'Military', 3),
('What U.S. military operation in 1983 invaded Grenada to rescue American medical students?',
 ARRAY['Operation Urgent Fury','Operation Just Cause','Operation Eagle Claw','Operation Restore Hope'],
 'Operation Urgent Fury', 'Military', 3),
('The Green Berets are the common nickname for which U.S. Army unit?',
 ARRAY['Special Forces','Army Rangers','Delta Force','82nd Airborne'],
 'Special Forces', 'Military', 3),
('The Coast Guard uses which Latin motto meaning "Always Ready"?',
 ARRAY['Semper Paratus','Semper Fidelis','Semper Fortis','Semper Invictus'],
 'Semper Paratus', 'Military', 3),
('What was the name of the military operation to liberate Kuwait during the Gulf War in 1991?',
 ARRAY['Operation Desert Storm','Operation Desert Shield','Operation Desert Sabre','Operation Desert Fox'],
 'Operation Desert Storm', 'Military', 4),
('Which U.S. military operation in 1989 overthrew Panamanian dictator Manuel Noriega?',
 ARRAY['Operation Just Cause','Operation Urgent Fury','Operation Praying Mantis','Operation Eldorado Canyon'],
 'Operation Just Cause', 'Military', 4),
('What was the name of the failed 1980 military mission to rescue American hostages in Iran?',
 ARRAY['Operation Eagle Claw','Operation Neptune Spear','Operation Red Dawn','Operation Credible Sport'],
 'Operation Eagle Claw', 'Military', 4),
('The Doolittle Raid in April 1942 launched B-25 bombers from which aircraft carrier to strike Japan?',
 ARRAY['USS Hornet','USS Enterprise','USS Yorktown','USS Wasp'],
 'USS Hornet', 'Military', 4),
('In what year was the U.S. Air Force established as a separate military branch?',
 ARRAY['1947','1941','1943','1950'],
 '1947', 'Military', 4),
('Which battle during the Korean War saw U.S. Marines conduct one of the most celebrated amphibious landings in history?',
 ARRAY['Inchon','Pusan','Chosin Reservoir','Pork Chop Hill'],
 'Inchon', 'Military', 4),
('What was the primary fighter jet used by the U.S. Air Force during the Korean War?',
 ARRAY['F-86 Sabre','F-80 Shooting Star','F-84 Thunderjet','P-51 Mustang'],
 'F-86 Sabre', 'Military', 4),
('What was the codename for the planned but never executed Allied invasion of the Japanese home islands in World War II?',
 ARRAY['Operation Downfall','Operation Olympic','Operation Coronet','Operation Ketsu-Go'],
 'Operation Downfall', 'Military', 5),
('The Battle of Leyte Gulf in 1944 was the largest naval battle in what war?',
 ARRAY['World War II','World War I','Korean War','Spanish-American War'],
 'World War II', 'Military', 5),
('Castle Bravo, the most powerful U.S. nuclear device ever detonated, was tested in what year?',
 ARRAY['1954','1952','1956','1958'],
 '1954', 'Military', 5),
('General Douglas MacArthur was relieved of command in Korea by which U.S. President?',
 ARRAY['Harry Truman','Dwight Eisenhower','Franklin Roosevelt','John Kennedy'],
 'Harry Truman', 'Military', 5),
('The Battle of Ia Drang Valley in 1965 was significant as the first major engagement between U.S. forces and which enemy?',
 ARRAY['North Vietnamese Army','Viet Cong','Khmer Rouge','Pathet Lao'],
 'North Vietnamese Army', 'Military', 5),
('The Navajo Code Talkers served in which theater of World War II?',
 ARRAY['Pacific','European','North African','Mediterranean'],
 'Pacific', 'Military', 5),
('The Powell Doctrine, named after General Colin Powell, emphasizes what before committing U.S. forces to war?',
 ARRAY['Overwhelming force and clear exit strategy','Surgical strikes and minimal casualties','Air superiority before ground troops','Congressional declaration of war'],
 'Overwhelming force and clear exit strategy', 'Military', 5),
('What is the name of the Night Stalkers, the special operations aviation regiment based at Fort Campbell?',
 ARRAY['160th SOAR','75th Ranger Regiment','82nd Aviation Brigade','18th Airborne Corps Aviation'],
 '160th SOAR', 'Military', 6),
('The Battle of the Philippine Sea in June 1944 was nicknamed by American pilots what, due to the lopsided air losses?',
 ARRAY['The Great Marianas Turkey Shoot','The Pacific Slaughter','The Zero Massacre','The Island Ambush'],
 'The Great Marianas Turkey Shoot', 'Military', 6),
('U.S. Army racial segregation was formally abolished by executive order in what year?',
 ARRAY['1948','1945','1950','1954'],
 '1948', 'Military', 6),
('The USS Cole was attacked by al-Qaeda suicide bombers in the harbor of which city in 2000?',
 ARRAY['Aden, Yemen','Mogadishu, Somalia','Beirut, Lebanon','Manama, Bahrain'],
 'Aden, Yemen', 'Military', 6),
('Operation Market Garden in 1944 was a failed Allied airborne operation to seize bridges in which country?',
 ARRAY['Netherlands','Belgium','Germany','France'],
 'Netherlands', 'Military', 6),
('Which branch of the U.S. military established the Marine Raiders, modeled after British Commandos?',
 ARRAY['Marine Corps','Army','Navy','Special Operations Command'],
 'Marine Corps', 'Military', 6),
('What was the name of the WWII-era deception operation designed to mislead Germany about the D-Day landing location?',
 ARRAY['Operation Fortitude','Operation Bodyguard','Operation Quicksilver','Operation Cockade'],
 'Operation Fortitude', 'Military', 6),
('The Battle of Put-in-Bay on Lake Erie was a decisive American naval victory in which war?',
 ARRAY['War of 1812','Revolutionary War','Mexican-American War','Spanish-American War'],
 'War of 1812', 'Military', 7),
('What was the codename for the secret WWII program that brought Nazi scientists to the United States after the war?',
 ARRAY['Operation Paperclip','Operation Overcast','Operation Alsos','Operation Epsilon'],
 'Operation Paperclip', 'Military', 7),
('The AirLand Battle doctrine developed during the Cold War replaced which earlier doctrine?',
 ARRAY['Active Defense','Flexible Response','Massive Retaliation','Forward Defense'],
 'Active Defense', 'Military', 7),
('The MOAB, the largest non-nuclear bomb in the U.S. arsenal, was first used in combat in which country?',
 ARRAY['Afghanistan','Iraq','Syria','Libya'],
 'Afghanistan', 'Military', 7),
('The F-117 Nighthawk stealth aircraft was first used in combat during which military operation?',
 ARRAY['Operation Just Cause','Operation Desert Storm','Operation Urgent Fury','Operation El Dorado Canyon'],
 'Operation Just Cause', 'Military', 7),
('Which general commanded U.S. forces during World War I and was known by the nickname "Black Jack"?',
 ARRAY['John Pershing','Leonard Wood','Peyton March','Tasker Bliss'],
 'John Pershing', 'Military', 7),
('The Polaris program, which developed the submarine-launched ballistic missile, achieved its first operational deployment in what year?',
 ARRAY['1959','1955','1962','1957'],
 '1959', 'Military', 7),
('Project Have Blue was the classified predecessor program that led to the development of which aircraft?',
 ARRAY['F-117 Nighthawk','B-2 Spirit','SR-71 Blackbird','U-2 Dragon Lady'],
 'F-117 Nighthawk', 'Military', 8),
('During the Battle of Saratoga in 1777, the American victory convinced which European nation to formally ally with the United States?',
 ARRAY['France','Spain','Netherlands','Prussia'],
 'France', 'Military', 8),
('The Battle of Chapultepec in 1847 during the Mexican-American War is referenced in which line of the Marine Corps Hymn?',
 ARRAY['Halls of Montezuma','Shores of Tripoli','Every clime and place','Proud to claim the title'],
 'Halls of Montezuma', 'Military', 8),
('The B-2 Spirit stealth bomber is operated by which wing based at Whiteman Air Force Base?',
 ARRAY['509th Bomb Wing','8th Bomb Wing','2nd Bomb Wing','7th Bomb Wing'],
 '509th Bomb Wing', 'Military', 8),
('Which Army general formulated the Effects-Based Operations concept that shaped planning for Operation Desert Storm?',
 ARRAY['John Warden','Norman Schwarzkopf','Wesley Clark','Colin Powell'],
 'John Warden', 'Military', 8),
('The Lend-Lease Act of 1941 provided military supplies to Allied nations including the Soviet Union. It was authorized under which section that allowed the President to lend or lease equipment?',
 ARRAY['Section 3(a)','Section 1','Section 5','Section 7'],
 'Section 3(a)', 'Military', 9),
('Which general commanded the Eighth Army during the Inchon-Seoul campaign in the Korean War?',
 ARRAY['Walton Walker','Matthew Ridgway','James Van Fleet','Edward Almond'],
 'Walton Walker', 'Military', 9),
('Project Aquatone, the secret program that produced the U-2 spy plane, was developed at which facility commonly known as Skunk Works?',
 ARRAY['Lockheed Advanced Development Projects','Boeing Phantom Works','Northrop Advanced Systems','Grumman Design Center'],
 'Lockheed Advanced Development Projects', 'Military', 9),
('The capture of Emilio Aguinaldo at Palanan in 1901 effectively ended organized resistance during which conflict?',
 ARRAY['Philippine-American War','Spanish-American War','Boxer Rebellion','Moro Rebellion'],
 'Philippine-American War', 'Military', 9),
('The William DePuy Active Defense doctrine was replaced by AirLand Battle in what year, reflecting lessons from the 1973 Arab-Israeli War?',
 ARRAY['1982','1976','1979','1986'],
 '1982', 'Military', 9),
('The JDAM guidance kit, which converts unguided bombs into precision weapons, uses what guidance system?',
 ARRAY['GPS','Laser designation','Infrared homing','Terrain contour matching'],
 'GPS', 'Military', 9);

-- National Parks (53 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('In which state is Zion National Park located?',
 ARRAY['Utah','Arizona','Nevada','Colorado'],
 'Utah', 'National Parks', 1),
('What is the name of the famous arch-shaped rock formation that serves as the symbol of Arches National Park?',
 ARRAY['Delicate Arch','Landscape Arch','Balanced Rock','Double Arch'],
 'Delicate Arch', 'National Parks', 1),
('Which national park in Hawaii features active volcanoes including Kilauea?',
 ARRAY['Hawaii Volcanoes','Haleakala','Kaloko-Honokohau','Pu''uhonua o Honaunau'],
 'Hawaii Volcanoes', 'National Parks', 1),
('Great Smoky Mountains National Park sits on the border of Tennessee and which other state?',
 ARRAY['North Carolina','Georgia','Virginia','South Carolina'],
 'North Carolina', 'National Parks', 1),
('Bryce Canyon National Park in Utah is famous for its orange, red, and white rock spires called what?',
 ARRAY['Hoodoos','Mesas','Buttes','Spires'],
 'Hoodoos', 'National Parks', 2),
('Which national park in California is home to the tallest trees on Earth?',
 ARRAY['Redwood','Sequoia','Yosemite','Joshua Tree'],
 'Redwood', 'National Parks', 2),
('Badlands National Park is located in which state?',
 ARRAY['South Dakota','Wyoming','Montana','Nebraska'],
 'South Dakota', 'National Parks', 2),
('What is the name of the volcanic crater lake in Oregon that is one of the deepest lakes in the United States?',
 ARRAY['Crater Lake','Diamond Lake','Klamath Lake','Upper Klamath'],
 'Crater Lake', 'National Parks', 2),
('Joshua Tree National Park is located in which state?',
 ARRAY['California','Arizona','Nevada','New Mexico'],
 'California', 'National Parks', 2),
('Haleakala National Park protects a dormant shield volcano on which Hawaiian island?',
 ARRAY['Maui','Hawaii','Oahu','Kauai'],
 'Maui', 'National Parks', 3),
('Which national park in New Mexico is famous for its large population of bats that emerge each evening?',
 ARRAY['Carlsbad Caverns','White Sands','Guadalupe Mountains','Bandelier'],
 'Carlsbad Caverns', 'National Parks', 3),
('Cuyahoga Valley National Park is located in which state?',
 ARRAY['Ohio','Indiana','Michigan','Pennsylvania'],
 'Ohio', 'National Parks', 3),
('Which national park in Wyoming sits adjacent to Yellowstone and is known for its dramatic mountain peaks?',
 ARRAY['Grand Teton','Bighorn Canyon','Devils Tower','Fossil Butte'],
 'Grand Teton', 'National Parks', 3),
('What is the name of the most visited trail in Zion National Park that requires hikers to wade through a river?',
 ARRAY['The Narrows','Angel''s Landing','Emerald Pools','Canyon Overlook'],
 'The Narrows', 'National Parks', 3),
('Lassen Volcanic National Park in California features a rare type of volcano known as what?',
 ARRAY['Plug dome volcano','Cinder cone','Shield volcano','Stratovolcano'],
 'Plug dome volcano', 'National Parks', 3),
('Which national park, established in 2020, is located in West Virginia and is known for its gorge and white-water rafting?',
 ARRAY['New River Gorge','Gauley River','Spruce Knob-Seneca Rocks','Canaan Valley'],
 'New River Gorge', 'National Parks', 3),
('Great Sand Dunes National Park, home to the tallest sand dunes in North America, is located in which state?',
 ARRAY['Colorado','New Mexico','Arizona','Utah'],
 'Colorado', 'National Parks', 4),
('Which national park on an island in Lake Superior is famous for its wolf and moose populations?',
 ARRAY['Isle Royale','Pictured Rocks','Sleeping Bear Dunes','Apostle Islands'],
 'Isle Royale', 'National Parks', 4),
('Congaree National Park in South Carolina protects the largest intact old-growth bottomland hardwood forest east of what geographical feature?',
 ARRAY['Mississippi River','Appalachian Mountains','Ohio River','Missouri River'],
 'Mississippi River', 'National Parks', 4),
('White Sands National Park in New Mexico features the world''s largest gypsum dunefield, located in which mountain range valley?',
 ARRAY['San Andres Mountains','Sacramento Mountains','Organ Mountains','Guadalupe Mountains'],
 'San Andres Mountains', 'National Parks', 4),
('Kobuk Valley National Park in Alaska lies above which geographic boundary?',
 ARRAY['Arctic Circle','Tropic of Cancer','60th parallel','Brooks Range divide'],
 'Arctic Circle', 'National Parks', 4),
('Channel Islands National Park protects how many islands off the coast of Southern California?',
 ARRAY['5','4','6','8'],
 '5', 'National Parks', 4),
('Guadalupe Mountains National Park contains Guadalupe Peak, which is the highest point in which state?',
 ARRAY['Texas','New Mexico','Arizona','Oklahoma'],
 'Texas', 'National Parks', 4),
('Which national park in Washington State is known for the Hoh Rain Forest, which receives up to 14 feet of rain annually?',
 ARRAY['Olympic','North Cascades','Mount Rainier','San Juan Island'],
 'Olympic', 'National Parks', 5),
('The Pinnacles National Park in California was formed by ancient volcanic activity along which fault system?',
 ARRAY['San Andreas Fault','Hayward Fault','Calaveras Fault','Garlock Fault'],
 'San Andreas Fault', 'National Parks', 5),
('Going-to-the-Sun Road in Glacier National Park crosses the Continental Divide at which pass?',
 ARRAY['Logan Pass','Marias Pass','Piegan Pass','Swiftcurrent Pass'],
 'Logan Pass', 'National Parks', 5),
('Katmai National Park in Alaska is famous for its brown bears gathering to catch what fish?',
 ARRAY['Salmon','Trout','Arctic char','Halibut'],
 'Salmon', 'National Parks', 5),
('Rocky Mountain National Park contains Trail Ridge Road, one of the highest paved roads in the U.S. reaching approximately how many feet in elevation?',
 ARRAY['12,183 feet','10,000 feet','14,000 feet','11,500 feet'],
 '12,183 feet', 'National Parks', 5),
('Mesa Verde National Park in Colorado preserves cliff dwellings built by which ancient peoples?',
 ARRAY['Ancestral Puebloans','Hohokam','Mogollon','Fremont'],
 'Ancestral Puebloans', 'National Parks', 5),
('The Tallgrass Prairie National Preserve is located in which state, protecting one of the last remnants of tallgrass prairie?',
 ARRAY['Kansas','Nebraska','Oklahoma','Iowa'],
 'Kansas', 'National Parks', 6),
('Which national park in North Dakota is named after a president who ranched in the area and is located in the Badlands?',
 ARRAY['Theodore Roosevelt','Andrew Jackson','Abraham Lincoln','Ulysses Grant'],
 'Theodore Roosevelt', 'National Parks', 6),
('Great Basin National Park in Nevada is home to bristlecone pines, which are among the oldest living organisms on Earth, estimated at up to how many years old?',
 ARRAY['5,000 years','3,000 years','7,000 years','2,500 years'],
 '5,000 years', 'National Parks', 6),
('Crater Lake in Oregon was formed by the eruption and collapse of which ancient volcano?',
 ARRAY['Mount Mazama','Mount Jefferson','Mount McLoughlin','Mount Bailey'],
 'Mount Mazama', 'National Parks', 6),
('Petrified Forest National Park in Arizona contains wood petrified by what two minerals?',
 ARRAY['Iron and manganese','Quartz and feldspar','Silica and calcite','Copper and iron'],
 'Iron and manganese', 'National Parks', 6),
('Virgin Islands National Park covers about two-thirds of which island?',
 ARRAY['St. John','St. Thomas','St. Croix','Tortola'],
 'St. John', 'National Parks', 6),
('Glacier Bay National Park in Alaska contains more than how many glaciers?',
 ARRAY['1,000','500','200','750'],
 '1,000', 'National Parks', 6),
('Mammoth Cave National Park in Kentucky has approximately how many miles of surveyed passageways, making it the world''s longest known cave system?',
 ARRAY['400 miles','200 miles','600 miles','150 miles'],
 '400 miles', 'National Parks', 7),
('Big Bend National Park in Texas borders which country along the Rio Grande?',
 ARRAY['Mexico','No foreign country','Guatemala','Canada'],
 'Mexico', 'National Parks', 7),
('North Cascades National Park in Washington State is sometimes called what due to its rugged Alpine terrain?',
 ARRAY['American Alps','North American Switzerland','Pacific Himalaya','Wild Cascades'],
 'American Alps', 'National Parks', 7),
('Saguaro National Park is divided into two districts surrounding which Arizona city?',
 ARRAY['Tucson','Phoenix','Flagstaff','Yuma'],
 'Tucson', 'National Parks', 7),
('Capitol Reef National Park in Utah is centered on a geologic feature called the Waterpocket Fold, which is what type of formation?',
 ARRAY['Monocline','Anticline','Syncline','Horst'],
 'Monocline', 'National Parks', 7),
('Canyonlands National Park in Utah is divided into districts by the confluence of which two rivers?',
 ARRAY['Colorado and Green rivers','Colorado and San Juan rivers','Green and San Juan rivers','Colorado and Dirty Devil rivers'],
 'Colorado and Green rivers', 'National Parks', 7),
('Apostle Islands National Lakeshore in Wisconsin consists of how many islands in Lake Superior?',
 ARRAY['21','14','28','18'],
 '21', 'National Parks', 8),
('The Arches National Park area known as the Fiery Furnace is characterized by what type of terrain?',
 ARRAY['A maze of narrow sandstone canyons','A geothermal hot spring field','A petrified lava flow','A salt flat basin'],
 'A maze of narrow sandstone canyons', 'National Parks', 8),
('Wrangell-St. Elias National Park, the largest U.S. national park, encompasses how many acres?',
 ARRAY['13.2 million acres','9 million acres','7.5 million acres','11 million acres'],
 '13.2 million acres', 'National Parks', 8),
('Craters of the Moon National Monument in Idaho is dominated by lava flows consisting primarily of what rock type?',
 ARRAY['Basalt','Rhyolite','Obsidian','Andesite'],
 'Basalt', 'National Parks', 8),
('Delaware Water Gap National Recreation Area straddles the border of New Jersey and which other state?',
 ARRAY['Pennsylvania','New York','Maryland','Connecticut'],
 'Pennsylvania', 'National Parks', 8),
('Isle Royale National Park is notable for its long-running predator-prey study tracking wolves and moose, which has been ongoing since what year?',
 ARRAY['1958','1950','1970','1945'],
 '1958', 'National Parks', 9),
('The Wave, a famous sandstone rock formation in the Vermilion Cliffs National Monument, requires a permit lottery. In which state is it located?',
 ARRAY['Arizona','Utah','Nevada','Colorado'],
 'Arizona', 'National Parks', 9),
('Kobuk Valley National Park contains the Kobuk Sand Dunes, which are notable for being sand dunes located north of the Arctic Circle. The dunes cover approximately how many square miles?',
 ARRAY['25 square miles','10 square miles','50 square miles','5 square miles'],
 '25 square miles', 'National Parks', 9),
('Congaree National Park''s old-growth forest contains some of the tallest trees in the eastern U.S., with champion loblolly pines reaching close to how many feet tall?',
 ARRAY['167 feet','130 feet','200 feet','110 feet'],
 '167 feet', 'National Parks', 9),
('The Maze district of Canyonlands National Park is considered one of the most remote and difficult terrains in the U.S. park system. It requires what type of special vehicle to reach?',
 ARRAY['High-clearance 4WD vehicle','Helicopter','Boat','Pack horse'],
 'High-clearance 4WD vehicle', 'National Parks', 9),
('Capitol Reef National Park preserves a 19th-century settlement called Fruita, established by which religious group?',
 ARRAY['Mormon settlers','Quakers','Mennonites','Shakers'],
 'Mormon settlers', 'National Parks', 9);

-- US History (66 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which president signed the Kansas-Nebraska Act into law in 1854?',
 ARRAY['James Buchanan','Franklin Pierce','Millard Fillmore','Zachary Taylor'],
 'Franklin Pierce', 'US History', 1),
('What was the name of the first permanent English settlement in America, founded in 1585 but later abandoned?',
 ARRAY['Plymouth','Roanoke','Jamestown','St. Augustine'],
 'Roanoke', 'US History', 1),
('Which U.S. president purchased Florida from Spain in 1819?',
 ARRAY['James Monroe','John Adams','Andrew Jackson','James Madison'],
 'James Monroe', 'US History', 1),
('What year did the United States officially declare independence from Britain?',
 ARRAY['1774','1775','1776','1781'],
 '1776', 'US History', 1),
('Which battle is considered the turning point of the Civil War, fought in July 1863?',
 ARRAY['Antietam','Bull Run','Gettysburg','Chancellorsville'],
 'Gettysburg', 'US History', 1),
('Who was the commander of the Continental Army during the American Revolution?',
 ARRAY['Benjamin Franklin','John Adams','Thomas Jefferson','George Washington'],
 'George Washington', 'US History', 1),
('What term describes the U.S. policy of avoiding entanglements in European affairs in the 19th century?',
 ARRAY['Imperialism','Isolationism','Expansionism','Nationalism'],
 'Isolationism', 'US History', 2),
('Which amendment to the U.S. Constitution abolished slavery in 1865?',
 ARRAY['12th Amendment','13th Amendment','14th Amendment','15th Amendment'],
 '13th Amendment', 'US History', 2),
('What was the name of the economic policy under President Ronald Reagan that emphasized tax cuts and deregulation?',
 ARRAY['The New Deal','The Fair Deal','Reaganomics','Supply-Side Economics'],
 'Reaganomics', 'US History', 2),
('Which Native American leader led the Sioux and Cheyenne forces at the Battle of Little Bighorn in 1876?',
 ARRAY['Geronimo','Sitting Bull','Crazy Horse','Red Cloud'],
 'Sitting Bull', 'US History', 2),
('What was the primary cause of the Panic of 1837 financial crisis?',
 ARRAY['A banking collapse in Europe','Overspeculation in western lands','The failure of the Second Bank','Overproduction of cotton'],
 'Overspeculation in western lands', 'US History', 2),
('Which U.S. president issued the Monroe Doctrine in 1823?',
 ARRAY['John Quincy Adams','James Monroe','Andrew Jackson','John Adams'],
 'James Monroe', 'US History', 2),
('What was the significance of the Stonewall Inn riots of 1969?',
 ARRAY['They started the anti-Vietnam War movement','They sparked the modern LGBTQ+ rights movement','They began the Black Power movement','They launched the women''s liberation movement'],
 'They sparked the modern LGBTQ+ rights movement', 'US History', 2),
('Which U.S. territory was purchased from Russia in 1867?',
 ARRAY['Hawaii','Guam','Alaska','Puerto Rico'],
 'Alaska', 'US History', 2),
('What major legislation did President Lyndon B. Johnson sign in 1965 to protect voting rights?',
 ARRAY['Civil Rights Act','Fair Housing Act','Voting Rights Act','Equal Employment Act'],
 'Voting Rights Act', 'US History', 2),
('What was the name of the 1964 economic program introduced by LBJ to eliminate poverty?',
 ARRAY['The New Frontier','The New Deal','The Great Society','The Fair Deal'],
 'The Great Society', 'US History', 2),
('Who was the first U.S. president to be impeached by the House of Representatives?',
 ARRAY['Richard Nixon','Bill Clinton','Andrew Johnson','Abraham Lincoln'],
 'Andrew Johnson', 'US History', 3),
('What was the name of the U.S. ship whose sinking in Havana Harbor in 1898 helped trigger the Spanish-American War?',
 ARRAY['USS Maine','USS Constitution','USS Monitor','USS Arizona'],
 'USS Maine', 'US History', 3),
('Which 1920 event saw the deadliest act of domestic terrorism in U.S. history at the time, occurring on Wall Street?',
 ARRAY['Palmer Raids','Chicago Race Riot','Wall Street bombing','Tulsa Race Massacre'],
 'Wall Street bombing', 'US History', 3),
('Which president established the national park system with the Antiquities Act in 1906?',
 ARRAY['William Howard Taft','Woodrow Wilson','Theodore Roosevelt','William McKinley'],
 'Theodore Roosevelt', 'US History', 3),
('What was the nickname for the period of intense political repression and fear of Communist influence in the late 1940s and early 1950s?',
 ARRAY['The Red Scare','The Lavender Scare','The Big Scare','The Yellow Peril'],
 'The Red Scare', 'US History', 3),
('Which U.S. policy in 1947 pledged to support nations threatened by Soviet expansion?',
 ARRAY['Marshall Plan','Truman Doctrine','Containment Policy','NSC-68'],
 'Truman Doctrine', 'US History', 3),
('What was the name of the 1862 federal law that established land-grant colleges across the U.S.?',
 ARRAY['Northwest Ordinance','Morrill Act','Hatch Act','Pacific Railroad Act'],
 'Morrill Act', 'US History', 3),
('Which U.S. president first used the term "bully pulpit" to describe the presidency as a platform?',
 ARRAY['Woodrow Wilson','William Howard Taft','Warren Harding','Theodore Roosevelt'],
 'Theodore Roosevelt', 'US History', 3),
('What was the name of the 1919 race massacre in which white mobs attacked Black residents in Elaine, Arkansas?',
 ARRAY['Elaine Race Massacre','Elaine Riot','Red Summer Massacre','Delta Massacre'],
 'Elaine Race Massacre', 'US History', 4),
('Which U.S. general accepted the Japanese surrender aboard the USS Missouri in Tokyo Bay in 1945?',
 ARRAY['Dwight Eisenhower','Chester Nimitz','Douglas MacArthur','George Patton'],
 'Douglas MacArthur', 'US History', 4),
('What was the primary purpose of the 1935 Wagner Act?',
 ARRAY['To regulate banks after the Depression','To guarantee workers'' right to organize unions','To create Social Security benefits','To regulate the stock market'],
 'To guarantee workers'' right to organize unions', 'US History', 4),
('What was the name of the spy case in which Julius and Ethel Rosenberg were convicted of passing nuclear secrets to the Soviet Union?',
 ARRAY['The Hiss Affair','The Rosenberg Case','The Klaus Fuchs Case','The Atomic Spy Ring'],
 'The Rosenberg Case', 'US History', 4),
('Which U.S. president ordered the atomic bombing of Hiroshima and Nagasaki in 1945?',
 ARRAY['Franklin D. Roosevelt','Harry S. Truman','Dwight Eisenhower','Herbert Hoover'],
 'Harry S. Truman', 'US History', 4),
('What was the original purpose of the Freedmen''s Bureau, established in 1865?',
 ARRAY['To distribute land to freed slaves','To assist freed slaves and poor whites in the South','To enforce the 13th Amendment','To provide military protection in the South'],
 'To assist freed slaves and poor whites in the South', 'US History', 4),
('What was the name of the political scandal involving the Harding administration and oil leases on federal land?',
 ARRAY['Credit Mobilier','Teapot Dome','Crédit Lyonnais','Black Friday'],
 'Teapot Dome', 'US History', 4),
('Which 1944 domestic program provided low-cost mortgages and education benefits to returning WWII veterans?',
 ARRAY['Fair Deal','New Deal','GI Bill','Marshall Plan'],
 'GI Bill', 'US History', 4),
('In what year did the United States formally annex Hawaii?',
 ARRAY['1887','1893','1898','1903'],
 '1898', 'US History', 4),
('Who was the U.S. Secretary of State who negotiated the purchase of Alaska from Russia?',
 ARRAY['John Hay','Hamilton Fish','William Seward','Elihu Washburne'],
 'William Seward', 'US History', 5),
('Which U.S. president signed the Chinese Exclusion Act of 1882?',
 ARRAY['Rutherford B. Hayes','James Garfield','Chester Arthur','Grover Cleveland'],
 'Chester Arthur', 'US History', 5),
('What was the name of the 1955 civil rights case in which fourteen-year-old Emmett Till was murdered in Mississippi?',
 ARRAY['The Till Lynching','The Emmett Till Case','The Mississippi Atrocity','The Money Murder'],
 'The Emmett Till Case', 'US History', 5),
('Which amendment to the Constitution gave Congress the power to levy an income tax?',
 ARRAY['15th Amendment','16th Amendment','17th Amendment','18th Amendment'],
 '16th Amendment', 'US History', 5),
('What was the name of the 1969 environmental disaster in which the Cuyahoga River in Ohio caught fire, sparking the environmental movement?',
 ARRAY['Cuyahoga River Fire','Cleveland Chemical Spill','Lake Erie Disaster','Ohio River Pollution'],
 'Cuyahoga River Fire', 'US History', 5),
('Which U.S. president signed the National Environmental Policy Act in 1970, establishing the EPA?',
 ARRAY['Lyndon B. Johnson','Richard Nixon','Gerald Ford','Jimmy Carter'],
 'Richard Nixon', 'US History', 5),
('What was the name of the 1892 labor strike at Carnegie Steel in Pennsylvania?',
 ARRAY['Homestead Strike','Pittsburgh Strike','Carnegie Strike','Steel Workers Rebellion'],
 'Homestead Strike', 'US History', 5),
('Which U.S. city was the site of the first major race riot of the "Red Summer" of 1919?',
 ARRAY['Chicago','Washington D.C.','Tulsa','East St. Louis'],
 'Chicago', 'US History', 5),
('What was the primary goal of the National Recovery Administration (NRA) created by FDR in 1933?',
 ARRAY['To regulate the banking system','To set industry codes for fair competition','To provide relief to unemployed workers','To regulate agricultural production'],
 'To set industry codes for fair competition', 'US History', 5),
('Which president first established formal diplomatic relations with the People''s Republic of China in 1979?',
 ARRAY['Richard Nixon','Gerald Ford','Jimmy Carter','Ronald Reagan'],
 'Jimmy Carter', 'US History', 6),
('What was the name of the 1966 Supreme Court case that established Miranda rights for criminal suspects?',
 ARRAY['Gideon v. Wainwright','Mapp v. Ohio','Miranda v. Arizona','Terry v. Ohio'],
 'Miranda v. Arizona', 'US History', 6),
('Which U.S. president signed the Immigration Act of 1924, severely restricting immigration from southern and eastern Europe?',
 ARRAY['Warren Harding','Calvin Coolidge','Herbert Hoover','Woodrow Wilson'],
 'Calvin Coolidge', 'US History', 6),
('What was the name of the 1960 incident in which an American U-2 spy plane was shot down over the Soviet Union?',
 ARRAY['Gary Powers Incident','U-2 Affair','Cold War Crisis','Eisenhower Spy Scandal'],
 'U-2 Affair', 'US History', 6),
('Which U.S. constitutional amendment lowered the voting age from 21 to 18?',
 ARRAY['24th Amendment','25th Amendment','26th Amendment','27th Amendment'],
 '26th Amendment', 'US History', 6),
('What was the name of the 1971 leaking of classified Vietnam War documents to the press by Daniel Ellsberg?',
 ARRAY['The Vietnam Papers','The Pentagon Papers','The Defense Documents','The Ellsberg Affair'],
 'The Pentagon Papers', 'US History', 6),
('What was the name of the 1950 NSC report that outlined the United States'' military buildup strategy against the Soviet Union?',
 ARRAY['NSC-20','NSC-48','NSC-68','NSC-100'],
 'NSC-68', 'US History', 7),
('Which U.S. president authorized the covert operation to overthrow the Iranian government of Mohammed Mosaddegh in 1953?',
 ARRAY['Harry Truman','Dwight Eisenhower','John F. Kennedy','Lyndon Johnson'],
 'Dwight Eisenhower', 'US History', 7),
('What was the name of the 1918 federal law that criminalized antiwar speech and was used to prosecute Eugene Debs?',
 ARRAY['Espionage Act','Sedition Act','Alien Act','Defense Secrets Act'],
 'Sedition Act', 'US History', 7),
('Which U.S. senator from Wisconsin led the investigation into Communist infiltration of the U.S. Army in 1954?',
 ARRAY['Richard Nixon','Hubert Humphrey','Joseph McCarthy','Barry Goldwater'],
 'Joseph McCarthy', 'US History', 7),
('What was the codename for the U.S. nuclear weapons development program during World War II?',
 ARRAY['Operation Overlord','The Manhattan Project','Operation Downfall','Project Trinity'],
 'The Manhattan Project', 'US History', 7),
('What was the name of the 1877 labor uprising triggered by wage cuts on the railroads, often called the first nationwide strike?',
 ARRAY['Great Railroad Strike','National Labor Rebellion','The Great Upheaval','Railroad Workers'' War'],
 'Great Railroad Strike', 'US History', 7),
('Which U.S. government program in the 1950s and 1960s involved the CIA monitoring and infiltrating domestic civil rights organizations?',
 ARRAY['COINTELPRO','Operation CHAOS','Project MINARET','MKUltra'],
 'COINTELPRO', 'US History', 8),
('What was the name of the 1890 massacre of Lakota Sioux at a reservation in South Dakota?',
 ARRAY['Battle of Little Bighorn','Wounded Knee Massacre','Sand Creek Massacre','Pine Ridge Massacre'],
 'Wounded Knee Massacre', 'US History', 8),
('Which Reconstruction-era constitutional amendment guaranteed equal protection of the laws to all citizens?',
 ARRAY['13th Amendment','14th Amendment','15th Amendment','16th Amendment'],
 '14th Amendment', 'US History', 8),
('What was the name of the 1919 treaty that ended World War I, which the U.S. Senate refused to ratify?',
 ARRAY['Treaty of Brest-Litovsk','Treaty of Versailles','Treaty of London','Treaty of Paris'],
 'Treaty of Versailles', 'US History', 8),
('Which U.S. president created the Peace Corps in 1961?',
 ARRAY['Dwight Eisenhower','John F. Kennedy','Lyndon B. Johnson','Harry Truman'],
 'John F. Kennedy', 'US History', 8),
('What was the name of the congressional act passed in 1798 that made it a crime to criticize the federal government?',
 ARRAY['Espionage Act','Sedition Act of 1798','Alien Act','Insurrection Act'],
 'Sedition Act of 1798', 'US History', 8),
('Which Supreme Court case in 1944 allowed the executive branch to intern Japanese Americans without trial?',
 ARRAY['Ex parte Milligan','Hirabayashi v. United States','Korematsu v. United States','Ex parte Quirin'],
 'Korematsu v. United States', 'US History', 9),
('What was the name of the secret U.S. government program from 1932 to 1972 that withheld treatment from Black men with syphilis?',
 ARRAY['Tuskegee Syphilis Study','U.S. Public Health Study','Alabama Medical Experiment','Black Health Project'],
 'Tuskegee Syphilis Study', 'US History', 9),
('Which 1905 case established the legal precedent that states could not impose maximum working hour laws on bakers?',
 ARRAY['Lochner v. New York','Adair v. United States','Muller v. Oregon','Coppage v. Kansas'],
 'Lochner v. New York', 'US History', 9),
('What was the name of the 1866 Supreme Court case that ruled military tribunals cannot try civilians when civilian courts are open?',
 ARRAY['Ex parte Milligan','Ex parte Merryman','Ex parte Quirin','In re Neagle'],
 'Ex parte Milligan', 'US History', 9),
('Which 1960 sit-in movement at a Woolworth''s lunch counter in North Carolina became a landmark moment of the civil rights movement?',
 ARRAY['Greensboro Sit-ins','Montgomery Sit-ins','Birmingham Sit-ins','Nashville Sit-ins'],
 'Greensboro Sit-ins', 'US History', 9),
('What was the name of the 1936 Democratic coalition that united labor unions, Catholics, Southern whites, and Black voters?',
 ARRAY['New Deal Coalition','Progressive Alliance','Democratic Front','Roosevelt Coalition'],
 'New Deal Coalition', 'US History', 9);

-- US Sports (53 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('How many points is a field goal worth in American football?',
 ARRAY['1','2','3','6'],
 '3', 'US Sports', 1),
('Which baseball team plays its home games at Wrigley Field in Chicago?',
 ARRAY['Chicago White Sox','Chicago Cubs','Milwaukee Brewers','St. Louis Cardinals'],
 'Chicago Cubs', 'US Sports', 1),
('In basketball, how many free throws does a player shoot after being fouled in the act of shooting a three-pointer?',
 ARRAY['1','2','3','4'],
 '3', 'US Sports', 1),
('Which U.S. city is home to the NFL team known as the Chiefs?',
 ARRAY['St. Louis','Kansas City','Memphis','Oklahoma City'],
 'Kansas City', 'US Sports', 1),
('What is the name of the championship game in the NFL played each February?',
 ARRAY['Championship Bowl','Pro Bowl','Super Bowl','World Bowl'],
 'Super Bowl', 'US Sports', 1),
('Which sport uses a bat, a ball, and three bases plus home plate?',
 ARRAY['Softball','Kickball','Baseball','Cricket'],
 'Baseball', 'US Sports', 1),
('What does NBA stand for?',
 ARRAY['National Basketball Association','North American Basketball Alliance','National Basketball Academy','National Basketball Athletics'],
 'National Basketball Association', 'US Sports', 2),
('Which team won the first Super Bowl in January 1967?',
 ARRAY['Dallas Cowboys','Miami Dolphins','Green Bay Packers','Kansas City Chiefs'],
 'Green Bay Packers', 'US Sports', 2),
('In which city do the Golden State Warriors play their home games?',
 ARRAY['Los Angeles','Sacramento','San Jose','San Francisco'],
 'San Francisco', 'US Sports', 2),
('Which golfer holds the record for the most career PGA Tour victories?',
 ARRAY['Jack Nicklaus','Arnold Palmer','Tiger Woods','Sam Snead'],
 'Sam Snead', 'US Sports', 2),
('What is the name of the trophy awarded to the winner of the NHL''s Eastern Conference Finals?',
 ARRAY['Patrick Roy Trophy','Prince of Wales Trophy','Adams Cup','Clarence Campbell Bowl'],
 'Prince of Wales Trophy', 'US Sports', 2),
('Which American tennis player won the most Grand Slam singles titles in the Open Era before being surpassed?',
 ARRAY['Andre Agassi','Jimmy Connors','John McEnroe','Pete Sampras'],
 'Pete Sampras', 'US Sports', 2),
('In which sport would you hear the term "hat trick"?',
 ARRAY['Basketball','Baseball','Ice Hockey','American Football'],
 'Ice Hockey', 'US Sports', 2),
('What is the length in yards of a standard American football field, not including end zones?',
 ARRAY['80','90','100','110'],
 '100', 'US Sports', 3),
('Which city has hosted the most MLB World Series games?',
 ARRAY['Boston','Chicago','Los Angeles','New York'],
 'New York', 'US Sports', 3),
('Who was the first player to hit 500 home runs in Major League Baseball?',
 ARRAY['Babe Ruth','Mel Ott','Ted Williams','Jimmie Foxx'],
 'Babe Ruth', 'US Sports', 3),
('What is the maximum number of sets in a men''s Grand Slam tennis match?',
 ARRAY['3','4','5','6'],
 '5', 'US Sports', 3),
('Which basketball player is known as "The Answer" and wore number 3 for the Philadelphia 76ers?',
 ARRAY['Allen Iverson','Stephon Marbury','Gary Payton','Jason Kidd'],
 'Allen Iverson', 'US Sports', 4),
('In what year did the AFL and NFL complete their merger, creating one unified NFL?',
 ARRAY['1966','1968','1970','1972'],
 '1970', 'US Sports', 4),
('Which American swimmer broke the world record in the 100m butterfly at the 1976 Montreal Olympics?',
 ARRAY['Mark Spitz','Johnny Weissmuller','Matt Biondi','Jim Montgomery'],
 'Jim Montgomery', 'US Sports', 4),
('Who was the first woman to compete in the Boston Marathon officially?',
 ARRAY['Joan Benoit','Roberta Gibb','Kathrine Switzer','Nina Kuscsik'],
 'Roberta Gibb', 'US Sports', 4),
('Which NBA team drafted Kobe Bryant 13th overall in the 1996 draft before trading him to the Lakers?',
 ARRAY['Orlando Magic','Charlotte Hornets','Dallas Mavericks','Phoenix Suns'],
 'Charlotte Hornets', 'US Sports', 4),
('What is the name of the award given annually to the best offensive lineman in the NFL?',
 ARRAY['Outland Trophy','Lombardi Award','Chuck Bednarik Award','Doak Walker Award'],
 'Outland Trophy', 'US Sports', 4),
('Which team won the first World Series in 1903?',
 ARRAY['New York Giants','Pittsburgh Pirates','Boston Americans','Chicago Cubs'],
 'Boston Americans', 'US Sports', 4),
('In what year did the NBA introduce the three-point line?',
 ARRAY['1977','1979','1981','1983'],
 '1979', 'US Sports', 5),
('Who holds the NHL record for most career goals scored, with 894?',
 ARRAY['Mario Lemieux','Brett Hull','Gordie Howe','Wayne Gretzky'],
 'Wayne Gretzky', 'US Sports', 5),
('What is the name of the college football game played on New Year''s Day in Miami?',
 ARRAY['Orange Bowl','Sugar Bowl','Cotton Bowl','Fiesta Bowl'],
 'Orange Bowl', 'US Sports', 5),
('Which boxer knocked out Mike Tyson in the 10th round in 1990 in the biggest upset in boxing history?',
 ARRAY['Lennox Lewis','Evander Holyfield','Buster Douglas','Razor Ruddock'],
 'Buster Douglas', 'US Sports', 5),
('Which NFL quarterback holds the record for the most regular season passing yards in a single season?',
 ARRAY['Tom Brady','Peyton Manning','Drew Brees','Patrick Mahomes'],
 'Peyton Manning', 'US Sports', 5),
('In which American city is the United States Tennis Association''s national tennis center located?',
 ARRAY['Washington D.C.','New York','Chicago','Los Angeles'],
 'New York', 'US Sports', 5),
('What is the name of the trophy awarded annually to the best defensive player in college football?',
 ARRAY['Chuck Bednarik Award','Butkus Award','Outland Trophy','Thorpe Award'],
 'Chuck Bednarik Award', 'US Sports', 5),
('Which Hall of Fame pitcher threw seven no-hitters during his career, the most in MLB history?',
 ARRAY['Randy Johnson','Sandy Koufax','Bob Gibson','Nolan Ryan'],
 'Nolan Ryan', 'US Sports', 6),
('Who was the first American to win the Tour de France cycling race?',
 ARRAY['Lance Armstrong','Greg LeMond','Andy Hampsten','Bobby Julich'],
 'Greg LeMond', 'US Sports', 6),
('Which NBA player was known as "Pistol Pete" and revolutionized the point guard position?',
 ARRAY['Pete Maravich','Pete Axthelm','Pete Carril','Pete Newell'],
 'Pete Maravich', 'US Sports', 6),
('In which year did the United States host the FIFA World Cup for the first time?',
 ARRAY['1990','1992','1994','1996'],
 '1994', 'US Sports', 6),
('Who was the first Black head coach in the NBA, hired by the Milwaukee Bucks in 1971?',
 ARRAY['Bill Russell','K.C. Jones','Al Attles','Wayne Embry'],
 'Al Attles', 'US Sports', 6),
('What is the name of the trophy given to the MLS Cup champion each year?',
 ARRAY['Supporters'' Shield','Lamar Hunt U.S. Open Cup','MLS Cup Trophy','Eastern Conference Trophy'],
 'MLS Cup Trophy', 'US Sports', 6),
('Who pitched the only perfect game in World Series history?',
 ARRAY['Sandy Koufax','Bob Gibson','Whitey Ford','Don Larsen'],
 'Don Larsen', 'US Sports', 7),
('Which American sprinter ran the 100-meter dash in 9.84 seconds at the 1996 Atlanta Olympics?',
 ARRAY['Maurice Greene','Carl Lewis','Leroy Burrell','Donovan Bailey'],
 'Donovan Bailey', 'US Sports', 7),
('In what year did Billie Jean King defeat Bobby Riggs in the famous "Battle of the Sexes" tennis match?',
 ARRAY['1971','1973','1975','1977'],
 '1973', 'US Sports', 7),
('Which American diver won gold medals in both the platform and springboard diving events at three consecutive Olympics?',
 ARRAY['Bob Webster','Pat McCormick','Sammy Lee','Greg Louganis'],
 'Greg Louganis', 'US Sports', 7),
('Which NFL team was the first to win back-to-back Super Bowls twice?',
 ARRAY['San Francisco 49ers','Dallas Cowboys','Pittsburgh Steelers','Denver Broncos'],
 'Pittsburgh Steelers', 'US Sports', 7),
('Who was the first American woman to win an Olympic gold medal in weightlifting?',
 ARRAY['Sarah Robles','Cheryl Haworth','Holley Mangold','Tara Nott'],
 'Tara Nott', 'US Sports', 7),
('What is the name of the bowling award given when a player records 12 consecutive strikes in a single game?',
 ARRAY['Hambone','Turkey','Perfect game','Golden Turkey'],
 'Perfect game', 'US Sports', 8),
('Which American sprinter won four gold medals at the 1936 Berlin Olympics despite racial prejudice at home?',
 ARRAY['Ralph Metcalfe','Eddie Tolan','Jesse Owens','Mack Robinson'],
 'Jesse Owens', 'US Sports', 8),
('Which MLB pitcher holds the record for the most career wins with 511?',
 ARRAY['Walter Johnson','Christy Mathewson','Grover Cleveland Alexander','Cy Young'],
 'Cy Young', 'US Sports', 8),
('What is the term in golf when a player completes a hole in the fewest strokes possible relative to par?',
 ARRAY['Birdie','Eagle','Albatross','Hole-in-one'],
 'Hole-in-one', 'US Sports', 8),
('Which American speed skater won five gold medals at the 1980 Lake Placid Winter Olympics?',
 ARRAY['Dan Jansen','Bonnie Blair','Eric Heiden','Jack Shea'],
 'Eric Heiden', 'US Sports', 8),
('Which boxing promoter is credited with popularizing heavyweight boxing in the 20th century through fighters like Ali and Foreman?',
 ARRAY['Don King','Bob Arum','Dan Duva','Lou DiBella'],
 'Don King', 'US Sports', 9),
('In what year did the American Basketball Association (ABA) merge with the NBA?',
 ARRAY['1974','1976','1978','1980'],
 '1976', 'US Sports', 9),
('Which NFL lineman holds the record for most consecutive starts at 282 games?',
 ARRAY['Bruce Matthews','Larry Allen','Forrest Gregg','Jim Marshall'],
 'Jim Marshall', 'US Sports', 9),
('What is the name of the award given annually to the best player in MLS chosen by the players themselves?',
 ARRAY['Golden Boot','Landon Donovan MVP Award','Supporters'' Shield','Best XI Award'],
 'Landon Donovan MVP Award', 'US Sports', 9),
('Who holds the WNBA record for most career points scored?',
 ARRAY['Lisa Leslie','Diana Taurasi','Tina Thompson','Lauren Jackson'],
 'Diana Taurasi', 'US Sports', 9);

