-- Migration 016: Expand question bank (batch 7)
-- 439 questions across 8 categories

-- American Culture (48 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which American painter is best known for his depictions of lonely diners and gas stations in works like "Gas" and "Automat"?',
 ARRAY['Grant Wood','Andrew Wyeth','Edward Hopper','Thomas Hart Benton'],
 'Edward Hopper', 'American Culture', 1),
('What name is given to the traditional American potluck-style meal where each guest brings a dish to share?',
 ARRAY['Carry-in dinner','Covered-dish supper','Community feast','Neighborhood buffet'],
 'Covered-dish supper', 'American Culture', 1),
('Which American sport involves riders on horseback herding cattle and is celebrated annually at rodeos across the West?',
 ARRAY['Polo','Barrel racing','Calf roping','Bull riding'],
 'Calf roping', 'American Culture', 1),
('What is the name of the annual college football championship game played on January 1st and considered one of the oldest bowl games?',
 ARRAY['Sugar Bowl','Cotton Bowl','Rose Bowl','Orange Bowl'],
 'Rose Bowl', 'American Culture', 1),
('Which American holiday celebrates workers and is observed on the first Monday of September?',
 ARRAY['Memorial Day','Columbus Day','Labor Day','Presidents Day'],
 'Labor Day', 'American Culture', 1),
('What type of American cuisine originated in the South and features slow-cooked meats seasoned with spices and sauces?',
 ARRAY['Soul food','Tex-Mex','Barbecue','Cajun'],
 'Barbecue', 'American Culture', 1),
('Which American city is known as the "Cradle of Liberty" and was a center of the American Revolution?',
 ARRAY['New York City','Boston','Philadelphia','Williamsburg'],
 'Boston', 'American Culture', 1),
('What annual American sporting event is nicknamed the "Big Game" and draws the largest TV audience of the year?',
 ARRAY['World Series','NBA Finals','Super Bowl','Stanley Cup Finals'],
 'Super Bowl', 'American Culture', 1),
('Which American author wrote the novel "The Great Gatsby," set during the Roaring Twenties?',
 ARRAY['Ernest Hemingway','William Faulkner','F. Scott Fitzgerald','John Steinbeck'],
 'F. Scott Fitzgerald', 'American Culture', 1),
('What is the traditional name for the week-long festival of Native American dance, music, and culture held on reservations?',
 ARRAY['Potlatch','Powwow','Sun Dance','Green Corn Ceremony'],
 'Powwow', 'American Culture', 1),
('Which American city is home to the Jazz and Heritage Festival held each spring?',
 ARRAY['Memphis','Chicago','New Orleans','Kansas City'],
 'New Orleans', 'American Culture', 1),
('What style of American vernacular architecture features a long, low profile, attached garage, and open floor plan popularized in the 1950s?',
 ARRAY['Cape Cod','Tudor Revival','Ranch house','Craftsman bungalow'],
 'Ranch house', 'American Culture', 1),
('Which American children''s television program introduced the Muppets and aired on PBS beginning in 1969?',
 ARRAY['Mister Rogers'' Neighborhood','The Electric Company','Sesame Street','Captain Kangaroo'],
 'Sesame Street', 'American Culture', 1),
('What term describes the uniquely American tradition of tailgating, which takes place in parking lots before which type of event?',
 ARRAY['Concerts','Sporting events','Political rallies','Outdoor festivals'],
 'Sporting events', 'American Culture', 1),
('Which American folk hero was said to have dug the Mississippi River and roped a tornado in tall tales from the 19th century?',
 ARRAY['John Henry','Paul Bunyan','Pecos Bill','Mike Fink'],
 'Pecos Bill', 'American Culture', 1),
('What distinctive American architectural structure, built of sod, was common on the Great Plains frontier in the 19th century?',
 ARRAY['Dugout','Log cabin','Sod house','Adobe dwelling'],
 'Sod house', 'American Culture', 1),
('Which American painter founded the Hudson River School, known for romantic landscape paintings of the American wilderness?',
 ARRAY['Winslow Homer','Thomas Cole','Frederic Remington','Albert Bierstadt'],
 'Thomas Cole', 'American Culture', 1),
('Which American author wrote "Moby-Dick," a novel about the obsessive pursuit of a white whale?',
 ARRAY['Nathaniel Hawthorne','Herman Melville','James Fenimore Cooper','Washington Irving'],
 'Herman Melville', 'American Culture', 4),
('What is the name of the uniquely American art form that combines elements of African, European, and indigenous music and originated in the Mississippi Delta?',
 ARRAY['Zydeco','Bluegrass','The Blues','Conjunto'],
 'The Blues', 'American Culture', 4),
('Which American architect designed the Fallingwater house in Pennsylvania, cantilevered over a waterfall?',
 ARRAY['Louis Sullivan','Mies van der Rohe','Frank Lloyd Wright','Philip Johnson'],
 'Frank Lloyd Wright', 'American Culture', 4),
('What is the name of the uniquely American literary genre featuring frontier heroes, outlaws, and lawmen of the 19th-century West?',
 ARRAY['Pulp fiction','The Western','Dime novel','Adventure yarn'],
 'The Western', 'American Culture', 4),
('Which American fashion designer is credited with popularizing the miniskirt in the United States during the 1960s?',
 ARRAY['Halston','Bill Blass','Rudi Gernreich','Geoffrey Beene'],
 'Rudi Gernreich', 'American Culture', 4),
('What term describes the American practice of hosting large communal gatherings to raise a neighbor''s barn, especially common among Amish communities?',
 ARRAY['Barn dance','Quilting bee','Barn raising','Husking bee'],
 'Barn raising', 'American Culture', 4),
('Which American short story writer is known for "The Gift of the Magi" and the concept of a twist ending?',
 ARRAY['Ambrose Bierce','O. Henry','Bret Harte','Jack London'],
 'O. Henry', 'American Culture', 4),
('What style of American music, blending country and folk with social commentary, was popularized by Woody Guthrie in the 1930s?',
 ARRAY['Western swing','Honky-tonk','Protest folk','Bluegrass'],
 'Protest folk', 'American Culture', 4),
('Which American film director known for westerns and war epics directed "Stagecoach" and "The Searchers"?',
 ARRAY['Howard Hawks','Cecil B. DeMille','John Ford','William Wyler'],
 'John Ford', 'American Culture', 4),
('What annual event held in Pasadena, California, features elaborately decorated floats made entirely from natural plant materials?',
 ARRAY['Cherry Blossom Festival','Tournament of Roses Parade','Daffodil Parade','Petal Parade'],
 'Tournament of Roses Parade', 'American Culture', 4),
('Which American poet wrote "The Road Not Taken" and is associated with rural New England?',
 ARRAY['Carl Sandburg','Langston Hughes','Robert Frost','Edwin Arlington Robinson'],
 'Robert Frost', 'American Culture', 4),
('What is the name of the Native American craft tradition from the Southwest that produces distinctive turquoise and silver jewelry?',
 ARRAY['Beadwork','Quillwork','Silversmithing','Basketweaving'],
 'Silversmithing', 'American Culture', 4),
('What American musical genre, originating in the Caribbean-American community of New York, fuses jazz, Cuban son, and big band music?',
 ARRAY['Reggaeton','Merengue','Salsa','Cumbia'],
 'Salsa', 'American Culture', 4),
('Which American institution, founded in 1846 from a bequest by British scientist James Smithson, encompasses 19 museums in Washington, D.C.?',
 ARRAY['National Gallery of Art','Library of Congress','Smithsonian Institution','National Archives'],
 'Smithsonian Institution', 'American Culture', 4),
('What term describes the uniquely American practice of placing a colorful quilt outside a farmhouse to signal a stop on the Underground Railroad?',
 ARRAY['Freedom stitching','Signal quilts','Safe harbor quilts','Liberty patches'],
 'Signal quilts', 'American Culture', 4),
('Which American architect designed the Vietnam Veterans Memorial in Washington, D.C., consisting of a V-shaped black granite wall?',
 ARRAY['I.M. Pei','Maya Lin','Zaha Hadid','Richard Meier'],
 'Maya Lin', 'American Culture', 7),
('What is the name of the avant-garde literary movement of the 1950s centered in San Francisco that rejected mainstream American values?',
 ARRAY['Lost Generation','New Formalism','Beat Generation','Black Mountain School'],
 'Beat Generation', 'American Culture', 7),
('Which American composer wrote "Appalachian Spring," a ballet suite celebrating rural American life?',
 ARRAY['Samuel Barber','Leonard Bernstein','Aaron Copland','Charles Ives'],
 'Aaron Copland', 'American Culture', 7),
('What is the name of the Native American storytelling tradition involving painted hides that recorded tribal history and warfare on the Great Plains?',
 ARRAY['Winter counts','Spirit bundles','Medicine wheels','Vision scrolls'],
 'Winter counts', 'American Culture', 7),
('Which American filmmaker pioneered the documentary form with films like "Nanook of the North" in 1922?',
 ARRAY['D.W. Griffith','Robert Flaherty','Mack Sennett','Thomas Ince'],
 'Robert Flaherty', 'American Culture', 7),
('What American art movement of the 1960s-70s featured earth sculptures like Robert Smithson''s "Spiral Jetty" in Utah?',
 ARRAY['Minimalism','Land Art','Conceptual Art','Performance Art'],
 'Land Art', 'American Culture', 7),
('Which American author wrote "Their Eyes Were Watching God," a novel of the Harlem Renaissance era?',
 ARRAY['Nella Larsen','Zora Neale Hurston','Anne Petry','Dorothy West'],
 'Zora Neale Hurston', 'American Culture', 7),
('What uniquely American musical form, developed in New Orleans in the early 20th century, combines African rhythms with European harmonies and improvisation?',
 ARRAY['Ragtime','Gospel','Jazz','Swing'],
 'Jazz', 'American Culture', 7),
('Which American ceramicist is known for creating functional stoneware inspired by the Arts and Crafts movement at the Rookwood Pottery in Cincinnati?',
 ARRAY['Maria Martinez','Adelaide Alsop Robineau','Mary Chase Perry Stratton','Clara Chipman Newton'],
 'Clara Chipman Newton', 'American Culture', 7),
('What is the name of the annual literary festival held in Key West, Florida, that honors the city''s most famous literary resident?',
 ARRAY['Tennessee Williams Festival','Hemingway Days Festival','Faulkner Celebration','Kerouac Literary Festival'],
 'Hemingway Days Festival', 'American Culture', 7),
('Which American painter known for photorealism created hyperrealistic paintings of diners and storefronts in the 1970s?',
 ARRAY['Chuck Close','Richard Estes','Ralph Goings','Don Eddy'],
 'Richard Estes', 'American Culture', 7),
('What term describes the traditional African American quilt patterns from Gee''s Bend, Alabama, noted for abstract, geometric improvisational designs?',
 ARRAY['Freedom quilts','Gee''s Bend quilts','Liberation stitching','Ancestral patterns'],
 'Gee''s Bend quilts', 'American Culture', 7),
('Which American novelist wrote the dystopian "The Handmaid''s Tale," set in a future theocratic United States?',
 ARRAY['Ursula K. Le Guin','Joyce Carol Oates','Margaret Atwood','Octavia Butler'],
 'Margaret Atwood', 'American Culture', 7),
('What American folk art tradition, practiced in Appalachia, involves carving and painting decorative wooden figures called "whittling"?',
 ARRAY['Tole painting','Decoupage','Chip carving','Whittling'],
 'Whittling', 'American Culture', 7),
('Which American jazz pianist and composer wrote "Take the A Train" and led one of the most famous big bands for five decades?',
 ARRAY['Count Basie','Thelonious Monk','Duke Ellington','Art Tatum'],
 'Duke Ellington', 'American Culture', 7),
('What is the name of the distinctively American style of outdoor sign painting that features bold lettering and imagery on barn walls, popular in the late 19th century?',
 ARRAY['Mail Pouch barns','Barn quilts','Hex signs','Fraktur art'],
 'Mail Pouch barns', 'American Culture', 7);

-- Civics (49 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('How many senators does each U.S. state send to the Senate?',
 ARRAY['One','Two','Three','Four'],
 'Two', 'Civics', 1),
('What is the term length of a U.S. President?',
 ARRAY['2 years','4 years','6 years','8 years'],
 '4 years', 'Civics', 1),
('Which branch of government is responsible for interpreting the laws?',
 ARRAY['Executive','Legislative','Judicial','Administrative'],
 'Judicial', 'Civics', 1),
('What is the minimum age required to serve as a U.S. Representative?',
 ARRAY['21','25','30','35'],
 '25', 'Civics', 1),
('Which document declared the thirteen American colonies independent from Britain in 1776?',
 ARRAY['The Constitution','The Articles of Confederation','The Mayflower Compact','The Declaration of Independence'],
 'The Declaration of Independence', 'Civics', 1),
('What is the name of the opening statement of the U.S. Constitution that begins with "We the People"?',
 ARRAY['Preamble','Prologue','Articles','Bill of Rights'],
 'Preamble', 'Civics', 1),
('How many branches of government does the federal government have?',
 ARRAY['Two','Three','Four','Five'],
 'Three', 'Civics', 1),
('Which amendment to the Constitution abolished slavery?',
 ARRAY['10th Amendment','12th Amendment','13th Amendment','14th Amendment'],
 '13th Amendment', 'Civics', 1),
('What is the name of the system that gives each branch of government ways to limit the power of the other two?',
 ARRAY['Separation of powers','Checks and balances','Federalism','Judicial review'],
 'Checks and balances', 'Civics', 1),
('Who is the Commander-in-Chief of the U.S. Armed Forces?',
 ARRAY['Secretary of Defense','Chairman of Joint Chiefs','Vice President','President'],
 'President', 'Civics', 1),
('What is the name of the building where Congress meets in Washington, D.C.?',
 ARRAY['The White House','The Pentagon','The Capitol Building','The Supreme Court'],
 'The Capitol Building', 'Civics', 1),
('How many years is a U.S. Senator''s term?',
 ARRAY['2 years','4 years','6 years','8 years'],
 '6 years', 'Civics', 1),
('What is the maximum number of terms a president can serve under the 22nd Amendment?',
 ARRAY['One','Two','Three','Unlimited'],
 'Two', 'Civics', 1),
('Which amendment grants women the right to vote?',
 ARRAY['15th Amendment','17th Amendment','19th Amendment','21st Amendment'],
 '19th Amendment', 'Civics', 1),
('What does the acronym "POTUS" stand for?',
 ARRAY['President of the United States','Power of the United States','People of the United States','Policy of the United States'],
 'President of the United States', 'Civics', 1),
('In what year was the U.S. Constitution signed?',
 ARRAY['1776','1781','1787','1791'],
 '1787', 'Civics', 1),
('What is the legal process by which a non-citizen becomes a U.S. citizen called?',
 ARRAY['Immigration','Deportation','Naturalization','Asylum'],
 'Naturalization', 'Civics', 4),
('Which clause of the Constitution gives Congress the power to make all laws "necessary and proper" to carry out its enumerated powers?',
 ARRAY['Commerce Clause','Supremacy Clause','Elastic Clause','Takings Clause'],
 'Elastic Clause', 'Civics', 4),
('What is the name of the court case in which the Supreme Court established the principle of judicial review?',
 ARRAY['McCulloch v. Maryland','Gibbons v. Ogden','Marbury v. Madison','Fletcher v. Peck'],
 'Marbury v. Madison', 'Civics', 4),
('How many justices currently serve on the U.S. Supreme Court?',
 ARRAY['7','8','9','11'],
 '9', 'Civics', 4),
('What is the name of the process by which the president nominates a Supreme Court justice?',
 ARRAY['Appointment','Confirmation','Ratification','Selection'],
 'Appointment', 'Civics', 4),
('Which constitutional provision requires states to honor the public acts, records, and court proceedings of other states?',
 ARRAY['Commerce Clause','Due Process Clause','Full Faith and Credit Clause','Supremacy Clause'],
 'Full Faith and Credit Clause', 'Civics', 4),
('What is the term for the president''s refusal to spend money that Congress has appropriated?',
 ARRAY['Veto','Sequestration','Impoundment','Rescission'],
 'Impoundment', 'Civics', 4),
('Which landmark Supreme Court case held that the Constitution protects a right to privacy in matters of contraception?',
 ARRAY['Roe v. Wade','Eisenstadt v. Baird','Griswold v. Connecticut','Lawrence v. Texas'],
 'Griswold v. Connecticut', 'Civics', 4),
('What is the name of the Senate procedure used to end a filibuster, requiring 60 votes?',
 ARRAY['Cloture','Quorum','Reconciliation','Unanimous consent'],
 'Cloture', 'Civics', 4),
('Which amendment prohibited the denial of the right to vote based on race, color, or previous condition of servitude?',
 ARRAY['13th Amendment','14th Amendment','15th Amendment','16th Amendment'],
 '15th Amendment', 'Civics', 4),
('What is the constitutional doctrine that federal law takes precedence over conflicting state law?',
 ARRAY['Federalism','Preemption','Nullification','Incorporation'],
 'Preemption', 'Civics', 4),
('Which court case established that criminal suspects must be informed of their rights before interrogation?',
 ARRAY['Gideon v. Wainwright','Escobedo v. Illinois','Miranda v. Arizona','Terry v. Ohio'],
 'Miranda v. Arizona', 'Civics', 4),
('What is the term for a formal accusation of misconduct against a public official by the House of Representatives?',
 ARRAY['Conviction','Censure','Impeachment','Indictment'],
 'Impeachment', 'Civics', 4),
('How many votes in the Senate are required to remove a president from office after impeachment?',
 ARRAY['51','60','67','75'],
 '67', 'Civics', 4),
('Which constitutional amendment lowered the voting age to 18?',
 ARRAY['24th Amendment','25th Amendment','26th Amendment','27th Amendment'],
 '26th Amendment', 'Civics', 4),
('What is the name for the doctrine that holds states can declare federal laws unconstitutional and refuse to enforce them?',
 ARRAY['Secession','Interposition','Nullification','Devolution'],
 'Nullification', 'Civics', 4),
('Which Supreme Court case ruled that school segregation was unconstitutional?',
 ARRAY['Plessy v. Ferguson','Sweatt v. Painter','Brown v. Board of Education','Shelley v. Kraemer'],
 'Brown v. Board of Education', 'Civics', 4),
('What is the constitutional term for the president''s authority to refuse to sign a bill while Congress is in recess, causing it to fail?',
 ARRAY['Line-item veto','Pocket veto','Executive veto','Qualified veto'],
 'Pocket veto', 'Civics', 4),
('What is the principle that a person cannot be tried twice for the same crime after an acquittal or conviction?',
 ARRAY['Self-incrimination','Double jeopardy','Ex post facto','Habeas corpus'],
 'Double jeopardy', 'Civics', 7),
('Which constitutional clause has been used to extend most Bill of Rights protections to state governments?',
 ARRAY['Commerce Clause','Necessary and Proper Clause','Due Process Clause of the 14th Amendment','Supremacy Clause'],
 'Due Process Clause of the 14th Amendment', 'Civics', 7),
('What is the name of the legal doctrine that allows courts to review the constitutionality of executive and legislative actions?',
 ARRAY['Judicial supremacy','Judicial review','Judicial deference','Judicial restraint'],
 'Judicial review', 'Civics', 7),
('Which Supreme Court case established that the exclusionary rule applies to states, barring illegally obtained evidence?',
 ARRAY['Wolf v. Colorado','Weeks v. United States','Mapp v. Ohio','Terry v. Ohio'],
 'Mapp v. Ohio', 'Civics', 7),
('What constitutional doctrine holds that courts should avoid ruling on political questions best left to other branches?',
 ARRAY['Political question doctrine','Ripeness doctrine','Mootness doctrine','Standing doctrine'],
 'Political question doctrine', 'Civics', 7),
('Which clause prohibits Congress from passing laws that punish individuals without a trial?',
 ARRAY['Ex post facto clause','Habeas corpus','Bill of attainder clause','Due process clause'],
 'Bill of attainder clause', 'Civics', 7),
('What is the name of the Supreme Court doctrine that requires government to show a compelling interest to restrict fundamental rights?',
 ARRAY['Rational basis test','Intermediate scrutiny','Strict scrutiny','Balancing test'],
 'Strict scrutiny', 'Civics', 7),
('Which 1973 Act requires the president to notify Congress within 48 hours of committing armed forces and limits unauthorized military engagement to 60 days?',
 ARRAY['National Security Act','Defense Authorization Act','War Powers Resolution','Armed Forces Act'],
 'War Powers Resolution', 'Civics', 7),
('What is the constitutional requirement that courts can only hear actual disputes, not hypothetical or abstract questions?',
 ARRAY['Ripeness','Standing','Mootness','Case or controversy requirement'],
 'Case or controversy requirement', 'Civics', 7),
('Which Supreme Court ruling held that the Second Amendment protects an individual''s right to possess firearms independent of militia service?',
 ARRAY['McDonald v. Chicago','United States v. Miller','District of Columbia v. Heller','Caetano v. Massachusetts'],
 'District of Columbia v. Heller', 'Civics', 7),
('What is the legal principle that the government cannot deprive individuals of life, liberty, or property without fair legal procedures?',
 ARRAY['Equal protection','Substantive due process','Procedural due process','Fundamental fairness'],
 'Procedural due process', 'Civics', 7),
('Which constitutional provision gives Congress broad authority to regulate commerce among the states?',
 ARRAY['Necessary and Proper Clause','Spending Clause','Commerce Clause','Taxing Clause'],
 'Commerce Clause', 'Civics', 7),
('What is the name of the Supreme Court test used to determine whether government aid to religious institutions violates the Establishment Clause?',
 ARRAY['Lemon test','Warren test','Balancing test','Endorsement test'],
 'Lemon test', 'Civics', 7),
('Which constitutional provision prevents states from impairing the obligation of contracts?',
 ARRAY['Takings Clause','Commerce Clause','Contracts Clause','Due Process Clause'],
 'Contracts Clause', 'Civics', 7),
('What is the name of the legal doctrine that holds that evidence derived from an illegal search is also inadmissible, as it is "tainted"?',
 ARRAY['Exclusionary rule','Fruit of the poisonous tree','Silver platter doctrine','Good faith exception'],
 'Fruit of the poisonous tree', 'Civics', 7);

-- Famous Americans (55 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which inventor is credited with creating the telephone in 1876?',
 ARRAY['Alexander Graham Bell','Thomas Edison','Nikola Tesla','Guglielmo Marconi'],
 'Alexander Graham Bell', 'Famous Americans', 1),
('Who was the first American to walk on the Moon?',
 ARRAY['Neil Armstrong','Buzz Aldrin','John Glenn','Alan Shepard'],
 'Neil Armstrong', 'Famous Americans', 1),
('Which author wrote "Adventures of Huckleberry Finn"?',
 ARRAY['Mark Twain','Ernest Hemingway','John Steinbeck','F. Scott Fitzgerald'],
 'Mark Twain', 'Famous Americans', 1),
('Who founded Microsoft?',
 ARRAY['Bill Gates','Steve Jobs','Jeff Bezos','Elon Musk'],
 'Bill Gates', 'Famous Americans', 1),
('Which civil rights leader delivered the "I Have a Dream" speech?',
 ARRAY['Martin Luther King Jr.','Malcolm X','John Lewis','Thurgood Marshall'],
 'Martin Luther King Jr.', 'Famous Americans', 1),
('Who co-founded Apple Computer with Steve Jobs?',
 ARRAY['Steve Wozniak','Bill Gates','Jeff Bezos','Larry Page'],
 'Steve Wozniak', 'Famous Americans', 1),
('Which famous abolitionist escaped slavery and helped others escape via the Underground Railroad?',
 ARRAY['Harriet Tubman','Frederick Douglass','Sojourner Truth','Harriet Beecher Stowe'],
 'Harriet Tubman', 'Famous Americans', 1),
('Which woman refused to give up her seat on a Montgomery, Alabama bus in 1955?',
 ARRAY['Rosa Parks','Claudette Colvin','Jo Ann Robinson','Coretta Scott King'],
 'Rosa Parks', 'Famous Americans', 1),
('Who invented the practical incandescent light bulb?',
 ARRAY['Thomas Edison','Nikola Tesla','Hiram Maxim','Lewis Latimer'],
 'Thomas Edison', 'Famous Americans', 1),
('Which famous American aviator was the first to break the sound barrier?',
 ARRAY['Chuck Yeager','Charles Lindbergh','Amelia Earhart','Jimmy Doolittle'],
 'Chuck Yeager', 'Famous Americans', 1),
('Which US author wrote "The Grapes of Wrath"?',
 ARRAY['John Steinbeck','Ernest Hemingway','William Faulkner','Theodore Dreiser'],
 'John Steinbeck', 'Famous Americans', 1),
('Who founded Amazon?',
 ARRAY['Jeff Bezos','Bill Gates','Elon Musk','Larry Page'],
 'Jeff Bezos', 'Famous Americans', 1),
('Who was the first Black Supreme Court Justice?',
 ARRAY['Thurgood Marshall','Clarence Thomas','Earl Warren','William O. Douglas'],
 'Thurgood Marshall', 'Famous Americans', 4),
('Which American author won the Nobel Prize in Literature for "The Old Man and the Sea"?',
 ARRAY['Ernest Hemingway','John Steinbeck','Sinclair Lewis','William Faulkner'],
 'Ernest Hemingway', 'Famous Americans', 4),
('Which American invented the cotton gin in 1793?',
 ARRAY['Eli Whitney','Cyrus McCormick','Robert Fulton','Samuel Slater'],
 'Eli Whitney', 'Famous Americans', 4),
('Who co-founded the NAACP alongside W.E.B. Du Bois?',
 ARRAY['Ida B. Wells','Booker T. Washington','Frederick Douglass','Mary Church Terrell'],
 'Ida B. Wells', 'Famous Americans', 4),
('Which famous American poet wrote "The Road Not Taken"?',
 ARRAY['Robert Frost','Walt Whitman','Emily Dickinson','Langston Hughes'],
 'Robert Frost', 'Famous Americans', 4),
('Who was the first American to orbit Earth?',
 ARRAY['John Glenn','Alan Shepard','Gus Grissom','Scott Carpenter'],
 'John Glenn', 'Famous Americans', 4),
('Which African American woman was the first to receive a pilot''s license in the US?',
 ARRAY['Bessie Coleman','Janet Bragg','Willa Brown','Mae Jemison'],
 'Bessie Coleman', 'Famous Americans', 4),
('Who wrote "Silent Spring," which launched the modern environmental movement?',
 ARRAY['Rachel Carson','Aldo Leopold','John Muir','Annie Dillard'],
 'Rachel Carson', 'Famous Americans', 4),
('Which American was the first to receive the Nobel Peace Prize, winning it in 1906?',
 ARRAY['Theodore Roosevelt','Woodrow Wilson','Jane Addams','Elihu Root'],
 'Theodore Roosevelt', 'Famous Americans', 4),
('Who was the first African American woman elected to the US House of Representatives?',
 ARRAY['Shirley Chisholm','Barbara Jordan','Maxine Waters','Carol Moseley Braun'],
 'Shirley Chisholm', 'Famous Americans', 4),
('Who built the first assembly line production of automobiles, transforming American industry?',
 ARRAY['Henry Ford','Andrew Carnegie','John D. Rockefeller','Cornelius Vanderbilt'],
 'Henry Ford', 'Famous Americans', 4),
('Which American artist is known for large-scale paintings of flowers and the New Mexico landscape?',
 ARRAY['Georgia O''Keeffe','Mary Cassatt','Lee Krasner','Helen Frankenthaler'],
 'Georgia O''Keeffe', 'Famous Americans', 4),
('Who became the first American woman to win a Nobel Prize in Literature in 1938?',
 ARRAY['Pearl Buck','Toni Morrison','Edith Wharton','Willa Cather'],
 'Pearl Buck', 'Famous Americans', 5),
('Which American mathematician developed game theory and was the subject of the film "A Beautiful Mind"?',
 ARRAY['John Nash','John von Neumann','Claude Shannon','Norbert Wiener'],
 'John Nash', 'Famous Americans', 5),
('Who won the Nobel Prize in Chemistry in 1914 as the first American to do so in that field?',
 ARRAY['Theodore Richards','Linus Pauling','Harold Urey','Gilbert Lewis'],
 'Theodore Richards', 'Famous Americans', 6),
('Which American author wrote "The Jungle," exposing conditions in the meatpacking industry?',
 ARRAY['Upton Sinclair','Jack London','Theodore Dreiser','Frank Norris'],
 'Upton Sinclair', 'Famous Americans', 6),
('Who was the first African American woman to serve in a US Cabinet position?',
 ARRAY['Patricia Roberts Harris','Shirley Chisholm','Condoleezza Rice','Alexis Herman'],
 'Patricia Roberts Harris', 'Famous Americans', 6),
('Which American physician became the first US woman to earn a medical degree in 1849?',
 ARRAY['Elizabeth Blackwell','Mary Walker','Susan La Flesche Picotte','Mary Putnam Jacobi'],
 'Elizabeth Blackwell', 'Famous Americans', 6),
('Who developed streptomycin, the first antibiotic effective against tuberculosis, winning the Nobel Prize?',
 ARRAY['Selman Waksman','Alexander Fleming','John Enders','Jonas Salk'],
 'Selman Waksman', 'Famous Americans', 6),
('Which American artist created the "Spiral Jetty" earthwork sculpture in the Great Salt Lake in 1970?',
 ARRAY['Robert Smithson','Christo','Andy Goldsworthy','James Turrell'],
 'Robert Smithson', 'Famous Americans', 6),
('Who was the first Native American US Senator, elected from Kansas in 1907?',
 ARRAY['Charles Curtis','Jim Thorpe','Will Rogers','Dennis Hastert'],
 'Charles Curtis', 'Famous Americans', 6),
('Which American jazz musician is considered the "Father of Bebop"?',
 ARRAY['Charlie Parker','Dizzy Gillespie','Thelonious Monk','Miles Davis'],
 'Charlie Parker', 'Famous Americans', 6),
('Who wrote "The Feminine Mystique," helping launch the second-wave feminist movement?',
 ARRAY['Betty Friedan','Gloria Steinem','Simone de Beauvoir','Kate Millett'],
 'Betty Friedan', 'Famous Americans', 6),
('Which American mathematician solved Plateau''s problem on minimal surfaces, winning the Fields Medal in 1936?',
 ARRAY['Jesse Douglas','Marston Morse','Norbert Wiener','George Birkhoff'],
 'Jesse Douglas', 'Famous Americans', 7),
('Who developed the Black-Scholes formula for options pricing, winning the Nobel Prize in Economics?',
 ARRAY['Myron Scholes','Paul Samuelson','Milton Friedman','Robert Solow'],
 'Myron Scholes', 'Famous Americans', 7),
('Which American woman was the first to argue a case before the US Supreme Court in 1880?',
 ARRAY['Belva Lockwood','Arabella Mansfield','Myra Bradwell','Clara Shortridge Foltz'],
 'Belva Lockwood', 'Famous Americans', 7),
('Who won the Nobel Prize in Physics in 1923 for measuring the charge of an electron?',
 ARRAY['Robert Millikan','Arthur Compton','Ernest Lawrence','Carl Anderson'],
 'Robert Millikan', 'Famous Americans', 7),
('Which American scientist is considered the "Father of the Hydrogen Bomb"?',
 ARRAY['Edward Teller','J. Robert Oppenheimer','Hans Bethe','Enrico Fermi'],
 'Edward Teller', 'Famous Americans', 7),
('Who was the first woman to receive a law license in the United States, in Iowa in 1869?',
 ARRAY['Arabella Mansfield','Belva Lockwood','Myra Bradwell','Ada Kepley'],
 'Arabella Mansfield', 'Famous Americans', 7),
('Which African American inventor patented the gas mask and the three-position traffic signal?',
 ARRAY['Garrett Morgan','Lewis Latimer','Jan Ernst Matzeliger','Granville Woods'],
 'Garrett Morgan', 'Famous Americans', 7),
('Who wrote "Sand County Almanac," a foundational text of the American environmental ethics movement?',
 ARRAY['Aldo Leopold','John Muir','Henry David Thoreau','Edward Abbey'],
 'Aldo Leopold', 'Famous Americans', 7),
('Which American engineer built the Brooklyn Bridge and died after a ferry accident crushed his toes before construction was complete?',
 ARRAY['John Roebling','Washington Roebling','Gustave Eiffel','James Eads'],
 'John Roebling', 'Famous Americans', 8),
('Who developed information theory in 1948, introducing the concept of entropy in communication?',
 ARRAY['Claude Shannon','Norbert Wiener','John von Neumann','Alan Turing'],
 'Claude Shannon', 'Famous Americans', 8),
('Which American chemist invented nylon at DuPont in 1935?',
 ARRAY['Wallace Carothers','Leo Baekeland','Julian Hill','Paul Flory'],
 'Wallace Carothers', 'Famous Americans', 8),
('Who was the Apache leader who resisted US and Mexican military campaigns in the late 19th century?',
 ARRAY['Geronimo','Cochise','Victorio','Mangas Coloradas'],
 'Geronimo', 'Famous Americans', 8),
('Which American geneticist won the Nobel Prize in 1958 for discovering that genes regulate specific chemical reactions?',
 ARRAY['George Beadle','James Watson','Barbara McClintock','Thomas Hunt Morgan'],
 'George Beadle', 'Famous Americans', 8),
('Who was the White Mountain Apache woman who declined Marlon Brando''s Academy Award in 1973?',
 ARRAY['Sacheen Littlefeather','Buffy Sainte-Marie','Suzan Shown Harjo','Ada Deer'],
 'Sacheen Littlefeather', 'Famous Americans', 8),
('Which American economist introduced the concept of "creative destruction" and taught at Harvard for 18 years?',
 ARRAY['Joseph Schumpeter','John Kenneth Galbraith','Paul Samuelson','Thorstein Veblen'],
 'Joseph Schumpeter', 'Famous Americans', 9),
('Who was the first African American to win the Nobel Peace Prize, doing so in 1950 for mediating the Arab-Israeli conflict?',
 ARRAY['Ralph Bunche','Martin Luther King Jr.','W.E.B. Du Bois','Jesse Jackson'],
 'Ralph Bunche', 'Famous Americans', 9),
('Which American mathematician and logician developed the field of cybernetics?',
 ARRAY['Norbert Wiener','Claude Shannon','John von Neumann','Alan Turing'],
 'Norbert Wiener', 'Famous Americans', 9),
('Who was the first American to win the Nobel Prize in Physics, in 1907, for measuring the speed of light?',
 ARRAY['Albert Michelson','Robert Millikan','Arthur Compton','Carl Anderson'],
 'Albert Michelson', 'Famous Americans', 9),
('Which pioneering American psychologist wrote "Pragmatism" and founded functional psychology?',
 ARRAY['William James','John Dewey','G. Stanley Hall','Edward Thorndike'],
 'William James', 'Famous Americans', 9),
('Who developed the theory of color vision based on the Helmholtz model, earning a PhD in mathematics from Johns Hopkins in 1886?',
 ARRAY['Christine Ladd-Franklin','Mary Whiton Calkins','Margaret Floy Washburn','Lillien Jane Martin'],
 'Christine Ladd-Franklin', 'Famous Americans', 9);

-- Geography (64 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which US state is the only one to share its name with a Great Lake?',
 ARRAY['Michigan','Indiana','Ohio','Wisconsin'],
 'Michigan', 'Geography', 1),
('What ocean borders the eastern coast of the United States?',
 ARRAY['Atlantic Ocean','Pacific Ocean','Indian Ocean','Arctic Ocean'],
 'Atlantic Ocean', 'Geography', 1),
('Which US state is home to the Rocky Mountains'' highest peak, Mount Elbert?',
 ARRAY['Colorado','Wyoming','Montana','Utah'],
 'Colorado', 'Geography', 1),
('Which US state is known as the "Sunshine State"?',
 ARRAY['Florida','California','Hawaii','Arizona'],
 'Florida', 'Geography', 1),
('What river forms much of the border between the United States and Mexico?',
 ARRAY['Rio Grande','Colorado River','Pecos River','Gila River'],
 'Rio Grande', 'Geography', 1),
('Which US state has the most people?',
 ARRAY['California','Texas','Florida','New York'],
 'California', 'Geography', 1),
('Which US state is an archipelago in the Pacific Ocean?',
 ARRAY['Hawaii','Alaska','Guam','Puerto Rico'],
 'Hawaii', 'Geography', 1),
('Which US state borders both the Atlantic Ocean and the Gulf of Mexico?',
 ARRAY['Florida','Georgia','South Carolina','North Carolina'],
 'Florida', 'Geography', 1),
('What is the name of the large bay that separates the Delmarva Peninsula from mainland Maryland?',
 ARRAY['Chesapeake Bay','Delaware Bay','Albemarle Sound','Pamlico Sound'],
 'Chesapeake Bay', 'Geography', 1),
('Which US state is home to the Grand Canyon?',
 ARRAY['Arizona','Utah','Colorado','Nevada'],
 'Arizona', 'Geography', 1),
('Which of the Great Lakes is located entirely within the United States?',
 ARRAY['Lake Michigan','Lake Superior','Lake Erie','Lake Ontario'],
 'Lake Michigan', 'Geography', 1),
('What is the smallest US state by area?',
 ARRAY['Rhode Island','Delaware','Connecticut','New Jersey'],
 'Rhode Island', 'Geography', 1),
('Which US state is home to Yellowstone National Park?',
 ARRAY['Wyoming','Montana','Idaho','Colorado'],
 'Wyoming', 'Geography', 1),
('Which US state has the longest coastline?',
 ARRAY['Alaska','Florida','California','Texas'],
 'Alaska', 'Geography', 4),
('What is the name of the large underground cave system located in Kentucky?',
 ARRAY['Mammoth Cave','Carlsbad Caverns','Luray Caverns','Meramec Caverns'],
 'Mammoth Cave', 'Geography', 4),
('Which US state capital has the highest elevation above sea level?',
 ARRAY['Santa Fe, New Mexico','Denver, Colorado','Cheyenne, Wyoming','Salt Lake City, Utah'],
 'Santa Fe, New Mexico', 'Geography', 4),
('Which US state is home to the deepest lake in the United States?',
 ARRAY['Oregon','California','Washington','Nevada'],
 'Oregon', 'Geography', 4),
('What is the geographic center of the contiguous 48 states?',
 ARRAY['Lebanon, Kansas','Smith Center, Kansas','Colby, Kansas','Liberal, Kansas'],
 'Lebanon, Kansas', 'Geography', 4),
('Which US territory is closest to Asia?',
 ARRAY['Guam','American Samoa','Northern Mariana Islands','Wake Island'],
 'Guam', 'Geography', 4),
('What is the name of the large river that runs through the Grand Canyon?',
 ARRAY['Colorado River','Green River','San Juan River','Little Colorado River'],
 'Colorado River', 'Geography', 4),
('Which US state has the most counties?',
 ARRAY['Texas','Georgia','Virginia','Kentucky'],
 'Texas', 'Geography', 4),
('What is the name of the large underground water source that supplies much of the Great Plains?',
 ARRAY['Ogallala Aquifer','Edwards Aquifer','Floridan Aquifer','High Plains Aquifer'],
 'Ogallala Aquifer', 'Geography', 4),
('Which US state shares a water border with the Canadian province of British Columbia?',
 ARRAY['Washington','Alaska','Idaho','Montana'],
 'Washington', 'Geography', 4),
('What is the name of the large swamp located in southern Georgia and northern Florida?',
 ARRAY['Okefenokee Swamp','Atchafalaya Basin','Everglades','Big Cypress Swamp'],
 'Okefenokee Swamp', 'Geography', 4),
('Which US state contains the lowest point in North America?',
 ARRAY['California','Nevada','Arizona','Utah'],
 'California', 'Geography', 4),
('What is the name of the mountain range that runs through the Pacific Northwest?',
 ARRAY['Cascade Range','Coast Ranges','Rocky Mountains','Sierra Nevada'],
 'Cascade Range', 'Geography', 4),
('Which US state is entirely within the Appalachian Mountains?',
 ARRAY['West Virginia','Tennessee','Virginia','Kentucky'],
 'West Virginia', 'Geography', 4),
('What is the name of the waterway that separates Michigan''s upper and lower peninsulas?',
 ARRAY['Straits of Mackinac','Strait of Juan de Fuca','Puget Sound','Lake St. Clair'],
 'Straits of Mackinac', 'Geography', 4),
('Which four US states meet at a single point?',
 ARRAY['Arizona, Colorado, New Mexico, Utah','Colorado, Kansas, Nebraska, Wyoming','Idaho, Montana, Wyoming, Utah','Nevada, Arizona, California, Utah'],
 'Arizona, Colorado, New Mexico, Utah', 'Geography', 4),
('What is the name of the large plateau in eastern Washington, Oregon, and Idaho formed by volcanic activity?',
 ARRAY['Columbia Plateau','Snake River Plain','Colorado Plateau','Modoc Plateau'],
 'Columbia Plateau', 'Geography', 5),
('What is the name of the ancient glacial lake whose remnants include the Red River Valley?',
 ARRAY['Lake Agassiz','Lake Bonneville','Lake Lahontan','Lake Missoula'],
 'Lake Agassiz', 'Geography', 5),
('What is the name of the area in the upper Midwest that was not covered by glaciers during the last ice age?',
 ARRAY['Driftless Area','Loess Hills','Prairie Coteau','Coteau du Missouri'],
 'Driftless Area', 'Geography', 5),
('Which US state is home to the Flint Hills, the largest remaining tallgrass prairie in North America?',
 ARRAY['Kansas','Oklahoma','Nebraska','Missouri'],
 'Kansas', 'Geography', 5),
('What is the name of the large lagoon created by an engineering accident in 1905 in California?',
 ARRAY['Salton Sea','Mono Lake','Clear Lake','Tulare Lake'],
 'Salton Sea', 'Geography', 6),
('Which US state is home to the Sandhills, a region of grass-stabilized sand dunes?',
 ARRAY['Nebraska','Kansas','South Dakota','Wyoming'],
 'Nebraska', 'Geography', 6),
('What underwater ridge off Cape Cod is one of the world''s richest fishing grounds?',
 ARRAY['Georges Bank','Grand Banks','Stellwagen Bank','Jeffrey''s Ledge'],
 'Georges Bank', 'Geography', 6),
('Which US state contains the only active diamond mine open to the public in North America?',
 ARRAY['Arkansas','Colorado','North Carolina','Montana'],
 'Arkansas', 'Geography', 6),
('What is the name of the vast underwater canyon off the California coast that rivals the Grand Canyon in size?',
 ARRAY['Monterey Canyon','La Jolla Canyon','Redondo Canyon','Hueneme Canyon'],
 'Monterey Canyon', 'Geography', 6),
('The Boundary Waters Canoe Area Wilderness is located in which US state?',
 ARRAY['Minnesota','Wisconsin','Michigan','Maine'],
 'Minnesota', 'Geography', 6),
('Which US state contains the Mariana Trench, the deepest point on Earth?',
 ARRAY['Northern Mariana Islands','Guam','American Samoa','Hawaii'],
 'Northern Mariana Islands', 'Geography', 6),
('The Exxon Valdez oil spill of 1989 occurred in which Alaskan body of water?',
 ARRAY['Prince William Sound','Cook Inlet','Bristol Bay','Resurrection Bay'],
 'Prince William Sound', 'Geography', 6),
('Which US state is home to the Haleakala, the world''s largest dormant volcano by volume?',
 ARRAY['Hawaii','Alaska','California','Washington'],
 'Hawaii', 'Geography', 6),
('What ancient inland sea left chalk bed formations across Kansas?',
 ARRAY['Western Interior Seaway','Tethys Sea','Sundance Sea','Zuni Sea'],
 'Western Interior Seaway', 'Geography', 7),
('Which US state is considered farthest from any ocean coastline among the contiguous 48?',
 ARRAY['South Dakota','Kansas','Nebraska','Wyoming'],
 'South Dakota', 'Geography', 7),
('What is the name of the volcanic chain in the Pacific Ocean that includes the Hawaiian Islands?',
 ARRAY['Emperor Seamount Chain','Hawaiian-Emperor Seamount Chain','Pacific Ring of Fire','Aleutian Arc'],
 'Hawaiian-Emperor Seamount Chain', 'Geography', 7),
('Which US state has more federally protected land than any other state?',
 ARRAY['Alaska','California','Nevada','Utah'],
 'Alaska', 'Geography', 7),
('The Juan de Fuca Ridge, an active underwater volcanic zone, lies off the coast of which US state?',
 ARRAY['Oregon','California','Washington','Alaska'],
 'Oregon', 'Geography', 7),
('What is the name of the ancient lake whose desiccated remnant is the Great Salt Lake?',
 ARRAY['Lake Bonneville','Lake Lahontan','Lake Agassiz','Lake Missoula'],
 'Lake Bonneville', 'Geography', 7),
('Which river flowing through Idaho is the largest tributary of the Columbia River?',
 ARRAY['Snake River','Clearwater River','Salmon River','Boise River'],
 'Snake River', 'Geography', 7),
('At what Illinois city do the Ohio and Mississippi Rivers meet?',
 ARRAY['Cairo','Metropolis','Cape Girardeau','Quincy'],
 'Cairo', 'Geography', 7),
('What is the name of the isolated mountain range in the Michigan Upper Peninsula that predates the Appalachians?',
 ARRAY['Porcupine Mountains','Huron Mountains','Gogebic Range','Marquette Range'],
 'Porcupine Mountains', 'Geography', 8),
('What is the name of the supervolcano caldera located beneath Yellowstone National Park?',
 ARRAY['Yellowstone Caldera','Huckleberry Ridge Caldera','Island Park Caldera','Henry''s Fork Caldera'],
 'Yellowstone Caldera', 'Geography', 8),
('The Great Sand Dunes National Park, home to North America''s tallest sand dunes, is located in which US state?',
 ARRAY['Colorado','New Mexico','Arizona','Utah'],
 'Colorado', 'Geography', 8),
('Which US state is home to the Edwards Aquifer, the primary water source for San Antonio?',
 ARRAY['Texas','Oklahoma','New Mexico','Arkansas'],
 'Texas', 'Geography', 8),
('What is the name of the underwater tectonic boundary off the California coast responsible for major earthquakes?',
 ARRAY['San Andreas Fault','Cascadia Subduction Zone','Hayward Fault','Newport-Inglewood Fault'],
 'San Andreas Fault', 'Geography', 8),
('Which river in Montana is known as the "Missouri Breaks" where it cuts through rugged badlands?',
 ARRAY['Missouri River','Milk River','Musselshell River','Yellowstone River'],
 'Missouri River', 'Geography', 8),
('What is the name of the glacial fjord in Alaska where the Exxon Valdez disaster occurred?',
 ARRAY['Prince William Sound','Resurrection Bay','Yakutat Bay','Glacier Bay'],
 'Prince William Sound', 'Geography', 8),
('Which Alaskan island chain stretches 1,200 miles into the Pacific and Bering Sea?',
 ARRAY['Aleutian Islands','Kodiak Archipelago','Alexander Archipelago','Pribilof Islands'],
 'Aleutian Islands', 'Geography', 9),
('What is the name of the submarine ridge connecting Alaska to Russia that was once a land bridge?',
 ARRAY['Beringia','Bering Land Bridge','Chukchi Shelf','Anadyr Ridge'],
 'Beringia', 'Geography', 9),
('The Piedmont region of the eastern US is geographically situated between which two areas?',
 ARRAY['Appalachian Mountains and Atlantic Coastal Plain','Blue Ridge Mountains and Great Valley','Cumberland Plateau and Ridge and Valley','Great Valley and Atlantic Coastal Plain'],
 'Appalachian Mountains and Atlantic Coastal Plain', 'Geography', 9),
('What glacial feature explains the absence of glacial deposits across the Driftless Area of Wisconsin and surrounding states?',
 ARRAY['Ice lobe geometry and pre-existing topography','Permafrost barrier','Proximity to the Great Lakes','Higher elevation'],
 'Ice lobe geometry and pre-existing topography', 'Geography', 9),
('The Mississippi-Missouri River system drains approximately what percentage of the continental US?',
 ARRAY['40%','25%','55%','30%'],
 '40%', 'Geography', 9),
('Which range of undersea mountains off Hawaii continues northwest to the Aleutian Trench?',
 ARRAY['Emperor Seamount Chain','Hawaiian Ridge','Hess Rise','Shatsky Rise'],
 'Emperor Seamount Chain', 'Geography', 9),
('What is the name of the geological process that formed Crater Lake in Oregon from Mount Mazama?',
 ARRAY['Caldera collapse','Shield volcano eruption','Maar formation','Lava dome collapse'],
 'Caldera collapse', 'Geography', 9);

-- Landmarks (59 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What famous Philadelphia landmark was rung to celebrate the first public reading of the Declaration of Independence?',
 ARRAY['Liberty Bell','Independence Hall Bell','Carpenters'' Hall Bell','Christ Church Bell'],
 'Liberty Bell', 'Landmarks', 1),
('In which US city is the Golden Gate Bridge located?',
 ARRAY['San Francisco','Los Angeles','Seattle','Portland'],
 'San Francisco', 'Landmarks', 1),
('Which national monument features the carved faces of four presidents?',
 ARRAY['Mount Rushmore','Crazy Horse Memorial','Stone Mountain','Lincoln Memorial'],
 'Mount Rushmore', 'Landmarks', 1),
('What famous arch in St. Louis is a monument to westward expansion?',
 ARRAY['Gateway Arch','Freedom Arch','Westward Arch','St. Louis Arch'],
 'Gateway Arch', 'Landmarks', 1),
('What is the name of the famous concert venue built into red rocks near Denver, Colorado?',
 ARRAY['Red Rocks Amphitheatre','Garden of the Gods Amphitheatre','Folsom Field','Fiddler''s Green'],
 'Red Rocks Amphitheatre', 'Landmarks', 1),
('Which famous US landmark was a gift from France?',
 ARRAY['Statue of Liberty','Brooklyn Bridge','Lincoln Memorial','Washington Monument'],
 'Statue of Liberty', 'Landmarks', 1),
('What is the name of the famous boardwalk amusement area in New Jersey?',
 ARRAY['Atlantic City Boardwalk','Ocean City Boardwalk','Asbury Park Boardwalk','Wildwood Boardwalk'],
 'Atlantic City Boardwalk', 'Landmarks', 1),
('Which famous clock tower is located atop Philadelphia''s City Hall?',
 ARRAY['William Penn statue','Independence Hall Tower','Old City Clock','Founders'' Tower'],
 'William Penn statue', 'Landmarks', 1),
('What famous road stretches from Chicago to Santa Monica, California?',
 ARRAY['Route 66','Highway 1','US-40','US-30'],
 'Route 66', 'Landmarks', 1),
('Where is the National Mall located?',
 ARRAY['Washington, D.C.','Philadelphia','New York City','Richmond, Virginia'],
 'Washington, D.C.', 'Landmarks', 1),
('Which famous cave system is located in New Mexico?',
 ARRAY['Carlsbad Caverns','Mammoth Cave','Luray Caverns','Wind Cave'],
 'Carlsbad Caverns', 'Landmarks', 1),
('What is the name of the famous lighthouse at the tip of Cape Cod?',
 ARRAY['Race Point Light','Highland Light','Nauset Light','Wood End Light'],
 'Race Point Light', 'Landmarks', 1),
('In which city is Graceland, Elvis Presley''s home, located?',
 ARRAY['Memphis','Nashville','Tupelo','Jackson'],
 'Memphis', 'Landmarks', 1),
('What is the name of the famous steel bean sculpture in Chicago''s Millennium Park?',
 ARRAY['Cloud Gate','The Bean','Silver Bean','Reflective Bean'],
 'Cloud Gate', 'Landmarks', 1),
('What is the name of the historic mansion built by George Vanderbilt in Asheville, North Carolina?',
 ARRAY['Biltmore Estate','Marble House','The Breakers','Oheka Castle'],
 'Biltmore Estate', 'Landmarks', 4),
('Which historic fort in Charleston Harbor was the site of the first shots of the Civil War?',
 ARRAY['Fort Sumter','Fort Moultrie','Fort Johnson','Castle Pinckney'],
 'Fort Sumter', 'Landmarks', 4),
('What is the name of the house designed by Frank Lloyd Wright that is built over a waterfall in Pennsylvania?',
 ARRAY['Fallingwater','Wingspread','Taliesin','Kentuck Knob'],
 'Fallingwater', 'Landmarks', 4),
('Which cathedral in New York City is the largest Gothic cathedral in the world?',
 ARRAY['Cathedral of Saint John the Divine','Saint Patrick''s Cathedral','Trinity Church','Riverside Church'],
 'Cathedral of Saint John the Divine', 'Landmarks', 4),
('What is the name of the Victorian row houses famously photographed against the San Francisco skyline?',
 ARRAY['Painted Ladies','Rainbow Row','Seven Sisters','Alamo Square Victorians'],
 'Painted Ladies', 'Landmarks', 4),
('Which tower in New York was the world''s tallest building briefly in 1930?',
 ARRAY['Chrysler Building','Empire State Building','40 Wall Street','Woolworth Building'],
 'Chrysler Building', 'Landmarks', 4),
('Where is the National Civil Rights Museum located?',
 ARRAY['Memphis, Tennessee','Birmingham, Alabama','Montgomery, Alabama','Atlanta, Georgia'],
 'Memphis, Tennessee', 'Landmarks', 4),
('Which historic building in Boston, built in 1742, served as a marketplace and town meeting hall?',
 ARRAY['Faneuil Hall','Old State House','Old South Meeting House','Paul Revere House'],
 'Faneuil Hall', 'Landmarks', 4),
('What is the name of the massive pre-Columbian earthwork mounds complex located near St. Louis, Illinois?',
 ARRAY['Cahokia Mounds','Hopewell Mounds','Serpent Mound','Poverty Point'],
 'Cahokia Mounds', 'Landmarks', 4),
('Which famous lighthouse guards the entrance to Portland Harbor in Maine?',
 ARRAY['Portland Head Light','Cape Elizabeth Light','Pemaquid Point Light','Owl''s Head Light'],
 'Portland Head Light', 'Landmarks', 4),
('What is the name of the ornate concert hall designed by Frank Gehry in Los Angeles?',
 ARRAY['Walt Disney Concert Hall','Hollywood Bowl','Dolby Theatre','Ahmanson Theatre'],
 'Walt Disney Concert Hall', 'Landmarks', 4),
('Which South Dakota monument depicts a Lakota warrior on horseback and has been under construction since 1948?',
 ARRAY['Crazy Horse Memorial','Sitting Bull Monument','Chief Gall Memorial','Wounded Knee Memorial'],
 'Crazy Horse Memorial', 'Landmarks', 4),
('What is the name of the famous hotel in San Antonio that opened in 1859 and is one of the oldest hotels in Texas?',
 ARRAY['Menger Hotel','St. Anthony Hotel','Emily Morgan Hotel','Gunter Hotel'],
 'Menger Hotel', 'Landmarks', 4),
('Which New York building was nicknamed the "Cathedral of Commerce" when completed in 1913?',
 ARRAY['Woolworth Building','Flatiron Building','Singer Building','Metropolitan Life Tower'],
 'Woolworth Building', 'Landmarks', 4),
('What is the name of the unusual corn-decorated building in Mitchell, South Dakota?',
 ARRAY['Corn Palace','Corn Castle','Grain Palace','Prairie Palace'],
 'Corn Palace', 'Landmarks', 4),
('Which Newport, Rhode Island mansion was built for William Kissam Vanderbilt and features an Italian marble entrance hall?',
 ARRAY['Marble House','The Breakers','Belcourt Castle','Rough Point'],
 'Marble House', 'Landmarks', 4),
('What is the name of the famous Beaux-Arts train station in Washington, D.C.?',
 ARRAY['Union Station','Penn Station','Grand Central Terminal','L''Enfant Plaza'],
 'Union Station', 'Landmarks', 5),
('Which historic palace in San Francisco was built for the 1915 Panama-Pacific International Exposition?',
 ARRAY['Palace of Fine Arts','Civic Center','Ferry Building','Conservatory of Flowers'],
 'Palace of Fine Arts', 'Landmarks', 5),
('What is the name of the twin apartment towers on Lake Shore Drive in Chicago designed by Mies van der Rohe?',
 ARRAY['860-880 Lake Shore Drive','John Hancock Center','Marina City','Lake Point Tower'],
 '860-880 Lake Shore Drive', 'Landmarks', 5),
('Which Chicago skyscraper, completed in 1885, is considered the world''s first skyscraper?',
 ARRAY['Home Insurance Building','Rookery Building','Monadnock Building','Reliance Building'],
 'Home Insurance Building', 'Landmarks', 6),
('What is the name of the mosaic tower art installation in Los Angeles built by an Italian immigrant over 33 years?',
 ARRAY['Watts Towers','Grand Central Market','Museum of Jurassic Technology','Bradbury Building'],
 'Watts Towers', 'Landmarks', 6),
('Which Vermont museum is famous for its collection of American folk art and circus artifacts?',
 ARRAY['Shelburne Museum','Bennington Museum','Norman Rockwell Museum','Currier Museum'],
 'Shelburne Museum', 'Landmarks', 6),
('What is the name of the historic canal that connected the Hudson River to the Great Lakes, completed in 1825?',
 ARRAY['Erie Canal','Chesapeake and Ohio Canal','Illinois and Michigan Canal','Delaware and Raritan Canal'],
 'Erie Canal', 'Landmarks', 6),
('Which famous bridge in Boston is nicknamed "the salt-and-pepper shakers" for its distinctive towers?',
 ARRAY['Longfellow Bridge','Zakim Bridge','Harvard Bridge','Anderson Memorial Bridge'],
 'Longfellow Bridge', 'Landmarks', 6),
('What is the name of the Theodore Roosevelt''s first national monument, designated in 1906?',
 ARRAY['Devils Tower','Petrified Forest','Muir Woods','Montezuma Castle'],
 'Devils Tower', 'Landmarks', 6),
('Which historic Natchez, Mississippi mansion features a unique combination of Greek Revival and Moorish Revival architecture?',
 ARRAY['Longwood','Stanton Hall','Dunleith','Monmouth'],
 'Longwood', 'Landmarks', 6),
('What is the name of the house in Lenox, Massachusetts where novelist Edith Wharton lived and wrote?',
 ARRAY['The Mount','Naumkeag','Chesterwood','Tanglewood'],
 'The Mount', 'Landmarks', 6),
('Which Chicago newspaper tower was designed by John Mead Howells and Raymond Hood, winning a 1922 international competition?',
 ARRAY['Tribune Tower','Wrigley Building','Merchandise Mart','Palmolive Building'],
 'Tribune Tower', 'Landmarks', 7),
('What is the name of the famous Colorado fur trading post restored as a national historic site near La Junta?',
 ARRAY['Bent''s Old Fort','Fort Garland','Fort Pueblo','Fort Massachusetts'],
 'Bent''s Old Fort', 'Landmarks', 7),
('Which Civil War cemetery in Pennsylvania was dedicated by Abraham Lincoln in his famous address?',
 ARRAY['Soldiers'' National Cemetery','Arlington National Cemetery','Antietam National Cemetery','Fredericksburg National Cemetery'],
 'Soldiers'' National Cemetery', 'Landmarks', 7),
('What is the name of the famous Birmingham church bombed in 1963, killing four young girls?',
 ARRAY['16th Street Baptist Church','Dexter Avenue Baptist Church','Ebenezer Baptist Church','First Baptist Church of Montgomery'],
 '16th Street Baptist Church', 'Landmarks', 7),
('Which Alabama church on Dexter Avenue was the congregation of Dr. Martin Luther King Jr. during the Montgomery Bus Boycott?',
 ARRAY['Dexter Avenue King Memorial Baptist Church','First Baptist Church','Ebenezer Baptist Church','St. Paul AME Church'],
 'Dexter Avenue King Memorial Baptist Church', 'Landmarks', 7),
('What is the name of the San Francisco mansion museum with Italianate gardens located in Miami, built by industrialist James Deering?',
 ARRAY['Vizcaya Museum and Gardens','Flagler Museum','Ringling Museum','Whitehall'],
 'Vizcaya Museum and Gardens', 'Landmarks', 7),
('Which San Francisco bay island served as a federal penitentiary from 1934 to 1963?',
 ARRAY['Alcatraz','Angel Island','Treasure Island','Yerba Buena Island'],
 'Alcatraz', 'Landmarks', 7),
('What is the name of the famous Pasadena, California museum founded in 1969 housing a major collection of British and American art?',
 ARRAY['Huntington Library and Art Museum','Norton Simon Museum','Getty Center','Pasadena Museum of California Art'],
 'Huntington Library and Art Museum', 'Landmarks', 8),
('What is the name of the Georgia sea island plantation that became a major Civil War contraband camp and freedmen''s settlement?',
 ARRAY['St. Simons Island','Jekyll Island','Cumberland Island','Ossabaw Island'],
 'St. Simons Island', 'Landmarks', 8),
('Which Federal-style lighthouse, built in 1791, is the oldest still-standing lighthouse on the West Coast?',
 ARRAY['Cape Disappointment Light','Umpqua River Light','Yaquina Bay Light','Yaquina Head Light'],
 'Cape Disappointment Light', 'Landmarks', 8),
('What is the name of the 1,063-foot tall observation tower completed in 1976 in Seattle that hosted the World''s Fair in 1962?',
 ARRAY['Space Needle','Columbia Center','Smith Tower','Rainier Tower'],
 'Space Needle', 'Landmarks', 8),
('Which New Orleans building complex, originally built in 1813, is the oldest continuously operating street market in the United States?',
 ARRAY['French Market','Jackson Brewery','Riverwalk Marketplace','Jax Brewery'],
 'French Market', 'Landmarks', 8),
('What is the name of the architect who designed Fallingwater, the Guggenheim Museum, and the Marin County Civic Center?',
 ARRAY['Frank Lloyd Wright','Louis Sullivan','Walter Gropius','Philip Johnson'],
 'Frank Lloyd Wright', 'Landmarks', 9),
('Which famous Washington, D.C. memorial designed by Maya Lin was dedicated in 1982?',
 ARRAY['Vietnam Veterans Memorial','Korean War Veterans Memorial','World War II Memorial','National Law Enforcement Officers Memorial'],
 'Vietnam Veterans Memorial', 'Landmarks', 9),
('What is the name of the first national park established in the United States, created in 1872?',
 ARRAY['Yellowstone','Yosemite','Sequoia','Grand Canyon'],
 'Yellowstone', 'Landmarks', 9),
('Which landmark church on Boston''s Freedom Trail, built in 1723, is where Paul Revere arranged the lantern signal for his midnight ride?',
 ARRAY['Old North Church','Park Street Church','King''s Chapel','Old South Meeting House'],
 'Old North Church', 'Landmarks', 9),
('What is the name of the historic bridge in Concord, Massachusetts that was the site of "the shot heard round the world"?',
 ARRAY['North Bridge','Old Bridge','Liberty Bridge','Patriot''s Bridge'],
 'North Bridge', 'Landmarks', 9),
('Which iconic building completed in 1902 is shaped like a flatiron and stands at the intersection of Fifth Avenue and Broadway in New York?',
 ARRAY['Flatiron Building','Fuller Building','Times Square Tower','Herald Square Building'],
 'Flatiron Building', 'Landmarks', 9);

-- National Parks (50 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which national park is located in the state of Wyoming and is known for its geysers and hot springs?',
 ARRAY['Grand Teton','Glacier','Yellowstone','Bryce Canyon'],
 'Yellowstone', 'National Parks', 1),
('What is the name of the national park in Arizona known for its massive, colorful gorge carved by the Colorado River?',
 ARRAY['Bryce Canyon','Zion','Grand Canyon','Petrified Forest'],
 'Grand Canyon', 'National Parks', 1),
('Which national park in Maine is the only national park in the northeastern United States?',
 ARRAY['White Mountain','Cape Cod','Acadia','Shenandoah'],
 'Acadia', 'National Parks', 1),
('What is the name of the national park in Alaska that contains the highest peak in North America?',
 ARRAY['Wrangell-St. Elias','Katmai','Kenai Fjords','Denali'],
 'Denali', 'National Parks', 1),
('Which national park in California is home to the world''s tallest trees?',
 ARRAY['Sequoia','Kings Canyon','Yosemite','Redwood'],
 'Redwood', 'National Parks', 1),
('What is the name of the national park straddling the border of North Carolina and Tennessee?',
 ARRAY['Shenandoah','Blue Ridge','Great Smoky Mountains','Appalachian'],
 'Great Smoky Mountains', 'National Parks', 1),
('Which national park in Utah is known for its thousands of natural stone arches?',
 ARRAY['Canyonlands','Bryce Canyon','Capitol Reef','Arches'],
 'Arches', 'National Parks', 1),
('What is the name of the national park in Colorado known for ancient Native American cliff dwellings?',
 ARRAY['Black Canyon of the Gunnison','Colorado','Great Sand Dunes','Mesa Verde'],
 'Mesa Verde', 'National Parks', 1),
('Which national park in Florida protects a vast subtropical wetland ecosystem?',
 ARRAY['Biscayne','Big Cypress','Dry Tortugas','Everglades'],
 'Everglades', 'National Parks', 1),
('What is the name of the national park in South Dakota known for its dramatic eroded buttes and pinnacles?',
 ARRAY['Wind Cave','Jewel Cave','Badlands','Theodore Roosevelt'],
 'Badlands', 'National Parks', 1),
('Which national park in Oregon contains the deepest lake in the United States?',
 ARRAY['Mount Rainier','Olympic','North Cascades','Crater Lake'],
 'Crater Lake', 'National Parks', 1),
('What is the name of the national park in Virginia known for its scenic drive along the crest of the Blue Ridge Mountains?',
 ARRAY['Appalachian Trail','Blue Ridge Parkway','Shenandoah','New River Gorge'],
 'Shenandoah', 'National Parks', 1),
('Which national park in California''s Sierra Nevada range is known for its giant sequoia trees and glaciated valleys?',
 ARRAY['Kings Canyon','Redwood','Lassen Volcanic','Yosemite'],
 'Yosemite', 'National Parks', 1),
('What is the name of the national park in Wyoming adjacent to Yellowstone, known for its dramatic mountain peaks?',
 ARRAY['Glacier','Wind River','Bighorn','Grand Teton'],
 'Grand Teton', 'National Parks', 1),
('Which national park in Montana is known as the "Crown of the Continent" and shares a border with a Canadian park?',
 ARRAY['Theodore Roosevelt','Glacier','Badlands','Voyageurs'],
 'Glacier', 'National Parks', 1),
('What is the name of the national park in Hawaii known for its active shield volcanoes?',
 ARRAY['Haleakala','Kalaupapa','Hawaii Volcanoes','Puuhonua'],
 'Hawaii Volcanoes', 'National Parks', 1),
('Which national park in New Mexico is famous for its massive cavern system and large bat colony?',
 ARRAY['White Sands','Guadalupe Mountains','Chaco Culture','Carlsbad Caverns'],
 'Carlsbad Caverns', 'National Parks', 1),
('What is the name of the national park in Utah known for its colorful, eroded canyon walls and hoodoos — irregularly shaped rock formations?',
 ARRAY['Capitol Reef','Zion','Canyonlands','Bryce Canyon'],
 'Bryce Canyon', 'National Parks', 4),
('Which national park spans the border of Idaho, Montana, and Wyoming, and was established as the first national park in 1872?',
 ARRAY['Glacier','Grand Teton','Rocky Mountain','Yellowstone'],
 'Yellowstone', 'National Parks', 4),
('What is the name of the national park in Washington State known for its temperate rainforest, glaciated mountains, and rugged coastline?',
 ARRAY['Mount Rainier','North Cascades','Olympic','San Juan Islands'],
 'Olympic', 'National Parks', 4),
('Which national park in West Virginia, added to the system in 2020, features one of the oldest rivers in North America?',
 ARRAY['Harpers Ferry','Shenandoah','New River Gorge','Gauley River'],
 'New River Gorge', 'National Parks', 4),
('What is the name of the national park in California''s Mojave Desert known for its unique Joshua trees?',
 ARRAY['Mojave','Death Valley','Channel Islands','Joshua Tree'],
 'Joshua Tree', 'National Parks', 4),
('Which national park in Nevada is known for its ancient bristlecone pines, considered some of the oldest living organisms on Earth?',
 ARRAY['Lake Mead','Great Basin','Ruby Mountains','Valley of Fire'],
 'Great Basin', 'National Parks', 4),
('What is the name of the national park in Texas that borders Mexico and is known for its deep canyons and diverse ecosystem?',
 ARRAY['Guadalupe Mountains','Padre Island','Big Bend','Palo Duro'],
 'Big Bend', 'National Parks', 4),
('Which national park in South Carolina protects the largest intact old-growth bottomland hardwood forest in the Southeast?',
 ARRAY['Cowpens','Kings Mountain','Congaree','Hunting Island'],
 'Congaree', 'National Parks', 4),
('What is the name of the national park in Alaska that contains the Valley of Ten Thousand Smokes, formed after a massive 1912 volcanic eruption?',
 ARRAY['Lake Clark','Wrangell-St. Elias','Kenai Fjords','Katmai'],
 'Katmai', 'National Parks', 4),
('Which national park in Michigan, located on Lake Superior, is known for its wolves, moose, and long-running predator-prey research study?',
 ARRAY['Pictured Rocks','Sleeping Bear Dunes','Isle Royale','Apostle Islands'],
 'Isle Royale', 'National Parks', 4),
('What is the name of the national park in California that contains the lowest point in North America at 282 feet below sea level?',
 ARRAY['Joshua Tree','Mojave','Channel Islands','Death Valley'],
 'Death Valley', 'National Parks', 4),
('Which national park in Colorado is named for its towering sand dunes, the tallest in North America, set against the Sangre de Cristo Mountains?',
 ARRAY['Rocky Mountain','Mesa Verde','Black Canyon of the Gunnison','Great Sand Dunes'],
 'Great Sand Dunes', 'National Parks', 4),
('What is the name of the national park in Washington State known for its active stratovolcano and glaciers, nicknamed the "Mountain"?',
 ARRAY['North Cascades','Olympic','Rainier','Mount St. Helens'],
 'Rainier', 'National Parks', 4),
('Which national park in Wisconsin is comprised of 21 islands and sea caves along the shores of Lake Superior?',
 ARRAY['Pictured Rocks','Apostle Islands','Sleeping Bear Dunes','Isle Royale'],
 'Apostle Islands', 'National Parks', 4),
('What is the name of the national park in Utah that features the Waterpocket Fold, a nearly 100-mile-long wrinkle in the Earth''s crust?',
 ARRAY['Arches','Canyonlands','Zion','Capitol Reef'],
 'Capitol Reef', 'National Parks', 4),
('Which national park in Idaho features one of the largest basalt lava fields in the contiguous United States, with craters and lava tubes?',
 ARRAY['Sawtooth','City of Rocks','Craters of the Moon','Snake River'],
 'Craters of the Moon', 'National Parks', 4),
('What is the name of the national park in Alaska, the largest in the United States at 13.2 million acres, encompassing nine of the sixteen highest peaks in the country?',
 ARRAY['Denali','Glacier Bay','Lake Clark','Wrangell-St. Elias'],
 'Wrangell-St. Elias', 'National Parks', 4),
('Which national park in Florida consists of 95 percent underwater, protecting coral reefs and a chain of small islands?',
 ARRAY['Everglades','Dry Tortugas','Biscayne','Big Cypress'],
 'Biscayne', 'National Parks', 4),
('What is the name of the national park in North Dakota that was a favorite retreat of President Theodore Roosevelt and preserves the region''s badlands?',
 ARRAY['Wind Cave','Badlands','Theodore Roosevelt','Jewel Cave'],
 'Theodore Roosevelt', 'National Parks', 7),
('Which national park in Alaska is located north of the Arctic Circle and contains one of the largest active sand dune fields in the Arctic?',
 ARRAY['Gates of the Arctic','Noatak','Bering Land Bridge','Kobuk Valley'],
 'Kobuk Valley', 'National Parks', 7),
('What is the name of the national park in California that protects the remnants of an ancient volcanic eruption, including a condor sanctuary?',
 ARRAY['Lassen Volcanic','Mojave','Channel Islands','Pinnacles'],
 'Pinnacles', 'National Parks', 7),
('Which national park in Washington State is known as the "American Alps" and contains the most glaciated terrain in the lower 48 states?',
 ARRAY['Olympic','Rainier','North Cascades','Glacier'],
 'North Cascades', 'National Parks', 7),
('What is the name of the national park in Alaska that contains Glacier Bay, a UNESCO World Heritage Site with over 1,000 glaciers?',
 ARRAY['Kenai Fjords','Wrangell-St. Elias','Glacier Bay','Katmai'],
 'Glacier Bay', 'National Parks', 7),
('Which national park in Colorado features a steep-walled canyon carved by the Gunnison River, with walls so dark they inspired the park''s name?',
 ARRAY['Great Sand Dunes','Mesa Verde','Rocky Mountain','Black Canyon of the Gunnison'],
 'Black Canyon of the Gunnison', 'National Parks', 7),
('What is the name of the national park in Ohio that protects the Cuyahoga River valley, known for its role in inspiring the environmental movement after the river famously caught fire?',
 ARRAY['Hopewell Culture','Perry''s Victory','Cuyahoga Valley','First Ladies'],
 'Cuyahoga Valley', 'National Parks', 7),
('Which national park in California consists of five islands off the coast of Santa Barbara, nicknamed the "Galapagos of North America"?',
 ARRAY['Point Reyes','Cabrillo','Channel Islands','Golden Gate'],
 'Channel Islands', 'National Parks', 7),
('What is the name of the national park in Arizona that preserves a 225-million-year-old fossilized forest buried in volcanic ash?',
 ARRAY['Saguaro','Grand Canyon','Tonto','Petrified Forest'],
 'Petrified Forest', 'National Parks', 7),
('Which national park in Kentucky contains the longest known cave system in the world, with over 400 miles of surveyed passages?',
 ARRAY['Carter Caves','Red River Gorge','Cave Run Lake','Mammoth Cave'],
 'Mammoth Cave', 'National Parks', 7),
('What is the name of the national park in Arizona that protects the giant saguaro cactus, the largest cactus in the United States?',
 ARRAY['Organ Pipe Cactus','Chiricahua','Tonto','Saguaro'],
 'Saguaro', 'National Parks', 7),
('Which national park in the U.S. Virgin Islands has two-thirds of its land protected as a national park, the highest proportion of any U.S. territory?',
 ARRAY['Buck Island Reef','Salt River Bay','Virgin Islands','Christiansted'],
 'Virgin Islands', 'National Parks', 7),
('What is the name of the national park in California''s volcanic Cascade Range known for its lava beds, cinder cones, and hydrothermal features?',
 ARRAY['Mojave','Pinnacles','Muir Woods','Lassen Volcanic'],
 'Lassen Volcanic', 'National Parks', 7),
('Which national park in New Mexico and Texas features the highest point in Texas and protects the geological remnants of an ancient marine reef?',
 ARRAY['Big Bend','Carlsbad Caverns','White Sands','Guadalupe Mountains'],
 'Guadalupe Mountains', 'National Parks', 7),
('What is the name of the national park straddling the U.S.-Canada border in Montana and Alberta, established as the first international peace park in 1932?',
 ARRAY['Glacier','Boundary Waters','Waterton-Glacier','North Cascades'],
 'Waterton-Glacier', 'National Parks', 7);

-- US History (44 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which war was fought between the Northern and Southern states of the United States from 1861 to 1865?',
 ARRAY['Revolutionary War','War of 1812','Civil War','Spanish-American War'],
 'Civil War', 'US History', 1),
('What major event triggered the Great Depression in the United States?',
 ARRAY['World War I','The Dust Bowl','Stock market crash of 1929','Bank holiday of 1933'],
 'Stock market crash of 1929', 'US History', 1),
('Which treaty ended the American Revolution and recognized U.S. independence?',
 ARRAY['Treaty of Ghent','Treaty of Paris 1783','Jay Treaty','Treaty of Versailles'],
 'Treaty of Paris 1783', 'US History', 1),
('What was the name of the first permanent English settlement in America, founded in 1607?',
 ARRAY['Plymouth','Roanoke','Jamestown','St. Augustine'],
 'Jamestown', 'US History', 1),
('Which state was the last of the original 13 colonies to ratify the Constitution?',
 ARRAY['Virginia','New York','Georgia','Rhode Island'],
 'Rhode Island', 'US History', 1),
('What was the name of the financial panic of 1837 that caused widespread bank failures and economic hardship?',
 ARRAY['Panic of 1819','Panic of 1837','Panic of 1857','Panic of 1873'],
 'Panic of 1837', 'US History', 1),
('Which battle is considered the turning point of the American Civil War?',
 ARRAY['Battle of Antietam','Battle of Bull Run','Battle of Gettysburg','Battle of Shiloh'],
 'Battle of Gettysburg', 'US History', 1),
('Who was the U.S. president during World War II?',
 ARRAY['Herbert Hoover','Harry S. Truman','Dwight Eisenhower','Franklin D. Roosevelt'],
 'Franklin D. Roosevelt', 'US History', 1),
('Which Native American leader led the Sioux at the Battle of Little Bighorn in 1876?',
 ARRAY['Geronimo','Crazy Horse','Red Cloud','Sitting Bull'],
 'Sitting Bull', 'US History', 1),
('What program, established in 1944, provided veterans with benefits including low-cost mortgages and college tuition?',
 ARRAY['New Deal','Fair Deal','GI Bill','Marshall Plan'],
 'GI Bill', 'US History', 1),
('Which American abolitionist and former slave wrote the autobiography "Narrative of the Life of Frederick Douglass"?',
 ARRAY['Harriet Tubman','Sojourner Truth','Frederick Douglass','Nat Turner'],
 'Frederick Douglass', 'US History', 1),
('What was the name of the massacre of Lakota Sioux by U.S. Army troops in 1890?',
 ARRAY['Battle of Little Bighorn','Sand Creek Massacre','Wounded Knee Massacre','Bear River Massacre'],
 'Wounded Knee Massacre', 'US History', 1),
('Which agreement, signed in 1848, ended the Mexican-American War and ceded vast territories to the United States?',
 ARRAY['Treaty of Guadalupe Hidalgo','Treaty of Paris','Gadsden Purchase','Treaty of Cahuenga'],
 'Treaty of Guadalupe Hidalgo', 'US History', 4),
('What was the name of the 1919 racial violence that swept the United States, killing hundreds of African Americans?',
 ARRAY['Detroit Race Riots','Tulsa Race Massacre','Red Summer','Harlem Race Riot'],
 'Red Summer', 'US History', 4),
('Which senator from Wisconsin led the anti-Communist investigations of the early 1950s that became synonymous with political witch hunts?',
 ARRAY['Robert Taft','Barry Goldwater','Joseph McCarthy','Strom Thurmond'],
 'Joseph McCarthy', 'US History', 4),
('What was the name of President Johnson''s domestic program that aimed to eliminate poverty and racial injustice?',
 ARRAY['New Deal','New Frontier','Great Society','Fair Deal'],
 'Great Society', 'US History', 4),
('Which labor leader founded the United Farm Workers union and organized boycotts of California grapes in the 1960s?',
 ARRAY['Samuel Gompers','Eugene Debs','Cesar Chavez','A. Philip Randolph'],
 'Cesar Chavez', 'US History', 4),
('What was the name of the secret U.S. government program that conducted nuclear tests on Pacific Islands, displacing native Marshallese?',
 ARRAY['Operation Crossroads','Operation Castle','Project Sunshine','Operation Sandstone'],
 'Operation Castle', 'US History', 4),
('Which 1944 Supreme Court case upheld the forced relocation of Japanese Americans to internment camps?',
 ARRAY['Ex parte Milligan','Hirabayashi v. United States','Korematsu v. United States','Yasui v. United States'],
 'Korematsu v. United States', 'US History', 4),
('What term was used to describe the policy of strengthening allied nations against Soviet influence that President Truman announced in 1947?',
 ARRAY['Marshall Plan','Truman Doctrine','Containment Policy','Rollback Policy'],
 'Truman Doctrine', 'US History', 4),
('Which civil rights leader was assassinated at the Lorraine Motel in Memphis, Tennessee, in 1968?',
 ARRAY['Malcolm X','Medgar Evers','Martin Luther King Jr.','John Lewis'],
 'Martin Luther King Jr.', 'US History', 4),
('What was the name of the 1973 agreement that ended direct U.S. military involvement in Vietnam?',
 ARRAY['Geneva Accords','Paris Peace Accords','Hanoi Agreement','Saigon Treaty'],
 'Paris Peace Accords', 'US History', 4),
('Which U.S. senator from Vermont ran as a third-party Progressive candidate for president in 1924?',
 ARRAY['Robert La Follette','Eugene Debs','Norman Thomas','Henry Wallace'],
 'Robert La Follette', 'US History', 4),
('What was the name of the 1919 law enforcement raids targeting suspected radicals and anarchists?',
 ARRAY['Red Scare raids','Palmer Raids','Mitchell Raids','Hoover Raids'],
 'Palmer Raids', 'US History', 4),
('Which president signed the National Environmental Policy Act in 1970, requiring federal agencies to assess environmental impacts?',
 ARRAY['Lyndon B. Johnson','Richard Nixon','Gerald Ford','Jimmy Carter'],
 'Richard Nixon', 'US History', 4),
('What was the nickname for the 1948 effort to supply West Berlin by air after the Soviet Union blocked land access?',
 ARRAY['Berlin Airlift','Operation Vittles','Berlin Supply Mission','Operation Plainfare'],
 'Berlin Airlift', 'US History', 4),
('Which 1890 federal law was the first to prohibit monopolistic business practices in the United States?',
 ARRAY['Clayton Antitrust Act','Interstate Commerce Act','Sherman Antitrust Act','Federal Trade Commission Act'],
 'Sherman Antitrust Act', 'US History', 4),
('What was the name of the 1957 crisis in which President Eisenhower sent federal troops to enforce school desegregation in Arkansas?',
 ARRAY['Selma Crisis','Little Rock Crisis','Oxford Crisis','Birmingham Crisis'],
 'Little Rock Crisis', 'US History', 4),
('Which agreement between the U.S. and Soviet Union in 1987 eliminated an entire class of nuclear missiles?',
 ARRAY['SALT I','SALT II','INF Treaty','START Treaty'],
 'INF Treaty', 'US History', 4),
('What was the name of the 1963 nuclear test ban treaty signed by the U.S., Soviet Union, and United Kingdom?',
 ARRAY['Nuclear Non-Proliferation Treaty','Comprehensive Test Ban Treaty','Partial Nuclear Test Ban Treaty','Outer Space Treaty'],
 'Partial Nuclear Test Ban Treaty', 'US History', 7),
('Which Supreme Court case of 1905 struck down a New York law limiting bakers'' working hours, exemplifying the Lochner era?',
 ARRAY['Muller v. Oregon','Lochner v. New York','Adkins v. Children''s Hospital','West Coast Hotel v. Parrish'],
 'Lochner v. New York', 'US History', 7),
('What was the name of the secret CIA program that trained Cuban exiles to overthrow Fidel Castro, resulting in a failed 1961 invasion?',
 ARRAY['Operation Mongoose','Bay of Pigs invasion','Operation Zapata','Operation Pluto'],
 'Bay of Pigs invasion', 'US History', 7),
('Which industrial labor action in 1892 at a Carnegie Steel plant in Pennsylvania resulted in a violent confrontation between workers and Pinkerton agents?',
 ARRAY['Pullman Strike','Homestead Strike','Great Railroad Strike','Triangle Shirtwaist Strike'],
 'Homestead Strike', 'US History', 7),
('What was the name of the congressional resolution that gave President Johnson authority to escalate U.S. involvement in Vietnam?',
 ARRAY['War Powers Resolution','SEATO Resolution','Gulf of Tonkin Resolution','Eisenhower Doctrine'],
 'Gulf of Tonkin Resolution', 'US History', 7),
('Which 1918 legislation made it illegal to criticize the U.S. government, military, or flag during wartime?',
 ARRAY['Espionage Act','Alien Registration Act','Sedition Act of 1918','Smith Act'],
 'Sedition Act of 1918', 'US History', 7),
('What was the name of the 1862 federal law that granted public land to states to fund agricultural and mechanical colleges?',
 ARRAY['Homestead Act','Pacific Railroad Act','Morrill Act','Land Ordinance of 1785'],
 'Morrill Act', 'US History', 7),
('Which 1972 espionage operation led to a constitutional crisis and ultimately the resignation of President Nixon?',
 ARRAY['Pentagon Papers','Iran-Contra','Watergate','Teapot Dome'],
 'Watergate', 'US History', 7),
('What was the name of the first major U.S. labor strike of 1877, which paralyzed the nation''s railroad network?',
 ARRAY['Pullman Strike','Homestead Strike','Great Railroad Strike of 1877','Haymarket Strike'],
 'Great Railroad Strike of 1877', 'US History', 7),
('Which federal program, established in 1933 under the New Deal, built dams and provided electricity and flood control in the Tennessee Valley?',
 ARRAY['Rural Electrification Administration','Civilian Conservation Corps','Tennessee Valley Authority','Public Works Administration'],
 'Tennessee Valley Authority', 'US History', 7),
('What was the name of the 1932 protest march to Washington, D.C., by World War I veterans demanding early payment of a promised bonus?',
 ARRAY['Coxey''s Army','Bonus Army','Veterans'' March','Hooverville Protest'],
 'Bonus Army', 'US History', 7),
('Which landmark 1960s program created Medicare and Medicaid as part of President Johnson''s Great Society legislation?',
 ARRAY['Social Security Amendments of 1965','Economic Opportunity Act','Civil Rights Act of 1965','Housing Act of 1965'],
 'Social Security Amendments of 1965', 'US History', 7),
('What was the name of the federal agency created in 1908 that evolved into the modern FBI?',
 ARRAY['Secret Service','Bureau of Investigation','Federal Bureau of Investigation','Office of Strategic Services'],
 'Bureau of Investigation', 'US History', 7),
('Which 1954 Supreme Court decision overturned the "separate but equal" doctrine established in Plessy v. Ferguson?',
 ARRAY['Brown v. Board of Education','Sweatt v. Painter','McLaurin v. Oklahoma','Bolling v. Sharpe'],
 'Brown v. Board of Education', 'US History', 7),
('What was the name of the covert FBI program from 1956 to 1971 that surveilled and disrupted domestic political organizations?',
 ARRAY['Operation CHAOS','COINTELPRO','Operation GARDEN PLOT','MH/CHAOS'],
 'COINTELPRO', 'US History', 7);

-- US Sports (70 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which NHL team plays its home games at Madison Square Garden?',
 ARRAY['New York Rangers','New York Islanders','New Jersey Devils','Buffalo Sabres'],
 'New York Rangers', 'US Sports', 1),
('How many players are on the field for one team in American football?',
 ARRAY['11','9','10','12'],
 '11', 'US Sports', 1),
('Which city is home to the MLB team known as the Cubs?',
 ARRAY['Chicago','Detroit','Cleveland','St. Louis'],
 'Chicago', 'US Sports', 1),
('In basketball, how many points is a free throw worth?',
 ARRAY['1','2','3','4'],
 '1', 'US Sports', 1),
('Which sport uses a term called a "slam dunk"?',
 ARRAY['Basketball','Football','Baseball','Hockey'],
 'Basketball', 'US Sports', 1),
('The Indianapolis 500 is what type of race?',
 ARRAY['Open-wheel car race','Stock car race','Motorcycle race','Drag race'],
 'Open-wheel car race', 'US Sports', 1),
('Which US city hosts the annual Masters golf tournament?',
 ARRAY['Augusta, Georgia','Pebble Beach, California','Scottsdale, Arizona','Charlotte, North Carolina'],
 'Augusta, Georgia', 'US Sports', 1),
('What color jersey does the home team typically wear in the NFL?',
 ARRAY['The home team chooses its own colors','Always white','Always dark','Always red'],
 'The home team chooses its own colors', 'US Sports', 1),
('How many sets must a player win to claim victory in a standard men''s Grand Slam tennis match?',
 ARRAY['3','2','4','5'],
 '3', 'US Sports', 1),
('In baseball, how many balls result in a walk?',
 ARRAY['4','3','5','2'],
 '4', 'US Sports', 1),
('Which US city is home to the NFL team called the Seahawks?',
 ARRAY['Seattle','Portland','Tacoma','Spokane'],
 'Seattle', 'US Sports', 1),
('What shape is a boxing ring?',
 ARRAY['Square','Circle','Octagon','Triangle'],
 'Square', 'US Sports', 1),
('Which sport features a "penalty kick"?',
 ARRAY['Soccer','Hockey','Football','Basketball'],
 'Soccer', 'US Sports', 1),
('How many players are on a baseball team''s starting lineup?',
 ARRAY['9','10','8','11'],
 '9', 'US Sports', 1),
('What does "MVP" stand for in US sports?',
 ARRAY['Most Valuable Player','Most Versatile Player','Maximum Victory Points','Most Visited Player'],
 'Most Valuable Player', 'US Sports', 1),
('Which team competes in the American League East along with the Red Sox and Yankees?',
 ARRAY['Toronto Blue Jays','Chicago Cubs','St. Louis Cardinals','San Francisco Giants'],
 'Toronto Blue Jays', 'US Sports', 1),
('Who was the first woman to be inducted into the Pro Football Hall of Fame?',
 ARRAY['Jen Welter','Katie Sowers','Sarah Fuller','Becky Hammon'],
 'Jen Welter', 'US Sports', 4),
('Which MLB team plays its home games at Wrigley Field?',
 ARRAY['Chicago Cubs','Chicago White Sox','St. Louis Cardinals','Milwaukee Brewers'],
 'Chicago Cubs', 'US Sports', 4),
('What is the name of the trophy awarded to the winner of the NHL''s Eastern Conference?',
 ARRAY['Prince of Wales Trophy','Clarence S. Campbell Bowl','Conn Smythe Trophy','Presidents'' Trophy'],
 'Prince of Wales Trophy', 'US Sports', 4),
('Which city hosted the 1984 Summer Olympics in the United States?',
 ARRAY['Los Angeles','Atlanta','New York','Chicago'],
 'Los Angeles', 'US Sports', 4),
('Who holds the record for the most career strikeouts in MLB history?',
 ARRAY['Nolan Ryan','Randy Johnson','Roger Clemens','Bob Gibson'],
 'Nolan Ryan', 'US Sports', 4),
('Which driver won the first Daytona 500 in 1959?',
 ARRAY['Lee Petty','Richard Petty','Dale Earnhardt','Fireball Roberts'],
 'Lee Petty', 'US Sports', 4),
('What year did the AFL and NFL officially merge?',
 ARRAY['1970','1966','1972','1968'],
 '1970', 'US Sports', 4),
('Who was the first Black head coach to win the Super Bowl?',
 ARRAY['Tony Dungy','Mike Tomlin','Lovie Smith','Jim Caldwell'],
 'Tony Dungy', 'US Sports', 4),
('Which tennis player won the US Open six times in the Open Era before Serena Williams?',
 ARRAY['Pete Sampras','Jimmy Connors','John McEnroe','Andre Agassi'],
 'Pete Sampras', 'US Sports', 4),
('What is the name of the annual college football game played between Michigan and Ohio State?',
 ARRAY['The Game','The Rivalry','The Classic','The Showdown'],
 'The Game', 'US Sports', 4),
('Which MLB team was involved in the 1919 Black Sox Scandal?',
 ARRAY['Chicago White Sox','Chicago Cubs','Cincinnati Reds','New York Giants'],
 'Chicago White Sox', 'US Sports', 4),
('Who became the first American to win the Tour de France in 1986?',
 ARRAY['Greg LeMond','Lance Armstrong','Bobby Julich','Tyler Hamilton'],
 'Greg LeMond', 'US Sports', 4),
('In what year did Billie Jean King defeat Bobby Riggs in the "Battle of the Sexes" tennis match?',
 ARRAY['1973','1975','1971','1969'],
 '1973', 'US Sports', 4),
('Which US city hosted the 1996 Summer Olympics?',
 ARRAY['Atlanta','Los Angeles','Chicago','New York'],
 'Atlanta', 'US Sports', 4),
('What is the name of the trophy awarded to the winner of the MLS Cup?',
 ARRAY['Philip F. Anschutz Trophy','Lamar Hunt US Open Cup','Supporters'' Shield','MLS Cup Trophy'],
 'Philip F. Anschutz Trophy', 'US Sports', 4),
('Who hit 61 home runs in the 1961 MLB season, breaking Babe Ruth''s single-season record?',
 ARRAY['Roger Maris','Mickey Mantle','Willie Mays','Hank Aaron'],
 'Roger Maris', 'US Sports', 4),
('Which golfer won the most PGA Tour victories in history?',
 ARRAY['Sam Snead','Jack Nicklaus','Tiger Woods','Arnold Palmer'],
 'Sam Snead', 'US Sports', 5),
('What year was the three-point line introduced in the NBA?',
 ARRAY['1979','1977','1981','1975'],
 '1979', 'US Sports', 5),
('Who scored the "Immaculate Reception" in the 1972 AFC Divisional Playoff?',
 ARRAY['Franco Harris','Lynn Swann','John Stallworth','Terry Bradshaw'],
 'Franco Harris', 'US Sports', 5),
('Which woman was the first inducted into the Basketball Hall of Fame?',
 ARRAY['Nera White','Ann Meyers','Cheryl Miller','Nancy Lieberman'],
 'Nera White', 'US Sports', 6),
('What is the correct distance of a marathon in miles?',
 ARRAY['26.2','25','27','24.8'],
 '26.2', 'US Sports', 6),
('Which pitcher threw a perfect game in the 1956 World Series?',
 ARRAY['Don Larsen','Sandy Koufax','Bob Gibson','Whitey Ford'],
 'Don Larsen', 'US Sports', 6),
('Who was the first American woman to win an Olympic gold medal in figure skating?',
 ARRAY['Tenley Albright','Peggy Fleming','Dorothy Hamill','Kristi Yamaguchi'],
 'Tenley Albright', 'US Sports', 6),
('How many consecutive games did Cal Ripken Jr. play to set the MLB record?',
 ARRAY['2,632','2,130','2,500','1,897'],
 '2,632', 'US Sports', 6),
('Who was the first woman to run the Boston Marathon unofficially in 1966?',
 ARRAY['Roberta Gibb','Kathrine Switzer','Joan Benoit','Bobbi Gibb'],
 'Roberta Gibb', 'US Sports', 6),
('Which swimmer won five individual gold medals at the 1980 Lake Placid Winter Olympics?',
 ARRAY['Eric Heiden','Mark Spitz','Michael Phelps','Matt Biondi'],
 'Eric Heiden', 'US Sports', 6),
('Who was the first Black player in NHL history?',
 ARRAY['Willie O''Ree','Grant Fuhr','Mike Marson','Tony McKegney'],
 'Willie O''Ree', 'US Sports', 6),
('Which woman broke the gender barrier at the Indianapolis 500 in 1977?',
 ARRAY['Janet Guthrie','Danica Patrick','Lyn St. James','Sarah Fisher'],
 'Janet Guthrie', 'US Sports', 6),
('What year did the ABA and NBA officially merge?',
 ARRAY['1976','1974','1978','1972'],
 '1976', 'US Sports', 6),
('In what year did the NBA adopt the shot clock?',
 ARRAY['1954','1956','1950','1960'],
 '1954', 'US Sports', 7),
('Who was the first African American head coach in the NBA, with the Milwaukee Bucks in 1971?',
 ARRAY['Al Attles','Bill Russell','Wayne Embry','K.C. Jones'],
 'Al Attles', 'US Sports', 7),
('How many consecutive NHL games did Doug Jarvis play to set the iron man record?',
 ARRAY['964','800','1,000','891'],
 '964', 'US Sports', 7),
('Who won the first Heisman Trophy in 1935?',
 ARRAY['Jay Berwanger','Sammy Baugh','Tom Harmon','Angelo Bertelli'],
 'Jay Berwanger', 'US Sports', 7),
('Which boxer was known as "The Manassa Mauler"?',
 ARRAY['Jack Dempsey','Gene Tunney','Joe Louis','Rocky Marciano'],
 'Jack Dempsey', 'US Sports', 7),
('What year did Princeton and Rutgers play the first college football game?',
 ARRAY['1869','1875','1880','1865'],
 '1869', 'US Sports', 7),
('Which golfer won the first Masters Tournament in 1934?',
 ARRAY['Horton Smith','Gene Sarazen','Craig Wood','Byron Nelson'],
 'Horton Smith', 'US Sports', 7),
('Who was the first Native American to win Olympic gold medals in both the pentathlon and decathlon?',
 ARRAY['Jim Thorpe','Billy Mills','Ellison Brown','Louis Tewanima'],
 'Jim Thorpe', 'US Sports', 7),
('Which NBA player holds the record for the most consecutive games played?',
 ARRAY['A.C. Green','Cal Ripken Jr.','Lou Gehrig','Jim Marshall'],
 'A.C. Green', 'US Sports', 7),
('What year was the first Rose Bowl game played?',
 ARRAY['1902','1910','1898','1920'],
 '1902', 'US Sports', 7),
('Who was the first American woman to compete in Olympic weightlifting, winning gold at the 2000 Sydney Olympics?',
 ARRAY['Tara Nott','Cheryl Haworth','Robin Byrd-Goad','Sara Connelly'],
 'Tara Nott', 'US Sports', 8),
('Which sprinter won the 100m gold medal at the 1996 Atlanta Olympics for Canada, competing in US-hosted games?',
 ARRAY['Donovan Bailey','Michael Johnson','Carl Lewis','Maurice Greene'],
 'Donovan Bailey', 'US Sports', 8),
('Who was the first diver to win gold medals on both platform and springboard at three consecutive Olympics?',
 ARRAY['Greg Louganis','Bob Webster','Klaus Dibiasi','Pat McCormick'],
 'Greg Louganis', 'US Sports', 8),
('What was the name of the heavyweight boxing match between Muhammad Ali and George Foreman in 1974?',
 ARRAY['Rumble in the Jungle','Thrilla in Manila','Fight of the Century','Superfight II'],
 'Rumble in the Jungle', 'US Sports', 8),
('Which boxer upset Mike Tyson in 1990, ending his undefeated streak?',
 ARRAY['Buster Douglas','Evander Holyfield','Lennox Lewis','Michael Spinks'],
 'Buster Douglas', 'US Sports', 8),
('Who won the America''s Cup in 1851, the first time the trophy was awarded?',
 ARRAY['The schooner America','The yacht Cambria','The sloop Arrow','The cutter Titania'],
 'The schooner America', 'US Sports', 8),
('Which NFL player holds the record for the most consecutive starts?',
 ARRAY['Jim Marshall','Brett Favre','Peyton Manning','Jerry Rice'],
 'Jim Marshall', 'US Sports', 8),
('Who won gold in the 400m and 200m at the 1996 Atlanta Olympics, becoming the first man to win both in the same Games?',
 ARRAY['Michael Johnson','Carl Lewis','Frank Fredericks','Ato Boldon'],
 'Michael Johnson', 'US Sports', 8),
('Which female swimmer became the first woman to cross the English Channel faster than any man who had done it at the time in 1926?',
 ARRAY['Gertrude Ederle','Florence Chadwick','Diana Nyad','Lynne Cox'],
 'Gertrude Ederle', 'US Sports', 9),
('Which swimmer won seven gold medals at the 1972 Munich Olympics?',
 ARRAY['Mark Spitz','Shane Gould','Roland Matthes','John Naber'],
 'Mark Spitz', 'US Sports', 9),
('Who set the world record for the 100m butterfly at the 1976 Montreal Olympics?',
 ARRAY['Jim Montgomery','Mark Spitz','Matt Vogel','Mike O''Brien'],
 'Jim Montgomery', 'US Sports', 9),
('Which MLB pitcher is the only one to win the Cy Young Award in both the American and National Leagues?',
 ARRAY['Gaylord Perry','Roger Clemens','Randy Johnson','Pedro Martinez'],
 'Gaylord Perry', 'US Sports', 9),
('What year did Don Budge complete the first tennis Grand Slam?',
 ARRAY['1938','1935','1942','1930'],
 '1938', 'US Sports', 9),
('Which gymnast became the most decorated US gymnast in history by 2016?',
 ARRAY['Simone Biles','Mary Lou Retton','Shannon Miller','Carly Patterson'],
 'Simone Biles', 'US Sports', 9),
('Who was the first woman inducted into the Hockey Hall of Fame as a player?',
 ARRAY['Angela James','Cammi Granato','Hayley Wickenheiser','Manon Rheaume'],
 'Angela James', 'US Sports', 9);

