-- Migration 017: Expand question bank (batch 8)
-- 387 questions across 8 categories (15 duplicates removed)

-- American Culture (51 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which American author wrote "The Great Gatsby," a novel set during the Jazz Age?',
 ARRAY['Ernest Hemingway', 'F. Scott Fitzgerald', 'William Faulkner', 'Sinclair Lewis'],
 'F. Scott Fitzgerald', 'American Culture', 2),
('The cultural phenomenon known as "Beatlemania" swept the United States after the British band appeared on which television show in 1964?',
 ARRAY['The Tonight Show', 'American Bandstand', 'The Ed Sullivan Show', 'The Dick Cavett Show'],
 'The Ed Sullivan Show', 'American Culture', 3),
('Which annual event in Pasadena, California features elaborate floats made entirely of flowers?',
 ARRAY['Rose Parade', 'Cherry Blossom Festival', 'Flower Bowl Parade', 'Tournament of Petals'],
 'Rose Parade', 'American Culture', 2),
('The "Oregon Trail" video game, popular in schools during the 1970s-90s, was developed by which company?',
 ARRAY['Atari', 'MECC', 'Apple', 'Broderbund'],
 'MECC', 'American Culture', 6),
('Which American filmmaker known for westerns directed "The Searchers" and "Stagecoach"?',
 ARRAY['Howard Hawks', 'John Huston', 'Cecil B. DeMille', 'John Ford'],
 'John Ford', 'American Culture', 4),
('The "Harlem Shake" dance craze of 2013 and the original "Harlem Shake" song are connected to which music genre?',
 ARRAY['Hip-hop', 'Electronic dance music', 'R&B', 'Funk'],
 'Electronic dance music', 'American Culture', 5),
('Which American holiday is celebrated on the third Monday of February to honor past presidents?',
 ARRAY['Veterans Day', 'Memorial Day', 'Presidents'' Day', 'Inauguration Day'],
 'Presidents'' Day', 'American Culture', 2),
('The Macy''s Thanksgiving Day Parade has been held in New York City since which year?',
 ARRAY['1914', '1920', '1924', '1929'],
 '1924', 'American Culture', 5),
('Which American poet wrote "The Waste Land," considered one of the most important works of modernist literature?',
 ARRAY['Ezra Pound', 'T.S. Eliot', 'William Carlos Williams', 'e.e. cummings'],
 'T.S. Eliot', 'American Culture', 6),
('The phrase "Keep up with the Joneses" originated from a comic strip created in which year?',
 ARRAY['1903', '1913', '1923', '1933'],
 '1913', 'American Culture', 8),
('Which American artist created the iconic "Campbell''s Soup Cans" series of paintings in 1962?',
 ARRAY['Roy Lichtenstein', 'Andy Warhol', 'Jasper Johns', 'Robert Rauschenberg'],
 'Andy Warhol', 'American Culture', 3),
('The "American Gothic" painting by Grant Wood depicts a farmer and his wife. What tool does the farmer hold?',
 ARRAY['Scythe', 'Pitchfork', 'Rake', 'Shovel'],
 'Pitchfork', 'American Culture', 3),
('Which Chicago-based magazine, founded in 1945, became famous for its men''s entertainment and lifestyle content?',
 ARRAY['Esquire', 'GQ', 'Playboy', 'Details'],
 'Playboy', 'American Culture', 3),
('The tradition of trick-or-treating during Halloween became widespread in America during which decade?',
 ARRAY['1920s', '1930s', '1940s', '1950s'],
 '1950s', 'American Culture', 6),
('Which American author wrote the dystopian novel "Fahrenheit 451"?',
 ARRAY['George Orwell', 'Ray Bradbury', 'Philip K. Dick', 'Kurt Vonnegut'],
 'Ray Bradbury', 'American Culture', 3),
('The "Pledge of Allegiance" was first published in which magazine in 1892?',
 ARRAY['The Atlantic', 'Harper''s Weekly', 'The Youth''s Companion', 'Life Magazine'],
 'The Youth''s Companion', 'American Culture', 7),
('Which American TV show popularized the cooking competition format and premiered in 2006 on Bravo?',
 ARRAY['Hell''s Kitchen', 'Top Chef', 'MasterChef', 'Chopped'],
 'Top Chef', 'American Culture', 5),
('The "Harlem Renaissance" was primarily a cultural movement centered in which decade?',
 ARRAY['1900s', '1910s', '1920s', '1930s'],
 '1920s', 'American Culture', 3),
('Which famous American musician is known as the "Father of the Blues"?',
 ARRAY['Robert Johnson', 'Muddy Waters', 'W.C. Handy', 'Howlin'' Wolf'],
 'W.C. Handy', 'American Culture', 6),
('The phrase "The American Dream" was first popularized by historian James Truslow Adams in which year?',
 ARRAY['1921', '1926', '1931', '1936'],
 '1931', 'American Culture', 8),
('Which famous American author wrote the novel "Moby-Dick"?',
 ARRAY['Nathaniel Hawthorne', 'Washington Irving', 'Herman Melville', 'Edgar Allan Poe'],
 'Herman Melville', 'American Culture', 2),
('The famous "Dewey Defeats Truman" newspaper headline error occurred during the presidential election of which year?',
 ARRAY['1944', '1946', '1948', '1950'],
 '1948', 'American Culture', 5),
('Which dance originating in the 1920s required partners to do the Charleston while holding each other?',
 ARRAY['Lindy Hop', 'Foxtrot', 'Black Bottom', 'Balboa'],
 'Lindy Hop', 'American Culture', 6),
('What term describes the informal system of restaurants and diners along American highways in the mid-20th century?',
 ARRAY['Highway Dining', 'Road Food Culture', 'Diner Culture', 'Motor Court Cuisine'],
 'Diner Culture', 'American Culture', 5),
('Which famous American talk show host is known as the "Queen of All Media" and ran her show from 1986 to 2011?',
 ARRAY['Ellen DeGeneres', 'Oprah Winfrey', 'Rosie O''Donnell', 'Donahue'],
 'Oprah Winfrey', 'American Culture', 1),
('The television show "Seinfeld" ran from 1989 to 1998. What was the show''s famous mantra about its content?',
 ARRAY['"No Plot, No Problem"', '"Nothing Matters"', '"A Show About Nothing"', '"Everyday Nowhere"'],
 '"A Show About Nothing"', 'American Culture', 3),
('The literary movement known as "Southern Gothic" is most associated with which American author?',
 ARRAY['William Faulkner', 'Truman Capote', 'Flannery O''Connor', 'Carson McCullers'],
 'Flannery O''Connor', 'American Culture', 7),
('Which New York City neighborhood became famous as the center of abstract expressionist painting in the 1940s and 50s?',
 ARRAY['Greenwich Village', 'SoHo', 'Chelsea', 'The East Village'],
 'Greenwich Village', 'American Culture', 6),
('The famous "Rosie the Riveter" poster was created to encourage women to do what during World War II?',
 ARRAY['Buy war bonds', 'Join the military', 'Work in war industries', 'Grow victory gardens'],
 'Work in war industries', 'American Culture', 3),
('Which American holiday, originating in the late 19th century, honors the labor movement and is celebrated on the first Monday of September?',
 ARRAY['Workers'' Day', 'Union Day', 'Labor Day', 'Industrial Day'],
 'Labor Day', 'American Culture', 2),
('The "Star Wars" franchise began with which film released in 1977?',
 ARRAY['A New Hope', 'Return of the Jedi', 'The Empire Strikes Back', 'Revenge of the Sith'],
 'A New Hope', 'American Culture', 2),
('Which American author wrote "Adventures of Huckleberry Finn," published in 1884?',
 ARRAY['Bret Harte', 'Mark Twain', 'O. Henry', 'Jack London'],
 'Mark Twain', 'American Culture', 2),
('The "New Deal" was a series of programs launched by President Roosevelt to address which national crisis?',
 ARRAY['World War I aftermath', 'The Great Depression', 'The Dust Bowl', 'The Spanish Flu epidemic'],
 'The Great Depression', 'American Culture', 3),
('Which American artist is known for her photographs of the Great Depression, including "Migrant Mother"?',
 ARRAY['Margaret Bourke-White', 'Diane Arbus', 'Dorothea Lange', 'Mary Ellen Mark'],
 'Dorothea Lange', 'American Culture', 5),
('The term "Okies" was used during the 1930s to refer to migrants fleeing which region due to dust storms and drought?',
 ARRAY['Oklahoma and nearby Great Plains states', 'The Appalachian region', 'The Mississippi Delta', 'The Southwest desert'],
 'Oklahoma and nearby Great Plains states', 'American Culture', 4),
('Which famous American architect designed the iconic TWA Flight Center at JFK Airport in New York?',
 ARRAY['Philip Johnson', 'I.M. Pei', 'Eero Saarinen', 'Walter Gropius'],
 'Eero Saarinen', 'American Culture', 7),
('The famous comedy film genre known as "screwball comedy" reached its peak in which decade?',
 ARRAY['1920s', '1930s', '1940s', '1950s'],
 '1930s', 'American Culture', 6),
('Which American novelist wrote the Pulitzer Prize-winning "The Grapes of Wrath" in 1939?',
 ARRAY['Theodore Dreiser', 'Upton Sinclair', 'John Steinbeck', 'Sinclair Lewis'],
 'John Steinbeck', 'American Culture', 2),
('The famous civil rights anthem "We Shall Overcome" has roots in which earlier song tradition?',
 ARRAY['Gospel music', 'Slave spirituals', 'Folk songs', 'Blues music'],
 'Gospel music', 'American Culture', 6),
('Which annual music festival held in the Coachella Valley has been held at the same site since 1999?',
 ARRAY['Coachella Valley Music and Arts Festival', 'Desert Trip', 'Stagecoach', 'BNP Paribas Open'],
 'Coachella Valley Music and Arts Festival', 'American Culture', 2),
('The famous "I Have a Dream" speech by Martin Luther King Jr. was delivered in which city?',
 ARRAY['Atlanta', 'Birmingham', 'Washington DC', 'New York City'],
 'Washington DC', 'American Culture', 1),
('What is the name of the Boston-based alternative weekly newspaper founded in 1966 that became a template for alternative media?',
 ARRAY['The Village Voice', 'The Boston Phoenix', 'The Real Paper', 'The Cambridge Chronicle'],
 'The Boston Phoenix', 'American Culture', 9),
('Which musician, known as "The King of Rock and Roll," recorded his first song at Sun Studio in Memphis in 1953?',
 ARRAY['Chuck Berry', 'Little Richard', 'Jerry Lee Lewis', 'Elvis Presley'],
 'Elvis Presley', 'American Culture', 1),
('The literary journal "The Little Review" first published which controversial novel serially from 1918 to 1920?',
 ARRAY['The Sun Also Rises', 'Ulysses', 'The Sound and the Fury', 'Mrs. Dalloway'],
 'Ulysses', 'American Culture', 9),
('Which annual event held in New Orleans celebrates the Catholic tradition before Lent begins?',
 ARRAY['Jazz Fest', 'Mardi Gras', 'French Quarter Festival', 'Creole Tomato Festival'],
 'Mardi Gras', 'American Culture', 1),
('The famous "Saturday Night Fever" soundtrack helped popularize which genre of music in the late 1970s?',
 ARRAY['Funk', 'Soul', 'Disco', 'Soft Rock'],
 'Disco', 'American Culture', 3),
('Which famous comedy troupe from Chicago has launched the careers of Bill Murray, John Belushi, and Tina Fey?',
 ARRAY['The Groundlings', 'Upright Citizens Brigade', 'The Second City', 'iO Theater'],
 'The Second City', 'American Culture', 5),
('The term "bebop" refers to a style of what type of music that emerged in the 1940s?',
 ARRAY['Blues', 'Jazz', 'Rhythm and Blues', 'Soul'],
 'Jazz', 'American Culture', 4),
('The famous Route 66 highway officially ended in which city?',
 ARRAY['Los Angeles', 'San Diego', 'Santa Monica', 'Long Beach'],
 'Santa Monica', 'American Culture', 5),
('Which American writer is credited with coining the term "the Lost Generation" to describe post-WWI American expatriates in Paris?',
 ARRAY['F. Scott Fitzgerald', 'Ernest Hemingway', 'Gertrude Stein', 'Sherwood Anderson'],
 'Gertrude Stein', 'American Culture', 7),
('The famous American political cartoon symbol of the donkey for the Democratic Party first appeared in a cartoon by which artist in 1870?',
 ARRAY['Thomas Nast', 'Joseph Keppler', 'Art Young', 'Homer Davenport'],
 'Thomas Nast', 'American Culture', 7);

-- Civics (48 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the name of the process by which a president nominates and the Senate confirms federal judges?',
 ARRAY['Judicial appointment', 'Advice and consent', 'Executive confirmation', 'Legislative ratification'],
 'Advice and consent', 'Civics', 3),
('Which amendment abolished slavery in the United States?',
 ARRAY['12th Amendment', '13th Amendment', '14th Amendment', '15th Amendment'],
 '13th Amendment', 'Civics', 2),
('What is the term for a formal agreement between the United States and another country that requires Senate approval?',
 ARRAY['Executive agreement', 'Treaty', 'Protocol', 'Accord'],
 'Treaty', 'Civics', 3),
('Under the Constitution, which branch of government has the power to declare war?',
 ARRAY['Executive branch', 'Judicial branch', 'Legislative branch', 'Joint Chiefs of Staff'],
 'Legislative branch', 'Civics', 3),
('What is the minimum number of states needed to call a constitutional convention?',
 ARRAY['26 states', '34 states', '38 states', '40 states'],
 '34 states', 'Civics', 7),
('Which constitutional amendment gave the District of Columbia electoral votes for president?',
 ARRAY['21st Amendment', '22nd Amendment', '23rd Amendment', '24th Amendment'],
 '23rd Amendment', 'Civics', 6),
('What term describes the power of Congress to investigate the executive branch?',
 ARRAY['Oversight power', 'Inquiry power', 'Review power', 'Supervision power'],
 'Oversight power', 'Civics', 5),
('What is the official title of the person who presides over the Senate when the Vice President is absent?',
 ARRAY['Senate Majority Leader', 'President pro tempore', 'Senate Speaker', 'Senate Chairman'],
 'President pro tempore', 'Civics', 4),
('Which Supreme Court case established that racial segregation in public schools was unconstitutional?',
 ARRAY['Plessy v. Ferguson', 'Brown v. Board of Education', 'Loving v. Virginia', 'Swann v. Charlotte-Mecklenburg'],
 'Brown v. Board of Education', 'Civics', 2),
('What is the term for the president''s power to refuse to spend funds appropriated by Congress?',
 ARRAY['Veto power', 'Impoundment', 'Line-item veto', 'Sequestration'],
 'Impoundment', 'Civics', 8),
('How many years does a member of the House of Representatives serve per term?',
 ARRAY['2 years', '4 years', '6 years', '8 years'],
 '2 years', 'Civics', 1),
('Which amendment to the Constitution repealed Prohibition?',
 ARRAY['19th Amendment', '20th Amendment', '21st Amendment', '22nd Amendment'],
 '21st Amendment', 'Civics', 4),
('What is the legal doctrine that allows courts to refuse to hear cases involving political disputes?',
 ARRAY['Standing doctrine', 'Political question doctrine', 'Ripeness doctrine', 'Mootness doctrine'],
 'Political question doctrine', 'Civics', 9),
('What is the name of the federal budget process by which automatic spending cuts are triggered?',
 ARRAY['Impoundment', 'Sequestration', 'Reconciliation', 'Appropriation'],
 'Sequestration', 'Civics', 7),
('What constitutional provision requires states to honor each other''s legal judgments?',
 ARRAY['Commerce Clause', 'Due Process Clause', 'Full Faith and Credit Clause', 'Privileges and Immunities Clause'],
 'Full Faith and Credit Clause', 'Civics', 5),
('Which landmark case ruled that the death penalty for juvenile offenders was unconstitutional?',
 ARRAY['Atkins v. Virginia', 'Roper v. Simmons', 'Kennedy v. Louisiana', 'Graham v. Florida'],
 'Roper v. Simmons', 'Civics', 9),
('What is the constitutional requirement for the president to report to Congress on the state of the nation?',
 ARRAY['Executive Address', 'State of the Union', 'Presidential Report', 'National Briefing'],
 'State of the Union', 'Civics', 2),
('Which constitutional amendment set a time limit on the ratification of proposed amendments?',
 ARRAY['No amendment sets a time limit', '17th Amendment', '20th Amendment', 'Congress sets limits by statute'],
 'No amendment sets a time limit', 'Civics', 8),
('What Supreme Court case ruled that burning money is protected free speech?',
 ARRAY['Texas v. Johnson', 'United States v. Eichman', 'Cohen v. California', 'Tinker v. Des Moines'],
 'United States v. Eichman', 'Civics', 9),
('What is the term for a senator''s use of extended debate to delay or block a vote?',
 ARRAY['Recess', 'Filibuster', 'Cloture', 'Quorum call'],
 'Filibuster', 'Civics', 3),
('What is the legal standard required for police to make a warrantless arrest?',
 ARRAY['Reasonable suspicion', 'Probable cause', 'Preponderance of evidence', 'Clear and convincing evidence'],
 'Probable cause', 'Civics', 5),
('What constitutional clause prohibits Congress from passing laws targeting a specific person for punishment?',
 ARRAY['Ex post facto clause', 'Bill of attainder clause', 'Due process clause', 'Equal protection clause'],
 'Bill of attainder clause', 'Civics', 7),
('What is the name of the power that allows the federal government to take private property for public use with fair compensation?',
 ARRAY['Police power', 'Eminent domain', 'Regulatory taking', 'Condemnation power'],
 'Eminent domain', 'Civics', 4),
('Which Supreme Court case held that students do not shed their constitutional rights at the schoolhouse gate?',
 ARRAY['Hazelwood v. Kuhlmeier', 'Bethel v. Fraser', 'Tinker v. Des Moines', 'Morse v. Frederick'],
 'Tinker v. Des Moines', 'Civics', 6),
('What is the name of the constitutional provision that prohibits laws punishing actions that were legal when committed?',
 ARRAY['Bill of attainder', 'Ex post facto law', 'Habeas corpus', 'Due process'],
 'Ex post facto law', 'Civics', 5),
('Which branch of government has the power to coin money?',
 ARRAY['Executive branch', 'Judicial branch', 'Legislative branch', 'Federal Reserve'],
 'Legislative branch', 'Civics', 3),
('What term describes the concept that no one is above the law, including government officials?',
 ARRAY['Separation of powers', 'Judicial supremacy', 'Rule of law', 'Popular sovereignty'],
 'Rule of law', 'Civics', 2),
('How many electoral votes does a presidential candidate need to win the presidency?',
 ARRAY['250', '260', '270', '280'],
 '270', 'Civics', 2),
('What is the name of the Supreme Court case that established the principle of one person, one vote?',
 ARRAY['Baker v. Carr', 'Reynolds v. Sims', 'Wesberry v. Sanders', 'Gray v. Sanders'],
 'Reynolds v. Sims', 'Civics', 8),
('Which amendment lowered the voting age to 18?',
 ARRAY['24th Amendment', '25th Amendment', '26th Amendment', '27th Amendment'],
 '26th Amendment', 'Civics', 2),
('What is the term for the formal accusation that begins the impeachment process?',
 ARRAY['Indictment', 'Articles of impeachment', 'Bill of impeachment', 'Charge of impeachment'],
 'Articles of impeachment', 'Civics', 5),
('Which constitutional provision grants Congress the power to regulate interstate commerce?',
 ARRAY['Necessary and Proper Clause', 'Supremacy Clause', 'Commerce Clause', 'General Welfare Clause'],
 'Commerce Clause', 'Civics', 3),
('What is the number of justices needed for a majority opinion on the Supreme Court?',
 ARRAY['4', '5', '6', '7'],
 '5', 'Civics', 4),
('What is the constitutional term for the government''s obligation to provide basic procedural fairness?',
 ARRAY['Equal protection', 'Due process', 'Rule of law', 'Just compensation'],
 'Due process', 'Civics', 3),
('Which amendment requires just compensation when the government takes private property?',
 ARRAY['4th Amendment', '5th Amendment', '6th Amendment', '7th Amendment'],
 '5th Amendment', 'Civics', 5),
('What is the term for a presidential refusal to sign a bill that is automatically enacted after 10 days of congressional session?',
 ARRAY['Line-item veto', 'Pocket veto', 'Override veto', 'Silent veto'],
 'Pocket veto', 'Civics', 6),
('Which Supreme Court case ruled that segregation of interstate bus travel was unconstitutional?',
 ARRAY['Heart of Atlanta Motel v. United States', 'Boynton v. Virginia', 'Morgan v. Virginia', 'Bailey v. Patterson'],
 'Boynton v. Virginia', 'Civics', 9),
('What is the constitutional requirement that prevents double prosecution for the same crime?',
 ARRAY['Self-incrimination clause', 'Double jeopardy clause', 'Due process clause', 'Equal protection clause'],
 'Double jeopardy clause', 'Civics', 4),
('How many votes in the Senate are required to ratify a treaty?',
 ARRAY['Simple majority (51)', 'Three-fifths (60)', 'Two-thirds (67)', 'Three-quarters (75)'],
 'Two-thirds (67)', 'Civics', 5),
('What is the name of the government body that oversees the federal budget and advises the president on economic policy?',
 ARRAY['Office of Management and Budget', 'Council of Economic Advisers', 'Congressional Budget Office', 'Treasury Department'],
 'Office of Management and Budget', 'Civics', 6),
('Which landmark Supreme Court ruling held that corporations have a right to spend money in elections under the First Amendment?',
 ARRAY['Buckley v. Valeo', 'McConnell v. FEC', 'Citizens United v. FEC', 'McCutcheon v. FEC'],
 'Citizens United v. FEC', 'Civics', 5),
('What constitutional principle holds that federal law takes precedence over conflicting state law?',
 ARRAY['Federal preemption', 'Necessary and Proper Clause', 'Commerce Clause', 'Supremacy Clause'],
 'Federal preemption', 'Civics', 6),
('What is the term for the president''s ability to grant pardons for federal crimes?',
 ARRAY['Executive clemency', 'Pardon power', 'Commutation authority', 'Reprieve power'],
 'Pardon power', 'Civics', 3),
('Which constitutional amendment granted citizenship to formerly enslaved people?',
 ARRAY['13th Amendment', '14th Amendment', '15th Amendment', '16th Amendment'],
 '14th Amendment', 'Civics', 3),
('What is the name of the government official who represents the United States in foreign countries?',
 ARRAY['Consul', 'Ambassador', 'Attaché', 'Envoy'],
 'Ambassador', 'Civics', 2),
('What is the constitutional term for the authority of states to police and protect the health, safety, and welfare of their citizens?',
 ARRAY['Reserved power', 'Police power', 'Plenary power', 'Inherent power'],
 'Police power', 'Civics', 6),
('Which Supreme Court case ruled that evidence obtained from an illegal search cannot be used at trial?',
 ARRAY['Weeks v. United States', 'Mapp v. Ohio', 'Terry v. Ohio', 'Katz v. United States'],
 'Mapp v. Ohio', 'Civics', 7),
('What is the name of the clause in the 14th Amendment that requires states to treat all persons equally under the law?',
 ARRAY['Due process clause', 'Citizenship clause', 'Equal protection clause', 'Privileges and immunities clause'],
 'Equal protection clause', 'Civics', 4);

-- Famous Americans (42 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which American inventor developed the first practical sewing machine in 1846?',
 ARRAY['Eli Whitney', 'Elias Howe', 'Isaac Singer', 'Charles Goodyear'],
 'Elias Howe', 'Famous Americans', 6),
('Who was the first woman elected to the US House of Representatives?',
 ARRAY['Shirley Chisholm', 'Jeannette Rankin', 'Patsy Mink', 'Clare Boothe Luce'],
 'Jeannette Rankin', 'Famous Americans', 7),
('Which American chemist developed the polio vaccine using killed virus?',
 ARRAY['Jonas Salk', 'Albert Sabin', 'John Enders', 'Thomas Weller'],
 'Jonas Salk', 'Famous Americans', 3),
('Who composed the music for the Broadway musical "West Side Story"?',
 ARRAY['Cole Porter', 'George Gershwin', 'Leonard Bernstein', 'Stephen Sondheim'],
 'Leonard Bernstein', 'Famous Americans', 4),
('Who was the first African American to win the Academy Award for Best Actor?',
 ARRAY['Sidney Poitier', 'Denzel Washington', 'Forest Whitaker', 'Jamie Foxx'],
 'Sidney Poitier', 'Famous Americans', 5),
('Which American scientist discovered that DNA has a double helix structure along with Francis Crick?',
 ARRAY['Linus Pauling', 'James Watson', 'Erwin Chargaff', 'Maurice Wilkins'],
 'James Watson', 'Famous Americans', 5),
('Which American playwright wrote "Death of a Salesman"?',
 ARRAY['Tennessee Williams', 'Eugene O''Neill', 'Arthur Miller', 'Edward Albee'],
 'Arthur Miller', 'Famous Americans', 4),
('Which American entrepreneur founded Federal Express in 1971?',
 ARRAY['Howard Hughes', 'Fred Smith', 'Ross Perot', 'Sam Walton'],
 'Fred Smith', 'Famous Americans', 7),
('Who was the American architect known for designing the Vietnam Veterans Memorial in Washington DC?',
 ARRAY['I.M. Pei', 'Frank Gehry', 'Maya Lin', 'Zaha Hadid'],
 'Maya Lin', 'Famous Americans', 5),
('Which American novelist wrote "The Color Purple" and won the Pulitzer Prize in 1983?',
 ARRAY['Toni Morrison', 'Alice Walker', 'Zora Neale Hurston', 'Maya Angelou'],
 'Alice Walker', 'Famous Americans', 4),
('Who was the first American woman to win an Olympic gold medal?',
 ARRAY['Mildred "Babe" Didrikson', 'Helen Wills', 'Gertrude Ederle', 'Ethelda Bleibtrey'],
 'Ethelda Bleibtrey', 'Famous Americans', 9),
('Which American businessman and philanthropist founded Standard Oil in 1870?',
 ARRAY['Andrew Carnegie', 'J.P. Morgan', 'John D. Rockefeller', 'Cornelius Vanderbilt'],
 'John D. Rockefeller', 'Famous Americans', 3),
('Who wrote the poem "The Road Not Taken"?',
 ARRAY['Walt Whitman', 'Emily Dickinson', 'Carl Sandburg', 'Robert Frost'],
 'Robert Frost', 'Famous Americans', 2),
('Which American general commanded Allied forces in Europe during World War II?',
 ARRAY['Douglas MacArthur', 'Omar Bradley', 'George Patton', 'Dwight D. Eisenhower'],
 'Dwight D. Eisenhower', 'Famous Americans', 3),
('Who was the first African American woman to win a Grammy Award?',
 ARRAY['Ella Fitzgerald', 'Billie Holiday', 'Sarah Vaughan', 'Dinah Washington'],
 'Ella Fitzgerald', 'Famous Americans', 8),
('Which American scientist developed the theory of continental drift?',
 ARRAY['Alfred Wegener', 'Charles Richter', 'Harry Hess', 'J. Tuzo Wilson'],
 'Harry Hess', 'Famous Americans', 9),
('Who was the lead designer of the first American space suit used during the Apollo missions?',
 ARRAY['Wernher von Braun', 'Neil Armstrong', 'Deke Slayton', 'Eleanore Foraker'],
 'Wernher von Braun', 'Famous Americans', 9),
('Which American writer is considered the founder of the American short story as a literary genre?',
 ARRAY['Nathaniel Hawthorne', 'Washington Irving', 'Edgar Allan Poe', 'Herman Melville'],
 'Washington Irving', 'Famous Americans', 7),
('Who was the first Hispanic American to serve as a US Cabinet member?',
 ARRAY['Julian Castro', 'Henry Cisneros', 'Lauro Cavazos', 'Federico Peña'],
 'Lauro Cavazos', 'Famous Americans', 9),
('Which American scientist won the Nobel Prize for discovering the electron?',
 ARRAY['Robert Millikan', 'Albert Michelson', 'J.J. Thomson', 'Richard Feynman'],
 'Robert Millikan', 'Famous Americans', 7),
('Who was the American photographer known for documenting the Great Depression, particularly in "Migrant Mother"?',
 ARRAY['Ansel Adams', 'Gordon Parks', 'Walker Evans', 'Dorothea Lange'],
 'Dorothea Lange', 'Famous Americans', 5),
('Which American abolitionist and women''s rights activist wrote "Incidents in the Life of a Slave Girl"?',
 ARRAY['Sojourner Truth', 'Harriet Jacobs', 'Frances Ellen Watkins Harper', 'Mary Ann Shadd'],
 'Harriet Jacobs', 'Famous Americans', 8),
('Who was the first American woman to fly in space?',
 ARRAY['Mae Jemison', 'Eileen Collins', 'Peggy Whitson', 'Sally Ride'],
 'Sally Ride', 'Famous Americans', 3),
('Which American composer wrote "Rhapsody in Blue"?',
 ARRAY['Aaron Copland', 'Samuel Barber', 'George Gershwin', 'Duke Ellington'],
 'George Gershwin', 'Famous Americans', 4),
('Who was the first person to swim the English Channel from both directions?',
 ARRAY['Florence Chadwick', 'Gertrude Ederle', 'Diana Nyad', 'Lynne Cox'],
 'Florence Chadwick', 'Famous Americans', 9),
('Which American industrialist built Carnegie Hall and endowed thousands of public libraries?',
 ARRAY['J.P. Morgan', 'Andrew Carnegie', 'Cornelius Vanderbilt', 'John D. Rockefeller'],
 'Andrew Carnegie', 'Famous Americans', 3),
('Who was the American astronomer who discovered that the universe is expanding?',
 ARRAY['Carl Sagan', 'Edwin Hubble', 'Vera Rubin', 'Harlow Shapley'],
 'Edwin Hubble', 'Famous Americans', 5),
('Which American journalist is known as the "Mother of Modern Investigative Journalism" for her exposé of Standard Oil?',
 ARRAY['Nellie Bly', 'Ida Tarbell', 'Helen Thomas', 'Dorothy Thompson'],
 'Ida Tarbell', 'Famous Americans', 6),
('Who was the first African American to earn a PhD from Harvard University?',
 ARRAY['Booker T. Washington', 'W.E.B. Du Bois', 'Carter G. Woodson', 'Alain Locke'],
 'W.E.B. Du Bois', 'Famous Americans', 6),
('Which American architect designed the iconic Fallingwater house in Pennsylvania?',
 ARRAY['Louis Sullivan', 'Mies van der Rohe', 'Frank Lloyd Wright', 'Philip Johnson'],
 'Frank Lloyd Wright', 'Famous Americans', 4),
('Who was the first Latino to serve on the US Supreme Court?',
 ARRAY['Miguel Estrada', 'Sonia Sotomayor', 'Alberto Gonzales', 'Samuel Alito'],
 'Sonia Sotomayor', 'Famous Americans', 4),
('Which American author wrote "The Jungle," exposing unsanitary conditions in the meatpacking industry?',
 ARRAY['Jack London', 'Theodore Dreiser', 'Upton Sinclair', 'Frank Norris'],
 'Upton Sinclair', 'Famous Americans', 4),
('Who was the American naval officer who opened Japan to trade with the West in 1853?',
 ARRAY['John Paul Jones', 'Stephen Decatur', 'Matthew Perry', 'David Farragut'],
 'Matthew Perry', 'Famous Americans', 6),
('Which American mathematician developed game theory, later depicted in the film "A Beautiful Mind"?',
 ARRAY['Claude Shannon', 'Norbert Wiener', 'John Nash', 'John von Neumann'],
 'John Nash', 'Famous Americans', 5),
('Which American scientist developed the first nuclear reactor in Chicago in 1942?',
 ARRAY['J. Robert Oppenheimer', 'Enrico Fermi', 'Edward Teller', 'Leo Szilard'],
 'Enrico Fermi', 'Famous Americans', 6),
('Who was the American labor organizer who co-founded the International Workers of the World (IWW)?',
 ARRAY['Eugene V. Debs', 'Samuel Gompers', 'Mary Harris "Mother" Jones', 'Big Bill Haywood'],
 'Big Bill Haywood', 'Famous Americans', 8),
('Who was the first woman to earn a medical degree in the United States?',
 ARRAY['Mary Walker', 'Clara Barton', 'Elizabeth Blackwell', 'Alice Hamilton'],
 'Elizabeth Blackwell', 'Famous Americans', 5),
('Which American abstract expressionist painter developed the "drip painting" technique?',
 ARRAY['Mark Rothko', 'Willem de Kooning', 'Jackson Pollock', 'Franz Kline'],
 'Jackson Pollock', 'Famous Americans', 4),
('Who was the African American pilot who was the first to earn a US military pilot''s license?',
 ARRAY['Bessie Coleman', 'Eugene Bullard', 'Benjamin Davis Jr.', 'Tuskegee Airmen'],
 'Eugene Bullard', 'Famous Americans', 9),
('Which American entrepreneur co-founded Apple Computer with Steve Jobs in 1976?',
 ARRAY['Bill Gates', 'Steve Wozniak', 'Michael Dell', 'Larry Ellison'],
 'Steve Wozniak', 'Famous Americans', 3),
('Who was the American reformer who established Hull House in Chicago to aid immigrants and the poor?',
 ARRAY['Lillian Wald', 'Florence Kelley', 'Jane Addams', 'Mary Richmond'],
 'Jane Addams', 'Famous Americans', 5),
('Which American frontiersman and sharpshooter became famous for his Wild West shows?',
 ARRAY['Wyatt Earp', 'Wild Bill Hickok', 'Buffalo Bill Cody', 'Calamity Jane'],
 'Buffalo Bill Cody', 'Famous Americans', 3);

-- Geography (48 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the capital city of Alaska?',
 ARRAY['Anchorage', 'Fairbanks', 'Juneau', 'Sitka'],
 'Juneau', 'Geography', 3),
('Which US state contains the most freshwater lakes?',
 ARRAY['Michigan', 'Wisconsin', 'Minnesota', 'Alaska'],
 'Minnesota', 'Geography', 4),
('What is the name of the narrow strip of land connecting North America to South America?',
 ARRAY['Isthmus of Suez', 'Isthmus of Panama', 'Isthmus of Tehuantepec', 'Isthmus of Darien'],
 'Isthmus of Panama', 'Geography', 3),
('Which US state is home to the Badlands National Park?',
 ARRAY['North Dakota', 'Wyoming', 'Montana', 'South Dakota'],
 'South Dakota', 'Geography', 3),
('What is the name of the body of water that separates Manhattan Island from the Bronx?',
 ARRAY['Hudson River', 'East River', 'Harlem River', 'Spuyten Duyvil Creek'],
 'Harlem River', 'Geography', 7),
('Which US territory is located in the Caribbean Sea and is the largest of the US territories?',
 ARRAY['US Virgin Islands', 'Puerto Rico', 'Guam', 'American Samoa'],
 'Puerto Rico', 'Geography', 2),
('What mountain range runs along the border between Tennessee and North Carolina?',
 ARRAY['Blue Ridge Mountains', 'Smoky Mountains', 'Cumberland Mountains', 'Allegheny Mountains'],
 'Smoky Mountains', 'Geography', 4),
('Which state has the longest border with Canada?',
 ARRAY['Montana', 'North Dakota', 'Alaska', 'Michigan'],
 'Alaska', 'Geography', 3),
('What is the name of the large estuary in Virginia and Maryland that is the largest in the United States?',
 ARRAY['Delaware Bay', 'Albemarle Sound', 'Chesapeake Bay', 'Pamlico Sound'],
 'Chesapeake Bay', 'Geography', 2),
('Which US city is known as the "Gateway to the West"?',
 ARRAY['Kansas City', 'St. Louis', 'Chicago', 'Cincinnati'],
 'St. Louis', 'Geography', 3),
('What is the name of the chain of volcanic islands that extend westward from Alaska?',
 ARRAY['Kodiak Islands', 'Pribilof Islands', 'Aleutian Islands', 'Alexander Archipelago'],
 'Aleutian Islands', 'Geography', 4),
('Which river forms the eastern boundary between Oregon and Idaho?',
 ARRAY['Columbia River', 'Willamette River', 'Snake River', 'Deschutes River'],
 'Snake River', 'Geography', 6),
('What is the name of the large plateau in eastern Washington State known for its agricultural productivity?',
 ARRAY['Columbia Plateau', 'Snake River Plain', 'Palouse', 'Channeled Scablands'],
 'Palouse', 'Geography', 8),
('Which US state contains the largest area of desert?',
 ARRAY['Nevada', 'Arizona', 'New Mexico', 'California'],
 'Nevada', 'Geography', 5),
('What is the name of the narrow passage between the Atlantic Ocean and the Gulf of Mexico at the southern tip of Florida?',
 ARRAY['Straits of Florida', 'Florida Passage', 'Caribbean Strait', 'Florida Channel'],
 'Straits of Florida', 'Geography', 6),
('Which US state has the highest number of active volcanoes?',
 ARRAY['Hawaii', 'Washington', 'Oregon', 'Alaska'],
 'Alaska', 'Geography', 5),
('What is the name of the large bay on the southern coast of Alaska?',
 ARRAY['Bristol Bay', 'Cook Inlet', 'Prince William Sound', 'Gulf of Alaska'],
 'Cook Inlet', 'Geography', 6),
('Which of the following states is NOT part of the New England region?',
 ARRAY['Vermont', 'New Hampshire', 'New York', 'Maine'],
 'New York', 'Geography', 3),
('What is the name of the major aquifer that underlies a large portion of the Southeast United States?',
 ARRAY['High Plains Aquifer', 'Floridan Aquifer', 'Gulf Coast Aquifer', 'Southeastern Aquifer'],
 'Floridan Aquifer', 'Geography', 8),
('Which US city sits at the confluence of the Allegheny and Monongahela rivers?',
 ARRAY['Cleveland', 'Cincinnati', 'Pittsburgh', 'Buffalo'],
 'Pittsburgh', 'Geography', 4),
('Which state contains the geographic center of the contiguous United States?',
 ARRAY['Kansas', 'Nebraska', 'Missouri', 'Oklahoma'],
 'Kansas', 'Geography', 5),
('What is the name of the low-lying region along the Atlantic and Gulf coasts that extends from New Jersey to Texas?',
 ARRAY['Piedmont', 'Tidewater', 'Atlantic Coastal Plain', 'Gulf Lowlands'],
 'Atlantic Coastal Plain', 'Geography', 5),
('Which river drains into the Gulf of Mexico near New Orleans?',
 ARRAY['Missouri River', 'Ohio River', 'Mississippi River', 'Arkansas River'],
 'Mississippi River', 'Geography', 1),
('What is the name of the large swamp in southeastern Georgia and northeastern Florida?',
 ARRAY['Great Dismal Swamp', 'Atchafalaya Swamp', 'Okefenokee Swamp', 'Everglades'],
 'Okefenokee Swamp', 'Geography', 5),
('Which US state is home to Glacier National Park?',
 ARRAY['Wyoming', 'Idaho', 'Montana', 'Colorado'],
 'Montana', 'Geography', 3),
('What is the name of the fertile river valley in California known as the breadbasket of the state?',
 ARRAY['Napa Valley', 'San Joaquin Valley', 'Central Valley', 'Imperial Valley'],
 'Central Valley', 'Geography', 4),
('Which large lake sits on the border between the United States and Canada in the northeast?',
 ARRAY['Lake Huron', 'Lake Ontario', 'Lake Champlain', 'Lake Erie'],
 'Lake Ontario', 'Geography', 4),
('What is the name of the high desert plateau in Utah known for its red rock formations?',
 ARRAY['Colorado Plateau', 'Great Basin', 'Uinta Basin', 'Escalante Basin'],
 'Colorado Plateau', 'Geography', 5),
('Which US city is the southernmost major city on the mainland?',
 ARRAY['Miami', 'Key West', 'Brownsville', 'New Orleans'],
 'Brownsville', 'Geography', 7),
('What is the name of the long, narrow island that runs parallel to Long Island Sound?',
 ARRAY['Fire Island', 'Long Beach Island', 'Block Island', 'Fishers Island'],
 'Fire Island', 'Geography', 7),
('Which state borders both the Pacific Ocean and the Gulf of California?',
 ARRAY['No US state does', 'California', 'Arizona', 'New Mexico'],
 'No US state does', 'Geography', 8),
('What is the name of the unique geological region in southwest Wisconsin that escaped glaciation?',
 ARRAY['Baraboo Hills', 'Driftless Area', 'Kettle Moraine', 'Ice Age Trail'],
 'Driftless Area', 'Geography', 8),
('Which state capital sits at the highest elevation above sea level?',
 ARRAY['Denver, Colorado', 'Cheyenne, Wyoming', 'Salt Lake City, Utah', 'Santa Fe, New Mexico'],
 'Santa Fe, New Mexico', 'Geography', 6),
('What is the name of the river that forms the boundary between Illinois and Missouri?',
 ARRAY['Ohio River', 'Wabash River', 'Mississippi River', 'Missouri River'],
 'Mississippi River', 'Geography', 4),
('Which US island territory is located roughly 2,400 miles southwest of Honolulu?',
 ARRAY['Wake Island', 'Johnston Atoll', 'Midway Atoll', 'Palmyra Atoll'],
 'Midway Atoll', 'Geography', 8),
('What is the name of the large natural harbor in San Francisco Bay that serves as a major port?',
 ARRAY['Oakland Harbor', 'Richmond Harbor', 'San Francisco Bay', 'Suisun Bay'],
 'San Francisco Bay', 'Geography', 3),
('Which US state contains a portion of the Great Smoky Mountains AND the Blue Ridge Parkway?',
 ARRAY['Tennessee', 'Georgia', 'North Carolina', 'Virginia'],
 'North Carolina', 'Geography', 5),
('What is the name of the vast underground cave system in Kentucky, the longest known in the world?',
 ARRAY['Carlsbad Caverns', 'Luray Caverns', 'Mammoth Cave', 'Jewel Cave'],
 'Mammoth Cave', 'Geography', 4),
('Which US city is built on a series of islands at the mouth of the Mississippi River?',
 ARRAY['Baton Rouge', 'Mobile', 'New Orleans', 'Biloxi'],
 'New Orleans', 'Geography', 5),
('What is the name of the mountain pass that was commonly used by pioneers traveling to California on the Oregon Trail?',
 ARRAY['Donner Pass', 'South Pass', 'Cumberland Gap', 'Raton Pass'],
 'South Pass', 'Geography', 7),
('What is the term for the flat-topped hills and mountains found throughout the American Southwest?',
 ARRAY['Buttes', 'Mesas', 'Plateaus', 'Pinnacles'],
 'Mesas', 'Geography', 3),
('Which US state is home to the Ozark Mountains?',
 ARRAY['Missouri', 'Oklahoma', 'Kentucky', 'Arkansas'],
 'Missouri', 'Geography', 5),
('What is the name of the body of water between the Florida peninsula and the Florida Panhandle?',
 ARRAY['Gulf of Mexico', 'Apalachee Bay', 'Tampa Bay', 'Charlotte Harbor'],
 'Apalachee Bay', 'Geography', 8),
('Which US city is sometimes called the "Emerald City"?',
 ARRAY['Portland, Oregon', 'Seattle, Washington', 'Denver, Colorado', 'Charlotte, North Carolina'],
 'Seattle, Washington', 'Geography', 3),
('What is the name of the large volcanic crater in Hawaii that is the world''s largest dormant volcano?',
 ARRAY['Kilauea', 'Mauna Loa', 'Haleakala', 'Hualalai'],
 'Haleakala', 'Geography', 6),
('Which river flows through the Grand Canyon?',
 ARRAY['Green River', 'San Juan River', 'Colorado River', 'Gila River'],
 'Colorado River', 'Geography', 2),
('What is the name of the northernmost point of the contiguous United States?',
 ARRAY['Point Barrow', 'Northwest Angle', 'Angle Inlet', 'Buffalo Pass'],
 'Northwest Angle', 'Geography', 9),
('Which US state has borders with the most other states?',
 ARRAY['Kentucky', 'Tennessee', 'Missouri', 'Colorado'],
 'Tennessee', 'Geography', 6);

-- Landmarks (50 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('The Alamo mission in San Antonio was originally built by which religious order?',
 ARRAY['Dominicans', 'Franciscans', 'Jesuits', 'Augustinians'],
 'Franciscans', 'Landmarks', 6),
('Which famous suspension bridge connects the upper and lower peninsulas of Michigan?',
 ARRAY['Mackinac Bridge', 'Ambassador Bridge', 'Blue Water Bridge', 'Zilwaukee Bridge'],
 'Mackinac Bridge', 'Landmarks', 4),
('The Lincoln Memorial in Washington DC contains a statue of Lincoln seated in how many feet tall?',
 ARRAY['15 feet', '19 feet', '26 feet', '30 feet'],
 '19 feet', 'Landmarks', 8),
('The National Mall in Washington DC stretches from the Capitol to which monument?',
 ARRAY['White House', 'Lincoln Memorial', 'Washington Monument', 'Jefferson Memorial'],
 'Lincoln Memorial', 'Landmarks', 3),
('Which famous road is known as the "Mother Road" stretching from Chicago to Santa Monica?',
 ARRAY['Route 40', 'Route 66', 'Route 1', 'Route 30'],
 'Route 66', 'Landmarks', 2),
('The Chrysler Building in New York City was briefly the world''s tallest building in which year?',
 ARRAY['1927', '1930', '1933', '1935'],
 '1930', 'Landmarks', 7),
('The Space Needle in Seattle was built for which World''s Fair?',
 ARRAY['1958 World''s Fair', '1960 World''s Fair', '1962 World''s Fair', '1964 World''s Fair'],
 '1962 World''s Fair', 'Landmarks', 5),
('Which famous American lighthouse is located on Cape Hatteras, North Carolina and features a distinctive black and white spiral pattern?',
 ARRAY['Cape Hatteras Light', 'Outer Banks Light', 'Diamond Shoals Light', 'Bodie Island Light'],
 'Cape Hatteras Light', 'Landmarks', 5),
('The Statue of Freedom atop the US Capitol building holds what in her right hand?',
 ARRAY['A torch', 'A sword', 'A sheathed sword and laurel wreath', 'A scroll'],
 'A sheathed sword and laurel wreath', 'Landmarks', 9),
('Jefferson Memorial in Washington DC is built in the style of which Roman building?',
 ARRAY['Colosseum', 'Pantheon', 'Forum', 'Circus Maximus'],
 'Pantheon', 'Landmarks', 6),
('The Bonneville Dam on the Columbia River straddles the border of which two states?',
 ARRAY['Washington and Idaho', 'Oregon and Washington', 'Oregon and California', 'Idaho and Montana'],
 'Oregon and Washington', 'Landmarks', 6),
('Fallingwater, designed by Frank Lloyd Wright, is located in which state?',
 ARRAY['Illinois', 'Wisconsin', 'Pennsylvania', 'Ohio'],
 'Pennsylvania', 'Landmarks', 4),
('The original World Trade Center Twin Towers were designed by which architect?',
 ARRAY['I.M. Pei', 'Minoru Yamasaki', 'Philip Johnson', 'Eero Saarinen'],
 'Minoru Yamasaki', 'Landmarks', 7),
('Which American monument features the face of Chief Crazy Horse being carved into a mountain in South Dakota?',
 ARRAY['Sitting Bull Memorial', 'Crazy Horse Memorial', 'Native American Heritage Monument', 'Black Hills Monument'],
 'Crazy Horse Memorial', 'Landmarks', 3),
('The famous Painted Ladies Victorian houses are located in which American city?',
 ARRAY['Portland', 'Seattle', 'San Francisco', 'Denver'],
 'San Francisco', 'Landmarks', 4),
('The Grand Central Terminal in New York City opened in which year?',
 ARRAY['1903', '1908', '1913', '1919'],
 '1913', 'Landmarks', 6),
('Which bridge, opened in 1883, was the longest suspension bridge in the world at the time of its completion?',
 ARRAY['Manhattan Bridge', 'Williamsburg Bridge', 'Brooklyn Bridge', 'Queensboro Bridge'],
 'Brooklyn Bridge', 'Landmarks', 3),
('The Thomas Jefferson Memorial was dedicated in which year?',
 ARRAY['1935', '1939', '1943', '1947'],
 '1943', 'Landmarks', 7),
('The Hoover Dam is located on which river?',
 ARRAY['Colorado River', 'Rio Grande', 'Sacramento River', 'Snake River'],
 'Colorado River', 'Landmarks', 2),
('Which famous Frank Lloyd Wright building in New York City is shaped like a spiral ramp?',
 ARRAY['Guggenheim Museum', 'Carnegie Hall', 'Lincoln Center', 'MoMA'],
 'Guggenheim Museum', 'Landmarks', 4),
('The Gateway Arch in St. Louis is exactly how tall?',
 ARRAY['550 feet', '630 feet', '700 feet', '720 feet'],
 '630 feet', 'Landmarks', 6),
('What is the name of the famous fountain in Kansas City, Missouri, that is known as the City of Fountains?',
 ARRAY['Crown Fountain', 'J.C. Nichols Memorial Fountain', 'Buckingham Fountain', 'Bethesda Fountain'],
 'J.C. Nichols Memorial Fountain', 'Landmarks', 8),
('The Touro Synagogue in Newport, Rhode Island is the oldest surviving synagogue in the United States, built in which century?',
 ARRAY['17th century', '18th century', '19th century', '16th century'],
 '18th century', 'Landmarks', 7),
('Which iconic Las Vegas landmark was imploded in 1993 to make way for a new resort?',
 ARRAY['Riviera Hotel', 'Sands Hotel', 'Dunes Hotel', 'Flamingo Hotel'],
 'Dunes Hotel', 'Landmarks', 8),
('The original Faneuil Hall in Boston was built as what type of structure?',
 ARRAY['A church', 'A market and meeting hall', 'A government building', 'A theater'],
 'A market and meeting hall', 'Landmarks', 5),
('The famous Biltmore Estate in Asheville, NC was built by which wealthy family?',
 ARRAY['Carnegie', 'Rockefeller', 'Vanderbilt', 'Morgan'],
 'Vanderbilt', 'Landmarks', 4),
('The Mall of America in Bloomington, Minnesota is built on the former site of which demolished stadium?',
 ARRAY['Metropolitan Stadium', 'Memorial Stadium', 'Bloomington Civic Arena', 'Hubert H. Humphrey Dome'],
 'Metropolitan Stadium', 'Landmarks', 8),
('Which iconic building in Chicago is known for its distinctive corncob-shaped towers?',
 ARRAY['John Hancock Center', 'Marina City', 'Tribune Tower', 'Wrigley Building'],
 'Marina City', 'Landmarks', 6),
('The Crystal Cathedral, a famous glass megachurch, is located in which California city?',
 ARRAY['Los Angeles', 'San Diego', 'Garden Grove', 'Anaheim'],
 'Garden Grove', 'Landmarks', 7),
('The National Cathedral in Washington DC took how many years to complete?',
 ARRAY['43 years', '63 years', '83 years', '95 years'],
 '83 years', 'Landmarks', 8),
('Which US state capitol building is the only one that is not connected to any other structure?',
 ARRAY['Texas State Capitol', 'New Hampshire State House', 'Montana State Capitol', 'Wyoming State Capitol'],
 'New Hampshire State House', 'Landmarks', 9),
('The famous Longfellow Bridge in Boston crosses which river?',
 ARRAY['Mystic River', 'Charles River', 'Neponset River', 'Sudbury River'],
 'Charles River', 'Landmarks', 6),
('The Hearst Castle in San Simeon, California has how many bedrooms?',
 ARRAY['18 bedrooms', '28 bedrooms', '38 bedrooms', '56 bedrooms'],
 '38 bedrooms', 'Landmarks', 7),
('Which historic hotel in New Orleans, built in 1886, is one of the oldest continuously operating hotels in the US?',
 ARRAY['Hotel Monteleone', 'Pontchartrain Hotel', 'The Roosevelt', 'Windsor Court Hotel'],
 'Hotel Monteleone', 'Landmarks', 8),
('The US Holocaust Memorial Museum is located on which street in Washington DC?',
 ARRAY['Pennsylvania Avenue', 'Independence Avenue', 'Constitution Avenue', 'Maryland Avenue'],
 'Independence Avenue', 'Landmarks', 7),
('Which famous racetrack in Maryland has hosted the Preakness Stakes since 1873?',
 ARRAY['Laurel Park', 'Pimlico Race Course', 'Bowie Race Course', 'Timonium Fairgrounds'],
 'Pimlico Race Course', 'Landmarks', 5),
('The Neon Museum in which US city preserves historic neon signs from the city''s past?',
 ARRAY['Los Angeles', 'Las Vegas', 'Atlantic City', 'Reno'],
 'Las Vegas', 'Landmarks', 4),
('Which American city is home to the famous Market Street, once one of the busiest commercial streets in the nation?',
 ARRAY['Philadelphia', 'Boston', 'New York City', 'San Francisco'],
 'San Francisco', 'Landmarks', 5),
('The Cahokia Mounds, the largest pre-Columbian settlement north of Mexico, are located in which state?',
 ARRAY['Missouri', 'Illinois', 'Iowa', 'Indiana'],
 'Illinois', 'Landmarks', 6),
('The Empire State Building was completed in which year?',
 ARRAY['1929', '1930', '1931', '1933'],
 '1931', 'Landmarks', 3),
('The National Mall in Washington DC is approximately how long?',
 ARRAY['1.5 miles', '2 miles', '3 miles', '4 miles'],
 '2 miles', 'Landmarks', 6),
('The famous Pike Place Market in Seattle has been in continuous operation since which year?',
 ARRAY['1897', '1907', '1917', '1927'],
 '1907', 'Landmarks', 6),
('Which famous outdoor amphitheater near Denver, Colorado is carved into red sandstone formations?',
 ARRAY['Red Rocks Amphitheatre', 'Fiddler''s Green', 'Chautauqua Auditorium', 'Fillmore Auditorium'],
 'Red Rocks Amphitheatre', 'Landmarks', 3),
('The famous "Four Corners" monument marks the meeting point of which four US states?',
 ARRAY['Utah, Colorado, Arizona, New Mexico', 'Utah, Nevada, Arizona, California', 'Colorado, Kansas, Oklahoma, New Mexico', 'Utah, Colorado, Wyoming, Idaho'],
 'Utah, Colorado, Arizona, New Mexico', 'Landmarks', 3),
('Which famous steel arch bridge is located in Charleston, South Carolina?',
 ARRAY['Ravenel Bridge', 'Harbour Bridge', 'Cooper River Bridge', 'Ashley River Bridge'],
 'Ravenel Bridge', 'Landmarks', 7),
('The famous "Welcome to Las Vegas" sign was designed by which artist?',
 ARRAY['Betty Willis', 'Yesco Signs', 'Young Electric Sign Company', 'Ted Vierra'],
 'Betty Willis', 'Landmarks', 7),
('The historic Fort McHenry in Baltimore, Maryland inspired which famous American work?',
 ARRAY['America the Beautiful', 'The Pledge of Allegiance', 'The Star-Spangled Banner', 'Yankee Doodle'],
 'The Star-Spangled Banner', 'Landmarks', 3),
('The Transamerica Pyramid building is an iconic part of the skyline of which US city?',
 ARRAY['Los Angeles', 'Seattle', 'San Francisco', 'Portland'],
 'San Francisco', 'Landmarks', 3),
('Which famous clock tower is part of the historic ferry building in San Francisco?',
 ARRAY['Ferry Building Tower', 'Embarcadero Clock Tower', 'The Ferry Clock', 'The Harbor Tower'],
 'Ferry Building Tower', 'Landmarks', 7),
('The famous "Hollywood" sign originally read what when it was first erected in 1923?',
 ARRAY['HOLLYWOODLAND', 'HOLLYWOODVILLE', 'HOLLYWOODS', 'HOLLYWOOD ESTATES'],
 'HOLLYWOODLAND', 'Landmarks', 4);

-- Military (49 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What was the name of the surprise Japanese attack on the US naval base in Hawaii on December 7, 1941?',
 ARRAY['Operation Typhoon', 'Operation Z', 'Operation Barbarossa', 'Operation Sea Lion'],
 'Operation Z', 'Military', 7),
('Which Confederate general surrendered to Ulysses S. Grant at Appomattox Court House in 1865?',
 ARRAY['Stonewall Jackson', 'James Longstreet', 'Robert E. Lee', 'Braxton Bragg'],
 'Robert E. Lee', 'Military', 2),
('The sinking of which ship in Havana Harbor in 1898 helped spark the Spanish-American War?',
 ARRAY['USS Maine', 'USS Monitor', 'USS Merrimack', 'USS Arizona'],
 'USS Maine', 'Military', 3),
('Which US general was dismissed by President Truman during the Korean War for insubordination?',
 ARRAY['Omar Bradley', 'Douglas MacArthur', 'Matthew Ridgway', 'Mark Clark'],
 'Douglas MacArthur', 'Military', 4),
('The Tet Offensive of 1968 was a major military campaign during which war?',
 ARRAY['World War II', 'Korean War', 'Vietnam War', 'Gulf War'],
 'Vietnam War', 'Military', 3),
('Which US Navy ship was seized by North Korea in 1968 and never returned?',
 ARRAY['USS Pueblo', 'USS Liberty', 'USS Stark', 'USS Vincennes'],
 'USS Pueblo', 'Military', 8),
('What was the name of the first American to be killed in the Civil War, shot at Fort Sumter?',
 ARRAY['No one died at Fort Sumter', 'Private Daniel Hough', 'Captain Abner Doubleday', 'Major Robert Anderson'],
 'Private Daniel Hough', 'Military', 9),
('The American Expeditionary Forces in World War I were commanded by which general?',
 ARRAY['John Pershing', 'George Patton', 'Douglas MacArthur', 'Leonard Wood'],
 'John Pershing', 'Military', 5),
('Which battle in 1777 is often called the turning point of the American Revolutionary War?',
 ARRAY['Battle of Bunker Hill', 'Battle of Trenton', 'Battle of Saratoga', 'Battle of Yorktown'],
 'Battle of Saratoga', 'Military', 4),
('What was the first major land battle of the Civil War, fought in Virginia in July 1861?',
 ARRAY['Battle of Shiloh', 'First Battle of Bull Run', 'Battle of Chancellorsville', 'Battle of Seven Pines'],
 'First Battle of Bull Run', 'Military', 4),
('Which US military unit is known as the "Rainbow Division" from World War I?',
 ARRAY['1st Infantry Division', '42nd Infantry Division', '82nd Airborne Division', '3rd Infantry Division'],
 '42nd Infantry Division', 'Military', 8),
('The Battle of Belleau Wood in 1918 established the combat reputation of which branch?',
 ARRAY['US Army Rangers', 'US Navy SEALs', 'US Marine Corps', 'US Army Airborne'],
 'US Marine Corps', 'Military', 6),
('Which operation was the US military''s evacuation of Saigon in April 1975?',
 ARRAY['Operation Eagle Pull', 'Operation Frequent Wind', 'Operation Desert Wind', 'Operation Homecoming'],
 'Operation Frequent Wind', 'Military', 7),
('The first major US naval victory of the War of 1812 was won by which warship against HMS Guerriere?',
 ARRAY['USS Constitution', 'USS Chesapeake', 'USS United States', 'USS President'],
 'USS Constitution', 'Military', 5),
('What term describes the military strategy of General William Sherman''s march through Georgia in 1864?',
 ARRAY['Blitzkrieg', 'Total War', 'Guerrilla Warfare', 'Siege Warfare'],
 'Total War', 'Military', 5),
('The United States entered World War I in which year?',
 ARRAY['1914', '1915', '1916', '1917'],
 '1917', 'Military', 2),
('Which Native American leader defeated Lt. Col. George Custer at the Battle of Little Bighorn in 1876?',
 ARRAY['Geronimo', 'Crazy Horse', 'Sitting Bull', 'Red Cloud'],
 'Sitting Bull', 'Military', 4),
('What was the code name for the Allied invasion of Sicily in 1943?',
 ARRAY['Operation Husky', 'Operation Avalanche', 'Operation Torch', 'Operation Dragoon'],
 'Operation Husky', 'Military', 7),
('Which US general earned the nickname "Old Blood and Guts" during World War II?',
 ARRAY['Omar Bradley', 'George Patton', 'Dwight Eisenhower', 'Mark Clark'],
 'George Patton', 'Military', 3),
('The Battle of Coral Sea in 1942 was historically significant because it was the first naval battle fought entirely using what?',
 ARRAY['Submarines', 'Aircraft carriers', 'Torpedo boats', 'Battleships'],
 'Aircraft carriers', 'Military', 6),
('Which city was the scene of a famous 1836 battle where a small Texas force held off the Mexican army for 13 days?',
 ARRAY['San Antonio', 'Houston', 'Austin', 'Galveston'],
 'San Antonio', 'Military', 3),
('The US military intervention in Grenada in 1983 was code-named what?',
 ARRAY['Operation Urgent Fury', 'Operation Just Cause', 'Operation Eagle Claw', 'Operation Blue Spoon'],
 'Operation Urgent Fury', 'Military', 6),
('Which World War II battle saw the largest tank engagement on the Western Front, fought in the Ardennes in late 1944?',
 ARRAY['Battle of the Huertgen Forest', 'Battle of the Bulge', 'Operation Market Garden', 'Battle of Caen'],
 'Battle of the Bulge', 'Military', 3),
('The failed 1961 invasion of Cuba supported by the CIA is known by what name?',
 ARRAY['Operation Mongoose', 'Bay of Pigs Invasion', 'Operation Pluto', 'Operation Trinidad'],
 'Bay of Pigs Invasion', 'Military', 3),
('What was the name of the US military''s strategy to prevent Soviet expansion after World War II?',
 ARRAY['The Monroe Doctrine', 'The Truman Doctrine', 'The Eisenhower Doctrine', 'The Marshall Plan'],
 'The Truman Doctrine', 'Military', 5),
('The 1st Cavalry Division was the first major US unit airlifted into combat in which war?',
 ARRAY['Korean War', 'Vietnam War', 'Gulf War', 'Iraq War'],
 'Vietnam War', 'Military', 6),
('Which battle in the Pacific theater involved the largest amphibious assault in the Pacific War?',
 ARRAY['Battle of Okinawa', 'Battle of Guadalcanal', 'Battle of Peleliu', 'Battle of Saipan'],
 'Battle of Okinawa', 'Military', 6),
('Operation Overlord''s airborne assault on D-Day involved which two US divisions?',
 ARRAY['82nd and 101st Airborne', '1st and 2nd Airborne', '4th and 9th Infantry', '29th and 1st Infantry'],
 '82nd and 101st Airborne', 'Military', 7),
('The US Navy''s first submarine used in combat was the H.L. Hunley, which served which side during the Civil War?',
 ARRAY['Union', 'Confederate', 'It was neutral', 'Spanish Navy'],
 'Confederate', 'Military', 6),
('Which US president ordered the dropping of atomic bombs on Japan?',
 ARRAY['Franklin Roosevelt', 'Harry Truman', 'Dwight Eisenhower', 'Herbert Hoover'],
 'Harry Truman', 'Military', 2),
('The Battle of Ia Drang Valley in 1965 was the first major engagement between US Army forces and which enemy?',
 ARRAY['Viet Cong guerrillas', 'North Vietnamese Army regulars', 'Khmer Rouge', 'Pathet Lao'],
 'North Vietnamese Army regulars', 'Military', 7),
('Which Medal of Honor recipient single-handedly held off an enemy company during the Korean War, famed for his one-man stand at the Imjin River?',
 ARRAY['Audie Murphy', 'Hector Cafferata', 'Lewis Millett', 'Raymond Harvey'],
 'Hector Cafferata', 'Military', 9),
('The USNS Comfort and USNS Mercy are what type of military vessel?',
 ARRAY['Aircraft carriers', 'Hospital ships', 'Destroyer escorts', 'Amphibious assault ships'],
 'Hospital ships', 'Military', 5),
('What military operation in 1980 failed due to a helicopter crash in the Iranian desert while attempting to rescue American hostages?',
 ARRAY['Operation Cyclone', 'Operation Eagle Claw', 'Operation Credible Sport', 'Operation Honey Badger'],
 'Operation Eagle Claw', 'Military', 6),
('The 54th Massachusetts Infantry Regiment was notable for being composed primarily of whom during the Civil War?',
 ARRAY['Irish immigrants', 'African American soldiers', 'German immigrants', 'Native American soldiers'],
 'African American soldiers', 'Military', 4),
('What is the name of the military cemetery where most soldiers killed on D-Day are buried in France?',
 ARRAY['Meuse-Argonne American Cemetery', 'Aisne-Marne American Cemetery', 'Normandy American Cemetery', 'Ardennes American Cemetery'],
 'Normandy American Cemetery', 'Military', 5),
('Which US warship was sunk in Pearl Harbor and later raised, serving as the symbol of the attack?',
 ARRAY['USS Arizona', 'USS Nevada', 'USS Oklahoma', 'USS California'],
 'USS Arizona', 'Military', 2),
('The Siege of Vicksburg in 1863 gave the Union control of which strategically vital waterway?',
 ARRAY['Ohio River', 'Tennessee River', 'Mississippi River', 'Cumberland River'],
 'Mississippi River', 'Military', 4),
('What is the name of the Cold War military alliance that the United States helped found in 1949?',
 ARRAY['SEATO', 'NATO', 'CENTO', 'Warsaw Pact'],
 'NATO', 'Military', 2),
('The famous "Frozen Chosin" nickname refers to the extreme cold conditions US Marines faced in which battle?',
 ARRAY['Battle of Inchon', 'Battle of Pusan Perimeter', 'Battle of Chosin Reservoir', 'Battle of Triangle Hill'],
 'Battle of Chosin Reservoir', 'Military', 5),
('Operation Rolling Thunder was a sustained US bombing campaign against which country?',
 ARRAY['Cambodia', 'Laos', 'North Vietnam', 'North Korea'],
 'North Vietnam', 'Military', 5),
('Which US Army Ranger unit conducted the famous 1945 raid on the Cabanatuan POW camp in the Philippines?',
 ARRAY['1st Ranger Battalion', '6th Ranger Battalion', '3rd Ranger Battalion', '5th Ranger Battalion'],
 '6th Ranger Battalion', 'Military', 9),
('The Zimmermann Telegram, which helped bring the US into World War I, proposed a military alliance between Germany and which country?',
 ARRAY['Austria-Hungary', 'Mexico', 'Japan', 'Turkey'],
 'Mexico', 'Military', 5),
('What is the name of the US nuclear submarine that was lost with all hands in 1968?',
 ARRAY['USS Thresher', 'USS Scorpion', 'USS Triton', 'USS Nautilus'],
 'USS Scorpion', 'Military', 8),
('The Siege of Khe Sanh in 1968 was a 77-day battle during which war?',
 ARRAY['Korean War', 'World War II', 'Vietnam War', 'Gulf War'],
 'Vietnam War', 'Military', 5),
('Which US Army division is nicknamed the "Big Red One"?',
 ARRAY['2nd Infantry Division', '3rd Infantry Division', '1st Infantry Division', '4th Infantry Division'],
 '1st Infantry Division', 'Military', 6),
('The first US military action under the United Nations flag occurred during which conflict?',
 ARRAY['World War II', 'Korean War', 'Vietnam War', 'Gulf War'],
 'Korean War', 'Military', 6),
('What was the name of the US military draft lottery system used during the Vietnam War era?',
 ARRAY['Selective Service System', 'Universal Service Draft', 'Compulsory Military Service', 'National Defense Draft'],
 'Selective Service System', 'Military', 4),
('The military campaign to retake the Philippines in 1944-45 began with the invasion of which island?',
 ARRAY['Luzon', 'Mindanao', 'Leyte', 'Palawan'],
 'Leyte', 'Military', 7);

-- National Parks (51 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which national park in Florida is the only subtropical preserve in North America and protects vast sawgrass prairies?',
 ARRAY['Everglades National Park', 'Biscayne National Park', 'Big Cypress National Preserve', 'Fakahatchee Strand Preserve'],
 'Everglades National Park', 'National Parks', 2),
('Zion National Park''s famous Angels Landing trail features a steep climb with what safety feature for the final stretch?',
 ARRAY['Wooden stairways', 'Steel cable handholds', 'Iron spike ladders', 'Safety netting'],
 'Steel cable handholds', 'National Parks', 4),
('Which national park contains the largest known cave system in the world, with over 400 miles of explored passages?',
 ARRAY['Carlsbad Caverns', 'Mammoth Cave', 'Wind Cave', 'Jewel Cave'],
 'Mammoth Cave', 'National Parks', 4),
('The volcanic landscape of which national park in New Mexico features lava tube caves and cinder cones?',
 ARRAY['White Sands', 'Carlsbad Caverns', 'Bandelier', 'El Malpais'],
 'El Malpais', 'National Parks', 8),
('Sequoia National Park''s General Sherman tree holds what record?',
 ARRAY['Tallest tree in the world', 'Oldest living tree in the world', 'Largest tree by volume in the world', 'Widest tree trunk in the world'],
 'Largest tree by volume in the world', 'National Parks', 3),
('Which national park in Maine is the only one located in New England and features the famous Cadillac Mountain?',
 ARRAY['White Mountain National Forest', 'Acadia National Park', 'Cape Cod National Seashore', 'Minute Man National Historical Park'],
 'Acadia National Park', 'National Parks', 2),
('The Kenai Fjords National Park is located in which US state and is known for its massive ice field?',
 ARRAY['Washington', 'Oregon', 'Alaska', 'Montana'],
 'Alaska', 'National Parks', 4),
('Which national park in Utah contains the highest concentration of natural arches in the world?',
 ARRAY['Zion', 'Bryce Canyon', 'Arches', 'Canyonlands'],
 'Arches', 'National Parks', 2),
('Which national park is known for its ancient petroglyphs and is located in Nevada?',
 ARRAY['Great Basin', 'Lake Mead', 'Basin and Range', 'Great Basin''s Lehman Caves'],
 'Great Basin', 'National Parks', 7),
('The Petrified Forest National Park in Arizona preserves fossilized trees from which geological period?',
 ARRAY['Jurassic Period', 'Cretaceous Period', 'Triassic Period', 'Permian Period'],
 'Triassic Period', 'National Parks', 6),
('Voyageurs National Park, known for its water-based travel, is located in which state?',
 ARRAY['Wisconsin', 'Michigan', 'Minnesota', 'North Dakota'],
 'Minnesota', 'National Parks', 5),
('Which national park protects the longest cave in the world, located in Kentucky?',
 ARRAY['Carlsbad Caverns', 'Mammoth Cave', 'Wind Cave', 'Lechuguilla Cave'],
 'Mammoth Cave', 'National Parks', 3),
('The famous "Half Dome" granite formation is a landmark in which national park?',
 ARRAY['Kings Canyon', 'Sequoia', 'Yosemite', 'Joshua Tree'],
 'Yosemite', 'National Parks', 2),
('Which national park in North Dakota contains the Theodore Roosevelt cabin where he lived as a rancher?',
 ARRAY['Badlands National Park', 'Theodore Roosevelt National Park', 'Wind Cave National Park', 'Devils Tower National Monument'],
 'Theodore Roosevelt National Park', 'National Parks', 4),
('The famous El Capitan granite monolith is located in which national park?',
 ARRAY['Kings Canyon National Park', 'Yosemite National Park', 'Sequoia National Park', 'Joshua Tree National Park'],
 'Yosemite National Park', 'National Parks', 2),
('Denali, the highest peak in North America, rises to approximately what elevation?',
 ARRAY['18,000 feet', '19,500 feet', '20,310 feet', '21,200 feet'],
 '20,310 feet', 'National Parks', 4),
('Which national park in South Dakota features colorful spires and contains some of the richest fossil beds in the world?',
 ARRAY['Wind Cave', 'Jewel Cave', 'Badlands', 'Mount Rushmore'],
 'Badlands', 'National Parks', 3),
('The Guadalupe Mountains National Park in Texas protects an ancient marine fossil reef from which geological period?',
 ARRAY['Jurassic', 'Permian', 'Cretaceous', 'Devonian'],
 'Permian', 'National Parks', 7),
('Which national park in Michigan consists of an archipelago of islands in Lake Superior?',
 ARRAY['Isle Royale', 'Sleeping Bear Dunes', 'Pictured Rocks', 'Keweenaw'],
 'Isle Royale', 'National Parks', 4),
('The famous "Delicate Arch" is the unofficial symbol of which state and which national park?',
 ARRAY['Colorado and Mesa Verde', 'Utah and Arches', 'Arizona and Grand Canyon', 'Nevada and Great Basin'],
 'Utah and Arches', 'National Parks', 3),
('Which national park in Virginia and West Virginia is known for its underground caverns and Luray Caverns?',
 ARRAY['Shenandoah', 'New River Gorge', 'Appalachian Trail', 'Blue Ridge Parkway'],
 'Shenandoah', 'National Parks', 5),
('The Channel Islands National Park protects islands off the coast of which California city?',
 ARRAY['San Francisco', 'San Diego', 'Los Angeles area/Ventura', 'Santa Barbara'],
 'Los Angeles area/Ventura', 'National Parks', 6),
('Which national park is the driest and hottest in the United States, with recorded temperatures exceeding 130°F?',
 ARRAY['Mojave', 'Joshua Tree', 'Death Valley', 'Saguaro'],
 'Death Valley', 'National Parks', 2),
('Cuyahoga Valley National Park is located between which two Ohio cities?',
 ARRAY['Columbus and Dayton', 'Cleveland and Akron', 'Toledo and Sandusky', 'Cincinnati and Columbus'],
 'Cleveland and Akron', 'National Parks', 5),
('Which national park in Oregon features the deepest lake in the United States?',
 ARRAY['Mount Hood National Forest', 'Crater Lake', 'Oregon Dunes', 'John Day Fossil Beds'],
 'Crater Lake', 'National Parks', 2),
('The Haleakala National Park in Hawaii protects a dormant volcano on which island?',
 ARRAY['The Big Island', 'Oahu', 'Kauai', 'Maui'],
 'Maui', 'National Parks', 4),
('Which national park in New Mexico preserves the ruins of an ancient Pueblo civilization and features large kiva structures?',
 ARRAY['Aztec Ruins', 'Bandelier', 'Chaco Culture', 'Petroglyph'],
 'Chaco Culture', 'National Parks', 6),
('The Great Smoky Mountains is the most visited national park. Approximately how many visitors does it receive annually?',
 ARRAY['5 million', '8 million', '12 million', '15 million'],
 '12 million', 'National Parks', 6),
('Which national park in Washington state is known for its old-growth temperate rainforest on the Olympic Peninsula?',
 ARRAY['North Cascades', 'Mount Rainier', 'Olympic', 'San Juan Islands'],
 'Olympic', 'National Parks', 3),
('The Wrangell-St. Elias National Park in Alaska is the largest national park in the US. How large is it?',
 ARRAY['8 million acres', '11 million acres', '13.2 million acres', '15 million acres'],
 '13.2 million acres', 'National Parks', 7),
('Which national park contains the highest paved road in the United States, Trail Ridge Road?',
 ARRAY['Grand Teton', 'Yellowstone', 'Rocky Mountain', 'Great Sand Dunes'],
 'Rocky Mountain', 'National Parks', 5),
('Biscayne National Park in Florida is unique because the majority of its area consists of what?',
 ARRAY['Mangrove forests', 'Underwater marine environment', 'Coastal wetlands', 'Sandy beaches'],
 'Underwater marine environment', 'National Parks', 6),
('The Congaree National Park in South Carolina protects one of the last remaining examples of what type of ecosystem?',
 ARRAY['Longleaf pine forest', 'Old-growth bottomland hardwood forest', 'Coastal salt marsh', 'Cypress swamp'],
 'Old-growth bottomland hardwood forest', 'National Parks', 7),
('Which national park in Colorado features a deep gorge carved by the Gunnison River with nearly vertical walls?',
 ARRAY['Mesa Verde', 'Great Sand Dunes', 'Black Canyon of the Gunnison', 'Rocky Mountain'],
 'Black Canyon of the Gunnison', 'National Parks', 4),
('The Kobuk Valley National Park in Alaska is notable for which unusual desert feature?',
 ARRAY['Geysers', 'Active volcanoes', 'Sand dunes above the Arctic Circle', 'Underground hot springs'],
 'Sand dunes above the Arctic Circle', 'National Parks', 7),
('Which national park in South Carolina preserves the largest intact old-growth forest on the East Coast?',
 ARRAY['Congaree', 'Cape Hatteras', 'Cape Lookout', 'Chattahoochee'],
 'Congaree', 'National Parks', 7),
('Joshua Tree National Park sits at the convergence of which two desert ecosystems?',
 ARRAY['Sonoran and Great Basin', 'Mojave and Sonoran', 'Chihuahuan and Mojave', 'Great Basin and Chihuahuan'],
 'Mojave and Sonoran', 'National Parks', 6),
('The Katmai National Park in Alaska is famous for bears gathering to catch which type of fish?',
 ARRAY['Trout', 'Halibut', 'Sockeye salmon', 'King crab'],
 'Sockeye salmon', 'National Parks', 4),
('Which national park in Nevada is home to the ancient bristlecone pine trees, some of the oldest living organisms on Earth?',
 ARRAY['Death Valley', 'Great Basin', 'Lake Mead', 'Basin and Range'],
 'Great Basin', 'National Parks', 5),
('The Lassen Volcanic National Park in California last erupted in which decade?',
 ARRAY['1890s', '1910s', '1930s', '1950s'],
 '1910s', 'National Parks', 6),
('Glacier Bay National Park in Alaska is famous for actively calving glaciers that have retreated significantly since which century?',
 ARRAY['17th century', '18th century', '19th century', '20th century'],
 '18th century', 'National Parks', 7),
('The Capitol Reef National Park in Utah is centered around which geological feature?',
 ARRAY['The Colorado Plateau', 'The Waterpocket Fold', 'The San Rafael Swell', 'The Book Cliffs'],
 'The Waterpocket Fold', 'National Parks', 6),
('Which is the easternmost national park in the United States?',
 ARRAY['Acadia', 'Cape Cod', 'Shenandoah', 'Virgin Islands'],
 'Virgin Islands', 'National Parks', 7),
('The Tallgrass Prairie National Preserve in Kansas protects one of the last remaining tallgrass prairie ecosystems. What percentage of original tallgrass prairie remains in North America?',
 ARRAY['Less than 4%', 'About 10%', 'About 20%', 'About 35%'],
 'Less than 4%', 'National Parks', 7),
('Which national park in Arizona was established to protect the saguaro cactus and is divided into two districts near Tucson?',
 ARRAY['Organ Pipe Cactus', 'Chiricahua', 'Saguaro', 'Tonto'],
 'Saguaro', 'National Parks', 4),
('Pinnacles National Park in California was formed by the remains of an ancient volcano that has moved northward along which fault?',
 ARRAY['Hayward Fault', 'Calaveras Fault', 'San Andreas Fault', 'Denali Fault'],
 'San Andreas Fault', 'National Parks', 6),
('The New River Gorge National Park in West Virginia was designated a national park in which year?',
 ARRAY['2016', '2018', '2020', '2022'],
 '2020', 'National Parks', 5),
('Which national park in Hawaii is home to Kilauea, one of the world''s most active volcanoes?',
 ARRAY['Haleakala', 'Hawaii Volcanoes', 'Kaloko-Honokohau', 'Pu''uhonua o Honaunau'],
 'Hawaii Volcanoes', 'National Parks', 2),
('The North Cascades National Park in Washington is sometimes called the "American Alps." It contains how many glaciers?',
 ARRAY['More than 300', 'About 150', 'About 75', 'About 50'],
 'More than 300', 'National Parks', 8),
('Which national park protects a massive ancient petrified sand dune formation in southern Utah?',
 ARRAY['Canyonlands', 'Capitol Reef', 'Zion', 'Bryce Canyon'],
 'Zion', 'National Parks', 6),
('The Apostle Islands National Lakeshore in Wisconsin is located on which Great Lake?',
 ARRAY['Lake Michigan', 'Lake Superior', 'Lake Huron', 'Lake Erie'],
 'Lake Superior', 'National Parks', 5);

-- US Sports (48 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which baseball player holds the career record for most strikeouts as a pitcher?',
 ARRAY['Bob Gibson', 'Randy Johnson', 'Steve Carlton', 'Nolan Ryan'],
 'Nolan Ryan', 'US Sports', 4),
('What NFL team plays its home games at Lambeau Field in Green Bay, Wisconsin?',
 ARRAY['Chicago Bears', 'Minnesota Vikings', 'Green Bay Packers', 'Detroit Lions'],
 'Green Bay Packers', 'US Sports', 2),
('Which boxer was nicknamed "The Brown Bomber" and dominated heavyweight boxing in the 1930s and 40s?',
 ARRAY['Jack Dempsey', 'Joe Louis', 'Rocky Marciano', 'Archie Moore'],
 'Joe Louis', 'US Sports', 5),
('In what year did the WNBA play its inaugural season?',
 ARRAY['1994', '1996', '1997', '1999'],
 '1997', 'US Sports', 5),
('Who holds the NHL record for most career assists?',
 ARRAY['Mario Lemieux', 'Mark Messier', 'Wayne Gretzky', 'Steve Yzerman'],
 'Wayne Gretzky', 'US Sports', 4),
('What is the name of the trophy awarded to the winner of the NHL Western Conference Finals?',
 ARRAY['Clarence Campbell Bowl', 'Prince of Wales Trophy', 'Conn Smythe Trophy', 'Art Ross Trophy'],
 'Clarence Campbell Bowl', 'US Sports', 8),
('Which American tennis player won a record 18 Grand Slam singles titles before being surpassed?',
 ARRAY['Andre Agassi', 'Jimmy Connors', 'Pete Sampras', 'John McEnroe'],
 'Pete Sampras', 'US Sports', 4),
('In which city is the Pro Football Hall of Fame located?',
 ARRAY['Pittsburgh, Pennsylvania', 'Canton, Ohio', 'Cleveland, Ohio', 'Indianapolis, Indiana'],
 'Canton, Ohio', 'US Sports', 4),
('Who was the first player to score 100 points in a single NBA game?',
 ARRAY['Michael Jordan', 'Kareem Abdul-Jabbar', 'LeBron James', 'Wilt Chamberlain'],
 'Wilt Chamberlain', 'US Sports', 2),
('What is the traditional first major golf tournament of the year, held in Augusta, Georgia?',
 ARRAY['US Open', 'The Masters', 'The Open Championship', 'PGA Championship'],
 'The Masters', 'US Sports', 2),
('Which US city''s baseball team is nicknamed the "Cubbies"?',
 ARRAY['Cincinnati', 'St. Louis', 'Chicago', 'Milwaukee'],
 'Chicago', 'US Sports', 1),
('Who was the first African American head coach to win the Super Bowl?',
 ARRAY['Mike Tomlin', 'Lovie Smith', 'Tony Dungy', 'Dennis Green'],
 'Tony Dungy', 'US Sports', 5),
('What is the length of a standard NASCAR race at the Daytona International Speedway?',
 ARRAY['400 miles', '500 miles', '600 miles', '450 miles'],
 '500 miles', 'US Sports', 3),
('Which American swimmer won a record 23 Olympic gold medals throughout his career?',
 ARRAY['Mark Spitz', 'Ryan Lochte', 'Michael Phelps', 'Nathan Adrian'],
 'Michael Phelps', 'US Sports', 2),
('In what year did the American Football League (AFL) merge with the NFL?',
 ARRAY['1966', '1968', '1970', '1972'],
 '1970', 'US Sports', 6),
('Which college football team has won the most national championships in history?',
 ARRAY['Notre Dame', 'Ohio State', 'Michigan', 'Alabama'],
 'Alabama', 'US Sports', 5),
('What is the name of the annual college football game played in Pasadena, California on New Year''s Day?',
 ARRAY['Sugar Bowl', 'Orange Bowl', 'Rose Bowl', 'Fiesta Bowl'],
 'Rose Bowl', 'US Sports', 2),
('Who holds the record for the most career home runs in Major League Baseball?',
 ARRAY['Babe Ruth', 'Hank Aaron', 'Barry Bonds', 'Alex Rodriguez'],
 'Barry Bonds', 'US Sports', 4),
('Which NBA team won the most consecutive championships (8 in a row from 1959-1966)?',
 ARRAY['Los Angeles Lakers', 'Chicago Bulls', 'Boston Celtics', 'Philadelphia 76ers'],
 'Boston Celtics', 'US Sports', 5),
('What is the maximum number of players allowed on an NHL team''s active roster?',
 ARRAY['20 players', '23 players', '22 players', '18 players'],
 '23 players', 'US Sports', 7),
('Who was the first woman inducted into the Naismith Memorial Basketball Hall of Fame?',
 ARRAY['Cheryl Miller', 'Ann Meyers', 'Carol Blazejowski', 'Nera White'],
 'Nera White', 'US Sports', 9),
('Which golfer holds the record for the most major championship titles?',
 ARRAY['Arnold Palmer', 'Tiger Woods', 'Gary Player', 'Jack Nicklaus'],
 'Jack Nicklaus', 'US Sports', 4),
('What year did the NBA introduce the three-point line?',
 ARRAY['1977', '1979', '1981', '1983'],
 '1979', 'US Sports', 6),
('Which American city hosted the 1980 Winter Olympic Games?',
 ARRAY['Denver, Colorado', 'Salt Lake City, Utah', 'Lake Placid, New York', 'Aspen, Colorado'],
 'Lake Placid, New York', 'US Sports', 5),
('Who was the first woman to compete in the Indianapolis 500?',
 ARRAY['Danica Patrick', 'Janet Guthrie', 'Sarah Fisher', 'Milka Duno'],
 'Janet Guthrie', 'US Sports', 6),
('What is the official name of the trophy awarded to the Super Bowl champion?',
 ARRAY['George Halas Trophy', 'Vince Lombardi Trophy', 'Pete Rozelle Trophy', 'Lamar Hunt Trophy'],
 'Vince Lombardi Trophy', 'US Sports', 3),
('Which team won the infamous "Miracle on Ice" game at the 1980 Winter Olympics?',
 ARRAY['Canada', 'Sweden', 'United States', 'Czechoslovakia'],
 'United States', 'US Sports', 3),
('How many feet is the distance between bases on a Major League Baseball field?',
 ARRAY['80 feet', '90 feet', '100 feet', '85 feet'],
 '90 feet', 'US Sports', 4),
('What is the name of the award given to the most outstanding player in the NHL playoffs?',
 ARRAY['Hart Trophy', 'Vezina Trophy', 'Conn Smythe Trophy', 'Calder Trophy'],
 'Conn Smythe Trophy', 'US Sports', 6),
('Which MLB player broke Lou Gehrig''s record for consecutive games played in 1995?',
 ARRAY['Pete Rose', 'Cal Ripken Jr.', 'Joe DiMaggio', 'Tony Gwynn'],
 'Cal Ripken Jr.', 'US Sports', 4),
('What is the distance of the Kentucky Derby horse race?',
 ARRAY['1 mile', '1.25 miles', '1.5 miles', '1.75 miles'],
 '1.25 miles', 'US Sports', 6),
('Which American tennis player defeated Bobby Riggs in the famous "Battle of the Sexes" match in 1973?',
 ARRAY['Chris Evert', 'Virginia Wade', 'Billie Jean King', 'Margaret Court'],
 'Billie Jean King', 'US Sports', 4),
('Who was the first player in NFL history to rush for more than 2,000 yards in a single season?',
 ARRAY['Walter Payton', 'Earl Campbell', 'O.J. Simpson', 'Tony Dorsett'],
 'O.J. Simpson', 'US Sports', 7),
('What is the name of the annual charity golf tournament founded by Bing Crosby that is now called the AT&T Pebble Beach Pro-Am?',
 ARRAY['Crosby Clambake', 'Bing Crosby National Pro-Am', 'Pebble Beach Invitational', 'Crosby Classic'],
 'Bing Crosby National Pro-Am', 'US Sports', 8),
('Which American gymnast became the first to win four gold medals at a single Olympic Games in 1984?',
 ARRAY['Cathy Rigby', 'Kim Zmeskal', 'Nadia Comaneci', 'Mary Lou Retton'],
 'Mary Lou Retton', 'US Sports', 4),
('What is the name of the award given to the most outstanding player in Major League Baseball?',
 ARRAY['Cy Young Award', 'MVP Award', 'Gold Glove Award', 'Silver Slugger Award'],
 'MVP Award', 'US Sports', 2),
('Which city is home to the NFL team called the "49ers"?',
 ARRAY['Los Angeles', 'Oakland', 'San Francisco', 'San Jose'],
 'San Francisco', 'US Sports', 2),
('Who was the first African American to play in the NHL?',
 ARRAY['Grant Fuhr', 'Tony McKegney', 'Willie O''Ree', 'Mike Marson'],
 'Willie O''Ree', 'US Sports', 6),
('What is the maximum score in a perfect game of bowling?',
 ARRAY['250', '275', '300', '310'],
 '300', 'US Sports', 2),
('Which US college athletic conference is known as the "SEC"?',
 ARRAY['Southeastern Conference', 'Southern Elevation Conference', 'Sports Excellence Conference', 'Sporting Elite Conference'],
 'Southeastern Conference', 'US Sports', 2),
('In what year did Jackie Robinson break the color barrier in Major League Baseball?',
 ARRAY['1945', '1947', '1949', '1951'],
 '1947', 'US Sports', 3),
('Which horse won the Triple Crown in 1973 and set records that still stand?',
 ARRAY['Seattle Slew', 'Affirmed', 'Secretariat', 'Citation'],
 'Secretariat', 'US Sports', 4),
('What is the official name of the trophy given to the MLB World Series champion?',
 ARRAY['The Commissioner''s Trophy', 'The World Series Trophy', 'The Championship Trophy', 'The Pennant Trophy'],
 'The Commissioner''s Trophy', 'US Sports', 6),
('Which American football player holds the record for most career touchdown passes?',
 ARRAY['Peyton Manning', 'Brett Favre', 'Drew Brees', 'Tom Brady'],
 'Tom Brady', 'US Sports', 4),
('What is the name of the annual college basketball tournament often called "March Madness"?',
 ARRAY['NIT Tournament', 'NCAA Tournament', 'NAIA Tournament', 'CBI Tournament'],
 'NCAA Tournament', 'US Sports', 1),
('Which American city hosted the Summer Olympics in 1996?',
 ARRAY['Chicago', 'Los Angeles', 'Atlanta', 'New York'],
 'Atlanta', 'US Sports', 3),
('What is the playing surface dimensions of a standard NBA basketball court in feet?',
 ARRAY['84 feet by 50 feet', '94 feet by 50 feet', '94 feet by 54 feet', '90 feet by 50 feet'],
 '94 feet by 50 feet', 'US Sports', 6),
('Which jockey rode Secretariat to the Triple Crown victory in 1973?',
 ARRAY['Willie Shoemaker', 'Steve Cauthen', 'Eddie Arcaro', 'Ron Turcotte'],
 'Ron Turcotte', 'US Sports', 7);

