-- Migration 018: Expand question bank (batch 9)
-- 369 questions across 8 categories

-- American Culture (43 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the name of the famous New York City parade that has been held every Thanksgiving since 1924?',
 ARRAY['Rose Parade', 'Macy''s Thanksgiving Day Parade', 'St. Patrick''s Day Parade', 'New Year''s Parade'],
 'Macy''s Thanksgiving Day Parade', 'American Culture', 2),
('The Harlem Renaissance was a cultural movement centered in New York City primarily during which decade?',
 ARRAY['1910s', '1920s', '1930s', '1940s'],
 '1920s', 'American Culture', 3),
('Which American musician is credited as the "Father of the Blues"?',
 ARRAY['Robert Johnson', 'Muddy Waters', 'W.C. Handy', 'Lead Belly'],
 'W.C. Handy', 'American Culture', 5),
('What is the name of the annual arts festival held in the Nevada desert that celebrates self-expression and community?',
 ARRAY['Lollapalooza', 'Burning Man', 'Electric Daisy Carnival', 'Lightning in a Bottle'],
 'Burning Man', 'American Culture', 3),
('Which American poet wrote "Leaves of Grass," a celebrated collection that includes "Song of Myself"?',
 ARRAY['Emily Dickinson', 'Henry Wadsworth Longfellow', 'Walt Whitman', 'Edgar Allan Poe'],
 'Walt Whitman', 'American Culture', 3),
('The Pulitzer Prize was established in 1917 and is administered by which institution?',
 ARRAY['Harvard University', 'Columbia University', 'Yale University', 'New York University'],
 'Columbia University', 'American Culture', 6),
('Which style of American music originated in New Orleans in the early 20th century, blending African, European, and Indigenous influences?',
 ARRAY['Blues', 'Jazz', 'Gospel', 'Ragtime'],
 'Jazz', 'American Culture', 2),
('The counterculture movement of the 1960s was symbolized by the massive outdoor music festival held in Woodstock, New York in what year?',
 ARRAY['1967', '1968', '1969', '1970'],
 '1969', 'American Culture', 2),
('What is the name of the popular PBS children''s television show that debuted in 1969 and features Muppet characters?',
 ARRAY['The Electric Company', 'Mr. Rogers'' Neighborhood', 'Sesame Street', 'Reading Rainbow'],
 'Sesame Street', 'American Culture', 2),
('Who painted the iconic American Gothic depicting a farmer and woman in front of a house with a Gothic window?',
 ARRAY['Norman Rockwell', 'Edward Hopper', 'Grant Wood', 'Andrew Wyeth'],
 'Grant Wood', 'American Culture', 4),
('Which American literary movement, associated with writers like Ralph Waldo Emerson and Henry David Thoreau, emphasized the inherent goodness of nature and people?',
 ARRAY['Realism', 'Naturalism', 'Transcendentalism', 'Romanticism'],
 'Transcendentalism', 'American Culture', 4),
('The grunge music movement of the late 1980s and early 1990s originated in which US city?',
 ARRAY['Portland', 'San Francisco', 'Los Angeles', 'Seattle'],
 'Seattle', 'American Culture', 3),
('Which American artist is best known for the 1942 painting "Nighthawks," depicting people at a diner late at night?',
 ARRAY['Grant Wood', 'Edward Hopper', 'Charles Sheeler', 'Reginald Marsh'],
 'Edward Hopper', 'American Culture', 4),
('Which American novel by Herman Melville, published in 1851, tells the story of Captain Ahab''s obsessive pursuit of a white whale?',
 ARRAY['Billy Budd', 'Typee', 'Moby-Dick', 'The Confidence-Man'],
 'Moby-Dick', 'American Culture', 3),
('The civil rights anthem "We Shall Overcome" has its roots in which musical tradition?',
 ARRAY['Delta blues', 'Gospel music', 'Folk music', 'Spirituals'],
 'Gospel music', 'American Culture', 5),
('Which American writer is associated with the Beat Generation and wrote "On the Road"?',
 ARRAY['Allen Ginsberg', 'Jack Kerouac', 'William S. Burroughs', 'Lawrence Ferlinghetti'],
 'Jack Kerouac', 'American Culture', 3),
('What year was the Smithsonian Institution founded in Washington, DC?',
 ARRAY['1836', '1846', '1861', '1876'],
 '1846', 'American Culture', 5),
('The concept of the "American Dream" was popularized by which author in his 1931 book "The Epic of America"?',
 ARRAY['Horatio Alger', 'James Truslow Adams', 'Frederick Jackson Turner', 'Benjamin Franklin'],
 'James Truslow Adams', 'American Culture', 7),
('Which famous comedian got her start on the TV show "I Love Lucy," which debuted in 1951?',
 ARRAY['Carol Burnett', 'Lucille Ball', 'Mary Tyler Moore', 'Phyllis Diller'],
 'Lucille Ball', 'American Culture', 2),
('Aaron Copland composed "Appalachian Spring" as a ballet score in 1944. The piece was commissioned by which choreographer?',
 ARRAY['Martha Graham', 'Agnes de Mille', 'Merce Cunningham', 'José Limón'],
 'Martha Graham', 'American Culture', 7),
('Which American literary figure is considered the founder of the detective fiction genre, writing stories about C. Auguste Dupin?',
 ARRAY['Mark Twain', 'Nathaniel Hawthorne', 'Edgar Allan Poe', 'Washington Irving'],
 'Edgar Allan Poe', 'American Culture', 5),
('What is the name of the Saturday Night Live sketch comedy show''s home network that has aired since 1975?',
 ARRAY['CBS', 'ABC', 'NBC', 'Fox'],
 'NBC', 'American Culture', 2),
('The Hudson River School was a 19th-century art movement known for its landscape paintings. Who was its founder?',
 ARRAY['Frederic Church', 'Albert Bierstadt', 'Thomas Cole', 'Winslow Homer'],
 'Thomas Cole', 'American Culture', 6),
('Which American animator and entertainment company founder created Mickey Mouse in 1928?',
 ARRAY['Max Fleischer', 'Chuck Jones', 'Walter Lantz', 'Walt Disney'],
 'Walt Disney', 'American Culture', 1),
('"Rosie the Riveter" became an iconic image of women working in wartime industries during WWII. What does she symbolize?',
 ARRAY['Pacifism', 'Women''s suffrage', 'Female capability and patriotism in wartime', 'Labor union rights'],
 'Female capability and patriotism in wartime', 'American Culture', 3),
('The first Thanksgiving is traditionally celebrated for the feast between Pilgrims and members of which Native American tribe in 1621?',
 ARRAY['Pequot', 'Narragansett', 'Wampanoag', 'Massachusetts'],
 'Wampanoag', 'American Culture', 4),
('Which American author''s novel "To Kill a Mockingbird" won the Pulitzer Prize in 1961?',
 ARRAY['Carson McCullers', 'Flannery O''Connor', 'Harper Lee', 'Truman Capote'],
 'Harper Lee', 'American Culture', 2),
('Pop Art emerged in the United States in the late 1950s. Which American artist became its most iconic figure?',
 ARRAY['Jasper Johns', 'Roy Lichtenstein', 'Andy Warhol', 'Robert Rauschenberg'],
 'Andy Warhol', 'American Culture', 3),
('The Oregon Trail video game, which taught generations of students about westward expansion, was developed by which educational company in the early 1970s?',
 ARRAY['Broderbund', 'MECC', 'The Learning Company', 'Davidson & Associates'],
 'MECC', 'American Culture', 5),
('Which American folk singer wrote protest songs like "This Land Is Your Land" and became a voice for working-class Americans during the Great Depression?',
 ARRAY['Pete Seeger', 'Woody Guthrie', 'Lead Belly', 'Josh White'],
 'Woody Guthrie', 'American Culture', 4),
('The Second City comedy troupe in Chicago, founded in 1959, launched the careers of many famous comedians. Which of the following did NOT get their start there?',
 ARRAY['Bill Murray', 'John Belushi', 'Tina Fey', 'Steve Martin'],
 'Steve Martin', 'American Culture', 6),
('Which American author wrote "The Grapes of Wrath," depicting the plight of migrant workers during the Great Depression?',
 ARRAY['William Faulkner', 'John Steinbeck', 'Upton Sinclair', 'Theodore Dreiser'],
 'John Steinbeck', 'American Culture', 3),
('The Ashcan School was an early 20th-century American art movement that focused on depicting which subject matter?',
 ARRAY['Pristine natural landscapes', 'Gritty urban everyday life', 'Idealized portraits of the wealthy', 'Abstract geometric forms'],
 'Gritty urban everyday life', 'American Culture', 6),
('Which American composer is famous for his patriotic marches, including "Stars and Stripes Forever," earning him the nickname "The March King"?',
 ARRAY['Irving Berlin', 'George M. Cohan', 'John Philip Sousa', 'Stephen Foster'],
 'John Philip Sousa', 'American Culture', 4),
('Dorothea Lange''s photograph "Migrant Mother," taken in 1936, became an iconic image of which era?',
 ARRAY['The Roaring Twenties', 'The Great Depression', 'The Dust Bowl migration', 'The New Deal era'],
 'The Great Depression', 'American Culture', 3),
('Which American music festival held annually in Austin, Texas combines music, film, and interactive media?',
 ARRAY['Lollapalooza', 'Bonnaroo', 'SXSW', 'ACL Fest'],
 'SXSW', 'American Culture', 3),
('Mark Twain''s novel "Adventures of Huckleberry Finn" was published in which year?',
 ARRAY['1876', '1880', '1884', '1890'],
 '1884', 'American Culture', 4),
('Which famous New York cabaret and theater district, associated with song publishing, was located on 28th Street in Manhattan in the early 20th century?',
 ARRAY['Broadway', 'Tin Pan Alley', 'Harlem', 'The Bowery'],
 'Tin Pan Alley', 'American Culture', 6),
('The Pledge of Allegiance was first published in which magazine in 1892?',
 ARRAY['The Saturday Evening Post', 'Harper''s Weekly', 'Youth''s Companion', 'The Atlantic Monthly'],
 'Youth''s Companion', 'American Culture', 7),
('Which American artist created the earthwork sculpture "Spiral Jetty" in 1970, built with black basalt rocks on the Great Salt Lake?',
 ARRAY['Cristo', 'Andy Goldsworthy', 'Richard Serra', 'Robert Smithson'],
 'Robert Smithson', 'American Culture', 7),
('Bebop jazz, which developed in the early 1940s, was pioneered primarily by musicians in which city?',
 ARRAY['Chicago', 'New Orleans', 'New York City', 'Kansas City'],
 'New York City', 'American Culture', 5),
('The graphic novel "Maus" by Art Spiegelman, which depicts the Holocaust using mice and cats, won the Pulitzer Prize in which year?',
 ARRAY['1986', '1988', '1992', '1995'],
 '1992', 'American Culture', 7),
('Which American social reformer and author wrote "The Jungle" in 1906, exposing unsanitary conditions in the meatpacking industry?',
 ARRAY['Jacob Riis', 'Ida Tarbell', 'Upton Sinclair', 'Lincoln Steffens'],
 'Upton Sinclair', 'American Culture', 4);

-- Civics (48 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('What is the term for a senator who serves as president of the Senate in the absence of the Vice President?',
 ARRAY['Senate Majority Leader', 'President pro tempore', 'Senate Whip', 'Speaker of the Senate'],
 'President pro tempore', 'Civics', 5),
('How many justices must agree for the Supreme Court to grant certiorari and hear a case?',
 ARRAY['Three', 'Four', 'Five', 'Six'],
 'Four', 'Civics', 7),
('What document preceded the Constitution as the framework of the United States government?',
 ARRAY['The Mayflower Compact', 'The Articles of Confederation', 'The Declaration of Independence', 'The Northwest Ordinance'],
 'The Articles of Confederation', 'Civics', 4),
('Which Supreme Court case established the principle of "separate but equal" in 1896?',
 ARRAY['Brown v. Board of Education', 'Dred Scott v. Sandford', 'Plessy v. Ferguson', 'Korematsu v. United States'],
 'Plessy v. Ferguson', 'Civics', 6),
('What is the minimum number of states needed to ratify a new Constitutional amendment?',
 ARRAY['26 states', '30 states', '34 states', '38 states'],
 '38 states', 'Civics', 4),
('What is the term for the power of Congress to investigate the executive branch?',
 ARRAY['Legislative veto', 'Congressional oversight', 'Judicial review', 'Executive privilege'],
 'Congressional oversight', 'Civics', 5),
('Which amendment grants citizenship to all persons born or naturalized in the United States?',
 ARRAY['13th Amendment', '14th Amendment', '15th Amendment', '16th Amendment'],
 '14th Amendment', 'Civics', 3),
('What is the name of the constitutional clause that requires states to return fugitives to the state where they committed a crime?',
 ARRAY['Full Faith and Credit Clause', 'Extradition Clause', 'Commerce Clause', 'Supremacy Clause'],
 'Extradition Clause', 'Civics', 7),
('What is the name of the process by which a sitting president can delay a bill by refusing to sign it while Congress remains in session?',
 ARRAY['Line-item veto', 'Pocket veto', 'Regular veto', 'Prorogation'],
 'Regular veto', 'Civics', 6),
('How many members does the House of Representatives have from each state at minimum?',
 ARRAY['One', 'Two', 'Three', 'Four'],
 'One', 'Civics', 4),
('What is the constitutional requirement for the number of years a person must have been a US citizen to run for the House of Representatives?',
 ARRAY['5 years', '7 years', '9 years', '14 years'],
 '7 years', 'Civics', 6),
('Which amendment gave Congress the power to levy income taxes?',
 ARRAY['14th Amendment', '15th Amendment', '16th Amendment', '17th Amendment'],
 '16th Amendment', 'Civics', 5),
('What is the term for a presidential appointment that bypasses Senate confirmation because it occurs during a congressional recess?',
 ARRAY['Emergency appointment', 'Recess appointment', 'Interim appointment', 'Ad hoc appointment'],
 'Recess appointment', 'Civics', 6),
('Which Supreme Court case ruled that political spending by corporations and unions is protected free speech?',
 ARRAY['Buckley v. Valeo', 'Citizens United v. FEC', 'McCutcheon v. FEC', 'First National Bank v. Bellotti'],
 'Citizens United v. FEC', 'Civics', 7),
('What is the term for the legal doctrine that allows federal law to override conflicting state law?',
 ARRAY['Incorporation doctrine', 'Federal preemption', 'Supremacy clause', 'Commerce power'],
 'Federal preemption', 'Civics', 6),
('Which amendment to the Constitution ratified in 1920 granted women the right to vote?',
 ARRAY['17th Amendment', '18th Amendment', '19th Amendment', '20th Amendment'],
 '19th Amendment', 'Civics', 2),
('What is the term for a bill that has been passed by both chambers of Congress and signed by the president?',
 ARRAY['Resolution', 'Statute', 'Ordinance', 'Decree'],
 'Statute', 'Civics', 4),
('Which constitutional clause gives Congress the authority to regulate interstate commerce?',
 ARRAY['Necessary and Proper Clause', 'Commerce Clause', 'General Welfare Clause', 'Supremacy Clause'],
 'Commerce Clause', 'Civics', 3),
('What is the required residency in the state before a senator can be elected to office?',
 ARRAY['Must be a resident at time of election', '1 year of residency', '2 years of residency', '5 years of residency'],
 'Must be a resident at time of election', 'Civics', 7),
('Which article of the Constitution deals with relations between states?',
 ARRAY['Article II', 'Article III', 'Article IV', 'Article V'],
 'Article IV', 'Civics', 5),
('What term describes the practice of drawing electoral district boundaries to favor a particular political party?',
 ARRAY['Reapportionment', 'Redistricting', 'Gerrymandering', 'Packing'],
 'Gerrymandering', 'Civics', 4),
('Which amendment established Prohibition by banning the manufacture, sale, and transportation of alcohol?',
 ARRAY['16th Amendment', '17th Amendment', '18th Amendment', '19th Amendment'],
 '18th Amendment', 'Civics', 4),
('What is the official title of the head of the Department of Justice?',
 ARRAY['Solicitor General', 'Attorney General', 'Secretary of Justice', 'Chief Counsel'],
 'Attorney General', 'Civics', 3),
('What is the constitutional minimum age to serve as Vice President of the United States?',
 ARRAY['30 years old', '35 years old', '40 years old', 'No minimum age specified'],
 '35 years old', 'Civics', 5),
('In which case did the Supreme Court rule that students do not shed their constitutional rights at the schoolhouse gate?',
 ARRAY['Bethel v. Fraser', 'Tinker v. Des Moines', 'Hazelwood v. Kuhlmeier', 'Morse v. Frederick'],
 'Tinker v. Des Moines', 'Civics', 7),
('What vote threshold is required in the Senate to ratify a treaty?',
 ARRAY['Simple majority (51%)', 'Three-fifths (60%)', 'Two-thirds (67%)', 'Three-fourths (75%)'],
 'Two-thirds (67%)', 'Civics', 4),
('What is the term for a formal opinion written by a Supreme Court justice who agrees with the majority''s conclusion but for different reasons?',
 ARRAY['Dissenting opinion', 'Per curiam opinion', 'Concurring opinion', 'Plurality opinion'],
 'Concurring opinion', 'Civics', 6),
('Which act passed in 1973 limits the president''s ability to deploy military forces without congressional approval?',
 ARRAY['National Security Act', 'War Powers Resolution', 'Defense Authorization Act', 'Use of Force Act'],
 'War Powers Resolution', 'Civics', 5),
('Which amendment repealed Prohibition?',
 ARRAY['19th Amendment', '20th Amendment', '21st Amendment', '22nd Amendment'],
 '21st Amendment', 'Civics', 3),
('What is the constitutional provision that allows Congress to create laws not explicitly listed in the Constitution?',
 ARRAY['Elastic Clause', 'Commerce Clause', 'General Welfare Clause', 'Supremacy Clause'],
 'Elastic Clause', 'Civics', 4),
('Which Supreme Court case established that suspects must be informed of their rights before police interrogation?',
 ARRAY['Mapp v. Ohio', 'Gideon v. Wainwright', 'Miranda v. Arizona', 'Terry v. Ohio'],
 'Miranda v. Arizona', 'Civics', 3),
('What is the term for the president''s constitutional authority to refuse to spend money appropriated by Congress?',
 ARRAY['Line-item veto', 'Rescission', 'Impoundment', 'Sequestration'],
 'Impoundment', 'Civics', 8),
('Which landmark 1954 case ruled racial segregation in public schools unconstitutional?',
 ARRAY['Plessy v. Ferguson', 'Sweatt v. Painter', 'Brown v. Board of Education', 'Missouri ex rel. Gaines v. Canada'],
 'Brown v. Board of Education', 'Civics', 3),
('What is the term for the practice where the Senate refuses to vote on a presidential nominee, effectively killing the nomination?',
 ARRAY['Filibuster', 'Blue slip', 'Cloture', 'Advise and withhold'],
 'Blue slip', 'Civics', 8),
('Which constitutional amendment lowered the voting age from 21 to 18?',
 ARRAY['24th Amendment', '25th Amendment', '26th Amendment', '27th Amendment'],
 '26th Amendment', 'Civics', 4),
('What is the name for the power of the president to refuse to comply with congressional subpoenas?',
 ARRAY['Presidential immunity', 'Executive privilege', 'Commander-in-chief power', 'Separation of powers'],
 'Executive privilege', 'Civics', 6),
('Which clause of the First Amendment prohibits the government from establishing an official religion?',
 ARRAY['Free Exercise Clause', 'Establishment Clause', 'Speech Clause', 'Assembly Clause'],
 'Establishment Clause', 'Civics', 5),
('How many total amendments have been added to the US Constitution as of 2024?',
 ARRAY['25', '26', '27', '28'],
 '27', 'Civics', 3),
('Which Supreme Court ruling held that burning the American flag is protected symbolic speech?',
 ARRAY['Cohen v. California', 'Snyder v. Phelps', 'Texas v. Johnson', 'Chaplinsky v. New Hampshire'],
 'Texas v. Johnson', 'Civics', 6),
('What is the term for a justice''s written explanation when the court declines to hear a case?',
 ARRAY['Denial cert memo', 'Respublica opinion', 'Statement respecting denial', 'Summary disposition'],
 'Statement respecting denial', 'Civics', 9),
('Which amendment grants the right to bear arms?',
 ARRAY['1st Amendment', '2nd Amendment', '3rd Amendment', '4th Amendment'],
 '2nd Amendment', 'Civics', 1),
('What is the name of the constitutional requirement that Congress must pass a federal budget?',
 ARRAY['Appropriations Clause', 'Budget Control Act', 'Spending Clause', 'Congressional Budget Act'],
 'Appropriations Clause', 'Civics', 8),
('Which constitutional amendment prohibits poll taxes in federal elections?',
 ARRAY['23rd Amendment', '24th Amendment', '25th Amendment', '26th Amendment'],
 '24th Amendment', 'Civics', 5),
('What is the term for when the president signs an executive order to direct agencies without a congressional vote?',
 ARRAY['Presidential directive', 'Executive order', 'Presidential memorandum', 'Administrative regulation'],
 'Executive order', 'Civics', 3),
('Which Supreme Court case ruled that the government cannot deny benefits to citizens solely based on race?',
 ARRAY['Bolling v. Sharpe', 'Shelley v. Kraemer', 'Loving v. Virginia', 'Heart of Atlanta Motel v. United States'],
 'Bolling v. Sharpe', 'Civics', 9),
('What is the constitutional term for the process Congress uses to fund specific government programs?',
 ARRAY['Budgeting', 'Appropriation', 'Authorization', 'Allocation'],
 'Appropriation', 'Civics', 5),
('Which amendment protects against quartering soldiers in private homes?',
 ARRAY['2nd Amendment', '3rd Amendment', '4th Amendment', '5th Amendment'],
 '3rd Amendment', 'Civics', 4),
('What is the term for the principle that courts should follow precedent set in earlier decisions?',
 ARRAY['Res judicata', 'Stare decisis', 'Collateral estoppel', 'Judicial restraint'],
 'Stare decisis', 'Civics', 6);

-- Famous Americans (42 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which American inventor is credited with developing the first practical steamboat in 1807?',
 ARRAY['James Watt', 'Robert Fulton', 'Eli Whitney', 'Oliver Evans'],
 'Robert Fulton', 'Famous Americans', 4),
('Who was the first American woman to earn a PhD in mathematics from an American university?',
 ARRAY['Maryam Mirzakhani', 'Emmy Noether', 'Christine Ladd-Franklin', 'Grace Hopper'],
 'Christine Ladd-Franklin', 'Famous Americans', 8),
('Which American author wrote "The Scarlet Letter"?',
 ARRAY['Herman Melville', 'Nathaniel Hawthorne', 'Washington Irving', 'James Fenimore Cooper'],
 'Nathaniel Hawthorne', 'Famous Americans', 4),
('Which American mathematician developed game theory and won the Nobel Prize in Economics?',
 ARRAY['John von Neumann', 'Claude Shannon', 'John Nash', 'Richard Feynman'],
 'John Nash', 'Famous Americans', 6),
('Which American architect designed Fallingwater in Pennsylvania?',
 ARRAY['I.M. Pei', 'Louis Sullivan', 'Frank Lloyd Wright', 'Philip Johnson'],
 'Frank Lloyd Wright', 'Famous Americans', 4),
('Who was the first woman to serve on the US Supreme Court?',
 ARRAY['Ruth Bader Ginsburg', 'Elena Kagan', 'Sandra Day O''Connor', 'Sonia Sotomayor'],
 'Sandra Day O''Connor', 'Famous Americans', 3),
('Which American jazz musician is known as the "Duke" and led one of the most famous big bands?',
 ARRAY['Count Basie', 'Duke Ellington', 'Louis Armstrong', 'Dizzy Gillespie'],
 'Duke Ellington', 'Famous Americans', 4),
('Who was the first Native American to serve as Vice President of the United States?',
 ARRAY['Jim Thorpe', 'Sequoyah', 'Charles Curtis', 'Will Rogers'],
 'Charles Curtis', 'Famous Americans', 8),
('Which American writer created the detective character Sherlock Holmes''s American counterpart, known as the Father of the American detective story?',
 ARRAY['Dashiell Hammett', 'Raymond Chandler', 'Edgar Allan Poe', 'Mickey Spillane'],
 'Edgar Allan Poe', 'Famous Americans', 5),
('Who invented the cotton gin in 1793?',
 ARRAY['Benjamin Franklin', 'Eli Whitney', 'Cyrus McCormick', 'Robert Fulton'],
 'Eli Whitney', 'Famous Americans', 3),
('Which American First Lady was the first to have a college degree?',
 ARRAY['Abigail Adams', 'Lucy Webb Hayes', 'Dolley Madison', 'Mary Todd Lincoln'],
 'Lucy Webb Hayes', 'Famous Americans', 8),
('Who was the first American to win a Nobel Prize in any category?',
 ARRAY['Theodore Roosevelt', 'Albert Michelson', 'Henry James', 'Woodrow Wilson'],
 'Albert Michelson', 'Famous Americans', 8),
('Which American novelist wrote "The Adventures of Huckleberry Finn"?',
 ARRAY['Mark Twain', 'Jack London', 'Bret Harte', 'O. Henry'],
 'Mark Twain', 'Famous Americans', 2),
('Which American scientist discovered the structure of DNA alongside Francis Crick?',
 ARRAY['Linus Pauling', 'James Watson', 'Rosalind Franklin', 'George Beadle'],
 'James Watson', 'Famous Americans', 4),
('Who founded Standard Oil Company in 1870?',
 ARRAY['Andrew Carnegie', 'J.P. Morgan', 'John D. Rockefeller', 'Cornelius Vanderbilt'],
 'John D. Rockefeller', 'Famous Americans', 4),
('Which American playwright wrote "A Streetcar Named Desire"?',
 ARRAY['Eugene O''Neill', 'Arthur Miller', 'Tennessee Williams', 'Edward Albee'],
 'Tennessee Williams', 'Famous Americans', 5),
('Which American inventor created the vulcanization process for rubber?',
 ARRAY['Thomas Edison', 'Charles Goodyear', 'Samuel Morse', 'Elias Howe'],
 'Charles Goodyear', 'Famous Americans', 6),
('Who was the American admiral who commanded Allied naval forces in the Pacific during World War II?',
 ARRAY['Chester Nimitz', 'William Halsey', 'Ernest King', 'Raymond Spruance'],
 'Chester Nimitz', 'Famous Americans', 6),
('Who was the first Hispanic American appointed to a US Cabinet position?',
 ARRAY['Henry Cisneros', 'Lauro Cavazos', 'Federico Pena', 'Alberto Gonzales'],
 'Lauro Cavazos', 'Famous Americans', 9),
('Which American composer wrote "Rhapsody in Blue" in 1924?',
 ARRAY['Aaron Copland', 'Leonard Bernstein', 'George Gershwin', 'Cole Porter'],
 'George Gershwin', 'Famous Americans', 5),
('Who was the first Black woman in space?',
 ARRAY['Mae Jemison', 'Sally Ride', 'Christa McAuliffe', 'Judith Resnik'],
 'Mae Jemison', 'Famous Americans', 5),
('Who was the American chemist who invented nylon at DuPont in 1935?',
 ARRAY['Leo Baekeland', 'Wallace Carothers', 'Herman Mark', 'Roy Plunkett'],
 'Wallace Carothers', 'Famous Americans', 8),
('Which American poet wrote "Song of Myself" and "O Captain! My Captain!"?',
 ARRAY['Emily Dickinson', 'Henry Wadsworth Longfellow', 'Walt Whitman', 'Ralph Waldo Emerson'],
 'Walt Whitman', 'Famous Americans', 4),
('Who was the first African American woman to win the Nobel Prize in Literature?',
 ARRAY['Alice Walker', 'Toni Morrison', 'Maya Angelou', 'Zora Neale Hurston'],
 'Toni Morrison', 'Famous Americans', 5),
('Which American astronomer discovered that the universe is expanding in 1929?',
 ARRAY['Carl Sagan', 'Neil deGrasse Tyson', 'Edwin Hubble', 'Harlow Shapley'],
 'Edwin Hubble', 'Famous Americans', 5),
('Who founded Hull House in Chicago in 1889, providing services to immigrants?',
 ARRAY['Susan B. Anthony', 'Elizabeth Cady Stanton', 'Dorothea Dix', 'Jane Addams'],
 'Jane Addams', 'Famous Americans', 5),
('Which American computer scientist is known as the "Mother of COBOL" for developing the programming language?',
 ARRAY['Ada Lovelace', 'Grace Hopper', 'Frances Allen', 'Jean Jennings Bartik'],
 'Grace Hopper', 'Famous Americans', 6),
('Who was the Lakota Sioux leader who defeated General Custer at the Battle of Little Bighorn?',
 ARRAY['Geronimo', 'Red Cloud', 'Sitting Bull', 'Crazy Horse'],
 'Sitting Bull', 'Famous Americans', 5),
('Which American writer coined the term "The Lost Generation" for post-WWI writers?',
 ARRAY['Ernest Hemingway', 'F. Scott Fitzgerald', 'Gertrude Stein', 'Ezra Pound'],
 'Gertrude Stein', 'Famous Americans', 7),
('Who was the first woman to receive the Medal of Honor, serving as a surgeon during the Civil War?',
 ARRAY['Clara Barton', 'Harriet Tubman', 'Mary Edwards Walker', 'Dorothea Dix'],
 'Mary Edwards Walker', 'Famous Americans', 8),
('Which American civil rights leader founded the National Urban League?',
 ARRAY['Booker T. Washington', 'W.E.B. Du Bois', 'Whitney Young', 'A. Philip Randolph'],
 'Whitney Young', 'Famous Americans', 8),
('Who invented the telephone?',
 ARRAY['Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Guglielmo Marconi'],
 'Alexander Graham Bell', 'Famous Americans', 1),
('Which American filmmaker directed "Citizen Kane," widely considered one of the greatest films ever made?',
 ARRAY['John Ford', 'Billy Wilder', 'Orson Welles', 'Howard Hawks'],
 'Orson Welles', 'Famous Americans', 5),
('Which American physicist developed the theory of relativity?',
 ARRAY['Niels Bohr', 'Werner Heisenberg', 'Richard Feynman', 'Albert Einstein'],
 'Albert Einstein', 'Famous Americans', 1),
('Who was the American labor leader who organized the United Farm Workers union?',
 ARRAY['Samuel Gompers', 'Walter Reuther', 'Cesar Chavez', 'John L. Lewis'],
 'Cesar Chavez', 'Famous Americans', 4),
('Which American marine biologist wrote "The Sea Around Us"?',
 ARRAY['Jacques Cousteau', 'Sylvia Earle', 'Rachel Carson', 'William Beebe'],
 'Rachel Carson', 'Famous Americans', 6),
('Who was the president of the Confederacy during the American Civil War?',
 ARRAY['Robert E. Lee', 'Jefferson Davis', 'Stonewall Jackson', 'Alexander Stephens'],
 'Jefferson Davis', 'Famous Americans', 4),
('Which American mathematican''s work in 1948 founded modern information theory?',
 ARRAY['Norbert Wiener', 'John von Neumann', 'Claude Shannon', 'Alan Turing'],
 'Claude Shannon', 'Famous Americans', 8),
('Who founded the National Association for the Advancement of Colored People (NAACP) in 1909?',
 ARRAY['Booker T. Washington', 'Frederick Douglass', 'W.E.B. Du Bois', 'Marcus Garvey'],
 'W.E.B. Du Bois', 'Famous Americans', 5),
('Which American general commanded US forces during the Korean War before being dismissed by President Truman?',
 ARRAY['Omar Bradley', 'Dwight Eisenhower', 'Douglas MacArthur', 'Matthew Ridgway'],
 'Douglas MacArthur', 'Famous Americans', 6),
('Who was the first Black woman appointed to a US Cabinet position?',
 ARRAY['Shirley Chisholm', 'Patricia Roberts Harris', 'Condoleezza Rice', 'Mae Jemison'],
 'Patricia Roberts Harris', 'Famous Americans', 9),
('Which American poet is known for the collection "Leaves of Grass" first published in 1855?',
 ARRAY['Emily Dickinson', 'Henry Wadsworth Longfellow', 'Walt Whitman', 'Edgar Allan Poe'],
 'Walt Whitman', 'Famous Americans', 4);

-- Geography (45 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which US state has the most tornadoes on average each year?',
 ARRAY['Oklahoma', 'Kansas', 'Texas', 'Nebraska'],
 'Texas', 'Geography', 4),
('What is the name of the large underground cave system found in Kentucky, the longest known in the world?',
 ARRAY['Carlsbad Caverns', 'Lechuguilla Cave', 'Mammoth Cave', 'Wind Cave'],
 'Mammoth Cave', 'Geography', 3),
('Which river forms the border between Oregon and Washington?',
 ARRAY['Snake River', 'Willamette River', 'Columbia River', 'Rogue River'],
 'Columbia River', 'Geography', 4),
('What is the northernmost state in the contiguous United States?',
 ARRAY['Montana', 'Minnesota', 'North Dakota', 'Maine'],
 'Minnesota', 'Geography', 5),
('Which US city is known as the "Windy City"?',
 ARRAY['Detroit', 'Chicago', 'Milwaukee', 'Cleveland'],
 'Chicago', 'Geography', 1),
('What body of water lies between the Florida peninsula and the Florida Keys?',
 ARRAY['Florida Bay', 'Biscayne Bay', 'Tampa Bay', 'Charlotte Harbor'],
 'Florida Bay', 'Geography', 6),
('What is the name of the fault line that runs through California and is responsible for frequent earthquakes?',
 ARRAY['Cascadia Fault', 'Hayward Fault', 'San Andreas Fault', 'Elsinore Fault'],
 'San Andreas Fault', 'Geography', 2),
('Which US territory is located in the Caribbean Sea and consists of two main islands?',
 ARRAY['Guam', 'American Samoa', 'US Virgin Islands', 'Puerto Rico'],
 'US Virgin Islands', 'Geography', 5),
('What is the name of the mountain range that runs along the eastern side of California?',
 ARRAY['Sierra Nevada', 'Coast Ranges', 'Cascades', 'Transverse Ranges'],
 'Sierra Nevada', 'Geography', 4),
('Which Great Lake is the smallest by surface area?',
 ARRAY['Lake Erie', 'Lake Ontario', 'Lake Huron', 'Lake Michigan'],
 'Lake Ontario', 'Geography', 5),
('In which state is the geographic center of the contiguous United States located?',
 ARRAY['Nebraska', 'Kansas', 'Missouri', 'Iowa'],
 'Kansas', 'Geography', 6),
('What is the name of the large peninsula that makes up the southern portion of Florida?',
 ARRAY['Yucatan Peninsula', 'Floridian Peninsula', 'Delmarva Peninsula', 'Cape Canaveral'],
 'Floridian Peninsula', 'Geography', 3),
('Which state is home to the Badlands National Park?',
 ARRAY['Wyoming', 'Montana', 'North Dakota', 'South Dakota'],
 'South Dakota', 'Geography', 3),
('What is the name of the underwater volcanic ridge system off the coast of the Pacific Northwest?',
 ARRAY['Aleutian Ridge', 'Juan de Fuca Ridge', 'Mid-Atlantic Ridge', 'Cascadia Ridge'],
 'Juan de Fuca Ridge', 'Geography', 8),
('Which state has the most rivers by total length?',
 ARRAY['Minnesota', 'Missouri', 'Texas', 'Alaska'],
 'Texas', 'Geography', 6),
('Which US city is the southernmost state capital in the contiguous United States?',
 ARRAY['Austin, Texas', 'Baton Rouge, Louisiana', 'Tallahassee, Florida', 'Honolulu, Hawaii'],
 'Tallahassee, Florida', 'Geography', 5),
('What is the name of the volcanic island chain that extends westward from Alaska nearly 1,200 miles into the Pacific?',
 ARRAY['Hawaiian Islands', 'Pribilof Islands', 'Kodiak Islands', 'Aleutian Islands'],
 'Aleutian Islands', 'Geography', 5),
('Which state contains the most freshwater lakes?',
 ARRAY['Wisconsin', 'Michigan', 'Minnesota', 'Alaska'],
 'Minnesota', 'Geography', 5),
('What is the name of the plateau region in eastern Washington, Oregon, and Idaho formed by ancient lava flows?',
 ARRAY['Great Basin', 'Columbia Plateau', 'Snake River Plain', 'Blue Mountains Plateau'],
 'Columbia Plateau', 'Geography', 7),
('What is the name of the peninsula shared by Maryland, Delaware, and Virginia?',
 ARRAY['Cape Cod Peninsula', 'Olympic Peninsula', 'Kenai Peninsula', 'Delmarva Peninsula'],
 'Delmarva Peninsula', 'Geography', 5),
('Which state has the highest mean elevation above sea level?',
 ARRAY['Wyoming', 'Montana', 'Colorado', 'Utah'],
 'Colorado', 'Geography', 5),
('What is the name of the large freshwater aquifer that underlies much of the Great Plains?',
 ARRAY['Edwards Aquifer', 'Floridan Aquifer', 'Ogallala Aquifer', 'High Plains Aquifer'],
 'Ogallala Aquifer', 'Geography', 6),
('What is the name of the large swamp located along the Georgia-Florida border?',
 ARRAY['Everglades', 'Atchafalaya Swamp', 'Okefenokee Swamp', 'Dismal Swamp'],
 'Okefenokee Swamp', 'Geography', 6),
('Which state borders both the Atlantic Ocean and the Gulf of Mexico?',
 ARRAY['Georgia', 'Alabama', 'South Carolina', 'Florida'],
 'Florida', 'Geography', 2),
('Which US city serves as the gateway to the Pacific Northwest and is nicknamed the "Emerald City"?',
 ARRAY['Portland', 'Seattle', 'Vancouver', 'Tacoma'],
 'Seattle', 'Geography', 2),
('What is the name of the mountain range that runs along the Pacific coast of Washington and Oregon?',
 ARRAY['Sierra Nevada', 'Blue Mountains', 'Coast Ranges', 'Cascade Range'],
 'Coast Ranges', 'Geography', 5),
('Which state is home to the Flint Hills, the last large expanse of tallgrass prairie in North America?',
 ARRAY['Oklahoma', 'Nebraska', 'Kansas', 'Missouri'],
 'Kansas', 'Geography', 7),
('What is the name of the large tidal estuary in the mid-Atlantic states that is the largest in the United States?',
 ARRAY['Delaware Bay', 'Long Island Sound', 'Chesapeake Bay', 'Pamlico Sound'],
 'Chesapeake Bay', 'Geography', 4),
('Which mountain in Alaska is the tallest peak in North America?',
 ARRAY['Mount Foraker', 'Mount Hunter', 'Mount Fairweather', 'Denali'],
 'Denali', 'Geography', 2),
('What is the name of the ancient glacial lake whose remnant is the Red River Valley of the North?',
 ARRAY['Lake Agassiz', 'Lake Lahontan', 'Lake Bonneville', 'Lake Duluth'],
 'Lake Agassiz', 'Geography', 8),
('Which state contains the geographic feature known as the Northwest Angle, the only part of the contiguous US north of the 49th parallel?',
 ARRAY['North Dakota', 'Minnesota', 'Montana', 'Wisconsin'],
 'Minnesota', 'Geography', 8),
('What is the name of the national park in Wyoming famous for geothermal features and wildlife?',
 ARRAY['Grand Teton', 'Glacier', 'Yellowstone', 'Rocky Mountain'],
 'Yellowstone', 'Geography', 1),
('Which two states share the longest common border?',
 ARRAY['California and Nevada', 'Texas and New Mexico', 'Montana and Wyoming', 'Alaska and Yukon'],
 'Texas and New Mexico', 'Geography', 7),
('Which state has the greatest number of counties?',
 ARRAY['California', 'New York', 'Georgia', 'Texas'],
 'Texas', 'Geography', 4),
('What is the name of the large fertile valley in California used for agriculture?',
 ARRAY['Napa Valley', 'Willamette Valley', 'San Joaquin Valley', 'Sacramento Valley'],
 'San Joaquin Valley', 'Geography', 4),
('Which US state has the longest total border with Canada?',
 ARRAY['Montana', 'Michigan', 'Minnesota', 'Alaska'],
 'Alaska', 'Geography', 4),
('What is the name of the region in the American Southwest where four states meet at a single point?',
 ARRAY['Tri-State Corner', 'Four Corners', 'Southwest Junction', 'Desert Crossroads'],
 'Four Corners', 'Geography', 2),
('Which river drains the largest watershed in the United States?',
 ARRAY['Colorado River', 'Missouri River', 'Ohio River', 'Mississippi River'],
 'Mississippi River', 'Geography', 4),
('What is the name of the low coastal plain region between the Appalachian Mountains and the Atlantic coast?',
 ARRAY['Cumberland Plateau', 'Piedmont', 'Tidewater', 'Great Valley'],
 'Piedmont', 'Geography', 6),
('Which state is home to Great Sand Dunes National Park, which contains the tallest sand dunes in North America?',
 ARRAY['Arizona', 'New Mexico', 'Utah', 'Colorado'],
 'Colorado', 'Geography', 6),
('What is the name of the large inland sea that once covered much of the central United States, whose chalk deposits are found in Kansas?',
 ARRAY['Iapetus Sea', 'Tethys Sea', 'Western Interior Seaway', 'Sundance Sea'],
 'Western Interior Seaway', 'Geography', 9),
('Which state contains the confluence of the Ohio and Mississippi rivers at Cairo?',
 ARRAY['Kentucky', 'Missouri', 'Illinois', 'Tennessee'],
 'Illinois', 'Geography', 7),
('What is the name of the volcanic crater that forms the summit of Haleakala on Maui?',
 ARRAY['Kilauea', 'Mauna Kea summit', 'Haleakala Crater', 'Pu''u ''O''o'],
 'Haleakala Crater', 'Geography', 6),
('Which state borders the most other US states?',
 ARRAY['Missouri', 'Tennessee', 'Kentucky', 'Colorado'],
 'Tennessee', 'Geography', 6),
('What is the name of the large submarine canyon off the coast of California that rivals the Grand Canyon in depth?',
 ARRAY['Santa Cruz Canyon', 'Monterey Canyon', 'Santa Barbara Basin', 'Channel Canyon'],
 'Monterey Canyon', 'Geography', 8);

-- Landmarks (45 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('The Statue of Liberty was a gift to the United States from which country?',
 ARRAY['England', 'Italy', 'France', 'Spain'],
 'France', 'Landmarks', 1),
('In what year was the Golden Gate Bridge completed and opened to traffic?',
 ARRAY['1933', '1937', '1941', '1945'],
 '1937', 'Landmarks', 4),
('Which US president''s face is NOT carved on Mount Rushmore?',
 ARRAY['Thomas Jefferson', 'George Washington', 'John Adams', 'Abraham Lincoln'],
 'John Adams', 'Landmarks', 3),
('The Gateway Arch in St. Louis stands exactly how tall?',
 ARRAY['550 feet', '600 feet', '630 feet', '700 feet'],
 '630 feet', 'Landmarks', 4),
('What is the name of the famous outdoor amphitheater near Denver, Colorado, known for its stunning red sandstone formations?',
 ARRAY['Red Rocks Amphitheatre', 'Civic Center Amphitheater', 'Morrison Natural Amphitheater', 'Colorado Outdoor Theater'],
 'Red Rocks Amphitheatre', 'Landmarks', 3),
('Which bridge connects the upper and lower peninsulas of Michigan?',
 ARRAY['Confederation Bridge', 'Mackinac Bridge', 'Ambassador Bridge', 'Blue Water Bridge'],
 'Mackinac Bridge', 'Landmarks', 4),
('The National Mall in Washington DC stretches between which two landmarks?',
 ARRAY['White House and Capitol', 'Lincoln Memorial and Capitol', 'Washington Monument and White House', 'Jefferson Memorial and Capitol'],
 'Lincoln Memorial and Capitol', 'Landmarks', 4),
('Who designed the Vietnam Veterans Memorial in Washington, DC?',
 ARRAY['I.M. Pei', 'Frank Gehry', 'Maya Lin', 'Eero Saarinen'],
 'Maya Lin', 'Landmarks', 4),
('The Chrysler Building in New York City was completed in 1930. What architectural style is it known for?',
 ARRAY['Beaux-Arts', 'Art Deco', 'Modernist', 'Gothic Revival'],
 'Art Deco', 'Landmarks', 4),
('Which famous American landmark was originally called "HOLLYWOODLAND" when it was built in 1923?',
 ARRAY['The Hollywood Bowl', 'The Hollywood Sign', 'The Sunset Strip', 'Grauman''s Chinese Theatre'],
 'The Hollywood Sign', 'Landmarks', 3),
('In which state is the Biltmore Estate, the largest privately owned home in the United States?',
 ARRAY['South Carolina', 'Tennessee', 'Virginia', 'North Carolina'],
 'North Carolina', 'Landmarks', 4),
('What is the official name of the building commonly known as the Sears Tower in Chicago?',
 ARRAY['John Hancock Center', 'Willis Tower', 'Two Prudential Plaza', 'Aon Center'],
 'Willis Tower', 'Landmarks', 4),
('Which landmark in Philadelphia is a symbol of American independence and is known for its crack?',
 ARRAY['Independence Hall', 'Liberty Bell', 'Carpenter''s Hall', 'Congress Hall'],
 'Liberty Bell', 'Landmarks', 1),
('The Hoover Dam was built on the border between which two states?',
 ARRAY['California and Arizona', 'Nevada and Arizona', 'Utah and Nevada', 'Colorado and Utah'],
 'Nevada and Arizona', 'Landmarks', 3),
('What was the original purpose of Alcatraz Island before it became a federal prison?',
 ARRAY['Military fort and lighthouse', 'Naval base', 'Immigration station', 'Quarantine facility'],
 'Military fort and lighthouse', 'Landmarks', 5),
('The Thomas Jefferson Memorial in Washington, DC was modeled after which ancient structure?',
 ARRAY['The Parthenon in Athens', 'The Pantheon in Rome', 'The Colosseum in Rome', 'The Temple of Zeus in Olympia'],
 'The Pantheon in Rome', 'Landmarks', 5),
('Which famous architect designed Fallingwater, the house built over a waterfall in Pennsylvania?',
 ARRAY['Louis Sullivan', 'Mies van der Rohe', 'Frank Lloyd Wright', 'Walter Gropius'],
 'Frank Lloyd Wright', 'Landmarks', 4),
('The Crazy Horse Memorial in South Dakota, when completed, will be larger than which nearby landmark?',
 ARRAY['Badlands formations', 'Mount Rushmore', 'Devils Tower', 'Wall Drug'],
 'Mount Rushmore', 'Landmarks', 4),
('Grand Central Terminal in New York City, opened in 1913, is the world''s largest train station by what measure?',
 ARRAY['Square footage', 'Number of platforms and tracks', 'Number of daily passengers', 'Length of platforms'],
 'Number of platforms and tracks', 'Landmarks', 6),
('The Transamerica Pyramid in San Francisco was completed in which decade?',
 ARRAY['1960s', '1970s', '1980s', '1950s'],
 '1970s', 'Landmarks', 5),
('Which historic road connects Chicago, Illinois to Santa Monica, California and is known as the "Mother Road"?',
 ARRAY['Highway 1', 'Route 66', 'The Lincoln Highway', 'US-40'],
 'Route 66', 'Landmarks', 3),
('The Guggenheim Museum in New York City was designed by which architect and features a distinctive spiral ramp?',
 ARRAY['Frank Gehry', 'I.M. Pei', 'Frank Lloyd Wright', 'Philip Johnson'],
 'Frank Lloyd Wright', 'Landmarks', 5),
('Fort McHenry in Baltimore, Maryland inspired the writing of which patriotic song?',
 ARRAY['America the Beautiful', 'The Star-Spangled Banner', 'My Country, ''Tis of Thee', 'Yankee Doodle'],
 'The Star-Spangled Banner', 'Landmarks', 3),
('The Space Needle in Seattle was built for which event?',
 ARRAY['The 1960 Winter Olympics', 'The 1962 World''s Fair', 'The 1964 World''s Fair', 'The 1958 International Exposition'],
 'The 1962 World''s Fair', 'Landmarks', 4),
('In which Massachusetts city is the Freedom Trail, a 2.5-mile path connecting 16 historical sites?',
 ARRAY['Plymouth', 'Salem', 'Cambridge', 'Boston'],
 'Boston', 'Landmarks', 2),
('What is the name of Thomas Jefferson''s historic plantation home near Charlottesville, Virginia?',
 ARRAY['Montpelier', 'Mount Vernon', 'Monticello', 'Belle Grove'],
 'Monticello', 'Landmarks', 3),
('The Washington Monument in Washington, DC stands how tall?',
 ARRAY['455 feet', '505 feet', '555 feet', '605 feet'],
 '555 feet', 'Landmarks', 4),
('Which city is home to the Cahokia Mounds, the largest pre-Columbian settlement north of Mexico?',
 ARRAY['Chicago, Illinois', 'Collinsville, Illinois', 'St. Louis, Missouri', 'Cincinnati, Ohio'],
 'Collinsville, Illinois', 'Landmarks', 7),
('The Brooklyn Bridge, completed in 1883, connects Manhattan to which borough of New York City?',
 ARRAY['Queens', 'Staten Island', 'The Bronx', 'Brooklyn'],
 'Brooklyn', 'Landmarks', 2),
('Which landmark in Newport, Rhode Island is the oldest surviving synagogue building in the United States?',
 ARRAY['Congregation Jeshuat Israel', 'Touro Synagogue', 'Newport Hebrew Congregation', 'Sephardic Temple'],
 'Touro Synagogue', 'Landmarks', 7),
('What is the name of the famous outdoor market in Seattle, Washington, that has been in continuous operation since 1907?',
 ARRAY['Seattle Central Market', 'Pike Place Market', 'Farmers'' Market on First', 'Post Alley Market'],
 'Pike Place Market', 'Landmarks', 3),
('The Four Corners Monument marks the only point in the US where four states meet. Which states are they?',
 ARRAY['Colorado, Utah, Nevada, Arizona', 'Utah, Colorado, Arizona, New Mexico', 'Colorado, Wyoming, Utah, New Mexico', 'Arizona, Nevada, Utah, Colorado'],
 'Utah, Colorado, Arizona, New Mexico', 'Landmarks', 4),
('The Hearst Castle in San Simeon, California was the home of which media magnate?',
 ARRAY['Joseph Pulitzer', 'William Randolph Hearst', 'Rupert Murdoch', 'Ted Turner'],
 'William Randolph Hearst', 'Landmarks', 4),
('The Empire State Building held the title of world''s tallest building for how many years after its completion?',
 ARRAY['10 years', '20 years', '40 years', '30 years'],
 '40 years', 'Landmarks', 6),
('Which New Orleans landmark has been operating as a hotel since 1886 and features a famous revolving carousel bar?',
 ARRAY['Hotel Monteleone', 'The Roosevelt Hotel', 'Pontchartrain Hotel', 'The Windsor Court Hotel'],
 'Hotel Monteleone', 'Landmarks', 7),
('The Flatiron Building in New York City gets its name from its triangular shape. On which intersection was it built in 1902?',
 ARRAY['Broadway and Fifth Avenue', 'Park Avenue and 34th Street', 'Lexington Avenue and 23rd Street', 'Madison Avenue and 23rd Street'],
 'Broadway and Fifth Avenue', 'Landmarks', 6),
('Which famous racetrack in Maryland hosts the second leg of horse racing''s Triple Crown?',
 ARRAY['Churchill Downs', 'Belmont Park', 'Pimlico Race Course', 'Saratoga Race Course'],
 'Pimlico Race Course', 'Landmarks', 5),
('Graceland, the famous home of Elvis Presley, is located in which city?',
 ARRAY['Nashville, Tennessee', 'Memphis, Tennessee', 'Tupelo, Mississippi', 'Shreveport, Louisiana'],
 'Memphis, Tennessee', 'Landmarks', 2),
('The Bonneville Dam spans which river on the border of Oregon and Washington?',
 ARRAY['Snake River', 'Willamette River', 'Columbia River', 'Yakima River'],
 'Columbia River', 'Landmarks', 4),
('Which San Francisco landmark features a distinctive clock tower that survived the 1906 earthquake?',
 ARRAY['Coit Tower', 'Transamerica Pyramid', 'Ferry Building', 'City Hall'],
 'Ferry Building', 'Landmarks', 5),
('The US Holocaust Memorial Museum is located on which street in Washington, DC?',
 ARRAY['Constitution Avenue', 'Independence Avenue', 'Pennsylvania Avenue', 'National Mall'],
 'Independence Avenue', 'Landmarks', 6),
('Which historic Boston landmark on the Freedom Trail is nicknamed "Old Ironsides"?',
 ARRAY['USS Cassin Young', 'USS Constitution', 'USS Olympia', 'USS Massachusetts'],
 'USS Constitution', 'Landmarks', 4),
('The Neon Museum in which city preserves historic neon signs from the mid-20th century?',
 ARRAY['Hollywood', 'Las Vegas', 'Reno', 'Atlantic City'],
 'Las Vegas', 'Landmarks', 4),
('The Arthur Ravenel Jr. Bridge in Charleston, South Carolina crosses which waterway?',
 ARRAY['Ashley River', 'Savannah River', 'Cooper River', 'Wando River'],
 'Cooper River', 'Landmarks', 6),
('What is the name of the iconic welcome sign at the entrance to Las Vegas, designed by Betty Willis in 1959?',
 ARRAY['Welcome to Fabulous Las Vegas', 'Greetings from Las Vegas', 'Welcome to Sin City Las Vegas', 'Entering Las Vegas Nevada'],
 'Welcome to Fabulous Las Vegas', 'Landmarks', 5);

-- Military (52 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which general commanded Union forces at the Battle of Gettysburg?',
 ARRAY['Ulysses S. Grant', 'George McClellan', 'George Meade', 'William Sherman'],
 'George Meade', 'Military', 4),
('What was the name of the first US Navy nuclear-powered submarine?',
 ARRAY['USS Nautilus', 'USS Scorpion', 'USS Thresher', 'USS Triton'],
 'USS Nautilus', 'Military', 5),
('During the Vietnam War, what was the Ho Chi Minh Trail primarily used for?',
 ARRAY['Civilian evacuation routes', 'Supplying North Vietnamese forces in the South', 'US troop movements', 'Prisoner transport'],
 'Supplying North Vietnamese forces in the South', 'Military', 4),
('Which US military branch is responsible for conducting space operations?',
 ARRAY['Air Force', 'Navy', 'Space Force', 'Army'],
 'Space Force', 'Military', 2),
('What was the codename for the US invasion of Normandy on June 6, 1944?',
 ARRAY['Operation Overlord', 'Operation Neptune', 'Operation Torch', 'Operation Market Garden'],
 'Operation Neptune', 'Military', 6),
('Which Confederate general was known as "Stonewall"?',
 ARRAY['Robert E. Lee', 'James Longstreet', 'Thomas Jackson', 'J.E.B. Stuart'],
 'Thomas Jackson', 'Military', 3),
('What was the primary mission of the OSS during World War II?',
 ARRAY['Aerial bombardment', 'Naval blockades', 'Intelligence gathering and covert operations', 'Logistics and supply'],
 'Intelligence gathering and covert operations', 'Military', 5),
('In which city was the USS Indianapolis sunk by a Japanese submarine in 1945?',
 ARRAY['Near Okinawa', 'Near the Philippines', 'In the Philippine Sea', 'Near Iwo Jima'],
 'In the Philippine Sea', 'Military', 7),
('What is the name of the Marine Corps base located on Okinawa, Japan?',
 ARRAY['Camp Pendleton', 'Camp Foster', 'Camp Hansen', 'Camp Butler'],
 'Camp Butler', 'Military', 8),
('Which battle in 1781 effectively ended the American Revolutionary War?',
 ARRAY['Battle of Bunker Hill', 'Battle of Trenton', 'Battle of Yorktown', 'Battle of Camden'],
 'Battle of Yorktown', 'Military', 3),
('Which US military operation removed Manuel Noriega from power in Panama?',
 ARRAY['Operation Just Cause', 'Operation Urgent Fury', 'Operation Eagle Claw', 'Operation Nifty Package'],
 'Operation Just Cause', 'Military', 5),
('What type of aircraft was the U-2, famously shot down over the Soviet Union in 1960?',
 ARRAY['Fighter jet', 'Spy plane', 'Bomber', 'Transport aircraft'],
 'Spy plane', 'Military', 4),
('Which Native American tribe supplied code talkers for the US Marines in the Pacific during WWII?',
 ARRAY['Cherokee', 'Apache', 'Navajo', 'Sioux'],
 'Navajo', 'Military', 3),
('What was the significance of the Battle of Antietam in September 1862?',
 ARRAY['It ended Confederate forces in the East', 'It allowed Lincoln to issue the Emancipation Proclamation', 'It secured Maryland for the Union', 'It was the first major Union victory'],
 'It allowed Lincoln to issue the Emancipation Proclamation', 'Military', 5),
('The term "leatherneck" refers to members of which US military branch?',
 ARRAY['Army', 'Navy', 'Marine Corps', 'Coast Guard'],
 'Marine Corps', 'Military', 3),
('Which US president served as Supreme Commander of Allied Forces in Europe during WWII?',
 ARRAY['Harry Truman', 'Dwight Eisenhower', 'Douglas MacArthur', 'Omar Bradley'],
 'Dwight Eisenhower', 'Military', 2),
('What was the name of the military strategy used by the US in the Pacific to bypass Japanese strongholds?',
 ARRAY['Scorched Earth', 'Island Hopping', 'Rolling Thunder', 'Leapfrogging'],
 'Island Hopping', 'Military', 4),
('Which ship served as the site of Japan''s formal surrender in 1945?',
 ARRAY['USS Missouri', 'USS Enterprise', 'USS Iowa', 'USS New Jersey'],
 'USS Missouri', 'Military', 4),
('During the Civil War, what was the name of the Union''s naval blockade strategy to cut off Confederate trade?',
 ARRAY['The Blockade Plan', 'The Anaconda Plan', 'The Strangler Plan', 'The Sea Control Plan'],
 'The Anaconda Plan', 'Military', 5),
('What was the name of the secret US program to develop the atomic bomb?',
 ARRAY['Project Trinity', 'The Manhattan Project', 'Project Gadget', 'Project Oppenheimer'],
 'The Manhattan Project', 'Military', 2),
('Which military base in Hawaii was attacked on December 7, 1941?',
 ARRAY['Hickam Field', 'Pearl Harbor', 'Schofield Barracks', 'Wheeler Field'],
 'Pearl Harbor', 'Military', 1),
('What was the primary role of the Flying Tigers in WWII?',
 ARRAY['Bombing Japan', 'Defending Burma and China against Japan', 'Escorting bombers over Germany', 'Anti-submarine warfare'],
 'Defending Burma and China against Japan', 'Military', 6),
('Which US military division was known as the "Big Red One"?',
 ARRAY['2nd Infantry Division', '3rd Infantry Division', '1st Infantry Division', '4th Infantry Division'],
 '1st Infantry Division', 'Military', 5),
('What was the name of the US military''s deception operation before D-Day to mislead Germany?',
 ARRAY['Operation Fortitude', 'Operation Quicksilver', 'Operation Bodyguard', 'Operation Overlord'],
 'Operation Fortitude', 'Military', 7),
('Which war introduced trench warfare on a massive scale for American troops?',
 ARRAY['Civil War', 'Spanish-American War', 'World War I', 'World War II'],
 'World War I', 'Military', 3),
('What does NATO stand for?',
 ARRAY['National Atlantic Treaty Organization', 'North Atlantic Treaty Organization', 'North American Treaty Organization', 'National Army Treaty Organization'],
 'North Atlantic Treaty Organization', 'Military', 2),
('Which US warship was sunk by a German U-boat in 1915, helping sway public opinion toward WWI?',
 ARRAY['RMS Titanic', 'RMS Lusitania', 'SS Athenia', 'RMS Mauretania'],
 'RMS Lusitania', 'Military', 4),
('What was the name of the covert CIA program that trained Cuban exiles to invade Cuba in 1961?',
 ARRAY['Operation Mongoose', 'Operation Zapata', 'Operation Condor', 'Operation Ajax'],
 'Operation Zapata', 'Military', 7),
('Which US general was famously known for his use of armored tank warfare in WWII?',
 ARRAY['Omar Bradley', 'Dwight Eisenhower', 'George Patton', 'Mark Clark'],
 'George Patton', 'Military', 3),
('What was the primary purpose of the Berlin Airlift from 1948 to 1949?',
 ARRAY['Supplying Allied troops', 'Delivering supplies to West Berlin during Soviet blockade', 'Evacuating American citizens', 'Transporting German refugees'],
 'Delivering supplies to West Berlin during Soviet blockade', 'Military', 4),
('At which battle in 1775 did the famous order "Don''t fire until you see the whites of their eyes" originate?',
 ARRAY['Battle of Lexington', 'Battle of Bunker Hill', 'Battle of Concord', 'Battle of Breeds Hill'],
 'Battle of Bunker Hill', 'Military', 5),
('What is the name of the special operations unit that conducted the raid on Osama bin Laden''s compound?',
 ARRAY['Delta Force', 'SEAL Team 6', 'Rangers', 'Green Berets'],
 'SEAL Team 6', 'Military', 3),
('Which two US cities were targeted by atomic bombs in August 1945?',
 ARRAY['Tokyo and Osaka', 'Hiroshima and Nagasaki', 'Nagasaki and Kyoto', 'Hiroshima and Tokyo'],
 'Hiroshima and Nagasaki', 'Military', 2),
('What was the name of the failed US mission to rescue American hostages in Iran in 1980?',
 ARRAY['Operation Eagle Claw', 'Operation Desert One', 'Operation Blue Spoon', 'Operation Nimble Archer'],
 'Operation Eagle Claw', 'Military', 6),
('Which battle of the War of 1812 took place after the peace treaty was signed?',
 ARRAY['Battle of Lake Erie', 'Battle of Plattsburgh', 'Battle of New Orleans', 'Battle of Baltimore'],
 'Battle of New Orleans', 'Military', 5),
('What is the name of the military cemetery located in Arlington, Virginia?',
 ARRAY['Soldiers'' National Cemetery', 'Arlington National Cemetery', 'National Memorial Cemetery', 'Veterans'' National Cemetery'],
 'Arlington National Cemetery', 'Military', 1),
('Which branch of the US military operates the Blue Angels flight demonstration team?',
 ARRAY['Air Force', 'Army', 'Navy', 'Marine Corps'],
 'Navy', 'Military', 3),
('During the Korean War, what was the name given to the front line near the 38th parallel?',
 ARRAY['The Iron Line', 'The Main Line of Resistance', 'The DMZ Front', 'The Parallel Line'],
 'The Main Line of Resistance', 'Military', 8),
('What was the name of the US military''s Cold War strategy of "flexible response" attributed to?',
 ARRAY['Eisenhower Doctrine', 'Truman Doctrine', 'Kennedy''s defense policy', 'Nixon Doctrine'],
 'Kennedy''s defense policy', 'Military', 7),
('Which US military action in 1983 rescued American medical students on the island of Grenada?',
 ARRAY['Operation Just Cause', 'Operation Urgent Fury', 'Operation Eagle Claw', 'Operation Sharp Edge'],
 'Operation Urgent Fury', 'Military', 5),
('What does the term "combined arms" refer to in modern military doctrine?',
 ARRAY['Joint NATO operations', 'Coordinated use of infantry, armor, artillery, and air power', 'Intelligence sharing between branches', 'Allied nation cooperation'],
 'Coordinated use of infantry, armor, artillery, and air power', 'Military', 6),
('Which US aircraft carrier was the first to be sunk in combat during WWII?',
 ARRAY['USS Lexington', 'USS Yorktown', 'USS Wasp', 'USS Hornet'],
 'USS Lexington', 'Military', 7),
('What was the name of the US military''s buildup in Vietnam in 1965 that escalated American involvement?',
 ARRAY['Operation Rolling Thunder', 'Operation Flaming Dart', 'Operation Masher', 'Operation Starlite'],
 'Operation Starlite', 'Military', 8),
('Which US Army Ranger unit is headquartered at Fort Moore, Georgia?',
 ARRAY['1st Ranger Battalion', '75th Ranger Regiment', '160th SOAR', 'Special Forces Group'],
 '75th Ranger Regiment', 'Military', 6),
('What was the primary mission of the USS Maine when it exploded in Havana Harbor in 1898?',
 ARRAY['Showing force to Spain', 'Protecting American citizens in Cuba', 'Blockading Cuban ports', 'Evacuating American diplomats'],
 'Protecting American citizens in Cuba', 'Military', 6),
('Which US general led American forces during the Gulf War''s ground campaign in 1991?',
 ARRAY['Colin Powell', 'Norman Schwarzkopf', 'Wesley Clark', 'John Shalikashvili'],
 'Norman Schwarzkopf', 'Military', 4),
('What was the name of the top-secret US signals intelligence program during the Cold War?',
 ARRAY['COINTELPRO', 'ECHELON', 'PRISM', 'VENONA'],
 'ECHELON', 'Military', 8),
('Which US state is home to the largest military base by land area, Fort Wainwright?',
 ARRAY['Texas', 'California', 'Alaska', 'Nevada'],
 'Alaska', 'Military', 7),
('What was the name of the US military operation to stabilize Somalia in 1993?',
 ARRAY['Operation Gothic Serpent', 'Operation Restore Hope', 'Operation United Shield', 'Operation Provide Comfort'],
 'Operation Gothic Serpent', 'Military', 8),
('Which award is given to US military personnel wounded in combat?',
 ARRAY['Bronze Star', 'Silver Star', 'Purple Heart', 'Distinguished Service Medal'],
 'Purple Heart', 'Military', 1),
('What was the name of the last major German offensive on the Western Front in WWII?',
 ARRAY['Operation Citadel', 'Battle of the Bulge', 'Operation Autumn Mist', 'Operation Wacht am Rhein'],
 'Battle of the Bulge', 'Military', 4),
('Which US military base in Cuba has been operated continuously since 1903?',
 ARRAY['Naval Station Guantanamo Bay', 'Camp X-Ray', 'Naval Air Station Cuba', 'Fort Havana'],
 'Naval Station Guantanamo Bay', 'Military', 4);

-- National Parks (54 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('Which national park is home to the famous geyser Old Faithful?',
 ARRAY['Grand Teton', 'Yellowstone', 'Crater Lake', 'Lassen Volcanic'],
 'Yellowstone', 'National Parks', 1),
('What is the name of the national park that protects the Florida Everglades?',
 ARRAY['Big Cypress National Preserve', 'Everglades National Park', 'Dry Tortugas National Park', 'Biscayne National Park'],
 'Everglades National Park', 'National Parks', 2),
('In which state is Acadia National Park located?',
 ARRAY['Vermont', 'New Hampshire', 'Maine', 'Massachusetts'],
 'Maine', 'National Parks', 2),
('Which national park contains the largest concentration of geysers in the world?',
 ARRAY['Lassen Volcanic', 'Hawaii Volcanoes', 'Yellowstone', 'Mount Rainier'],
 'Yellowstone', 'National Parks', 3),
('What is the name of the iconic rock formation in Yosemite National Park that is popular with rock climbers?',
 ARRAY['Half Dome', 'El Capitan', 'Cathedral Peak', 'Cloud''s Rest'],
 'El Capitan', 'National Parks', 3),
('Which national park in Utah is known for its unique red rock formations called hoodoos?',
 ARRAY['Zion', 'Arches', 'Bryce Canyon', 'Canyonlands'],
 'Bryce Canyon', 'National Parks', 3),
('What river carved the Grand Canyon over millions of years?',
 ARRAY['Colorado River', 'Rio Grande', 'Snake River', 'Green River'],
 'Colorado River', 'National Parks', 2),
('Which national park is located on a chain of islands off the coast of Southern California?',
 ARRAY['Redwood National Park', 'Channel Islands National Park', 'Point Reyes National Seashore', 'Cabrillo National Monument'],
 'Channel Islands National Park', 'National Parks', 4),
('Denali National Park is home to the highest peak in North America. How tall is Denali?',
 ARRAY['18,008 feet', '20,310 feet', '19,540 feet', '21,102 feet'],
 '20,310 feet', 'National Parks', 4),
('Which national park preserves ancient cliff dwellings built by ancestral Pueblo people in Colorado?',
 ARRAY['Petrified Forest', 'Chaco Culture', 'Mesa Verde', 'Canyon de Chelly'],
 'Mesa Verde', 'National Parks', 3),
('What is the name of the scenic road that runs through Shenandoah National Park?',
 ARRAY['Blue Ridge Parkway', 'Skyline Drive', 'Natchez Trace Parkway', 'Park Scenic Byway'],
 'Skyline Drive', 'National Parks', 4),
('Which national park in Alaska is known for its massive brown bear population that gathers to fish for salmon?',
 ARRAY['Denali', 'Glacier Bay', 'Katmai', 'Wrangell-St. Elias'],
 'Katmai', 'National Parks', 5),
('The Appalachian Trail passes through how many states?',
 ARRAY['10', '12', '14', '16'],
 '14', 'National Parks', 4),
('What caused the caldera that forms Crater Lake in Oregon?',
 ARRAY['Meteor impact', 'Glacial carving', 'Collapse of ancient volcano Mount Mazama', 'Tectonic subsidence'],
 'Collapse of ancient volcano Mount Mazama', 'National Parks', 5),
('Which national park is found in the Florida Keys and is mostly underwater?',
 ARRAY['Everglades', 'Biscayne', 'Dry Tortugas', 'Canaveral National Seashore'],
 'Biscayne', 'National Parks', 5),
('Sequoia National Park contains the world''s largest tree by volume. What is its name?',
 ARRAY['General Lee', 'General Sherman', 'Hyperion', 'General Grant'],
 'General Sherman', 'National Parks', 3),
('Which national park features towering red rock canyons and the famous Angels Landing hike?',
 ARRAY['Bryce Canyon', 'Arches', 'Capitol Reef', 'Zion'],
 'Zion', 'National Parks', 2),
('In which state is the Guadalupe Mountains National Park, which contains the highest point in Texas?',
 ARRAY['New Mexico', 'Texas', 'Arizona', 'Colorado'],
 'Texas', 'National Parks', 4),
('What ancient sea creature fossils are prominently found in Badlands National Park?',
 ARRAY['Dinosaur bones', 'Marine invertebrates and prehistoric mammals', 'Trilobites', 'Giant shark teeth'],
 'Marine invertebrates and prehistoric mammals', 'National Parks', 5),
('Which national park in Hawaii protects an active volcano that has been continuously erupting?',
 ARRAY['Haleakala', 'Hawaii Volcanoes', 'Kaloko-Honokohau', 'Puuhonua o Honaunau'],
 'Hawaii Volcanoes', 'National Parks', 3),
('What is the name of the lake within Glacier National Park that is famous for its turquoise color?',
 ARRAY['Lake McDonald', 'St. Mary Lake', 'Swiftcurrent Lake', 'Lake Josephine'],
 'Lake McDonald', 'National Parks', 6),
('Which national park was established in 1872 as the world''s first national park?',
 ARRAY['Yosemite', 'Sequoia', 'Yellowstone', 'Grand Canyon'],
 'Yellowstone', 'National Parks', 2),
('The Going-to-the-Sun Road is a historic scenic road within which national park?',
 ARRAY['Rocky Mountain', 'Grand Teton', 'Glacier', 'North Cascades'],
 'Glacier', 'National Parks', 4),
('Which national park in South Dakota is known for its dramatically eroded buttes, pinnacles, and fossils?',
 ARRAY['Theodore Roosevelt', 'Wind Cave', 'Badlands', 'Mount Rushmore'],
 'Badlands', 'National Parks', 2),
('Arches National Park in Utah contains over how many natural stone arches?',
 ARRAY['Over 500', 'Over 1,000', 'Over 2,000', 'Over 3,000'],
 'Over 2,000', 'National Parks', 5),
('Which national park in Washington state features one of the largest temperate rainforests in the world?',
 ARRAY['North Cascades', 'Mount Rainier', 'Olympic', 'San Juan Island'],
 'Olympic', 'National Parks', 4),
('What type of geological feature makes White Sands National Park in New Mexico unique?',
 ARRAY['Red sandstone formations', 'Black lava fields', 'White gypsum sand dunes', 'Pink granite boulders'],
 'White gypsum sand dunes', 'National Parks', 3),
('Which national park became the 63rd US national park when it was established in 2020?',
 ARRAY['Indiana Dunes', 'New River Gorge', 'White Sands', 'Pinnacles'],
 'New River Gorge', 'National Parks', 5),
('In Great Smoky Mountains National Park, approximately how many species of flowering plants exist, giving it UNESCO World Heritage status?',
 ARRAY['Over 700', 'Over 1,500', 'Over 3,000', 'Over 5,000'],
 'Over 1,500', 'National Parks', 6),
('Which national park in Minnesota is known for its interconnected waterways and was once the territory of the Ojibwe people?',
 ARRAY['Isle Royale', 'Voyageurs', 'Boundary Waters', 'Grand Portage'],
 'Voyageurs', 'National Parks', 5),
('The Hoh Rain Forest, which receives up to 14 feet of rain per year, is located in which national park?',
 ARRAY['Redwood', 'Olympic', 'North Cascades', 'Mount Rainier'],
 'Olympic', 'National Parks', 5),
('Which national park in Arizona features a colorful ancient petrified forest from the Triassic period?',
 ARRAY['Saguaro', 'Grand Canyon', 'Petrified Forest', 'Organ Pipe Cactus'],
 'Petrified Forest', 'National Parks', 3),
('What is the name of the trail in Glacier National Park that follows the Continental Divide through the park?',
 ARRAY['Pacific Crest Trail', 'Continental Divide Trail', 'Highline Trail', 'Glacier Loop Trail'],
 'Continental Divide Trail', 'National Parks', 6),
('Joshua Tree National Park sits at the convergence of which two deserts?',
 ARRAY['Great Basin and Sonoran', 'Mojave and Chihuahuan', 'Mojave and Sonoran', 'Great Basin and Mojave'],
 'Mojave and Sonoran', 'National Parks', 4),
('Which national park in New Mexico protects the world''s largest known cave system?',
 ARRAY['White Sands', 'Guadalupe Mountains', 'Carlsbad Caverns', 'El Malpais'],
 'Carlsbad Caverns', 'National Parks', 3),
('What is the name of the national park in North Dakota that preserves the landscape where Theodore Roosevelt ranched?',
 ARRAY['Badlands', 'Theodore Roosevelt', 'Wind Cave', 'Agate Fossil Beds'],
 'Theodore Roosevelt', 'National Parks', 4),
('Which national park is home to the tallest sand dunes in North America?',
 ARRAY['White Sands', 'Great Sand Dunes', 'Indiana Dunes', 'Sleeping Bear Dunes'],
 'Great Sand Dunes', 'National Parks', 4),
('In which state is Congaree National Park, which protects old-growth bottomland hardwood forest?',
 ARRAY['Georgia', 'North Carolina', 'South Carolina', 'Alabama'],
 'South Carolina', 'National Parks', 5),
('What is the primary ecological attraction of Isle Royale National Park in Lake Superior?',
 ARRAY['Ancient copper mines', 'Wolf and moose predator-prey dynamics', 'Migratory bird sanctuary', 'Prehistoric burial mounds'],
 'Wolf and moose predator-prey dynamics', 'National Parks', 6),
('Which national park in California preserves the world''s tallest trees?',
 ARRAY['Sequoia', 'Kings Canyon', 'Redwood', 'Muir Woods'],
 'Redwood', 'National Parks', 3),
('Death Valley National Park holds which world record?',
 ARRAY['Coldest inhabited place', 'Lowest and hottest point in North America', 'Largest salt flat', 'Driest place on Earth'],
 'Lowest and hottest point in North America', 'National Parks', 3),
('Which national park in Utah is divided into four districts, including the remote Maze district?',
 ARRAY['Arches', 'Bryce Canyon', 'Capitol Reef', 'Canyonlands'],
 'Canyonlands', 'National Parks', 5),
('The Kenai Fjords National Park in Alaska is named for its coastal fjords carved by which geological force?',
 ARRAY['Volcanic activity', 'River erosion', 'Glacial activity', 'Tectonic uplift'],
 'Glacial activity', 'National Parks', 5),
('Which national park protects an archipelago in Lake Superior off the coast of Wisconsin?',
 ARRAY['Pictured Rocks', 'Isle Royale', 'Sleeping Bear Dunes', 'Apostle Islands'],
 'Apostle Islands', 'National Parks', 6),
('Lassen Volcanic National Park in California is one of the only parks to contain all four types of what?',
 ARRAY['Rock formations', 'Volcanic features', 'Hydrothermal features', 'Ecosystem zones'],
 'Volcanic features', 'National Parks', 7),
('Which national park in Nevada features the oldest living trees on Earth, the bristlecone pines?',
 ARRAY['Lake Mead', 'Great Basin', 'Death Valley', 'Mojave'],
 'Great Basin', 'National Parks', 5),
('What geological feature is the centerpiece of Capitol Reef National Park in Utah?',
 ARRAY['Giant sandstone arches', 'Waterpocket Fold', 'Ancient volcano crater', 'Underground cave system'],
 'Waterpocket Fold', 'National Parks', 6),
('Which national park in Virginia is the only national park in the state and features the Blue Ridge Mountains?',
 ARRAY['Appomattox Court House', 'Colonial National Historical Park', 'Shenandoah', 'Richmond National Battlefield'],
 'Shenandoah', 'National Parks', 3),
('Glacier Bay National Park in Alaska is primarily known for its calving glaciers. How far have the glaciers retreated since the 18th century?',
 ARRAY['About 10 miles', 'About 25 miles', 'About 65 miles', 'About 100 miles'],
 'About 65 miles', 'National Parks', 8),
('Which national park in California protects a region where the volcanic Cascades meet the Sierra Nevada?',
 ARRAY['Mount Shasta', 'Lassen Volcanic', 'Shasta-Trinity', 'Modoc'],
 'Lassen Volcanic', 'National Parks', 6),
('Which national park in Colorado protects a deep, sheer-walled gorge carved by the Gunnison River?',
 ARRAY['Rocky Mountain', 'Mesa Verde', 'Great Sand Dunes', 'Black Canyon of the Gunnison'],
 'Black Canyon of the Gunnison', 'National Parks', 4),
('What is the name of the iconic hiking trail in Zion National Park that requires the use of chains on steep sections?',
 ARRAY['The Narrows', 'Angels Landing', 'Emerald Pools', 'Canyon Overlook'],
 'Angels Landing', 'National Parks', 4),
('Which national park in the US Virgin Islands covers approximately two-thirds of the island of St. John?',
 ARRAY['Buck Island Reef', 'Virgin Islands', 'Salt River Bay', 'Christiansted'],
 'Virgin Islands', 'National Parks', 6),
('What is the most visited national park in the United States?',
 ARRAY['Yellowstone', 'Yosemite', 'Great Smoky Mountains', 'Grand Canyon'],
 'Great Smoky Mountains', 'National Parks', 3);

-- US Sports (40 questions)
INSERT INTO public.questions (text, options, correct_answer, category, difficulty) VALUES
('In what year did the American Football League and the NFL officially merge?',
 ARRAY['1966', '1968', '1970', '1972'],
 '1970', 'US Sports', 6),
('Which city hosted the 1904 Summer Olympics, the first held in the United States?',
 ARRAY['Chicago', 'New York', 'St. Louis', 'Boston'],
 'St. Louis', 'US Sports', 7),
('Which NBA player holds the record for most points scored in a single game?',
 ARRAY['Michael Jordan', 'Kobe Bryant', 'LeBron James', 'Wilt Chamberlain'],
 'Wilt Chamberlain', 'US Sports', 4),
('Who was the first woman inducted into the Pro Football Hall of Fame?',
 ARRAY['Pat Summitt', 'Lamar Hunt', 'Eleonora Randolph Sears', 'Kathleen Horger'],
 'Kathleen Horger', 'US Sports', 9),
('In baseball, how many feet are between each base?',
 ARRAY['75 feet', '80 feet', '90 feet', '100 feet'],
 '90 feet', 'US Sports', 3),
('Which golfer holds the record for most major championship titles?',
 ARRAY['Tiger Woods', 'Arnold Palmer', 'Jack Nicklaus', 'Gary Player'],
 'Jack Nicklaus', 'US Sports', 4),
('What is the name of the trophy awarded to the champion of Major League Baseball?',
 ARRAY['World Series Trophy', 'Commissioner''s Trophy', 'League Championship Trophy', 'October Classic Trophy'],
 'Commissioner''s Trophy', 'US Sports', 6),
('Which MLB pitcher holds the record for most career strikeouts?',
 ARRAY['Roger Clemens', 'Randy Johnson', 'Steve Carlton', 'Nolan Ryan'],
 'Nolan Ryan', 'US Sports', 4),
('In what year was the three-point line introduced in the NBA?',
 ARRAY['1975-76', '1977-78', '1979-80', '1981-82'],
 '1979-80', 'US Sports', 6),
('Which US city hosted the 1980 Winter Olympics?',
 ARRAY['Denver', 'Salt Lake City', 'Lake Placid', 'Squaw Valley'],
 'Lake Placid', 'US Sports', 5),
('Who holds the record for most career rushing yards in NFL history?',
 ARRAY['Barry Sanders', 'Walter Payton', 'Jerry Rice', 'Emmitt Smith'],
 'Emmitt Smith', 'US Sports', 4),
('Which boxer was nicknamed "The Brown Bomber" and dominated heavyweight boxing in the 1930s and 1940s?',
 ARRAY['Jack Dempsey', 'Joe Louis', 'Rocky Marciano', 'Sugar Ray Robinson'],
 'Joe Louis', 'US Sports', 5),
('What is the maximum number of players on an active NHL roster?',
 ARRAY['20 players', '23 players', '25 players', '28 players'],
 '23 players', 'US Sports', 6),
('In which year did the WNBA play its inaugural season?',
 ARRAY['1995', '1996', '1997', '1998'],
 '1997', 'US Sports', 5),
('What famous play is named for a Franco Harris catch in the 1972 AFC Divisional playoff game?',
 ARRAY['The Miracle Catch', 'The Immaculate Reception', 'The Holy Roller', 'The Catch'],
 'The Immaculate Reception', 'US Sports', 6),
('Which US swimmer won seven gold medals at the 1972 Munich Olympics?',
 ARRAY['Johnny Weissmuller', 'Matt Biondi', 'Mark Spitz', 'Don Schollander'],
 'Mark Spitz', 'US Sports', 5),
('What year did Jackie Robinson break Major League Baseball''s color barrier?',
 ARRAY['1945', '1946', '1947', '1948'],
 '1947', 'US Sports', 3),
('Which horse won the Triple Crown in 1973, setting records in all three races?',
 ARRAY['Man o'' War', 'Citation', 'Secretariat', 'Seattle Slew'],
 'Secretariat', 'US Sports', 4),
('Which college football trophy is awarded annually to the best player in the sport?',
 ARRAY['Rose Bowl Trophy', 'Heisman Trophy', 'Outland Trophy', 'Lombardi Award'],
 'Heisman Trophy', 'US Sports', 3),
('What is the name of the landmark hill on the Boston Marathon course that exhausts runners near mile 21?',
 ARRAY['Boylston Hill', 'Wellesley Hill', 'Newton Hill', 'Heartbreak Hill'],
 'Heartbreak Hill', 'US Sports', 5),
('Which NASCAR driver holds the record for most Cup Series wins at 200 victories?',
 ARRAY['Dale Earnhardt', 'Jeff Gordon', 'Richard Petty', 'Jimmie Johnson'],
 'Richard Petty', 'US Sports', 5),
('In which year did the US men''s hockey team pull off the "Miracle on Ice" at the Winter Olympics?',
 ARRAY['1976', '1980', '1984', '1988'],
 '1980', 'US Sports', 4),
('Who holds the record for most consecutive games played in NBA history?',
 ARRAY['A.C. Green', 'John Stockton', 'Robert Parish', 'Kareem Abdul-Jabbar'],
 'A.C. Green', 'US Sports', 7),
('In which US city is the Pro Football Hall of Fame located?',
 ARRAY['Cleveland, Ohio', 'Columbus, Ohio', 'Canton, Ohio', 'Akron, Ohio'],
 'Canton, Ohio', 'US Sports', 5),
('What was the first year a woman competed in the Indianapolis 500?',
 ARRAY['1971', '1974', '1977', '1980'],
 '1977', 'US Sports', 7),
('Which NBA team holds the record for most consecutive championships, winning 8 in a row from 1959 to 1966?',
 ARRAY['Chicago Bulls', 'Los Angeles Lakers', 'Boston Celtics', 'San Antonio Spurs'],
 'Boston Celtics', 'US Sports', 5),
('Who was the first gymnast to receive a perfect score of 10 at the Olympic Games?',
 ARRAY['Mary Lou Retton', 'Kerri Strug', 'Nadia Comaneci', 'Cathy Rigby'],
 'Nadia Comaneci', 'US Sports', 5),
('Which US tennis player has won the most US Open singles titles in the Open Era?',
 ARRAY['Andre Agassi', 'John McEnroe', 'Jimmy Connors', 'Pete Sampras'],
 'Pete Sampras', 'US Sports', 6),
('What is a perfect score in ten-pin bowling?',
 ARRAY['200', '250', '300', '360'],
 '300', 'US Sports', 3),
('Which American football player was the first to rush for more than 2,000 yards in a single NFL season?',
 ARRAY['Walter Payton', 'Earl Campbell', 'O.J. Simpson', 'Eric Dickerson'],
 'O.J. Simpson', 'US Sports', 6),
('Which US city hosted the Summer Olympics in 1932?',
 ARRAY['Chicago', 'New York', 'Los Angeles', 'San Francisco'],
 'Los Angeles', 'US Sports', 6),
('In what year did Major League Soccer (MLS) play its inaugural season?',
 ARRAY['1993', '1994', '1996', '1998'],
 '1996', 'US Sports', 6),
('Who holds the record for most career saves by a goalie in NHL history?',
 ARRAY['Patrick Roy', 'Terry Sawchuk', 'Martin Brodeur', 'Curtis Joseph'],
 'Martin Brodeur', 'US Sports', 6),
('Which US track and field athlete won four gold medals at the 1936 Berlin Olympics?',
 ARRAY['Ralph Metcalfe', 'Mack Robinson', 'Jesse Owens', 'Eddie Tolan'],
 'Jesse Owens', 'US Sports', 4),
('What is the name of the annual tennis tournament held at Flushing Meadows in New York?',
 ARRAY['The Masters', 'Wimbledon', 'US Open', 'Roland Garros'],
 'US Open', 'US Sports', 2),
('Which was the first US team to win five Super Bowls?',
 ARRAY['Dallas Cowboys', 'Pittsburgh Steelers', 'San Francisco 49ers', 'New England Patriots'],
 'San Francisco 49ers', 'US Sports', 6),
('Who was the first figure skater from the United States to win an Olympic gold medal?',
 ARRAY['Dorothy Hamill', 'Peggy Fleming', 'Tenley Albright', 'Carol Heiss'],
 'Tenley Albright', 'US Sports', 7),
('What is the name given to the championship trophy for the NHL''s Western Conference Finals?',
 ARRAY['Clarence Campbell Bowl', 'Conn Smythe Trophy', 'President''s Trophy', 'Hart Trophy'],
 'Clarence Campbell Bowl', 'US Sports', 7),
('Which city hosted the 1984 Summer Olympics?',
 ARRAY['Montreal', 'Moscow', 'Los Angeles', 'Seoul'],
 'Los Angeles', 'US Sports', 4),
('What is the distance run in a standard marathon race?',
 ARRAY['25 miles', '26.1 miles', '26.2 miles', '27 miles'],
 '26.2 miles', 'US Sports', 3);

